(function(G){'use strict';
const $=id=>document.getElementById(id),RANGE=260;
function eligibility(app,m){const e=app.engine,b=e?.b,u=e?.active;if(u?.retreat)return{ok:false,reason:'이탈보 · 이동/점프만 가능'};if(m?.action==='skillGate')return {ok:app.canInput()&&u.gateTurn!==`${b.round}:${b.teamEnds[0]}`,reason:'E · 축지진목'};if(!e||!u||!m||m.collected||u.side!==0||u.dead)return{ok:false,reason:'상호작용할 수 없음'};const d=Math.hypot(u.x-m.x,(u.y-m.y)*.75);if(d>RANGE)return{ok:false,reason:'더 가까이 이동'};if(Math.abs(u.y-m.y)>150)return{ok:false,reason:'같은 층으로 이동'};if(m.requiredClass&&u.cls!==m.requiredClass)return{ok:false,reason:`${G.HONRO_CONTENT.hero[m.requiredClass]?.name||'지정 인물'} 필요`};if(!app.canInput())return{ok:false,reason:'현재 행동이 끝난 뒤'};return{ok:true,reason:m.action==='ritual'?'E · 의식 시작':'E · 상호작용'};}
function candidates(app){if(!app.engine||app.done)return[];const e=app.engine,u=e.active;if(!u||u.side!==0||u.dead)return[];const gate=e.gateCandidate(),markers=[...(e.b.honroMarkers||[]),...(gate?[{...gate,id:'skillGate-'+gate.id,action:'skillGate',label:'축지진목'}]:[])];return markers.filter(m=>m.action&&!m.collected&&Math.hypot(u.x-m.x,(u.y-m.y)*.75)<=RANGE+70).map(m=>({marker:m,d:Math.hypot(u.x-m.x,u.y-m.y),...eligibility(app,m)})).sort((a,b)=>a.d-b.d);}
function linesFor(app,m){return G.HonroStoryContent.interaction(app,m)||[];}
function use(app,m){const ok=eligibility(app,m);if(!ok.ok)return false;if(m?.action==='skillGate'){const used=app.engine.useGate();if(used){app.dirty=true;app.updateHUD(true);}refresh(app);return used;}const e=app.engine,b=e.b,hs=b.honroState,u=e.active;
 if(m.action==='authored'){if(m.authoredAction&&G.HonroAllies.execute(app,m.authoredAction)===false)return false;m.collected=true;hs.flags['interact:'+m.id]=true;if(m.lines?.length)app.sayLines(m.lines);app.event(m.label);e.finishAction();app.dirty=true;refresh(app);return true;}
 if(m.action==='ritual'){hs.ritual={active:true,holderId:u.id};hs.waterfallSight=true;const veil=b.terrain.find(t=>t.id==='waterfall-veil');if(veil){veil.broken=true;b.sceneVersion++;}e.fx('ring',m.x,m.y-20,'#a5c9bd',95);const lines=linesFor(app,m);if(lines.length)app.sayLines(lines);app.event('담허가 받이진을 유지한다. 설오로 바꾸어 열린 물틈의 고리쇠를 노리자.');e.finishAction();app.dirty=true;refresh(app);return true;}
 m.collected=true;if(m.action==='ledger')hs.ledger=true;if(m.action==='receiver'){hs.receivers=(hs.receivers||0)+1;e.fx('ring',m.x,m.y-20,'#b8c999',65);}if(m.action==='rescue'){hs.rescuedCount=(hs.rescuedCount||0)+1;const target=e.unit(m.target);if(target){target.shield=Math.max(target.shield||0,60);target.fixed=true;target.honroResolved=true;e.fx('ring',target.x,target.y-target.h*.5,'#a7c3ad',60);}}
 const lines=linesFor(app,m);if(lines.length)app.sayLines(lines);app.event(m.action==='ledger'?'홍만의 장부를 찾았다.':m.action==='receiver'?'받이진을 세웠다.':'들린 사람에게서 원혼을 떼어냈다.');e.finishAction();app.dirty=true;refresh(app);return true;
}
function refresh(app){const host=$('context-interact');if(!host)return;const near=candidates(app),one=near[0],enabled=!!one?.ok,sig=one?`${one.marker.id}:${enabled}:${one.reason}:${near.length}`:'none';if(host.dataset.sig===sig)return;host.dataset.sig=sig;if(!one){host.hidden=true;host.innerHTML='';return;}host.hidden=false;const action=one.marker.action,label=action==='skillGate'?'축지':action==='ledger'?'장부 확인':action==='receiver'?'받이진 설치':action==='ritual'?'담허의 의식':action==='authored'?'상호작용':'구조';host.innerHTML=`<button ${enabled?'':'disabled'} data-context-interact="${one.marker.id}" aria-label="${label} · ${one.marker.label}"><i class="keycap">E</i><span>${label}</span><strong>${enabled?one.marker.label:one.reason}</strong></button>`;}
function mount(app){const battle=app.root.querySelector('.battle');if(!battle||$('context-interact'))return;const el=document.createElement('div');el.id='context-interact';el.className='context-interact';el.hidden=true;battle.appendChild(el);refresh(app);}
function nearest(app){return candidates(app).find(x=>x.ok)?.marker||null;}function key(app,e){if(e.code!=='KeyE'||e.repeat)return false;if(!app.dialogue&&!app.modal?.classList.contains('open')&&(app.engine?.manualDive()||app.engine?.turnArrow(app.scene?.turnTarget))){e.preventDefault();return true;}const m=nearest(app);if(!m)return false;e.preventDefault();return use(app,m);}
document.addEventListener('click',e=>{const btn=e.target.closest?.('[data-context-interact]');if(!btn)return;const app=G.HonroApp,m=app?candidates(app).find(x=>x.marker.id===btn.dataset.contextInteract)?.marker:null;if(app&&m)use(app,m);});
G.HonroInteractions={mount,refresh,nearest,use,key,candidates,eligibility};
})(globalThis);
