(function(G){'use strict';
const $=id=>document.getElementById(id),RANGE=260;
function eligibility(app,m){const e=app.engine,b=e?.b,u=e?.active;if(!e||!u||!m||m.collected||u.side!==0||u.dead)return{ok:false,reason:'상호작용할 수 없음'};const d=Math.hypot(u.x-m.x,(u.y-m.y)*.75);if(d>RANGE)return{ok:false,reason:'더 가까이 이동'};if(Math.abs(u.y-m.y)>150)return{ok:false,reason:'같은 층으로 이동'};if(m.requiredClass&&u.cls!==m.requiredClass)return{ok:false,reason:`${G.HONRO_CONTENT.hero[m.requiredClass]?.name||'지정 인물'} 필요`};if(!app.canInput())return{ok:false,reason:'현재 행동이 끝난 뒤'};return{ok:true,reason:m.action==='ritual'?'E · 의식 시작':'E · 상호작용'};}
function candidates(app){if(!app.engine||app.training||app.done)return[];const e=app.engine,u=e.active;if(!u||u.side!==0||u.dead)return[];return(e.b.honroMarkers||[]).filter(m=>m.action&&!m.collected&&Math.hypot(u.x-m.x,(u.y-m.y)*.75)<=RANGE+70).map(m=>({marker:m,d:Math.hypot(u.x-m.x,u.y-m.y),...eligibility(app,m)})).sort((a,b)=>a.d-b.d);}
function linesFor(app,m){const hs=app.engine.b.honroState;
 if(m.action==='ledger')return[['설오','여기 있습니다.'],['설오','“북쪽 산사람 열셋. 연목으로.”'],['담허','자네가 찾던 사람들인가?'],['설오','인원까지 맞습니다. 다음엔 “여덟. 아이 둘.”… 마지막엔 “길 막힘. 밤에는 배 띄우지 말 것.”이라고 적혀 있군요.'],['담허','몇 장이 뜯겨 나갔네. 남은 마지막 행은?'],['설오','“연목 주막에 머묾.” 여기까지입니다.']];
 if(m.action==='ritual')return[['담허','내가 이 자리를 붙들겠네. 물살 사이가 열려 있는 동안 고리쇠를 쏘게.'],['설오','보이면 바로 쏘겠습니다.']];
 if(m.action==='receiver')return hs.receivers===1?[['담허','한쪽은 됐네. 반대편도 같은 높이로 맞추게.']]:[['담허','두 자리가 이어졌네. 이제 하나씩 넘겨받을 수 있어.']];
 if(m.action==='rescue'){const name=m.label;return hs.rescuedCount===1?[[name,'……살았습니까, 나?'],['설오','예. 움직이지 마십시오.'],[name,'방울 든 처녀는 어디 있소? 그 사람이 아니었으면 내가 집사람을 해쳤을 거요. 죽이지 않고 여기 묶어 둔 겁니다.']]:[[name,'숨이… 돌아왔소.'],['담허','천천히. 사람 곁에서 떨어진 건 우리가 받았네.']];}return[];
}
function use(app,m){const ok=eligibility(app,m);if(!ok.ok)return false;const e=app.engine,b=e.b,hs=b.honroState,u=e.active;
 if(m.action==='authored'){if(m.authoredAction&&G.HonroAllies.execute(app,m.authoredAction)===false)return false;m.collected=true;hs.flags['interact:'+m.id]=true;if(m.lines?.length)app.sayLines(m.lines);app.event(m.label);e.finishAction();app.dirty=true;refresh(app);return true;}
 if(m.action==='ritual'){hs.ritual={active:true,holderId:u.id};hs.waterfallSight=true;const veil=b.terrain.find(t=>t.id==='waterfall-veil');if(veil){veil.broken=true;b.sceneVersion++;}e.fx('ring',m.x,m.y-20,'#a5c9bd',95);const lines=linesFor(app,m);if(lines.length)app.sayLines(lines);app.event('담허가 받이진을 유지한다. 설오로 바꾸어 열린 물틈의 고리쇠를 노리자.');e.finishAction();app.dirty=true;refresh(app);return true;}
 m.collected=true;if(m.action==='ledger')hs.ledger=true;if(m.action==='receiver'){hs.receivers=(hs.receivers||0)+1;e.fx('ring',m.x,m.y-20,'#b8c999',65);}if(m.action==='rescue'){hs.rescuedCount=(hs.rescuedCount||0)+1;const target=e.unit(m.target);if(target){target.shield=Math.max(target.shield||0,60);target.fixed=true;target.honroResolved=true;e.fx('ring',target.x,target.y-target.h*.5,'#a7c3ad',60);}}
 const lines=linesFor(app,m);if(lines.length)app.sayLines(lines);app.event(m.action==='ledger'?'홍만의 장부를 찾았다.':m.action==='receiver'?'받이진을 세웠다.':'들린 사람에게서 원혼을 떼어냈다.');e.finishAction();app.dirty=true;refresh(app);return true;
}
function refresh(app){const host=$('context-interact');if(!host)return;const near=candidates(app),one=near[0],enabled=!!one?.ok,sig=one?`${one.marker.id}:${enabled}:${one.reason}:${near.length}`:'none';if(host.dataset.sig===sig)return;host.dataset.sig=sig;if(!one){host.hidden=true;host.innerHTML='';return;}host.hidden=false;const action=one.marker.action,label=action==='ledger'?'장부 확인':action==='receiver'?'받이진 설치':action==='ritual'?'담허의 의식':action==='authored'?'상호작용':'구조';host.innerHTML=`<button ${enabled?'':'disabled'} data-context-interact="${one.marker.id}" aria-label="${label} · ${one.marker.label}"><i class="keycap">E</i><span>${label}</span><strong>${enabled?one.marker.label:one.reason}</strong></button>`;}
function mount(app){const battle=app.root.querySelector('.battle');if(!battle||$('context-interact'))return;const el=document.createElement('div');el.id='context-interact';el.className='context-interact';el.hidden=true;battle.appendChild(el);refresh(app);}
function nearest(app){return candidates(app).find(x=>x.ok)?.marker||null;}function key(app,e){if(e.code!=='KeyE'||e.repeat)return false;const m=nearest(app);if(!m)return false;e.preventDefault();return use(app,m);}
document.addEventListener('click',e=>{const btn=e.target.closest?.('[data-context-interact]');if(!btn)return;const app=G.HonroApp,m=app?.engine?.b.honroMarkers?.find(x=>x.id===btn.dataset.contextInteract);if(app&&m)use(app,m);});
G.HonroInteractions={mount,refresh,nearest,use,key,candidates,eligibility};
})(globalThis);
