(function(G){'use strict';
const H=G.HONRO_CONTENT,C=G.HONRO_CORE,$=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const data=()=>G.HonroJourneyContent;
function state(profile){const old=profile.honroJourney;if(!old||old.version!==1)profile.honroJourney={version:1,talked:{}};const s=profile.honroJourney;s.talked??={};return s;}
function location(profile){return data().next(profile)||data().ending;}
function active(profile){return profile.honroBattle||null;}
function currentId(profile){return active(profile)?.honroStage||data().next(profile)?.stageId||H.stages.at(-1).id;}
function finalConsonant(text){const last=String(text).charCodeAt(String(text).length-1)-0xac00;return last>=0&&last<=11171?last%28:0;}
function towards(place){const jong=finalConsonant(place);return place+(jong&&jong!==8?'으로':'로');}
function together(name){return name+(finalConsonant(name)?'과':'와');}
function speakerId(cls){return H.hero[cls]?.name;}
function talkId(next,cls){return `rest-talk-v1-${next?.stageId||'end'}-${cls}`;}
function restMarkup(app){const p=app.profile,d=data(),next=d.next(p),place=next||d.ending,previous=next?d.at(next.stageId-1):d.at(H.stages.at(-1).id),battle=active(p),s=state(p);
 const positions={archer:[36,84],mage:[44,79],knight:[61,82],occultist:[70,78]};
 const heroes=p.recruited.filter(cls=>H.hero[cls]).map(cls=>{const [x,y]=positions[cls]||[60,80],unread=!s.talked[talkId(next,cls)];return `<button class="rest-person rest-${cls}" data-action="rest-talk" data-class="${cls}" style="--person-x:${x}%;--person-y:${y}%" aria-label="${esc(together(speakerId(cls)))} 선택 대화${unread?' · 새 대화':''}"><canvas width="220" height="300" data-rest-person="${cls}" aria-hidden="true"></canvas><span class="rest-person-label">${esc(speakerId(cls))}${unread?'<i aria-hidden="true">···</i>':''}</span><small>이야기 듣기</small></button>`;}).join('');
 return `<main class="screen rest-screen">${app.top('길 위의 쉼터')}<section class="rest-landscape" aria-label="${esc(place.restName)}"><div class="rest-background" aria-hidden="true">${G.HonroJourneyArt.scene(place.variant,place.layer).replace('preserveAspectRatio="xMidYMid slice"','preserveAspectRatio="xMidYMax slice"')}</div><div class="rest-location"><span>${esc(place.region)} · ${place.layer==='underground'?'땅 아래':'지상'}</span><h1>${esc(place.restName)}</h1><p>${esc(place.restDescription)}</p></div><div class="rest-arrival"><span>지나온 길</span><strong>${esc(previous?.place||'산 아래 주막')}</strong><i>↘</i></div><div class="rest-people">${heroes}</div><button class="rest-fire" data-action="camp" aria-label="모닥불 · 모든 동행 능력치와 기예 준비"><span>모닥불</span><small>동행 · 능력치 · 기예</small></button>${next?`<button class="rest-sign" data-action="journey-enter" data-id="${next.stageId}"><small>다음 길 · ${esc(next.region)}</small><strong>${esc(towards(next.place))} 진입 <b>→</b></strong></button>`:'<div class="rest-sign rest-ending"><small>둘째 막 끝</small><strong>하늘 아래, 잠시 머무르다</strong><span>다음 여정은 준비 중입니다.</span></div>'}<div class="rest-note">동행을 누르면 이야기를 나눕니다.</div></section><footer class="rest-footer"><div class="rest-tools"><button data-action="journey-book"><span aria-hidden="true">冊</span> 여정첩</button><button class="ghost" data-action="training">허공터 · 기예 연습</button></div>${battle?`<button class="rest-resume primary" data-action="continue"><small>진행 중 · ${esc(d.at(battle.honroStage)?.place||H.stages[battle.honroStage-1]?.name)}</small><strong>저장된 전투 이어서 걷기 →</strong></button>`:`<p>${next?`${next.stageId} / ${H.stages.length}번째 길 · ${esc(next.event)}`:'지나온 길은 여정첩에서 다시 걸을 수 있습니다.'}</p>`}</footer><div id="dialogue-root"></div></main>`;
}
let restVisual;
function drawActor(ctx,cls){restVisual??=new G.HonroPartyVisual(G.HONRO_PARTY,G.HonroVectorRig,new G.HonroArcherVisual(G.HONRO_ARCHER,G.HonroVectorRig));restVisual.draw(ctx,{cls,facing:['archer','mage'].includes(cls)?1:-1,angle:25,side:0,x:0,portraitOnly:true},0);}
function layoutRest(){const scene=document.querySelector('.rest-landscape'),box=scene?.getBoundingClientRect?.();if(!box)return;const artHeight=box.height-(box.width<=700?90:0),scale=Math.max(box.width*(box.width<=700?1.6:1)/1600,artHeight/900),dy=artHeight-900*scale;scene.style.setProperty('--rest-ground',`${765*scale+dy}px`);scene.style.setProperty('--rest-sign-y',`${628*scale+dy}px`);}
function drawPeople(){layoutRest();for(const cv of document.querySelectorAll('canvas[data-rest-person]')){const cls=cv.dataset.restPerson,ctx=cv.getContext('2d');ctx.clearRect(0,0,220,300);ctx.save();ctx.translate(110,282);ctx.scale(2.5,2.5);drawActor(ctx,cls);ctx.restore();}}
function showRest(app){if(app.debugMode)return app.showMap();app.stopBattle();app.close();app.training=false;const pending=state(app.profile).pendingDirect,next=data().next(app.profile);if(!active(app.profile)&&pending&&next?.stageId===pending)return launch(app,pending,'next');G.HonroAct2.recruit(app.profile);G.HonroProgression.repairRecruits(app.profile);app.screen='rest';const s=state(app.profile);s.stageId=data().next(app.profile)?.stageId||null;app.root.innerHTML=restMarkup(app);drawPeople();app.persist();app.updateAudio();nextStory(app);}
function prelude(completed){return (G.HonroStoryContent.mapScenes[completed]||[]).map(([who,text,meta={}])=>who==='서술'||meta.kind==='narration'?['설오',completed===0?'고개에 오르기 전에 주막에서 홍만의 소식을 물어봐야겠다.':text,{...meta,kind:'dialogue'}]:[who,text,meta]);}
function startEntry(app,title){const id=`rest-interlude-v1-${app.stage.id}`,need=!app.profile.seen[id],context=need?(data().interlude?.(app.stage.id)||[]):[],lines=G.HonroObjectives.entry(app,{interlude:false});return G.HonroStory.start(app,[...context,...lines],{title,after:'entry',journeyInterludeId:need?id:null});}
function restoreStory(app){const saved=state(app.profile).story;if(!saved)return false;
 // A suspended battle can advance while an interrupted rest conversation is
 // still saved. Bind text to its original place; never regenerate a previous
 // place's dialogue from the new destination or let optional talk skip arrival.
 const nextStage=data().next(app.profile)?.stageId??null,match=/^rest-(?:interlude|talk)-v1-(\d+|end)(?:-|$)/.exec(saved.id||''),savedStage=saved.kind==='map'?(saved.completed>=H.stages.length?null:saved.completed+1):match?(match[1]==='end'?null:Number(match[1])):undefined;
 const completed=nextStage==null?H.stages.at(-1).id:nextStage-1,mapId=`map-story-v${G.HonroStoryContent.version}-${completed}`,arrivalId=`rest-interlude-v1-${nextStage??'end'}`;
 const requiredPending=(!app.profile.seen[mapId]&&prelude(completed).length)||!app.profile.seen[arrivalId];
 if(savedStage!==nextStage||(saved.stageId!==undefined&&saved.stageId!==savedStage)||(saved.kind==='optional'&&requiredPending)){state(app.profile).story=null;app.persist();return false;}
 let lines;if(saved.kind==='map')lines=prelude(saved.completed);else if(saved.kind==='optional')lines=data().optional(app.profile,data().next(app.profile)?.stageId??null,saved.cls);else lines=data().required(app.profile,data().next(app.profile)?.stageId??null);if(!lines?.length){state(app.profile).story=null;return false;}return G.HonroStory.start(app,lines,{id:saved.id,index:saved.index||0,title:location(app.profile).restName,after:'rest',restKind:saved.kind,restClass:saved.cls,restCompleted:saved.completed});}
function nextStory(app){if(app.screen!=='rest'||app.dialogue)return false;if(restoreStory(app))return true;const p=app.profile,next=data().next(p),completed=next?next.stageId-1:H.stages.at(-1).id,mapId=`map-story-v${G.HonroStoryContent.version}-${completed}`,mapLines=prelude(completed);
 if(mapLines?.length&&!p.seen[mapId])return G.HonroStory.start(app,mapLines,{id:mapId,index:p.honroMapStory?.id===mapId?p.honroMapStory.index:0,title:location(p).restName,after:'rest',restKind:'map',restCompleted:completed});
 const id=`rest-interlude-v1-${next?.stageId||'end'}`;if(p.seen[id])return false;const lines=data().required(p,next?.stageId??null);return lines?.length?G.HonroStory.start(app,lines,{id,title:location(p).restName,after:'rest',restKind:'arrival'}):false;
}
function saveStory(app){if(app.screen!=='rest')return;const d=app.dialogue,s=state(app.profile);s.story=d?{id:d.id,index:d.index,kind:d.restKind,cls:d.restClass,completed:d.restCompleted,stageId:data().next(app.profile)?.stageId??null}:null;app.persist();}
function finishStory(app,d){if(app.screen!=='rest'||d.after!=='rest')return false;const s=state(app.profile);s.story=null;if(d.restKind==='optional'){s.talked[d.id]=true;app.persist();app.root.innerHTML=restMarkup(app);drawPeople();document.querySelector(`[data-action="rest-talk"][data-class="${d.restClass}"]`)?.focus?.({preventScroll:true});return true;}app.persist();if(!nextStory(app))document.querySelector('[data-action="camp"]')?.focus?.({preventScroll:true});return true;}
function talk(app,cls){if(app.screen!=='rest'||app.dialogue||!app.profile.recruited.includes(cls))return;const next=data().next(app.profile),lines=data().optional(app.profile,next?.stageId??null,cls);if(lines?.length)G.HonroStory.start(app,lines,{id:talkId(next,cls),title:`${location(app.profile).restName} · ${speakerId(cls)}`,after:'rest',restKind:'optional',restClass:cls});}
function status(profile,place){if((active(profile)||data().next(profile))&&currentId(profile)===place.stageId)return active(profile)?'진행 중인 전투':'현재 길목';if(profile.cleared[place.stageId])return '지나온 길';return H.stages[place.stageId-1].requires.every(id=>profile.cleared[id])?'열린 길':'아직 닿지 않은 길';}
function bookMarkup(app){const p=app.profile,d=data(),finished=!active(p)&&!d.next(p),selected=app.journeySelection==='end'?d.ending:d.at(app.journeySelection)||location(p),layer=app.journeyLayer||selected.layer,places=d.places.filter(v=>v.layer===layer),current=currentId(p),next=d.next(p),done=!!p.cleared[selected.stageId],isCurrent=active(p)?.honroStage===selected.stageId,open=done||next?.stageId===selected.stageId;let route='';for(let i=1;i<places.length;i++){const a=places[i-1],b=places[i];route+=`<path d="M${a.map.join(' ')} Q${(a.map[0]+b.map[0])/2} ${Math.min(a.map[1],b.map[1])-35} ${b.map.join(' ')}" class="journey-route ${p.cleared[a.stageId]?'travelled':''}"/>`;}
 const pins=places.map(v=>{const st=H.stages[v.stageId-1],passed=!!p.cleared[v.stageId],here=!finished&&v.stageId===current,reached=passed||st.requires.every(id=>p.cleared[id]);return `<button class="journey-pin ${passed?'passed':''} ${here?'current':''} ${reached?'reached':'unreached'} ${selected.stageId===v.stageId?'selected':''}" data-action="journey-select" data-id="${v.stageId}" style="left:${v.map[0]/18}%;top:${v.map[1]/10.5}%" aria-label="${esc(v.place)} · ${status(p,v)}" ${here?'aria-current="location"':''}><i>${passed?'✓':v.stageId}</i><span>${esc(v.place)}</span>${here?'<b>현 위치</b>':''}</button>`;}).join('');
 return `<main class="screen journey-screen">${app.top('여정첩','rest')}<div class="journey-heading"><div><span>걸어온 길을 펼치다</span><h1>${layer==='underground'?'땅 아래의 물길':'연목과 북쪽 산길'}</h1></div><nav aria-label="지도 층"><button data-action="journey-layer" data-layer="surface" aria-pressed="${layer==='surface'}">지상</button><button data-action="journey-layer" data-layer="underground" aria-pressed="${layer==='underground'}">지하</button></nav></div><section class="journey-map-scroll" aria-label="지리와 지나온 길"><div class="journey-map">${G.HonroJourneyArt.atlas(layer)}<svg class="journey-route-overlay" viewBox="0 0 1800 1050" aria-hidden="true">${route}</svg>${[...new Set(places.map(v=>v.region))].map(region=>{const group=places.filter(v=>v.region===region),x=group.reduce((sum,v)=>sum+v.map[0],0)/group.length,y=Math.max(100,Math.min(...group.map(v=>v.map[1]))-105);return `<span class="journey-region" style="left:${x/18}%;top:${y/10.5}%">${esc(region)}</span>`;}).join('')}${pins}${finished&&layer==='surface'?`<button class="journey-pin current reached" style="left:${d.ending.map[0]/18}%;top:${d.ending.map[1]/10.5}%" data-action="journey-select" data-id="end" aria-current="location"><i>◎</i><span>${esc(d.ending.place)}</span><b>현 위치 · 둘째 막 끝</b></button>`:''}<div class="journey-map-legend"><span>◎ 현 위치</span><span>✓ 지나온 길</span><span>○ 아직 닿지 않은 길</span></div></div></section><section class="journey-detail" aria-live="polite"><div><span>${esc(selected.region)} · ${status(p,selected)}</span><h2>${esc(selected.place)}</h2><p>${open?esc(selected.event):'아직 닿지 않은 장소입니다. 앞선 길을 지나면 이야기가 열립니다.'}</p></div>${app.journeySelection==='end'?'<button class="primary" data-action="rest">새벽 쉼터로 돌아가기</button>':isCurrent?'<button class="primary" data-action="continue">저장된 전투 이어서 걷기</button>':done?`<button data-action="journey-replay" data-id="${selected.stageId}">지난 전투 다시 걷기</button>`:next?.stageId===selected.stageId?'<button class="primary" data-action="rest">현재 쉼터로 돌아가기</button>':'<button disabled>아직 닿지 않은 길</button>'}</section></main>`;
}
function revealBook(app){const viewport=document.querySelector('.journey-map-scroll'),map=document.querySelector('.journey-map'),place=app.journeySelection==='end'?data().ending:data().at(app.journeySelection);if(!viewport||!map||!place||place.layer!==app.journeyLayer)return;viewport.scrollLeft=Math.max(0,place.map[0]/1800*map.clientWidth-viewport.clientWidth/2);viewport.scrollTop=Math.max(0,place.map[1]/1050*map.clientHeight-viewport.clientHeight/2);}
function showBook(app,id,layer){app.stopBattle();app.close();app.screen='journey';const d=data();app.journeySelection=id==='end'?'end':d.at(+id)?+id:(app.journeySelection||(!active(app.profile)&&!d.next(app.profile)?'end':currentId(app.profile)));app.journeyLayer=layer||(app.journeySelection==='end'?'surface':d.at(app.journeySelection)?.layer)||'surface';if(layer&&(app.journeySelection==='end'?d.ending:d.at(app.journeySelection))?.layer!==layer){const here=d.at(active(app.profile)?.honroStage)||location(app.profile);app.journeySelection=here.layer===layer?(!active(app.profile)&&!d.next(app.profile)?'end':here.stageId):d.places.find(v=>v.layer===layer)?.stageId;}app.root.innerHTML=bookMarkup(app);revealBook(app);app.updateAudio();}
function selectBook(app,id){if(id!=='end'&&!data().at(+id))return;app.journeySelection=id==='end'?'end':+id;app.root.innerHTML=bookMarkup(app);revealBook(app);document.querySelector(`[data-action="journey-select"][data-id="${id}"]`)?.focus?.({preventScroll:true});}
function launch(app,id,kind){app.pendingJourneyLaunch=null;delete state(app.profile).pendingDirect;app.launch(id);if(app.engine&&!app.training){app.engine.b.honroJourneyReplay=kind==='replay';app.profile.honroBattle=clone(app.engine.b);app.persist();}}
function requestLaunch(app,id,kind='next'){id=Number(id);const st=H.stages[id-1],next=data().next(app.profile);if(!st||(!app.debugMode&&kind==='replay'&&!app.profile.cleared[id])||(!app.debugMode&&kind!=='replay'&&next?.stageId!==id))return;app.stopBattle();const b=active(app.profile);if(b){app.pendingJourneyLaunch={id,kind,session:b.session};app.open(`<h2>진행 중인 전투를 바꿀까요?</h2><p>현재 <strong>${esc(H.stages[(b.honroStage||1)-1].name)}</strong>의 전투가 저장되어 있습니다. <strong>${esc(st.name)}</strong>${kind==='replay'?'을 다시 시작하면':'에 새로 진입하면'} 저장된 전투 하나가 교체됩니다.</p><p>얻은 성장과 지난 완료 기록은 유지됩니다.</p><div class="actions"><button data-action="cancel-journey-launch">취소</button><button class="primary" data-action="confirm-journey-launch">전투를 바꾸고 진입</button></div>`,'journey-confirm');return;}launch(app,id,kind);}
function confirmLaunch(app){const pending=app.pendingJourneyLaunch;if(!pending)return;const b=active(app.profile);if(b?.session!==pending.session){app.pendingJourneyLaunch=null;app.close();app.notify('저장된 전투가 바뀌었습니다. 진입할 길을 다시 골라주세요.');return;}launch(app,pending.id,pending.kind);}
function recordOutcome(app,won){if(!won||app.engine?.b.honroJourneyReplay)return;const next=data().next(app.profile),s=state(app.profile);if(next?.stageId===app.stage.id+1&&data().transitionAfter(app.stage.id)==='direct')s.pendingDirect=next.stageId;else delete s.pendingDirect;}
function resultLabel(app){if(app.engine?.b.phase==='lost')return '쉼터로 돌아가기';const next=data().next(app.profile);return app.engine?.b.honroJourneyReplay?'여정첩으로':next&&next.stageId===app.stage.id+1&&data().transitionAfter(app.stage.id)==='direct'?`${towards(next.place)} 이어 걷기`:'다음 쉼터로';}
function resultContinue(app){if(!app.engine||!app.done)return;const b=app.engine.b,won=b.phase==='won',id=app.stage.id,replay=b.honroJourneyReplay;app.engine=null;app.profile.honroBattle=null;app.close();if(replay)return showBook(app,id);const next=data().next(app.profile);if(won&&next?.stageId===id+1&&data().transitionAfter(id)==='direct')return launch(app,next.stageId,'next');return showRest(app);}
G.HonroRestJourney={state,location,active,currentId,towards,startEntry,restMarkup,drawPeople,drawActor,layoutRest,showRest,nextStory,saveStory,finishStory,talk,bookMarkup,showBook,selectBook,requestLaunch,confirmLaunch,recordOutcome,resultLabel,resultContinue};
})(globalThis);
