(function(G){'use strict';
const H=G.HONRO_CONTENT,C=G.HONRO_CORE,$=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const data=()=>G.HonroJourneyContent;
function state(profile){const old=profile.honroJourney;if(!old||old.version!==1)profile.honroJourney={version:1,talked:{}};const s=profile.honroJourney;s.talked??={};return s;}
function location(profile){return data().next(profile)||data().ending;}
function active(profile){return profile.honroBattle||null;}
function currentId(profile){return active(profile)?.honroStage||data().next(profile)?.stageId||H.stages.at(-1).id;}
function finalConsonant(text){const last=String(text).charCodeAt(String(text).length-1)-0xac00;return last>=0&&last<=11171?last%28:0;}
function towards(place){const jong=finalConsonant(place);return place+(jong&&jong!==8?'으로':'로');}
function together(name){return name+(finalConsonant(name)?'과':'와');}
function speakerId(cls){return H.hero[cls]?.name;}
const endStoryKey=()=>H.stages.at(-1).id>20?'end-'+H.stages.at(-1).id:'end';
function talkId(next,cls){return `rest-talk-v1-${next?.stageId||endStoryKey()}-${cls}`;}
function restNext(app){return app.debugMode&&app.debugRestStage?data().at(app.debugRestStage):data().next(app.profile);}
function debugRest(app,id){if(!app.debugMode||!data().at(+id))return;app.stopBattle();app.debugRestStage=+id;app.journeySelection=+id;app.prepareDebugCamp();showRest(app);}
function restMarkup(app){const p=app.profile,d=data(),next=restNext(app),place=next||d.ending,previous=next?d.at(next.stageId-1):d.at(H.stages.at(-1).id),battle=active(p),s=state(p);
 const positions={archer:[36,84],mage:[44,79],knight:[61,82],occultist:[70,78]};
 const heroes=p.recruited.filter(cls=>H.hero[cls]).map(cls=>{const [x,y]=positions[cls]||[60,80],unread=!s.talked[talkId(next,cls)];return `<button class="rest-person rest-${cls}" data-action="rest-talk" data-class="${cls}" style="--person-x:${x}%;--person-y:${y}%" aria-label="${esc(together(speakerId(cls)))} 선택 대화${unread?' · 새 대화':''}"><canvas width="220" height="300" data-rest-person="${cls}" aria-hidden="true"></canvas><span class="rest-person-label">${esc(speakerId(cls))}${unread?'<i aria-hidden="true">···</i>':''}</span><small>이야기 듣기</small></button>`;}).join('');
 return `<main class="screen rest-screen">${app.top('길 위의 쉼터')}<section class="rest-landscape" aria-label="${esc(place.restName)}"><div class="rest-background" aria-hidden="true">${G.HonroJourneyArt.scene(place.variant,place.layer).replace('preserveAspectRatio="xMidYMid slice"','preserveAspectRatio="xMidYMax slice"')}</div><div class="rest-location"><span>${esc(place.region)} · ${place.layer==='underground'?'땅 아래':'지상'}</span><h1>${esc(place.restName)}</h1><p>${esc(place.restDescription)}</p></div><div class="rest-arrival"><span>지나온 길</span><strong>${esc(previous?.place||'산 아래 주막')}</strong><i>↘</i></div><div class="rest-people">${heroes}</div><button class="rest-fire" data-action="camp" aria-label="모닥불 · 모든 동행 능력치와 기예 준비"><span>모닥불</span><small>동행 · 능력치 · 기예</small></button>${next?`<button class="rest-sign" data-action="journey-enter" data-id="${next.stageId}"><small>다음 길 · ${esc(next.region)}</small><strong>${esc(towards(next.place))} 진입 <b>→</b></strong></button>`:`<div class="rest-sign rest-ending"><small>${esc(d.ending.actEnd||'둘째 막 끝')}</small><strong>${esc(d.ending.endingTitle||'하늘 아래, 잠시 머무르다')}</strong><span>${esc(d.ending.nextText||'다음 여정은 준비 중입니다.')}</span></div>`}<div class="rest-note">동행을 누르면 이야기를 나눕니다.</div></section><footer class="rest-footer"><div class="rest-tools"><button data-action="journey-book"><span aria-hidden="true">冊</span> 여정첩</button><button class="ghost" data-action="training">허공터 · 기예 연습</button></div>${battle?`<button class="rest-resume primary" data-action="continue"><small>진행 중 · ${esc(d.at(battle.honroStage)?.place||H.stages[battle.honroStage-1]?.name)}</small><strong>저장된 전투 이어서 걷기 →</strong></button>`:`<p>${next?`${next.stageId} / ${H.stages.length}번째 길 · ${esc(next.event)}`:'지나온 길은 여정첩에서 다시 걸을 수 있습니다.'}</p>`}</footer><div id="dialogue-root"></div></main>`;
}
// Use the same cached pose-target renderer and idle clips as the battlefield.
// Rest actors have no engine units, combat timers, or saved progression state.
const restRenderers=new Map(),restActors={archer:['seol_o',1,0],mage:['damheo',1,.73],knight:['hwigyeom',-1,1.31],occultist:['sodan',-1,2.03]};
const reducedMotion=G.matchMedia?.('(prefers-reduced-motion: reduce)');
function drawActor(ctx,cls,time=0){const spec=restActors[cls];if(!spec)return;const [id,facing,phase]=spec;let renderer=restRenderers.get(id);if(!renderer){renderer=G.HonroVectorRig.createCanvasRenderer(G.HONRO_PARTY[id]);restRenderers.set(id,renderer);}renderer.draw(ctx,{height:102,facing,animation:'idle',time:Math.max(0,time)+phase});}
function layoutRest(){const scene=document.querySelector('.rest-landscape'),box=scene?.getBoundingClientRect?.();if(!box)return;const artHeight=box.height-(box.width<=700?90:0),scale=Math.max(box.width*(box.width<=700?1.6:1)/1600,artHeight/900),dy=artHeight-900*scale;scene.style.setProperty('--rest-ground',`${765*scale+dy}px`);scene.style.setProperty('--rest-sign-y',`${628*scale+dy}px`);}
// v010 full-cycle bounds: Hwigyeom hat reaches -123.454 at height 102.
// With foot y282 and 8px top margin, max uniform scale is 2.2194; use 2.21.
// All four keep one scale, their asset proportions, foot anchor and button box.
function drawPeople(time=0,canvases=document.querySelectorAll('canvas[data-rest-person]')){for(const cv of canvases){const ctx=cv.getContext('2d');ctx.clearRect(0,0,cv.width,cv.height);ctx.save();ctx.translate(110,282);ctx.scale(2.21,2.21);drawActor(ctx,cv.dataset.restPerson,time);ctx.restore();}}
function paintMotion(m,time){drawPeople(time,m.people);for(const {node,kind,phase}of m.art){const attrs=G.HonroJourneyArt.motionFrame(kind,time,phase);for(const [key,value]of Object.entries(attrs))node.setAttribute(key,value);}m.draws++;}
function stopMotion(app){app.restMotion=null;}
function startMotion(app){const time=app.restMotion?.time||0;stopMotion(app);layoutRest();const scene=document.querySelector('.rest-landscape');if(!scene)return;const m=app.restMotion={scene,time,age:0,draws:0,paused:!!document.hidden,reduced:!!reducedMotion?.matches,people:[...document.querySelectorAll('canvas[data-rest-person]')],art:[...scene.querySelectorAll('[data-rest-motion]')].map(node=>({node,kind:node.dataset.restMotion,phase:Number(node.dataset.restPhase)||0}))};paintMotion(m,m.reduced?0:m.time);}
// The App already owns one rAF. Reuse its clamped dt, retain DOM handles only
// while this rest screen exists, and redraw at 24 Hz (20 Hz on narrow screens).
// No second rAF, timers, observers or per-entry listeners need cancellation.
function frame(app,dt){const m=app.restMotion;if(app.screen!=='rest'){if(m)stopMotion(app);return;}if(!m||m.scene.isConnected===false){stopMotion(app);return;}if(document.hidden){m.paused=true;m.age=0;return;}const reduce=!!reducedMotion?.matches;if(reduce){if(!m.reduced)paintMotion(m,0);m.reduced=true;m.age=0;return;}if(m.paused||m.reduced){m.paused=false;m.reduced=false;m.age=0;return;}const step=Math.min(.06,Math.max(0,Number(dt)||0));m.time+=step;m.age+=step;const interval=G.innerWidth<=700?1/20:1/24;if(m.age+1e-9<interval)return;m.age=Math.max(0,m.age-interval*Math.floor((m.age+1e-9)/interval));paintMotion(m,m.time);}
function showRest(app){if(G.HonroSplitCampaign?.redirectRest(app))return;app.stopBattle();app.close();app.training=false;const pending=state(app.profile).pendingDirect,next=data().next(app.profile);if(!app.debugRestStage&&!active(app.profile)&&pending&&next?.stageId===pending)return launch(app,pending,'next');G.HonroAct2.recruit(app.profile);G.HonroProgression.repairRecruits(app.profile);app.screen='rest';const s=state(app.profile);s.stageId=restNext(app)?.stageId||null;app.root.innerHTML=restMarkup(app);startMotion(app);app.persist();app.updateAudio();nextStory(app);}
function prelude(completed){return (G.HonroStoryContent.mapScenes[completed]||[]).map(([who,text,meta={}])=>who==='서술'||meta.kind==='narration'?['설오',completed===0?'고개에 오르기 전에 주막에서 홍만의 소식을 물어봐야겠다.':text,{...meta,kind:'dialogue'}]:[who,text,meta]);}
function startEntry(app,title){const id=`rest-interlude-v1-${app.stage.id}`,need=!app.profile.seen[id],context=need?(data().interlude?.(app.stage.id)||[]):[],lines=G.HonroObjectives.entry(app,{interlude:false});return G.HonroStory.start(app,[...context,...lines],{title,after:'entry',journeyInterludeId:need?id:null});}
function restoreStory(app){const saved=state(app.profile).story;if(!saved)return false;
 // A suspended battle can advance while an interrupted rest conversation is
 // still saved. Bind text to its original place; never regenerate a previous
 // place's dialogue from the new destination or let optional talk skip arrival.
 const nextStage=data().next(app.profile)?.stageId??null,match=/^rest-(?:interlude|talk)-v1-(\d+|end)(?:-|$)/.exec(saved.id||''),savedStage=saved.kind==='map'?(saved.completed>=H.stages.length?null:saved.completed+1):match?(match[1]==='end'?null:Number(match[1])):undefined;
 const completed=nextStage==null?H.stages.at(-1).id:nextStage-1,mapId=`map-story-v${G.HonroStoryContent.version}-${completed}`,arrivalId=`rest-interlude-v1-${nextStage??endStoryKey()}`;
 const requiredPending=(!app.profile.seen[mapId]&&prelude(completed).length)||!app.profile.seen[arrivalId];
 if(savedStage!==nextStage||(saved.stageId!==undefined&&saved.stageId!==savedStage)||(saved.kind==='optional'&&requiredPending)){state(app.profile).story=null;app.persist();return false;}
 let lines;if(saved.kind==='map')lines=prelude(saved.completed);else if(saved.kind==='optional')lines=data().optional(app.profile,data().next(app.profile)?.stageId??null,saved.cls);else lines=data().required(app.profile,data().next(app.profile)?.stageId??null);if(!lines?.length){state(app.profile).story=null;return false;}return G.HonroStory.start(app,lines,{id:saved.id,index:saved.index||0,title:location(app.profile).restName,after:'rest',restKind:saved.kind,restClass:saved.cls,restCompleted:saved.completed});}
function nextStory(app){if(app.debugMode&&app.debugRestStage)return false;if(app.screen!=='rest'||app.dialogue)return false;if(restoreStory(app))return true;const p=app.profile,next=data().next(p),completed=next?next.stageId-1:H.stages.at(-1).id,mapId=`map-story-v${G.HonroStoryContent.version}-${completed}`,mapLines=prelude(completed);
 if(mapLines?.length&&!p.seen[mapId])return G.HonroStory.start(app,mapLines,{id:mapId,index:p.honroMapStory?.id===mapId?p.honroMapStory.index:0,title:location(p).restName,after:'rest',restKind:'map',restCompleted:completed});
 const id=`rest-interlude-v1-${next?.stageId||endStoryKey()}`;if(p.seen[id])return false;const lines=data().required(p,next?.stageId??null);return lines?.length?G.HonroStory.start(app,lines,{id,title:location(p).restName,after:'rest',restKind:'arrival'}):false;
}
function saveStory(app){if(app.screen!=='rest')return;const d=app.dialogue,s=state(app.profile);s.story=d?{id:d.id,index:d.index,kind:d.restKind,cls:d.restClass,completed:d.restCompleted,stageId:data().next(app.profile)?.stageId??null}:null;app.persist();}
function finishStory(app,d){if(app.screen!=='rest'||d.after!=='rest')return false;const s=state(app.profile);s.story=null;if(d.restKind==='optional'){s.talked[d.id]=true;app.persist();app.root.innerHTML=restMarkup(app);startMotion(app);document.querySelector(`[data-action="rest-talk"][data-class="${d.restClass}"]`)?.focus?.({preventScroll:true});return true;}app.persist();if(!nextStory(app))document.querySelector('[data-action="camp"]')?.focus?.({preventScroll:true});return true;}
function talk(app,cls){if(app.screen!=='rest'||app.dialogue||!app.profile.recruited.includes(cls))return;const next=restNext(app),lines=data().optional(app.profile,next?.stageId??null,cls);if(lines?.length)G.HonroStory.start(app,lines,{id:talkId(next,cls),title:`${(restNext(app)||data().ending).restName} · ${speakerId(cls)}`,after:'rest',restKind:'optional',restClass:cls});}
function status(profile,place){if((active(profile)||data().next(profile))&&currentId(profile)===place.stageId)return active(profile)?'진행 중인 전투':'현재 길목';if(profile.cleared[place.stageId])return '지나온 길';return H.stages[place.stageId-1].requires.every(id=>profile.cleared[id])?'열린 길':'아직 닿지 않은 길';}
function unlocked(profile,place,debug=false){return debug||!!profile.cleared[place.stageId]||H.stages[place.stageId-1].requires.every(id=>!!profile.cleared[id]);}
function bookMarkup(app){
 const p=app.profile,d=data(),layer=app.journeyLayer||'surface',finished=!active(p)&&!d.next(p);
 const places=d.places.filter(v=>v.layer===layer),visible=places.filter(v=>unlocked(p,v,app.debugMode));
 const selected=app.journeySelection==='end'&&finished&&layer===d.ending.layer?d.ending:visible.find(v=>v.stageId===app.journeySelection)||null;
 const current=currentId(p),next=d.next(p),done=selected?!!p.cleared[selected.stageId]:false,isCurrent=selected&&active(p)?.honroStage===selected.stageId;
 const route=visible.slice(1).map((v,i)=>{const a=visible[i];return `<path d="M${a.map.join(' ')} Q${(a.map[0]+v.map[0])/2} ${Math.min(a.map[1],v.map[1])-35} ${v.map.join(' ')}" class="journey-route ${p.cleared[a.stageId]?'travelled':''}"/>`;}).join('');
 const pins=visible.map(v=>{const passed=!!p.cleared[v.stageId],here=!finished&&v.stageId===current,picked=selected?.stageId===v.stageId&&app.journeySelection!=='end';return `<button class="journey-pin ${passed?'passed':''} ${here?'current':''} ${picked?'selected':''}" data-action="journey-select" data-id="${v.stageId}" style="left:${v.map[0]/18}%;top:${v.map[1]/10.5}%" aria-label="${esc(v.place)} · ${status(p,v)}" aria-pressed="${picked}" ${here?'aria-current="location"':''}><i>${passed?'✓':v.stageId}</i><span>${esc(v.place)}</span>${here?'<b>현 위치</b>':''}</button>`;}).join('');
 const regions=[...new Set(visible.map(v=>v.region))].map(region=>{const group=visible.filter(v=>v.region===region),x=group.reduce((sum,v)=>sum+v.map[0],0)/group.length,y=Math.max(100,Math.min(...group.map(v=>v.map[1]))-105);return `<span class="journey-region" style="left:${x/18}%;top:${y/10.5}%">${esc(region)}</span>`;}).join('');
 const endPin=finished&&layer===d.ending.layer?`<button class="journey-pin current ${app.journeySelection==='end'?'selected':''}" style="left:${d.ending.map[0]/18}%;top:${d.ending.map[1]/10.5}%" data-action="journey-select" data-id="end" aria-current="location" aria-pressed="${app.journeySelection==='end'}"><i>◎</i><span>${esc(d.ending.place)}</span><b>현 위치 · ${esc(d.ending.actEnd||'막 끝')}</b></button>`:'';
 const details=!selected?'<div><span>지도</span><h2>아직 열린 길이 없습니다</h2><p>이곳의 지형을 먼저 살펴보세요.</p></div>':`<div><span>${esc(selected.region)} · ${status(p,selected)}</span><h2>${esc(selected.place)}</h2><p>${esc(selected.event)}</p></div>${app.journeySelection==='end'?'<button class="primary" data-action="rest">쉼터로 돌아가기</button>':isCurrent?'<button class="primary" data-action="continue">저장된 전투 이어서 걷기</button>':app.debugMode?`<button class="primary" data-action="${done?'journey-replay':'journey-enter'}" data-id="${selected.stageId}">${done?'지난 전투 다시 걷기':'들어가기'}</button>`:done?`<button data-action="journey-replay" data-id="${selected.stageId}">지난 전투 다시 걷기</button>`:next?.stageId===selected.stageId?'<button class="primary" data-action="rest">현재 쉼터로 돌아가기</button>':''}`;
 return `<main class="screen journey-screen journey-${layer}">${app.top('여정첩','rest')}<div class="journey-heading"><div><span>걸어온 길을 펼치다</span><h1>${layer==='city'?'강변 읍성과 옛 나루':layer==='underground'?'땅 아래의 물길':'연목과 북쪽 산길'}</h1></div><nav aria-label="지도 층"><button data-action="journey-layer" data-layer="surface" aria-pressed="${layer==='surface'}">지상</button><button data-action="journey-layer" data-layer="underground" aria-pressed="${layer==='underground'}">지하</button><button data-action="journey-layer" data-layer="city" aria-pressed="${layer==='city'}">읍성</button></nav></div><section class="journey-map-scroll" aria-label="지리와 지나온 길"><div class="journey-map" style="--journey-zoom:${Math.max(.85,Math.min(1.35,Number(app.journeyZoom)||1))}">${G.HonroJourneyArt.atlas(layer)}<svg class="journey-route-overlay" viewBox="0 0 1800 1050" aria-hidden="true">${route}</svg>${regions}${pins}${endPin}</div><div class="journey-map-legend"><span>◎ 현 위치</span><span>✓ 지나온 길</span><span>드래그로 이동 · 휠 / 두 손가락으로 확대·축소</span></div></section><section class="journey-detail" aria-live="polite">${details}</section></main>`;
}
function revealBook(app){const viewport=document.querySelector('.journey-map-scroll'),map=document.querySelector('.journey-map'),place=app.journeySelection==='end'?data().ending:data().at(app.journeySelection);if(!viewport||!map||!place||place.layer!==app.journeyLayer)return;viewport.scrollLeft=Math.max(0,place.map[0]/1800*map.clientWidth-viewport.clientWidth/2);viewport.scrollTop=Math.max(0,place.map[1]/1050*map.clientHeight-viewport.clientHeight/2);}
function zoomBook(app,zoom,clientX,clientY,fromX=clientX,fromY=clientY){
 if(app.screen!=='journey'||!Number.isFinite(zoom))return;
 const viewport=document.querySelector('.journey-map-scroll'),map=document.querySelector('.journey-map');if(!viewport||!map)return;
 const next=Math.max(.85,Math.min(1.35,zoom)),rect=viewport.getBoundingClientRect();
 const px=clientX-rect.left,py=clientY-rect.top,fx=(viewport.scrollLeft+fromX-rect.left)/map.clientWidth,fy=(viewport.scrollTop+fromY-rect.top)/map.clientHeight;
 app.journeyZoom=next;map.style.setProperty('--journey-zoom',String(next));
 // Keep the same point under the wheel or between the fingers, including a
 // moving pinch midpoint and a pan after reaching either zoom limit.
 viewport.scrollLeft=fx*map.clientWidth-px;viewport.scrollTop=fy*map.clientHeight-py;
}
function mountBook(app){
 const viewport=document.querySelector('.journey-map-scroll');if(!viewport||typeof viewport.addEventListener!=='function')return;
 const contacts=new Map();let moved=false,pinchZoom=1;
 const pinch=()=>{const [a,b]=contacts.values();return b?{x:(a.x+b.x)/2,y:(a.y+b.y)/2,gap:Math.hypot(a.x-b.x,a.y-b.y)}:null;};
 viewport.addEventListener('pointerdown',e=>{
  if(e.button!==0)return;if(!contacts.size)moved=false;
  contacts.set(e.pointerId,{x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY});
  // Capture on the original pin so an unmoved touch still produces its normal
  // click. Capture keeps a drag alive when it leaves the map's visible edge.
  (e.target.closest('button')||viewport).setPointerCapture?.(e.pointerId);
  if(contacts.size===2)pinchZoom=app.journeyZoom||1;
  if(contacts.size>1){moved=true;viewport.classList.add('dragging');}
 });
 viewport.addEventListener('pointermove',e=>{
  const point=contacts.get(e.pointerId);if(!point)return;
  const before=pinch(),dx=e.clientX-point.x,dy=e.clientY-point.y;point.x=e.clientX;point.y=e.clientY;
  if(before){const after=pinch();pinchZoom*=Math.max(1,after.gap)/Math.max(1,before.gap);zoomBook(app,pinchZoom,after.x,after.y,before.x,before.y);}
  else if(moved||Math.hypot(point.x-point.startX,point.y-point.startY)>5){moved=true;viewport.classList.add('dragging');viewport.scrollLeft-=dx;viewport.scrollTop-=dy;}
 });
 const stop=e=>{contacts.delete(e.pointerId);if(contacts.size>1)pinchZoom=app.journeyZoom||1;if(!contacts.size)viewport.classList.remove('dragging');};
 for(const type of ['pointerup','pointercancel','lostpointercapture'])viewport.addEventListener(type,stop);
 viewport.addEventListener('click',e=>{if(moved&&e.detail!==0){e.preventDefault();e.stopPropagation();}},{capture:true});
 viewport.addEventListener('wheel',e=>{
  e.preventDefault();if(!e.deltaY||contacts.size)return;
  const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?viewport.clientHeight:1);
  zoomBook(app,(app.journeyZoom||1)*Math.exp(-Math.max(-1000,Math.min(1000,delta))*.0014),e.clientX,e.clientY);
 },{passive:false});
}
function showBook(app,id,layer){app.stopBattle();app.close();app.screen='journey';const d=data(),target=id==='end'?d.ending:d.at(+id)||d.at(app.journeySelection)||d.at(currentId(app.profile))||d.places[0];app.journeyLayer=layer||target.layer||'surface';app.journeyZoom??=1;const visible=d.places.filter(v=>v.layer===app.journeyLayer&&unlocked(app.profile,v,app.debugMode));app.journeySelection=id==='end'&&!active(app.profile)&&!d.next(app.profile)&&app.journeyLayer===d.ending.layer?'end':visible.some(v=>v.stageId===target.stageId)?target.stageId:(visible.at(-1)?.stageId??null);app.root.innerHTML=bookMarkup(app);mountBook(app);revealBook(app);app.updateAudio();}
function selectBook(app,id){if(id!=='end'&&!data().at(+id))return;const place=id==='end'?data().ending:data().at(+id);if(id!=='end'&&!unlocked(app.profile,place,app.debugMode))return;if(app.debugMode&&id!=='end')return debugRest(app,+id);app.journeySelection=id==='end'?'end':+id;app.root.innerHTML=bookMarkup(app);mountBook(app);revealBook(app);document.querySelector(`[data-action="journey-select"][data-id="${id}"]`)?.focus?.({preventScroll:true});}
function launch(app,id,kind){app.pendingJourneyLaunch=null;delete state(app.profile).pendingDirect;app.launch(id);if(app.engine&&!app.training){app.engine.b.honroJourneyReplay=kind==='replay';app.profile.honroBattle=clone(app.engine.b);app.persist();}}
function requestLaunch(app,id,kind='next'){id=Number(id);if(app.debugMode&&(app.screen!=='rest'||app.debugRestStage!==id))return debugRest(app,id);const st=H.stages[id-1],next=data().next(app.profile);if(!st||(!app.debugMode&&kind==='replay'&&!app.profile.cleared[id])||(!app.debugMode&&kind!=='replay'&&next?.stageId!==id))return;app.stopBattle();const b=active(app.profile);if(b){app.pendingJourneyLaunch={id,kind,session:b.session};app.open(`<h2>진행 중인 전투를 바꿀까요?</h2><p>현재 <strong>${esc(H.stages[(b.honroStage||1)-1].name)}</strong>의 전투가 저장되어 있습니다. <strong>${esc(st.name)}</strong>${kind==='replay'?'을 다시 시작하면':'에 새로 진입하면'} 저장된 전투 하나가 교체됩니다.</p><p>얻은 성장과 지난 완료 기록은 유지됩니다.</p><div class="actions"><button data-action="cancel-journey-launch">취소</button><button class="primary" data-action="confirm-journey-launch">전투를 바꾸고 진입</button></div>`,'journey-confirm');return;}launch(app,id,kind);}
function confirmLaunch(app){const pending=app.pendingJourneyLaunch;if(!pending)return;const b=active(app.profile);if(b?.session!==pending.session){app.pendingJourneyLaunch=null;app.close();app.notify('저장된 전투가 바뀌었습니다. 진입할 길을 다시 골라주세요.');return;}launch(app,pending.id,pending.kind);}
function recordOutcome(app,won){if(!won||app.engine?.b.honroJourneyReplay)return;const next=data().next(app.profile),s=state(app.profile);if(next?.stageId===app.stage.id+1&&data().transitionAfter(app.stage.id)==='direct')s.pendingDirect=next.stageId;else delete s.pendingDirect;}
function resultLabel(app){if(app.customMap)return '원래 여정으로 돌아가기';const splitLabel=G.HonroSplitCampaign?.resultLabel(app);if(splitLabel)return splitLabel;if(app.engine?.b.phase==='lost')return '쉼터로 돌아가기';const next=data().next(app.profile);return app.engine?.b.honroJourneyReplay?'여정첩으로':next&&next.stageId===app.stage.id+1&&data().transitionAfter(app.stage.id)==='direct'?`${towards(next.place)} 이어 걷기`:'다음 쉼터로';}
function resultContinue(app){if(G.HonroSplitCampaign?.resultContinue(app))return;if(!app.engine||!app.done)return;const b=app.engine.b,won=b.phase==='won',id=app.stage.id,replay=b.honroJourneyReplay;app.engine=null;app.profile.honroBattle=null;app.close();if(won)app.debugRestStage=null;if(replay)return showBook(app,id);const next=data().next(app.profile);if(won&&next?.stageId===id+1&&data().transitionAfter(id)==='direct')return launch(app,next.stageId,'next');return showRest(app);}
G.HonroRestJourney={state,location,active,currentId,towards,startEntry,restMarkup,drawPeople,drawActor,layoutRest,startMotion,stopMotion,frame,showRest,nextStory,saveStory,finishStory,talk,bookMarkup,showBook,selectBook,zoomBook,requestLaunch,confirmLaunch,recordOutcome,resultLabel,resultContinue};
})(globalThis);
