import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {monsters} from './recipes.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const dir=path.join(root,'shared/assets/monsters'),out=path.join(root,'_local/reports/monster-forge');
const bytes=s=>Buffer.byteLength(s),sha=s=>createHash('sha256').update(s).digest('hex');
const xml=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
export async function buildMonsters(){
 await mkdir(dir,{recursive:true});await mkdir(out,{recursive:true});
 const sourceFiles=['tools/monster-forge/recipes.mjs','tools/monster-forge/species.mjs'];
 const inputs=await Promise.all(sourceFiles.map(async name=>[name,await readFile(path.join(root,name),'utf8')]));
 const sourceSha256=sha(inputs.map(([name,text])=>name+'\n'+text).join('\n')),rows=[];
 const baseline=JSON.parse(await readFile(path.join(root,'tests/fixtures/monster-baseline.json'),'utf8'));
 for(const a of monsters){
  const ids=new Set();for(const p of a.parts){if(ids.has(p.id)||p.parent&&!ids.has(p.parent))throw Error(`${a.id}: parts must be unique and parent-first: ${p.id}`);ids.add(p.id);}
  for(const clip of Object.values(a.clips))for(const t of clip.tracks){if(!ids.has(t.part)||!['x','y','rotate','scaleX','scaleY'].includes(t.channel)||t.keys[0][0]!==0||t.keys.at(-1)[0]!==1)throw Error(`${a.id}: invalid track`);for(let i=1;i<t.keys.length;i++)if(t.keys[i][0]<=t.keys[i-1][0])throw Error('Unordered keys');}
  const paths=a.parts.flatMap(p=>p.paths);for(const v of paths){if(/NaN|Infinity|[^MLCQZmlcqz\d.,\s+-]/.test(v.d)||v.fill&&!a.palette[v.fill]||v.stroke&&!a.palette[v.stroke])throw Error(`${a.id}: invalid path or palette`);}
  // Expand implicit lineto pairs too; authoring supports only explicit M/L/Q/C and Z.
  function count(d){let anchors=0,controls=0;for(const [,cmd,args] of d.matchAll(/([MLQCZ])([^MLQCZ]*)/gi)){const n=(args.match(/[-+]?(?:\d*\.)?\d+/g)||[]).length,upper=cmd.toUpperCase();if(upper==='M'||upper==='L')anchors+=n/2;else if(upper==='Q'){anchors+=n/4;controls+=n/4;}else if(upper==='C'){anchors+=n/6;controls+=n/3;}}return{anchors,controls};}
  const counts=paths.map(p=>count(p.d)),colors=[...new Set(paths.flatMap(p=>[p.fill,p.stroke]).filter(Boolean))];
  const anchors=counts.reduce((s,c)=>s+c.anchors,0),original=baseline.assets[a.id]?.anchors,ratio=anchors/original;
  if(!original||ratio<2.85||ratio>3.15)throw Error(`${a.id}: ${anchors}/${original} = ${ratio.toFixed(3)}; allowed original-anchor ratio is 2.85–3.15`);
  const raw=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${a.viewBox.join(' ')}" role="img"><title>${a.name}</title>\n${a.parts.map(p=>`<g id="${p.id}" stroke-linejoin="round" stroke-linecap="round">\n${p.paths.map(v=>`<path d="${xml(v.d)}" fill="${v.fill?a.palette[v.fill]:'none'}" stroke="${v.stroke?a.palette[v.stroke]:'none'}" stroke-width="${v.width}" data-lod="${v.lod}"/>`).join('\n')}\n</g>`).join('\n')}\n</svg>\n`;
  const svg=raw.replaceAll(/\n\s*/g,''),rig=JSON.stringify({version:1,baseHeight:a.baseHeight,viewBox:a.viewBox,parts:a.parts.map(({paths,...p})=>p)},null,2)+'\n',anim=JSON.stringify(a.clips,null,2)+'\n';
  await writeFile(path.join(dir,a.id+'.svg'),svg);await writeFile(path.join(dir,a.id+'.rig.json'),rig);await writeFile(path.join(dir,a.id+'.animation.json'),anim);
  rows.push({id:a.id,name:a.name,parts:a.parts.length,paths:paths.length,anchors,originalAnchors:original,anchorRatio:ratio,controls:counts.reduce((s,c)=>s+c.controls,0),colors:colors.length,lodPaths:[0,1,2].map(l=>paths.filter(v=>v.lod<=l).length),rawSvgBytes:bytes(raw),optimizedSvgBytes:bytes(svg),rigBytes:bytes(rig),animationBytes:bytes(anim),sha256:sha(svg)});
 }
 const bundle='// Generated by tools/monster-forge/build.mjs. Edit recipes.mjs and species.mjs.\nglobalThis.HONRO_MONSTERS='+JSON.stringify({version:1,sourceSha256,assets:Object.fromEntries(monsters.map(a=>[a.id,a]))})+';\n';
 await writeFile(path.join(dir,'monsters.runtime.js'),bundle);
 const report={sourceSha256,sourceFiles,anchorBudget:{minRatio:2.85,maxRatio:3.15,baseline:'tests/fixtures/monster-baseline.json'},runtimeBytes:bytes(bundle),counting:'Path anchors include implicit lineto pairs; Q has 1 and C has 2 additional control points. No subdivisions added for quotas.',assets:rows};
 await writeFile(path.join(out,'metrics.json'),JSON.stringify(report,null,2)+'\n');return report;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(JSON.stringify(await buildMonsters(),null,2));
