/** Shared production authoring primitives. Every structural face uses its drawn polygon. */
import {compileSVG} from '../environment/build-act2-art.mjs';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
export const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
export const pts=a=>a.map(([x,y])=>({x,y}));
export const pathD=a=>'M'+a.map(p=>p.join(' ')).join(' L')+' Z';
export const P=(a,fill,stroke='',width=2)=>`<path d="${pathD(a)}" fill="${fill}"${stroke?` stroke="${stroke}" stroke-width="${width}"`:''}/>`;
export const R=(x,y,w,h,c)=>P([[x,y],[x+w,y],[x+w,y+h],[x,y+h]],c);
export const line=(a,c,w=2)=>`<path d="M${a.map(p=>p.join(' ')).join(' L')}" fill="none" stroke="${c}" stroke-width="${w}"/>`;
export function asset(id,name,svg,collision,bounds,material='wood') {const[x,y,w,h]=bounds;return{id,name,category:'architecture',visual:[],vector:compileSVG(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${bounds.join(' ')}">${svg}</svg>`),collision:collision.map(pts),anchor:{x:0,y:0},sockets:[],tags:['act3-production'],params:{collisionSource:'drawn-structural-polygons'},material,breakable:false,oneWay:false,bounds:{x,y,w,h},reference:{heightM:h/60,bounds:{x,y,w,h},foot:{x:0,y:0},scaleRange:[.35,2],backgroundRange:[.35,2]}};}
export function put(p,s,a,id,x,y,scale=1,layer='back'){if(!p.library.some(q=>q.id===a.id))p.library.push(a);s.elements.push({id,assetId:a.id,x,y,scale,rotation:0,snap:false,depthLayer:'L1',layer});return s.elements.at(-1);}
export function terrain(s,id,p,material='stone',properties={}){s.terrains.push({id,name:id,type:'solid',points:pts(p),baseMaterial:material,oneWay:false,breakable:false,layer:'terrain',properties});return s.terrains.at(-1);}
export function foundation(s,profile){terrain(s,'a3-foundation',[...profile,[s.width,s.height],[0,s.height]]);}
export function pool(s,id,x1,x2,y,bottom){s.materials.push({id,kind:'water-pool',conductive:true,points:[[x1,y],[x2,y],[x2,bottom],[x1,bottom]],surface:[[x1,y],[x2,y]],bottom:[[x1,bottom],[x2,bottom]],attached:true});}
export function deck(id,w,h=36,{rail=true,stone=false}={}){const body=[[0,0],[w,0],[w,h],[0,h]],parts=[P(body,stone?'#718081':'#766649'),R(0,0,w,7,stone?'#b1b5a2':'#b7a371')];for(let x=20;x<w;x+=80)parts.push(line([[x,8],[x,h]],stone?'#4b6265':'#4e5141',2));if(rail){parts.push(R(0,-65,w,8,'#685e48'));for(let x=0;x<=w;x+=135)parts.push(R(x,-78,10,78,'#97886a'),R(x-3,-80,16,6,'#c1b088'));}return asset(id,stone?'돌다리·성벽길':'회랑·누마루',parts.join(''),[body],[-5,-88,w+20,h+95],stone?'stone':'wood');}
export function stairs(id,w,rise,{left=false,thin=false}={}){const n=Math.ceil(rise/14),p=[[0,0]],parts=[];for(let i=0;i<n;i++){const x=(i+1)*w/n,y=-(i+1)*rise/n;p.push([x-w/n,y],[x,y]);parts.push(line([[x-w/n,y+5],[x,y+5]],'#aab29a',2));}if(thin){p.push([w,-rise+34],[0,34]);}else p.push([w,45],[0,45]);let all=P(p,'#627676')+parts.join('');if(left){const flip=p.map(([x,y])=>[w-x,y]);all=P(flip,'#627676')+parts.map(v=>`<g transform="matrix(-1 0 0 1 ${w} 0)">${v}</g>`).join('');return asset(id,'반대편 석계단',all,[flip],[0,-rise,w,rise+50],'stone');}return asset(id,'석계단',all,[p],[0,-rise,w,rise+50],'stone');}
export function ramp(id,w,rise,{left=false,thin=false}={}){let poly=[[0,0],[w,-rise],[w,-rise+(thin?36:rise+45)],[0,thin?36:45]];if(left)poly=poly.map(([x,y])=>[w-x,y]);const parts=[P(poly,'#627676'),line(left?[[w,0],[0,-rise]]:[[0,0],[w,-rise]],'#aab29a',7)];for(let x=40;x<w;x+=80){const y=left?-rise+x*rise/w:-x*rise/w;parts.push(line([[x,y+8],[x,y+30]],'#465f63',2));}return asset(id,'하역 경사로',parts.join(''),[poly],[0,-rise,w,rise+50],'stone');}
export function hall(id,w,h,{roof=110,floors=1,wall='#a5a98f',timber='#655442',style='hall',cutaway=true,floorBreaks=[]}={}){
 const l=-w/2,r=w/2,eave=-h,peak=eave-roof,parts=[],solids=[];
 const roofPoly=[[l-42,eave-6],[l-8,eave-30],[-w*.2,peak+12],[0,peak],[w*.2,peak+12],[r+8,eave-30],[r+42,eave-6],[r+30,eave+21],[l-30,eave+21]];
 // Cutaway rear planes intentionally have no collision; visible floors and roof do.
 parts.push(R(l,eave+20,w,h-20,wall),R(l+18,eave+34,w-36,h-47,'#64756a'),R(l+w*.69,eave+35,w*.28,h-50,'#506560'));
 for(let f=0;f<floors;f++){const fy=-f*h/floors,hh=h/floors;for(let x=l+34,j=0;x<r-70;x+=112,j++){const wy=fy-hh+65;parts.push(R(x,wy,74,Math.min(150,hh-94),'#b7b79b'),R(x+6,wy+6,62,Math.min(138,hh-106),'#9ca78d'));for(let z=1;z<5;z++)parts.push(R(x+z*14,wy+6,3,Math.min(138,hh-106),'#61746b'));parts.push(R(x+4,wy+52,66,4,'#6a7d71'));}
  const gaps=floorBreaks.filter(q=>q.floor===f),ranges=[];let start=l;for(const q of gaps.sort((a,b)=>a.x1-b.x1)){ranges.push([start,q.x1]);start=q.x2;}ranges.push([start,r]);
  for(const [a,b]of ranges){if(b<=a)continue;const poly=[[a,fy],[b,fy],[b,fy+26],[a,fy+26]];parts.push(P(poly,'#73684f'),R(a,fy,b-a,7,'#b5a27b'));if(f>0||!cutaway)solids.push(poly);}
  parts.push(R(l,fy-hh+27,w,14,timber));
 }
 for(let x=l+18;x<r;x+=Math.max(160,w/5))parts.push(R(x,eave+30,17,h-30,timber),R(x+3,eave+35,4,h-40,'#a28e67'));
 if(!cutaway){const body=[[l,eave+22],[r,eave+22],[r,0],[l,0]];solids.unshift(body);}
 if(style==='granary'){for(let x=l+40;x<r-60;x+=95){parts.push(R(x,-120,66,104,'#a08b58'),R(x,-120,66,10,'#c2ad78'),line([[x+5,-110],[x+61,-24],[x+61,-110],[x+5,-24]],'#695d40',4));}}
 if(style==='market')for(let x=l+35,j=0;x<r-80;x+=110,j++)parts.push(P([[x,-185],[x+95,-185],[x+122,-113],[x-20,-113]],j%2?'#987862':'#78968c'),R(x-14,-112,129,14,'#b5a58a'));
 if(style==='burnt'){parts.push(P([[l+20,eave+20],[l+w*.22,eave+70],[l+w*.32,-14],[l+20,-14]],'#394b49'));for(const x of [l+22,l+w*.38,r-38])parts.push(P([[x,eave+30],[x+19,eave-70],[x+31,0],[x+7,0]],'#343f3b'));}
 parts.push(P(roofPoly,'#29404a','#1c323a',4),P([[l-23,eave-8],[-w*.2,peak+17],[0,peak+7],[w*.18,peak+20],[r+25,eave-8],[r-13,eave+2],[0,peak+32],[l+14,eave+3]],style==='burnt'?'#526160':'#69817c'));
 for(let x=l+20;x<r;x+=54){const y=peak+29+Math.abs(x)/(w/2)*(roof-24);parts.push(line([[x,y],[x+(x<0?-20:20),eave+5]],'#8a9b8d',2));}
 parts.push(line([[l-34,eave+10],[r+34,eave+10]],'#a6aa90',5),R(l-10,eave+23,w+20,11,'#4d7062'));solids.push(roofPoly);
 const a=asset(id,'실내가 열린 '+style,parts.join(''),solids,[l-50,peak-12,w+100,h+roof+45]);a.params.rearPlanes=['wall','windows','posts'];a.params.floorHeight=h/floors;a.params.style=style;return a;
}
export async function svgAsset(name){const dir=path.join(ROOT,'shared/assets/environment/act3-architecture');try{const m=JSON.parse(await readFile(path.join(dir,'production-manifest.json'),'utf8')),row=m.assets.find(a=>a.file===name);if(!row)return null;const v=compileSVG(await readFile(path.join(dir,name),'utf8')),a=asset(row.id,row.name,'',(row.suggestedSolids||[]).map(q=>q.points),v.viewBox);a.vector=v;a.reference=row.reference;a.params.collisionContract={file:name,solids:row.suggestedSolids};return a;}catch{return null;}}
export function marker(s,id,x,y,label,{action=false,requiredClass,target,type='act3'}={}){const m={id,type,x,y,label};if(action)m.action='act3';if(requiredClass)m.requiredClass=requiredClass;if(target)m.target=target;s.markers.push(m);return m;}
export function target(s,id,x,y,{hp=100,material='wood'}={}){const t=terrain(s,id,[[x-28,y-100],[x+28,y-100],[x+29,y],[x-29,y]],material,{hp,maxHp:hp,honroAct3Target:true,honroSeal:true});t.breakable=true;return t;}
export function gate(s,id,x,y,h=175){const t=terrain(s,id,[[x-22,y-h],[x+22,y-h],[x+22,y],[x-22,y]],'wood',{hp:100000,maxHp:100000,honroAct3Gate:true});t.breakable=true;return t;}
export function enemy(s,id,kind,x,y,cohort='street'){s.units.push({id,kind,team:'enemy',x,y,facing:-1,spawnIndex:s.units.filter(u=>u.team==='enemy').length,behavior:'patrol',stageOverrides:{honroCohort:cohort}});}
export function npc(s,id,x,y,{carrier=false}={}){s.units.push({id,kind:'object:civilian',team:'npc',x,y,facing:1,label:carrier?'기록 운반인':'주민',stageOverrides:{honroProtected:true,...(carrier?{fixed:false,maxMove:900,moveLeft:900}:{})}});}
export function players(s,x,y){for(const [i,kind]of ['archer','mage','knight','occultist'].entries())s.units.push({id:'p-'+kind,kind,team:'player',x:x+i*100,y,facing:1});s.anchors={spawn:{x,y},start:{x,y}};}
export function stage(g,id,name,width,height,kind){const s=g.HonroMaps.emptyStage('stage-'+id,name,width,height);s.metadata={stageId:id,act:3,actStage:id-20,campaign:true};s.initialState={honroAct3Revision:1,honroActiveLimit:3,honroState:{flags:{},collected:[],hold:0,lastRound:1,rescued:false,combatLog:[]}};s.meta={notes:`3-${id-20} ${name} · production architecture, ordinary movement`,seed:3000+id};s.design={act3:{version:1,kind,mainBuildings:[],bridges:[],requiredRoute:[],optionalRoutes:[],shotSamples:[],scope:'Canonical geometry; normal combat and mission completion require separate runtime verification.'}};s.routes=[];s.anchors={};return s;}
export function cityEnvironment(p,s,{mood='day',density=1,ground=2500,interior=false}={}){const colors={day:['#526f7e','#c0c2a2'],late:['#5b6972','#c4aa87'],burnt:['#59646a','#a9a18c'],night:['#152b3a','#536e75'],garden:['#687f82','#c3c6a5'],inside:['#3a4e50','#95a595']}[mood]||['#526f7e','#c0c2a2'];const E={version:4,preset:interior?'enclosed':'forest',skyVisible:true,atmosphere:{preset:interior?'enclosed':'temple',overrides:{skyTop:colors[0],skyBottom:colors[1],hazeStrength:interior?.18:.27,mistStrength:interior?.035:.07,lightStrength:mood==='night'?.06:.12}},zones:[{id:'act3-world',from:0,to:s.height,blend:200}],groups:[],surfaces:[],placements:[]};
 const types=[hall('a3-background-house',660,330,{cutaway:false}),hall('a3-background-office',920,550,{floors:2,wall:'#8d9a8b',cutaway:false}),hall('a3-background-granary',780,430,{style:'granary',cutaway:false}),hall('a3-background-low-market',540,240,{style:'market',cutaway:false})];for(const a of types){a.collision=[];a.tags=['act3-rear-city'];if(!p.library.some(b=>b.id===a.id))p.library.push(a);}
 if(!interior)for(const [layer,y,scale,step,offset]of [['L3',ground-450,.78,780/density,120],['L2',ground-150,.86,1130/density,420]]){const group={id:'a3-town-'+layer,depthLayer:layer,verticalMode:'WORLD',zoneId:'act3-world',x:0,y};E.groups.push(group);const support={id:group.id+'-ground',groupId:group.id,kind:'rear-ground',points:[{x:-18000,y:0},{x:s.width+18000,y:0}],bottom:18000};E.surfaces.push(support);for(let x=-6000,i=0;x<s.width+6000;x+=step,i++)E.placements.push({id:`a3-bg-${layer}-${i}`,assetId:types[(i+(s.metadata.stageId%4))%types.length].id,depthLayer:layer,groupId:group.id,supportId:support.id,x:x+offset,y:0,scale:scale*(i%3===0?1.08:.94),rotation:0});}s.environment=E;}
export function inside(x,y,ps){let k=false;for(let i=0,j=ps.length-1;i<ps.length;j=i++){const a=ps[i],b=ps[j];if((a.y>y)!=(b.y>y)&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x)k=!k;}return k;}
export function support(g,ts,x,y){const hits=ts.flatMap(t=>g.HONRO_CORE.terrainSurfaces(t,x).map(q=>({...q,t}))).filter(q=>Math.abs(q.slope)<=1.35&&!ts.some(t=>inside(x,q.y-2,g.HONRO_CORE.poly(t)))).sort((a,b)=>Math.abs(a.y-y)-Math.abs(b.y-y));return hits.length?{x,y:hits[0].y,support:hits[0].t.id}:null;}
export function settle(g,p,s){const ts=g.HonroMaps.compile(s,p).terrain.filter(t=>!t.honroAct3Target&&!t.honroAct3Gate);for(const u of s.units){const q=support(g,ts,u.x,u.y);if(!q)throw Error(`${s.id} ${u.id} has no support`);u.y=q.y;}for(const m of s.markers){const q=support(g,ts,m.x,m.y);if(!q)throw Error(`${s.id} ${m.id} has no support`);m.y=q.y;}s.design.act3.requiredRoute=s.design.act3.requiredRoute.map(v=>({...v,...support(g,ts,v.x,v.y)}));for(const r of s.design.act3.optionalRoutes)r.points=r.points.map(v=>({...v,...support(g,ts,v.x,v.y)}));s.routes=s.design.act3.requiredRoute.map(({x,y})=>({x,y}));s.anchors.spawn={x:s.units[0].x,y:s.units[0].y};s.anchors.exit={x:s.markers.at(-1).x,y:s.markers.at(-1).y};}
