/** Author only the fresh Stage8 map; old saved battles remain self-contained. */
import {BIER_SIZE,BIER_LAYOUT,BIER_NODES,bierTerrains,bierY,bierPose,bierRoutes,bierMovementSpec} from './stage8-bier-geometry.mjs';
export * from './stage8-bier-geometry.mjs';
const clone=v=>JSON.parse(JSON.stringify(v));
const SEEDS=[
 ['A-front','hound',1820,'s8-ground'],['A-front','boar',1940,'s8-ground'],['A-rear','hound',2100,'s8-ground'],['A-air','crow',2270,3570],
 ['B-front','hound',2400,'s8-ground'],['B-front','boar',2635,'s8-ground'],['B-front','hound',2780,'s8-ground'],['B-side','warden',3310,'s8-west-walk',true],['B-side','lantern',3430,3750],['B-rear','crow',3680,3940],
 ['C-front','hound',4080,'s8-west-court'],['C-front','boar',4190,'s8-west-court'],['C-front','hound',4300,'s8-west-court'],['C-support','lantern',5760,3860,true],['C-air','crow',6340,3550],
 ['D-west','crow',3250,3450],['D-west','crow',4630,2270],['D-east','crow',5520,2310,true],['D-east','ghost',5860,'s8-east-shoulder'],
 ['E-front','hound',6210,'s8-ground'],['E-front','boar',6330,'s8-ground'],['E-bend','warden',6880,'s8-ground',true],['E-rear','hound',7310,'s8-ground'],
 ['F-front','warden',7660,'s8-court',true],['F-front','hound',7790,'s8-court'],['F-rear','ghost',8650,'s8-ground'],['F-air','crow',8940,2260],['F-air','crow',9190,2390]
];
export function bierEncounterSeeds(roster='candidate28e5'){if(!['candidate28e5','oldBudget20e0'].includes(roster))throw Error('Unsupported Stage8 roster '+roster);const omit=new Set([2,6,9,12,16,18,22,27]);return SEEDS.flatMap(([cell,kind,x,support,elite=false],i)=>roster==='oldBudget20e0'&&omit.has(i)?[]:[{id:'s8-'+i,cell,kind,x,y:typeof support==='string'?bierY(support,x):support,support:typeof support==='string'?support:null,elite:roster==='candidate28e5'&&elite,air:typeof support!=='string'}]);}
export function bierEntrySpec(){const at=(id,x)=>({...bierPose(id,x),support:id,spacing:130,maxDistance:0});return{
 'stage8-first-seal':{side:'west',...at('s8-ground',1550),alternates:[at('s8-ground',1120)]},
 'stage8-settled-crows':{side:'upper-branch',x:5220,y:2290,spacing:145,maxDistance:0,air:true,alternates:[{x:5670,y:2510,spacing:145,maxDistance:0,air:true}]},
 'stage8-low-health':{side:'east',...at('s8-ground',9000),alternates:[at('s8-ground',9320)]}
};}
export async function authorStage8Bier(project,g,{roster='candidate28e5',art=true}={}){
 const p=clone(project),index=p.stages.findIndex(s=>s.metadata?.stageId===8);if(index<0)throw Error('Stage8 missing');const before=JSON.stringify(p.stages.filter((_,i)=>i!==index)),old=p.stages[index],s=clone(old),oldAssets=JSON.stringify(p.library.filter(a=>!a.id.startsWith('stage8:bier-')));
 Object.assign(s,{...BIER_SIZE,backdrop:'valley',terrains:bierTerrains(),elements:[],materials:[],units:[],events:[],encounters:[],markers:[],routes:[],camera:{}});for(const k of ['playBounds','terrainBounds','terrainDomainVersion','detailStats'])delete s[k];
 s.initialState={honroStage8BierRevision:1,honroStage8BierRoster:roster,honroActiveLimit:4,enemyLimit:4,honroStage8BierPopulationCap:(roster==='candidate28e5'?29:21)+8,honroState:{flags:{},collected:[],hold:0,lastRound:1,rescued:false,combatLog:[]}};
 for(const[cls,x]of[['archer',770],['mage',880],['knight',990]])s.units.push({id:'p-'+cls,kind:cls,team:'player',...bierPose('s8-ground',x),facing:1});
 for(const[id,x,support]of[['bier-knot-0',2520,'s8-ground'],['bier-knot-1',7920,'s8-east-hatch']]){const original=old.terrains.find(t=>t.id===id),y=bierY(support,x);if(!original)throw Error('Original seal missing '+id);s.terrains.push({...clone(original),points:[[x-42,y-148],[x+42,y-148],[x+42,y],[x-42,y]].map(([x,y])=>({x,y})),oneWay:false,properties:{...clone(original.properties),hp:480,maxHp:480,honroStage8Bier:true,honroMeleeTarget:true}});}
 const seeds=bierEncounterSeeds(roster);for(const row of seeds){s.units.push({id:row.id,kind:row.kind,team:'enemy',x:row.x,y:row.y,facing:-1,spawnIndex:seeds.indexOf(row),encounterGroup:row.cell,stageOverrides:{honroStage8BierEnemy:true,honroStage8BierElite:row.elite,elite:row.elite,honroCohort:row.cell,honroEncounterRole:row.air?'aerial-support':row.cell.endsWith('front')?'frontline':'flank-guard',honroEncounterSupport:row.support,honroCluster:row.cell,...(row.air?{fixed:true}:{})}});}
 s.encounters=[...new Set(seeds.map(u=>u.cell))].map(id=>({id,key:id,behavior:'patrol',unitIds:seeds.filter(u=>u.cell===id).map(u=>u.id)}));
 const boss=clone(old.units.find(u=>u.id==='boss'));if(!boss)throw Error('Existing bier boss missing');Object.assign(boss,{...bierPose('s8-east-hatch',8290),spawnX:8290,spawnY:bierY('s8-east-hatch',8290)});s.units.push(boss);
 const restPos=[bierPose('s8-ground',1220),bierPose('s8-ground',4700),bierPose('s8-branch',5190)];for(const[m,i]of old.markers.filter(m=>m.type==='rest').map((m,i)=>[m,i]))s.markers.push({...clone(m),...restPos[i]});if(s.markers.length!==3)throw Error('Exactly original three embers required');
 s.anchors={start:bierPose('s8-ground',770),spawn:bierPose('s8-ground',770),store:bierPose('s8-ground',2120),knotWest:bierPose('s8-ground',2520),courtyard:bierPose('s8-court',5950),storeHollow:bierPose('s8-west-court',4300),knotEast:bierPose('s8-east-hatch',7920),bier:bierPose('s8-east-hatch',8290),exit:bierPose('s8-ground',9370)};
 for(const[id,pos]of Object.entries(s.anchors))s.anchors[id]={...pos,support:pos.surfaceId};
 const entries=bierEntrySpec();s.initialState.honroStage8BierSpec={movement:bierMovementSpec(),entries};
 for(const[id,gate,kind,n,warning]of[['stage8-first-seal','first-seal','hound',3,'서쪽 장례 창고의 문틈으로 산개 셋이 다가온다.'],['stage8-settled-crows','settled-crows','crow',3,'상여가 내려앉은 뒤 큰 가지 쪽에서 까마귀 셋이 날아든다.'],['stage8-low-health','low-health','hound',2,'동쪽 상여터 뒤로 산개 둘이 다가온다.']]){const a=entries[id];s.events.push({id,once:true,when:{after:'stage8-gate-'+gate},warning,text:warning,entry:{x:a.x,y:a.y},action:{type:'spawn',kind,n,x:a.x,y:a.y,spacing:a.spacing,maxDistance:0,source:id,honroStage8Bier:true}});}
 const routes=bierRoutes(),nodes=clone(BIER_NODES),surfaces=BIER_LAYOUT.surfaces.filter(t=>t.top.length>1&&!['thin-screen','low-cover'].includes(t.role)).map(t=>({id:t.id,terrainId:t.id,role:t.role,edgeIndices:t.top.slice(1).map((_,i)=>i),roomIds:['bier-'+t.zone]}));
 s.design={bier:{revision:1,nodes,routes,initial:seeds.length+1,ordinary:seeds.length,elites:seeds.filter(u=>u.elite).length,finite:8,activeLimit:4,requiredRiseMax:150,entryLevel:7,entryXP:8644,primaryContour:clone(BIER_LAYOUT.surfaces[0].top),scope:'Connected buried store / two unequal courts; short wood maintenance hatch is one-way. Route cost and normal completion are distinct evidence.'},space:{version:1,geometryRevision:1,topologyId:'buried-bier-store-and-unequal-courts',rooms:Object.entries(nodes).map(([id,n])=>({id:'bier-'+id,terrainIds:BIER_LAYOUT.surfaces.filter(t=>t.zone===id).map(t=>t.id),ceilingIds:({A:['s8-west-root'],B:['s8-west-root','s8-west-shoulder'],H:['s8-west-shoulder'],G:['s8-west-court','s8-west-shoulder','s8-east-plinth'],E:['s8-court']}[id]||[]),bounds:{x:n.x-850,y:n.y-550,w:1700,h:1100},sky:['B','H','G'].includes(id)?'cave':['A','E'].includes(id)?'transition':'open',landmarkIds:[]})),surfaces,routes,connections:routes.map(r=>({id:r.id,from:'bier-'+r.id[0],to:'bier-'+r.id[1],kind:'walk',routeId:r.id,entry:clone(r.anchors[0]),exit:clone(r.anchors.at(-1)),requires:[]})),sites:{west:{objectiveId:'bier-knot-0',roomId:'bier-B',...bierPose('s8-ground',2420),standing:bierPose('s8-ground',2420),target:{x:2520,y:bierY('s8-ground',2520)-74,terrainId:'bier-knot-0'}},east:{objectiveId:'bier-knot-1',roomId:'bier-F',...bierPose('s8-east-hatch',7820),standing:bierPose('s8-east-hatch',7820),target:{x:7920,y:bierY('s8-east-hatch',7920)-74,terrainId:'bier-knot-1'}}},encounterSites:[],landmarks:[],scenery:[],lights:[],views:[]}};
 s.routes=routes.filter(r=>['AB','BC','CF'].includes(r.id)).flatMap(r=>r.anchors.map(({x,y,surfaceId})=>({x,y,surfaceId})));s.environment=g.HonroEnvironment.makeEnvironment(s,{preset:'forest'});s.environment.skyVisible=true;p.stages[index]=s;
 if(art){const{applyStage8BierArt}=await import('../environment/stage8-bier-art.mjs');await applyStage8BierArt(p);}
 const result=g.HonroMaps.finalize(g.HonroTerrainDomain.author(p));if(JSON.stringify(result.stages.filter((_,i)=>i!==index))!==before)throw Error('Stage8 author changed another map');if(JSON.stringify(result.library.filter(a=>!a.id.startsWith('stage8:bier-')))!==oldAssets)throw Error('Stage8 author changed unrelated assets');return result;
}
