// Ordered state fixtures and source/runtime regressions. This is not a normal
// input combat playthrough or a geometry/visual approval.
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {runtime,battlefield} from '../game/tests/helpers.mjs';
const g=await runtime({legacyMaps:false}),C=g.HONRO_CORE,A=g.HonroAct3,P=g.HonroProgression,plain=x=>JSON.parse(JSON.stringify(x)),checks=[];
const check=(name,fn)=>{fn();checks.push(name);console.log('PASS',name);};
const fixture=id=>{const q=battlefield(g,id);A.attach(q.app,q.e);q.app.canInput=()=>!q.app.dialogue&&q.b.side===0&&q.b.phase==='aim';return q;};
const ready=(q,s)=>{const u=q.e.heroesAlive().find(u=>u.cls===(s.requiredClass||'archer'));q.b.active=u.id;q.b.phase='aim';q.b.side=0;u.acted=false;q.app.actorBoundary=u.id;return u;};
const clearNear=(q,m)=>{for(const u of q.e.alive(1))if(A.sameFloor(u,m,600)){u.hp=0;u.dead=true;}};
const authored=g.HONRO_PROJECT.stages.filter(s=>s.metadata.stageId>=21).map(s=>s.metadata.stageId);
check('30 chapters keep a bounded ten-stage Act 3 and unavailable Act 4',()=>{assert.equal(g.HONRO_CONTENT.stages.length,30);assert.equal(g.HONRO_CONTENT.nextAct.id,4);assert.equal(g.HONRO_CONTENT.nextAct.available,false);for(let id=21;id<=30;id++){const st=g.HONRO_CONTENT.stages[id-1];assert.deepEqual(plain(st.requires),[id-1]);assert.equal(st.objective,'act3');assert(!st.steps.some(s=>s.kind==='clear'),'no extermination objectives');assert(st.story.length<=3);assert(st.outro.length<=3);}});
check('Canonical revelations remain in their chapter and reserve later-act answers',()=>{const chapter=id=>JSON.stringify(g.HONRO_CONTENT.stages[id-1]);assert(chapter(22).includes('반란군 마을이 아니라'));assert(chapter(25).includes('주민 전원을 죽였다고'));assert(chapter(25).includes('무명사'));assert(chapter(28).includes('주민 전원을 죽이라는 명령은 없습니다'));assert(chapter(29).includes('스승께 들린 혼은 없었다'));assert(chapter(30).includes('고향 곁'));for(let id=21;id<=30;id++){const text=chapter(id);for(const forbidden of ['유골과 재를 점토','저승에서도 들리는 종','현묵이 살아','담허가 죽','왕이 학살을 명령'])assert(!text.includes(forbidden));}});
for(const id of authored)check(`Stage ${id}: complete ordered source contract and current objective, finite balance`,()=>{const q=fixture(id);assert.equal(A.sourceIssue(q.b),null);assert(!A.state(q.b).complete);assert.equal(q.e.heroesAlive().length,4);assert(q.b.honroGrowth.weight>=q.b.units.filter(u=>u.side===1).reduce((n,u)=>n+(u.honroXpWeight||1),0));assert(q.b.units.every(u=>Number.isFinite(u.hp)&&Number.isFinite(u.attack)));assert.deepEqual(plain(g.HonroDifficulty.audit(q.st,q.b).issues),[]);assert.deepEqual(plain(A.state(plain(q.b))),plain(A.state(q.b)));});
for(const id of authored)check(`Stage ${id}: ordered action/hold/escort progress and replay-safe save`,()=>{const q=fixture(id),{b,e,app,st}=q;for(const s of st.steps){assert.equal(A.current(b)?.id,s.id);const u=ready(q,s),m=A.marker(b,s.id);clearNear(q,m);if(s.kind==='destroy'){e.damageTerrain(b.terrain.find(t=>t.id===s.id),1e6,0,u.id);}else if(s.kind==='hold'){Object.assign(u,{x:m.x,y:m.y});A.tick(app,0);for(let n=0;n<s.rounds+3&&!A.memory(b).done[s.id];n++){for(const v of e.alive(1))if(v.honroSpawnSource==='act3-'+s.id||A.sameFloor(v,m,600)){v.hp=0;v.dead=true;}b.teamEnds[1]++;A.tick(app,0);}assert.equal(A.memory(b).holds[s.id].spawned,s.wave.count);}else if(s.kind==='reach'){for(const v of s.allHeroes?e.heroesAlive():[u])Object.assign(v,{x:m.x,y:m.y});}else if(s.kind==='escort'){Object.assign(e.unit(s.target),{x:m.x,y:m.y});Object.assign(u,{x:m.x+60,y:m.y});}else{const point=A.interactionTarget(b,m);Object.assign(u,{x:point.x,y:point.y});clearNear(q,point);assert(A.eligibility(app,m).ok,`${id}/${s.id}: ${A.eligibility(app,m).reason}`);assert(A.use(app,m));assert(!A.use(app,m),'repeated E cannot repeat action');}A.tick(app,0);assert(A.memory(b).done[s.id],id+'/'+s.id);if(s.opens)assert(b.terrain.find(t=>t.id===s.opens).broken);assert.deepEqual(plain(A.state(plain(b))),plain(A.state(b)));}assert(A.state(b).complete);assert(app.speeches.length);P.complete(b);const once=plain(b.heroes);P.complete(b);assert.deepEqual(plain(b.heroes),once);});
check('Rescue follows live NPC and refuses stale or wrong-floor location',()=>{const q=fixture(21),m=A.marker(q.b,'gate-resident'),npc=q.e.unit(m.target),a=A.memory(q.b);a.done['wagon-lock']=true;const u=ready(q,{kind:'rescue'});npc.x+=450;npc.y-=350;Object.assign(u,{x:m.x,y:m.y});assert.equal(A.interactionTarget(q.b,m),npc);assert(!A.eligibility(q.app,m).ok);Object.assign(u,{x:npc.x,y:npc.y});clearNear(q,npc);assert(A.eligibility(q.app,m).ok);const t=A.state(q.b).targets[0];assert.equal(t.x,npc.x);assert.equal(t.y,npc.y-npc.h);q.e.hurt(npc,1e9,u.id);assert(npc.hp>0&&!npc.dead,'friendly damage cannot kill protected NPC');npc.dead=true;assert.equal(A.interactionTarget(q.b,m),null);assert.match(A.failure(q.b),/주민/);});
check('Destroying a later latch early cannot skip steps, gates or story',()=>{const q=fixture(22),t=q.b.terrain.find(t=>t.id==='upper-latch'),gate=q.b.terrain.find(t=>t.id==='upper-door');q.e.damageTerrain(t,1e6,0,q.e.heroesAlive().find(u=>u.cls==='archer').id);A.tick(q.app,0);assert.equal(A.current(q.b).id,'archive-seal');assert(!gate.broken);assert.equal(q.app.speeches.length,0);A.memory(q.b).done['archive-seal']=true;A.memory(q.b).done['ledger-case']=true;A.tick(q.app,0);assert(gate.broken);const n=q.app.speeches.length;A.tick(q.app,0);assert.equal(q.app.speeches.length,n);});
check('Hold pauses for dialogue and wrong storey, counts each enemy end once',()=>{const q=fixture(21),a=A.memory(q.b),s=q.st.steps[2],m=A.marker(q.b,s.id),u=ready(q,s);a.done['wagon-lock']=a.done['gate-resident']=true;clearNear(q,m);Object.assign(u,{x:m.x,y:m.y});A.tick(q.app,0);q.app.dialogue={};q.b.teamEnds[1]++;A.tick(q.app,.5);assert.equal(a.holds[s.id].progress,0);q.app.dialogue=null;A.tick(q.app,0);assert.equal(a.holds[s.id].progress,1);A.tick(q.app,0);assert.equal(a.holds[s.id].progress,1);u.y-=800;A.tick(q.app,0);q.b.teamEnds[1]++;A.tick(q.app,0);assert.equal(a.holds[s.id].progress,1);});
check('Corporeal fiends die normally, remain enemy-side corpses and grant XP once',()=>{const q=fixture(23),u=q.b.units.find(u=>u.honroAct3Fiend);assert(u&&!u.honroNonlethal);q.e.hurt(u,1e8,q.e.active.id);assert(u.dead&&u.hp===0);assert.equal(u.side,1);assert(!u.honroCivilian&&!u.honroSubdued);const xp=plain(q.b.heroes);q.e.hurt(u,1e8,q.e.active.id);A.tick(q.app,0);assert.deepEqual(plain(q.b.heroes),xp);});
check('Enthralled fiends return to enemy combat after release and can be slain',()=>{for(const rank of [1,8]){const q=fixture(23),u=q.b.units.find(u=>u.honroAct3Fiend&&!u.elite),owner=q.e.heroesAlive().find(u=>u.cls==='occultist');assert(q.e.captureEnemy(u,owner,rank,false));assert(u.enthrall&&u.side===0);q.e.releaseEnemy(u);A.tick(q.app,0);assert(!u.honroSubdued&&!u.honroNonlethal&&!u.enthrall&&u.side===1);q.e.hurt(u,1e8,owner.id);assert(u.dead&&u.hp===0&&u.side===1);}});
check('Missing authoring never appears complete and saved steps remain frozen',()=>{const q=fixture(21);const snapshot=plain(q.b.honroAct3Steps);q.b.honroMarkers=[];for(const s of A.steps(q.b))A.memory(q.b).done[s.id]=true;assert(A.sourceIssue(q.b));assert(!A.state(q.b).complete);const st=q.st.steps;q.st.steps=[];assert.deepEqual(plain(A.steps(q.b)),snapshot);q.st.steps=st;});
check('Required surviving class is checked only for unfinished work',()=>{const q=fixture(22),u=q.e.heroesAlive().find(u=>u.cls==='knight');u.dead=true;assert.match(A.failure(q.b),/휘겸/);A.memory(q.b).done['archive-seal']=true;assert.equal(A.failure(q.b),null);});
if(authored.includes(27))check('Fire pressure uses enemy turns, stops after both controls and has recoverable failure',()=>{const q=fixture(27);A.tick(q.app,0);q.app.dialogue={};q.b.teamEnds[1]=12;A.tick(q.app,1);assert.equal(A.memory(q.b).fireTurns,0);q.app.dialogue=null;A.tick(q.app,0);assert.match(A.failure(q.b),/불길/);const fresh=fixture(27);A.memory(fresh.b).done['water-release']=A.memory(fresh.b).done['fire-screen']=true;fresh.b.teamEnds[1]=100;A.tick(fresh.app,0);assert.equal(A.failure(fresh.b),null);});
if(authored.includes(30))check('Final escape needs all living actual heroes but never summons or defeated heroes',()=>{const q=fixture(30);for(const s of q.st.steps.slice(0,-1))A.memory(q.b).done[s.id]=true;const s=q.st.steps.at(-1),m=A.marker(q.b,s.id),all=q.e.heroesAlive();Object.assign(all[0],{x:m.x,y:m.y});A.tick(q.app,0);assert(!A.state(q.b).complete);for(const u of all)Object.assign(u,{x:m.x,y:m.y});q.b.units.push({...plain(all[0]),id:'summon-fixture',summoned:true,x:100},{...plain(all[0]),id:'enthrall-fixture',enthrall:3,x:100});A.tick(q.app,0);assert(A.state(q.b).complete);});
await mkdir('_local/reports/act3-runtime',{recursive:true});await writeFile('_local/reports/act3-runtime/objectives.json',JSON.stringify({checks,authoredStages:authored,scope:'State fixtures; not normal combat, traversal or browser proof.'},null,2));
if(!process.env.HONRO_ACT3_PARTIAL)assert.equal(authored.length,10,'All ten production maps must exist for the final test');else console.log('PARTIAL MAP SNAPSHOT:',authored.length,'/10; complete campaign not claimed');
