// Deterministic reward-ledger simulation, not a playable campaign clear.
import assert from 'node:assert/strict';
import {writeFile,mkdir} from 'node:fs/promises';
import {runtime,battlefield} from '../game/tests/helpers.mjs';
const g=await runtime({legacyMaps:false}),C=g.HONRO_CORE,P=g.HonroProgression,plain=x=>JSON.parse(JSON.stringify(x)),checks=[],table=[];
const check=(name,fn)=>{fn();checks.push(name);console.log('PASS',name);};
const p=C.defaults();p.recruited=['archer'];p.cleared={};delete p.honroGrowth;
check('First-clear ledger reproduces unchanged Acts 1 and 2 through 61,569 XP',()=>{for(let id=1;id<=20;id++){const st=g.HONRO_CONTENT.stages[id-1];if(id===11)g.HonroAct2.recruit(p);const {b}=battlefield(g,id,{profile:p});P.complete(b);p.heroes=plain(b.heroes);p.honroGrowth=plain(b.honroGrowth.ledger);p.cleared[id]={rounds:1};P.recruit(p,st);const oldStart=P.rewardXpAt(P.plan(id).entryLevel),oldEnd=P.rewardXpAt(P.plan(id).exitLevel);assert.deepEqual(plain(P.budget(id)),{start:oldStart,end:oldEnd,total:oldEnd-oldStart,combat:Math.round((oldEnd-oldStart)*.4)});}assert.equal(p.heroes.archer.xp,61569);assert.equal(P.legacyCampaignAnchor(),61569);for(const cls of p.recruited){assert.equal(C.levelOf(p.heroes[cls]),15);assert.equal(C.pointsEarned(p.heroes[cls]),31);}});
check('Ten new stage budgets use the current curve and reach level 22 with cap 30 unchanged',()=>{assert.equal(C.MAX_LEVEL,30);let prior=P.legacyCampaignAnchor();for(let id=21;id<=30;id++){const plan=P.plan(id),v=P.budget(id);assert.equal(plan.balanceStatus,'proposed');assert.equal(plan.rewardCurve,'current');assert.equal(v.start,prior);assert(v.total>0);assert.equal(v.end,P.xpAt(plan.exitLevel));assert.equal(v.combat,Math.round(v.total*.4));table.push({stage:id,entryXp:v.start,exitXp:v.end,totalXp:v.total,combatXp:v.combat,exitLevel:plan.exitLevel,pointsAtExit:C.pointsEarned({xp:v.end})});prior=v.end;}assert.equal(C.levelOf(prior),22);assert.equal(C.pointsEarned({xp:prior}),45);});
check('Current-curve budgets do not inherit the old level-25 zero-XP plateau',()=>{const plan=P.plan(30),before=plain(plan);Object.assign(plan,{entryLevel:25,exitLevel:25.65});const v=P.budget(30);assert(v.total>0);assert.equal(P.rewardXpAt(25),P.rewardXpAt(26));Object.assign(plan,before);});
check('Retry ledger and export/import never duplicate combat or clear XP',()=>{let q=battlefield(g,21,{profile:p});const budget=plain(q.b.honroGrowth.limit),start=q.b.heroes.archer.xp;P.awardCombat(q.e,q.e.active,1e8);assert.equal(q.b.heroes.archer.xp,start+budget.combat);P.awardCombat(q.e,q.e.active,1e8);assert.equal(q.b.heroes.archer.xp,start+budget.combat);const retry=plain(p);retry.heroes=plain(q.b.heroes);retry.honroBattle=plain(q.b);retry.honroGrowth=plain(q.b.honroGrowth.ledger);q=battlefield(g,21,{profile:retry});assert.deepEqual(plain(q.b.honroGrowth.limit),budget);P.awardCombat(q.e,q.e.active,1e8);assert.equal(q.b.heroes.archer.xp,start+budget.combat);P.complete(q.b);assert.equal(q.b.heroes.archer.xp,budget.end);retry.heroes=plain(q.b.heroes);retry.honroGrowth=plain(q.b.honroGrowth.ledger);retry.cleared[21]={rounds:1};delete retry.honroBattle;const replay=battlefield(g,21,{profile:retry});P.awardCombat(replay.e,replay.e.active,1e8);P.complete(replay.b);assert.deepEqual(plain(replay.b.heroes),plain(retry.heroes));});
check('Above-target old save keeps its XP and only adds the new stage budget',()=>{const high=plain(p);for(const cls of high.recruited)high.heroes[cls].xp=P.xpAt(24);const q=battlefield(g,21,{profile:high});assert.equal(q.b.honroGrowth.limit.start,P.xpAt(24));assert.equal(q.b.honroGrowth.limit.end,P.xpAt(24)+P.budget(21).total);P.complete(q.b);for(const cls of high.recruited)assert.equal(q.b.heroes[cls].xp,P.xpAt(24)+P.budget(21).total);});
await mkdir('_local/reports/act3-runtime',{recursive:true});await writeFile('_local/reports/act3-runtime/growth.json',JSON.stringify({checks,status:'proposed balance, not final user approval',stage20Anchor:P.legacyCampaignAnchor(),currentCurve:'round((180 + 90 * (level - 1)^1.65) * 1.5), cap 30',legacyCurve:'round(180 + 90 * (level - 1)^1.65), reward-only cap 25',table,scope:'Reward ledger and completion fixtures; not normal play.'},null,2));
console.log(JSON.stringify(table));
