// User-approved regional-fiend revision. Engine fixtures verify corporeal
// damage/death and survivor protection; this is not ordinary-input play.
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {assertFiendContract,assertFiendContractScope} from './act3-fiend-contract-helpers.mjs';
import vm from 'node:vm';
import {runtime,battlefield} from '../game/tests/helpers.mjs';
import {legacyObjectiveBattle} from './objective-legacy-helpers.mjs';
const g=await runtime({legacyMaps:false}),C=g.HONRO_CORE,A=g.HonroAct3,plain=x=>JSON.parse(JSON.stringify(x)),checks=[];
const check=(name,fn)=>{fn();checks.push(name);console.log('PASS',name);};
g.HonroScene=class {};g.document={addEventListener(){}};vm.runInContext(await readFile('shared/runtime/unit-info.js','utf8'),g);
const project=JSON.parse(await readFile('shared/data/campaign.json','utf8')),baseline=JSON.parse(await readFile('tests/fixtures/act3-fiend-semantic-contract.json','utf8'));
const fixture=id=>{const q=battlefield(g,id);A.attach(q.app,q.e);return q;};
const legacyFixture=id=>{const q=fixture(id);q.b=legacyObjectiveBattle(g,id,q.p);q.e=new C.Engine(q.b,()=>{},true);q.app.engine=q.e;A.attach(q.app,q.e);return q;};
check('Fiend roster, survivor protection and mission rules stay exact as Act 3 architecture evolves',()=>assertFiendContract(project,g.HONRO_CONTENT,g.HONRO_BALANCE,g.HonroWorld.archetypes,baseline));
check('Fiend contract allows reviewed architecture only and rejects identity protection or mission drift',()=>assertFiendContractScope(project,g.HONRO_CONTENT,g.HONRO_BALANCE,g.HonroWorld.archetypes,baseline));
check('Corporeal fiends retain material/qi response, tangible bodies and normal finite combat stats',()=>{for(const id of [23,25,27,28,29]){const q=fixture(id),fiends=q.b.units.filter(u=>u.honroAct3Fiend);assert(fiends.length);for(const u of fiends){assert.match(u.name,/악귀/);assert.match(g.HonroUnitInfo.description(u),/죽은 육신/);assert(g.HonroUnitInfo.description(u).includes(u.intent),'identity remains visible beside live AI intent');assert.equal(u.side,1);assert(!u.fixed&&!u.honroSpirit&&!u.spiritHidden&&!u.honroNonlethal&&!u.honroCivilian);assert.deepEqual(plain(C.defenseForUnit(u)),plain(C.MONSTER_EXISTENCE.human));assert.equal(C.existenceMultiplier({form:1,qi:0,soul:0},u),1);assert.equal(C.existenceMultiplier({form:0,qi:1,soul:0},u),1);assert.equal(C.existenceMultiplier({form:0,qi:0,soul:1},u),.88);assert(u.h>=90&&u.r>=24&&u.hp>1&&Number.isFinite(u.attack));}}});
check('Initial and reinforced fiends use ordinary lethal HP and once-only combat rewards',()=>{const q=fixture(25),s=q.st.steps.find(s=>s.id==='archive-hold'),m=A.marker(q.b,s.id),hero=q.e.heroesAlive()[0];A.memory(q.b).done['hidden-latch']=true;for(const u of q.e.alive(1))if(A.sameFloor(u,m,600)){u.dead=true;u.hp=0;}Object.assign(hero,{x:m.x,y:m.y});q.b.active=hero.id;q.app.actorBoundary=hero.id;A.tick(q.app,0);const wave=q.b.units.filter(u=>u.honroSpawnSource==='act3-archive-hold');assert.equal(wave.length,3);for(const u of wave){assert(u.honroAct3Fiend&&!u.honroNonlethal);q.e.hurt(u,1e8,hero.id);assert(u.dead&&u.hp===0&&u.side===1&&!u.honroSubdued);}const xp=plain(q.b.heroes);for(const u of wave)q.e.hurt(u,1e8,hero.id);assert.deepEqual(plain(q.b.heroes),xp);});
check('Death while enthralled cannot turn a fiend into a neutral survivor or resurrect on release',()=>{for(const rank of [1,8]){const q=fixture(23),u=q.b.units.find(u=>u.honroAct3Fiend&&!u.elite),owner=q.e.heroesAlive().find(u=>u.cls==='occultist');assert(q.e.captureEnemy(u,owner,rank));q.e.hurt(u,1e8,owner.id);assert(u.dead&&u.hp===0);q.e.releaseEnemy(u);A.tick(q.app,0);assert(u.dead&&u.hp===0&&u.side===1&&!u.enthrall&&!u.honroSubdued);}});
check('Living rescue and carrier NPCs stay human, protected from friendly hits and vulnerable to actual enemies',()=>{for(const id of [21,23,26,27]){const q=fixture(id),npc=q.b.units.find(u=>u.honroProtected),foe=q.e.alive(1)[0],before=npc.hp;assert(npc.honroType==='civilian'&&npc.side===2&&!npc.honroAct3Fiend);q.e.hurt(npc,1e8,q.e.active.id);assert.equal(npc.hp,before);q.e.hurt(npc,1e8,foe.id);assert(npc.dead&&npc.hp===0);assert.match(A.failure(q.b),/주민/);assert(!npc.honroAct3Fiend);}});
check('Legacy saved class-specific controls reject enemy captured summoned missing and wrong-class owners',()=>{for(const kind of ['enemy','captured','summoned','missing','wrong-class']){const q=legacyFixture(27),t=q.b.terrain.find(t=>t.id==='water-release'),hp=t.hp,archer=q.e.heroesAlive().find(u=>u.cls==='archer');let owner;if(kind==='enemy'||kind==='captured'){owner=q.e.alive(1).find(u=>u.cls==='archer');assert(owner);if(kind==='captured')assert(q.e.captureEnemy(owner,q.e.heroesAlive().find(u=>u.cls==='occultist'),1));}else if(kind==='summoned'){owner={...plain(archer),id:'summoned-archer-fixture',summoned:true};q.b.units.push(owner);}else if(kind==='wrong-class')owner=q.e.heroesAlive().find(u=>u.cls==='mage');q.e.damageTerrain(t,1e6,0,owner?.id||'missing-owner');assert.equal(t.hp,hp,kind);assert(!t.broken,kind);}});
check('Legacy saved companion shots remain valid after firing-owner death and unrestricted controls retain ordinary rules',()=>{for(const died of [false,true]){const q=legacyFixture(27),t=q.b.terrain.find(t=>t.id==='water-release'),owner=q.e.heroesAlive().find(u=>u.cls==='archer');if(died){owner.hp=0;owner.dead=true;}q.e.damageTerrain(t,1e6,0,owner.id);assert(t.broken,died?'already-fired companion shot':'living companion');}const q=legacyFixture(23),t=q.b.terrain.find(t=>t.id==='cargo-lock'),enemy=q.e.alive(1).find(u=>u.cls==='archer');q.e.damageTerrain(t,1e6,0,enemy.id);assert(t.broken,'unrestricted device damage is unchanged');});
check('Regional possession is explained before the first human-bodied fight without changing the old mystery',()=>{assert(project.stages.slice(20,22).every(s=>!s.units.some(u=>u.kind.startsWith('possessed'))));const entry=g.HONRO_CONTENT.stages[22].story.map(l=>l[1]).join(' ');for(const term of ['숨은 이미 끊겼','육신','되돌릴 수 없','짐꾼은 살아'])assert(entry.includes(term));const all=JSON.stringify(g.HONRO_CONTENT.stages.slice(20));assert(!/회수조|비살상|전투 불능|전국/.test(all));assert(g.HONRO_CONTENT.stages[20].beats['gate-resident'][0][1].includes('피했어요'));assert(all.includes('숨겨라… 지워라'));assert(all.includes('주민 전원을 죽이라는 명령은 없습니다'));assert(all.includes('스승께 들린 혼은 없었다'));});
await mkdir('_local/reports/act3-fiends',{recursive:true});await writeFile('_local/reports/act3-fiends/summary.json',JSON.stringify({checks,passed:true,baseline:baseline.sourceCommit,limits:['Synthetic combat states and hash invariants only; normal input/browsers are separate.','No migration is added for unreleased development-only surrender fixtures.']},null,2)+'\n');
