import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile,mkdir,writeFile} from 'node:fs/promises';
const g=vm.createContext({});vm.runInContext(await readFile('shared/runtime/camera.js','utf8'),g);let cases=0;for(const height of [202,402,620,844,1080])for(const width of [320,800,1440])for(const scale of [.12,.3,.7,1])for(const y of [0,2000,4500]){const u={y,h:100},v={x:400,y:g.HonroCamera.followY(u,height,scale),scale},foot=g.HonroCamera.screen(v,width,height,{x:400,y}),head=g.HonroCamera.screen(v,width,height,{x:400,y:y-u.h});assert(foot.y<=height*.78+1e-8);assert(head.y>=0);const point={x:-125,y:4120},screen=g.HonroCamera.screen(v,width,height,point),back=g.HonroCamera.world(v,width,height,screen.x,screen.y);assert(Math.abs(back.x-point.x)<1e-8&&Math.abs(back.y-point.y)<1e-8);cases++;}
g.HonroPartyPresentationHeight=u=>u.h*1.24;
for(const height of [124,202,232,402,620,844])for(const scale of [.12,.7,1,1.65]){const u={y:2000,h:92},fit=g.HonroCamera.fitFollowScale(u,height,scale),v={x:400,y:g.HonroCamera.followY(u,height,fit),scale:fit},top=g.HonroCamera.screen(v,944,height,{x:400,y:u.y-g.HonroPartyPresentationHeight(u)-16});assert(fit<=scale);assert(top.y>=height*.3-1e-7);cases++;}
assert.equal(g.HonroCamera.fitFollowScale({h:92},844,.82),.82,'already fitting tall-view zoom is unchanged');
const u={x:330,y:1752,h:92},width=944,height=232,scale=.85,x=u.x+170,y=g.HonroCamera.followY(u,height,scale),header={left:10,right:334,top:6,bottom:57.6},screenX=tx=>width/2+(u.x-tx)*scale;
const safe=g.HonroCamera.avoidHeaderX(u,x,y,width,height,scale,header);assert(screenX(safe)-16>=header.right+6);assert(Math.abs(screenX(safe)-screenX(x))<=64);assert(screenX(safe)>=22&&screenX(safe)<=width-22);cases++;
for(const box of [null,{left:0,right:920,top:0,bottom:100},{left:0,right:480,top:0,bottom:100},{left:10,right:334,top:180,bottom:220}]){assert.equal(g.HonroCamera.avoidHeaderX(u,x,y,width,height,scale,box),x,'no rectangle, no safe screen space, excessive shift or no vertical overlap preserves original target');cases++;}
const left=g.HonroCamera.avoidHeaderX(u,x,y,width,height,scale,{left:300,right:420,top:6,bottom:57.6});assert(screenX(left)+16<=300-6);assert(Math.abs(screenX(left)-screenX(x))<=64);cases++;
await mkdir('_local/reports/camera-follow',{recursive:true});await writeFile('_local/reports/camera-follow/summary.json',JSON.stringify({reconstructed:true,cases,limits:['Production camera math only. Renderer resize, real canvas CSS, touch and browser framing remain separate.']},null,2));console.log('PASS',cases,'production camera framing and projection cases');
