/** Reconstructed production input methods, synthetic event/DOM plumbing. */
import assert from 'node:assert/strict';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {runtime} from '../game/tests/helpers.mjs';
const g=await runtime({legacyMaps:false}),C=g.HONRO_CORE,S=C.SKILLS,source=await readFile('shared/runtime/main.js','utf8');let now=1000;
const docs=new Map(),wins=new Map(),nodes=new Map(),doc={addEventListener:(k,v)=>docs.set(k,v)},win={addEventListener:(k,v)=>wins.set(k,v)};
function node(id){if(!nodes.has(id))nodes.set(id,{style:{setProperty(){}},dataset:{},classList:{toggle(){}},querySelector(){return this.label??={textContent:''};},getBoundingClientRect:()=>({left:0,top:0,width:100,height:100}),setPointerCapture(){},hasPointerCapture:()=>false,addEventListener(){}});return nodes.get(id);}
const G={HonroStory:{turnPaused:()=>false},HonroUnitInfo:{bind(){},tap:()=>false,close(){}}},slices=[['        canInput()','        updateStick('],['        updateChargeDisplay()','        updateHUD('],['        bind() {','        equipConfirm(']];
const App=new Function('G','C','S','H','document','window','performance','$','clamp','return class {'+slices.map(([a,b])=>{assert(source.includes(a)&&source.includes(b));return source.slice(source.indexOf(a),source.indexOf(b));}).join('\n')+'}')(G,C,S,{hero:{}},doc,win,{now:()=>now},node,(x,a,b)=>Math.max(a,Math.min(b,x)));
function fixture(id='O04'){const profile=C.defaults(),b=C.createBattle(1,profile,'practice',{party:['occultist'],wind:0}),u=b.units[0];Object.assign(b,{width:5000,height:3000,terrain:[{id:'floor',x:0,y:1800,w:5000,h:1200,mat:'rock',hp:9999,maxHp:9999}],wind:0,drafts:[],fields:[]});Object.assign(u,{x:2000,y:1800,vx:0,vy:0,loadout:['O04','O02'],focus:9999,maxFocus:9999,ranks:{[id]:1,O04:1,O02:1},acted:false});b.units=[u];b.active=u.id;b.phase='aim';b.side=0;const a=new App();Object.assign(a,{engine:new C.Engine(b),profile,screen:'battle',selected:id,selectedByUnit:{},keys:new Set(),contacts:new Map(),stick:{x:0,y:0},scene:{world:(x,y)=>({x,y}),manual:false},modal:{classList:{contains:()=>false}},done:false,charging:false,updateHUD(){},root:{}});a.inputs();a.bind();return{a,b,u};}
const key=(code,type='keydown',repeat=false)=>docs.get(type)({code,repeat,target:{tagName:'BODY'},preventDefault(){}}),pointer=(pointerId=7)=>({pointerId,preventDefault(){}});let holds=0;
for(const id of ['O01','O02','O03','O04','O05','O12','O14','O15','O16'])for(const mode of ['keyboard','pointer'])for(const fraction of [0,.1,.25,.5,.75,1,2]){const {a,b,u}=fixture(id);u.loadout=[id];const seconds=a.engine.chargeDuration(u,S[id])*fraction;if(mode==='keyboard')key('Space');else node('fire').onpointerdown(pointer());assert(a.charging);now+=seconds*1000;a.power=a.chargePower();a.updateChargeDisplay();assert.equal(node('fire').label.textContent,Math.round(Math.min(1,fraction)*100)+'%');if(mode==='keyboard')key('Space','keyup');else node('fire').onpointerup(pointer());assert.equal(b.shots,1);assert(Math.abs(b.lastShots[u.id].power-Math.min(1,fraction))<1e-9);const p=b.projectiles[0];assert(Math.abs(Math.hypot(p.vx,p.vy)-480*Math.min(seconds,a.engine.chargeDuration(u,S[id])))<1e-7);key('Space','keyup');node('fire').onlostpointercapture(pointer());assert.equal(b.shots,1);holds++;}
for(const cancel of [()=>node('fire').onpointercancel(pointer()),()=>node('fire').onlostpointercapture(pointer()),()=>wins.get('blur')(),()=>key('Digit2')]){const {a,b}=fixture();node('fire').onpointerdown(pointer());now+=200;cancel();node('fire').onpointerup(pointer());key('Space','keyup');assert(!a.charging);assert.equal(b.shots,0);}
{const {a,b}=fixture();node('fire').onpointerdown(pointer());const at=a.chargeAt;now+=100;node('fire').onpointerdown(pointer(8));key('Space','keydown',true);assert.equal(a.chargeAt,at);assert.equal(a.firePointer,7);node('fire').onpointerup(pointer(8));assert.equal(b.shots,0);node('fire').onpointerup(pointer());assert.equal(b.shots,1);}
await mkdir('_local/reports/sodan-charge',{recursive:true});await writeFile('_local/reports/sodan-charge/input-contract.json',JSON.stringify({reconstructed:true,holds,cancellationCases:4,limits:['Production callbacks with synthetic DOM and clock; no real browser pointer capture or touch test.']},null,2));console.log('PASS',holds,'production keyboard/pointer holds, duplicate presses and cancellation');
