import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {runtime,battlefield} from '../game/tests/helpers.mjs';
const g=await runtime({legacyMaps:false}),C=g.HONRO_CORE,checks=[];
function test(name,fn){try{fn();checks.push({name,pass:true});console.log('PASS',name);}catch(e){checks.push({name,pass:false,error:String(e)});console.error('FAIL',name,e.stack);}}
const main=await readFile('shared/runtime/main.js','utf8'),method=main.slice(main.indexOf('        checkMission(e) {'),main.indexOf('        missionTick(dt)'));
const checkMission=new Function('G','C','return ({'+method+'}).checkMission')(g,C);
function finale(){const a=battlefield(g,10);a.e.checkEnd=()=>false;a.b.honroState.receivers=2;a.e.unit('boss').hp=a.e.unit('boss').maxHp*.4;a.b.honroEvents=[];return a;}
test('A triggered encounter waits for its own actor, not a selection change or another hero',()=>{const {app,e,b}=battlefield(g,3),u=e.active,v=e.heroesAlive().find(v=>v!==u);b.honroEvents=[{id:'actor-test',when:{progress:1},lines:[['설오','먼저 끝내겠습니다.']]}];g.HonroEncounters.attach(app,e);g.HonroEncounters.update(app,0,{progress:100});assert.equal(app.speeches.length,0);assert.equal(b.honroState.eventActors['actor-test'].id,u.id);b.active=v.id;e.finishAction(true);assert.equal(app.speeches.length,0);b.active=u.id;e.finishAction();assert.equal(app.speeches.length,0);e.finishAction(true);assert.equal(app.speeches.length,1);g.HonroEncounters.actorEnd(app,u.id);assert.equal(app.speeches.length,1);});
test('Pending actor events persist across a save before the action has finished',()=>{const {app,e,b}=battlefield(g,3),id=b.active;b.honroEvents=[{id:'save-test',when:{progress:1},lines:[['설오','기록했습니다.']]}];g.HonroEncounters.update(app,0,{progress:100});const saved=structuredClone(b);app.engine=new C.Engine(saved);app.engine.checkEnd=()=>false;g.HonroEncounters.attach(app,app.engine);g.HonroEncounters.update(app,0,{progress:100});assert.equal(app.speeches.length,0);app.engine.finishAction(true);assert.equal(app.speeches.length,1);assert.equal(saved.honroState.eventLog[0].id,'save-test');});
test('Stage 10 waits for the current actor and turns Sodan into a stationary, trained channeler',()=>{const {app,e,b}=finale(),boss=e.unit('boss');g.HonroMission.tick(app,0);assert(!b.honroState.sodanCoop);g.HonroEncounters.actorEnd(app,b.active);assert(b.honroState.sodanCoop);assert.equal(boss.side,2);assert.equal(boss.allyRole,'channeler');assert(boss.fixed);assert.equal(b.enemyLimit,6);assert.equal(b.honroState.sodanBreach.units.length,8);assert(Object.keys(boss.ranks).length>2);const x=boss.x,y=boss.y;e.impulse(boss,300,-300);e.stepUnits(.1);assert.equal(boss.x,x);assert.equal(boss.y,y);assert(b.units.some(u=>u.honroTargetId===boss.id));});
test('Six full enemy turns are required, with fresh capped waves, saved progress and no tick-based shortcut',()=>{const {app,e,b,st}=finale();g.HonroEncounters.actorEnd(app,b.active);b.round=20;const hs=b.honroState;for(let i=0;i<100;i++)g.HonroMission.tick(app,0);assert.equal(hs.coopHold,0);assert(!g.HonroObjectives.state(b,st).complete);for(let turn=1;turn<=6;turn++){for(const u of e.alive(1)){u.dead=true;u.hp=0;}b.teamEnds[1]++;g.HonroEncounters.actorEnd(app,b.active);assert.equal(hs.coopHold,turn);assert.equal(g.HonroObjectives.state(b,st).complete,turn===6);if(turn<6)assert.equal(e.alive(1).length,6);const count=b.units.length;g.HonroEncounters.actorEnd(app,b.active);assert.equal(b.units.length,count);const saved=structuredClone(b);assert.equal(saved.honroState.coopHold,turn);}assert.equal(hs.finaleWaves.length,6);});
test('Converting during an enemy turn does not count that partial turn; crowd capacity prevents unlimited growth',()=>{const {app,e,b}=finale();b.side=1;g.HonroEncounters.actorEnd(app,b.active);b.teamEnds[1]++;g.HonroEncounters.actorEnd(app,b.active);assert.equal(b.honroState.coopHold,0);for(let i=0;i<5;i++){b.teamEnds[1]++;g.HonroEncounters.actorEnd(app,b.active);assert(e.alive(1).length<=g.HonroMission.FINALE_CAP);}assert.equal(b.honroState.coopHold,5);});
test('An early conversion keeps receiving waves after six defenses until the stage pacing floor',()=>{const {app,e,b,st}=finale();b.round=1;g.HonroEncounters.actorEnd(app,b.active);for(let turn=1;turn<=7;turn++){for(const u of e.alive(1)){u.dead=true;u.hp=0;}b.round++;b.teamEnds[1]++;g.HonroEncounters.actorEnd(app,b.active);assert.equal(e.alive(1).length,6);assert(!g.HonroObjectives.state(b,st).complete);}assert.equal(b.honroState.coopHold,6);assert.equal(b.honroState.finaleWaves.length,8);b.round=15;assert(g.HonroObjectives.state(b,st).complete);});
test('The cooperation transition discards only obsolete pre-cooperation instructions',()=>{const {app,e,b}=finale(),hs=b.honroState;const obsolete=['설오','Before',{storyId:'act1-v6-entry-follow-10-0'}],other=['설오','Other',{storyId:'other-discovery'}];hs.deferredStory=[{round:4,lines:[obsolete]},{round:4,lines:[other]}];hs.storyQueue=[obsolete,other];g.HonroEncounters.actorEnd(app,b.active);assert.equal(hs.deferredStory.length,1);assert.equal(hs.storyQueue.length,1);assert.equal(hs.storyQueue[0][2].storyId,'other-discovery');});
test('Sodan can die during the ritual and loss outranks completed defense progress',()=>{const {app,e,b}=finale();g.HonroEncounters.actorEnd(app,b.active);Object.assign(app,{checkMission,cancelInput(){}});const boss=e.unit('boss');boss.hp=0;boss.dead=true;b.round=30;b.honroState.coopHold=6;assert(app.checkMission(e));assert.equal(b.phase,'lost');});
test('Old cooperation saves preserve two earned turns and require four more without duplicating the opening wave',()=>{const {app,e,b}=finale(),hs=b.honroState;hs.sodanCoop=true;hs.coopHold=2;e.unit('boss').side=2;const count=b.units.length;g.HonroEncounters.actorEnd(app,b.active);assert.equal(b.units.length,count);assert.equal(hs.coopHold,2);assert(e.unit('boss').fixed);b.teamEnds[1]++;g.HonroEncounters.actorEnd(app,b.active);assert.equal(hs.coopHold,3);});
test('Every new companion spends valid SP once and fills usable slots; refunding or re-recruiting preserves player choices',()=>{for(const [cls,id] of [['mage',2],['knight',5],['occultist',10]]){const p=C.defaults();p.recruited=['archer'];p.party=['archer'];const st={...g.HONRO_CONTENT.stages[id-1],recruit:cls};g.HonroProgression.recruit(p,st);const h=p.heroes[cls];assert(C.pointsSpent(h,cls)>2);assert(C.pointsSpent(h,cls)<=C.pointsEarned(h));assert(p.loadouts[cls].length>=3);assert(p.loadouts[cls].every(id=>C.knownSkills(h,cls).includes(id)));C.resetTalents(h,cls);const before=JSON.stringify(h);g.HonroProgression.recruit(p,st);assert.equal(JSON.stringify(h),before);g.HonroProgression.repairRecruits(p);assert.equal(JSON.stringify(h),before);}});
test('Every stake rank buys exactly one extra turn; gates last longer, and all base critical rates/growth are reduced',()=>{for(const id of ['M07','M08','M09','M10','M11','M12','M14','M15','M99'])for(let r=2;r<=8;r++)assert.equal(C.stakeDuration(id,r)-C.stakeDuration(id,r-1),1);assert.equal(C.stakeDuration('M09',1),6);assert.equal(C.stakeDuration('M09',8),13);for(const cls of C.CLASS_IDS){const lo=C.criticalStats(cls,1),hi=C.criticalStats(cls,25);assert(lo.critChance>=.04&&lo.critChance<=.08);assert(hi.critChance>lo.critChance&&hi.critChance<=.1281);if(cls!=='archer')assert(hi.critChance<C.criticalStats('archer',25).critChance);}});
test('First rescue introduces Sodan in any order, and follow-up questions remain paired within short authored beats',()=>{for(const label of ['덕수','월이','칠복']){const {app,b}=battlefield(g,7),first=g.HonroStoryContent.interaction(app,{action:'rescue',label,target:label}),next=g.HonroStoryContent.interaction(app,{action:'rescue',label,target:label+'2'});assert(first.some(l=>l[0]==='설오'&&l[1].includes('누구')));assert(!next.some(l=>l[1].includes('누구')));}for(const st of g.HONRO_CONTENT.stages)for(const beat of [...(st.storyFollowups||[]),...Object.values(st.beats||{})])assert(beat.length<=5);const first=g.HONRO_CONTENT.stages[2].story;assert(first.findIndex(l=>l[1].includes('분입니까'))<first.findIndex(l=>l[1].includes('휘겸이라')));assert(g.HonroStoryContent.cooperation().some(l=>l[0]==='안내'&&l[2].kind==='guide'));});
function planningArena(){const {b}=battlefield(g,1);b.width=4000;b.height=2000;b.terrain=[{id:'floor',x:0,y:1500,w:4000,h:500,mat:'rock',hp:99999,maxHp:99999}];b.sceneVersion++;b.fields=[];b.drafts=[];b.waters=[];b.zones=[];b.wind=0;b.units=[C.makeUnit('archer',0,900,1500,{id:'target',hp:1000,maxHp:1000}),C.makeUnit('archer',1,350,1500,{id:'shooter',fixed:true,lastAct:b.round,focus:500,maxFocus:500,loadout:['LA01','LA02']})];b.active='shooter';b.side=1;b.phase='enemy';return b;}
test('Budgeted enemy planning makes the identical seeded decision and can restart from a mid-decision save',()=>{const initial=planningArena(),expected=new C.Engine(structuredClone(initial));expected.enemyAction();assert.equal(expected.b.phase,'flight');const actual=new C.Engine(structuredClone(initial)),old=g.performance;let clock=0;try{g.performance={now:()=>clock+=.2};actual.planningBudget(.1);actual.enemyAction();actual.planningBudget();assert.equal(actual.b.phase,'enemy');const save=structuredClone(actual.b);let frames=1;while(actual.b.phase==='enemy'&&frames++<500){actual.planningBudget(.1);actual.enemyAction();actual.planningBudget();}assert(frames>1&&frames<500);assert.equal(JSON.stringify(actual.b),JSON.stringify(expected.b));const resumed=new C.Engine(save);resumed.enemyAction();assert.equal(JSON.stringify(resumed.b),JSON.stringify(expected.b));}finally{g.performance=old;}});
test('A changed target invalidates incomplete aim planning before a shot is fired',()=>{const e=new C.Engine(planningArena()),old=g.performance;let clock=0;try{g.performance={now:()=>clock+=.2};e.planningBudget(.1);e.enemyAction();e.planningBudget();assert.equal(e.b.phase,'enemy');e.unit('target').x=1400;const expected=new C.Engine(structuredClone(e.b));expected.enemyAction();e.enemyAction();assert.equal(JSON.stringify(e.b),JSON.stringify(expected.b));}finally{g.performance=old;}});
test('Unit broad phase preserves exact slab hits, ties, tangencies and ignored units',()=>{const e=new C.Engine(planningArena());e.b.terrain=[];let seed=91821;const rand=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296);e.b.units=Array.from({length:28},(_,i)=>C.makeUnit('knight',1,rand()*1500,500+rand()*1000,{id:'box-'+i,r:10+rand()*35,h:60+rand()*90,dead:i%7===0}));for(let i=0;i<1200;i++){const a={x:rand()*1600,y:rand()*1600},z={x:rand()*1600,y:rand()*1600},r=i%9,skip=['box-4'];if(i<28){const u=e.b.units[i];a.x=z.x=u.x-u.r-r;a.y=u.y-u.h-50;z.y=u.y+50;}let best=null;for(const u of e.b.units){if(u.dead||u.id==='box-3'||skip.includes(u.id))continue;const hit=C.segRect(a,z,u.x-u.r,u.y-u.h,u.r*2,u.h,r);if(hit&&(!best||hit.t<best.t))best={id:u.id,...hit};}const hit=e.collision(a,z,r,'box-3',skip);assert.equal(hit?.unit?.id,best?.id);if(hit)assert.equal(JSON.stringify({t:hit.t,n:hit.n}),JSON.stringify({t:best.t,n:best.n}));}});
await mkdir('_local/reports/finale-performance',{recursive:true});await writeFile('_local/reports/finale-performance/unit.json',JSON.stringify({checks},null,2)+'\n');if(checks.some(x=>!x.pass))process.exitCode=1;
