import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {runtime} from '../game/tests/helpers.mjs';
const g=await runtime(),C=g.HONRO_CORE,checks=[],details={};
const plain=v=>JSON.parse(JSON.stringify(v));
function test(name,fn){try{fn();checks.push({name,pass:true});console.log('PASS',name);}catch(error){checks.push({name,pass:false,error:String(error)});console.error('FAIL',name,error.stack);}}
function arena(id='S00',rank=1){
 const cls=C.SKILLS[id].cls,profile=C.defaults();profile.heroes[cls].xp=C.xpAtLevel(25);profile.heroes[cls].ranks={[C.baseSkill(cls)]:1,[id]:rank};profile.loadouts[cls]=[id];
 const b=C.createBattle(1,profile,'practice',{party:[cls],wind:0});Object.assign(b,{width:6000,height:2300,practiceCombat:true,fields:[],waters:[],drafts:[],wind:0,terrain:[{id:'floor',x:0,y:1700,w:6000,h:600,mat:'rock',hp:99999,maxHp:99999}]});b.units=b.units.slice(0,1);
 const u=b.units[0];Object.assign(u,{x:800,y:1700,spawnX:800,spawnY:1700,attack:1,armor:0,focus:1000,maxFocus:1000,hp:1000,maxHp:1000,vx:0,vy:0,airborne:false,jumping:false,acted:false,loadout:[id],ranks:{[C.baseSkill(cls)]:1,[id]:rank},cooldowns:{},facing:1});
 const events=[],e=new C.Engine(b,v=>events.push(plain(v)));e.random=()=>.99;
 const foe=(x=900,y=1700,extra={})=>{const t=C.makeUnit('archer',1,x,y,{id:'foe'+b.units.length,role:'dummy',fixed:true,hp:10000,maxHp:10000,armor:0,shield:0,awake:true,loadout:['LA01'],...extra});b.units.push(t);return t;};
 const ready=(skill=id,advance=true)=>{if(advance)b.round++;Object.assign(b,{phase:'aim',side:0,active:u.id,projectiles:[],volley:undefined});Object.assign(u,{acted:false,airborne:false,jumping:false,vx:0,vy:0,loadout:[skill],cooldowns:{},focus:1000});};
 const fire=(power=.6,angle=45)=>{assert(e.fire(u.loadout[0],angle,power));return b.projectiles[0];};
 const run=(seconds=12)=>{for(let i=0;i<seconds/C.STEP&&(b.projectiles.length||u.meleeAction);i++){C.tickWarrior(e,C.STEP);e.stepVolley(C.STEP);for(const p of [...b.projectiles])if(b.projectiles.includes(p))e.stepProjectile(p,C.STEP);}};
 return {e,b,u,events,profile,foe,ready,fire,run};
}
test('Knight has a free talent-independent base, three five-skill trees and no common ultimate',()=>{assert.equal(C.baseSkill('knight'),'S00');assert(!C.TALENT_MAP.S00);assert.equal(C.TALENTS.filter(n=>n.cls==='knight').length,20);assert(!C.ultimateUnlocked(C.freshHero('knight'),'knight'));assert(C.SKILLS.S99.enemyOnly);assert.equal(C.SKILLS.AP05.name,'살흔');assert.equal(C.SKILLS.MP05.name,'주천');});
test('All sixteen martial skills cast and settle at ranks 1 and 8 without changing other heroes',()=>{for(const r of [1,8])for(const s of Object.values(C.SKILLS).filter(s=>s.martial&&!s.passive)){const a=arena(s.id,r);a.foe(1800);a.fire();a.run();assert(!a.b.projectiles.length&&!a.u.meleeAction,s.id);assert(Number.isFinite(a.u.x)&&!a.u.dead,s.id);}});
test('Quick vs full melee: damage, reach, cost, defensive stance and zero battlefield projectiles',()=>{const rows=[];for(const power of [0,1]){const a=arena(),t=a.foe(950);const hp=t.hp,mp=a.u.focus;const p=a.fire(power,20);assert(!p&&!a.b.projectiles.length);a.run();rows.push({damage:hp-t.hp,range:C.meleeRange(a.u,C.SKILLS.S00,power),cost:mp-a.u.focus,guard:a.u.martialGuard?.reduction||0});}assert(rows[1].damage>rows[0].damage*1.45);assert(rows[1].range>rows[0].range);assert(rows[1].cost>rows[0].cost);assert.equal(rows[0].guard,.12);assert.equal(rows[1].guard,0);details.quickFull=rows;});
test('Melee preview has no parabola and real terrain blocks sword range',()=>{const a=arena('S03'),t=a.foe(950);assert.equal(a.e.predict(a.u,C.SKILLS.S03,20,1).points.length,0);a.b.terrain.push({id:'wall',x:865,y:1450,w:30,h:250,mat:'rock',hp:99999,maxHp:99999});a.fire(1,20);a.run();assert.equal(t.hp,10000);});
test('Wide slash hits all front targets and misses behind',()=>{const a=arena('S03'),ts=[a.foe(890),a.foe(1000),a.foe(670)];a.fire(1,15);a.run();assert(ts[0].hp<10000&&ts[1].hp<10000);assert.equal(ts[2].hp,10000);});
test('Turning slash hits front and rear with very-close double coverage',()=>{const a=arena('S05'),front=a.foe(920),back=a.foe(680),near=a.foe(805);a.fire(.5,20);a.run();assert(front.hp<10000&&back.hp<10000);assert(10000-near.hp>=1.9*(10000-front.hp));});
test('Rapid slash rank counts, death handoff and no splash or movement',()=>{for(let r=1;r<=8;r++){const a=arena('S07',r),one=a.foe(850,1700,{hp:1}),two=a.foe(900),outside=a.foe(1300),x=a.u.x;a.fire(.5,20);a.run();assert(one.dead);assert(two.hp<10000);assert.equal(outside.hp,10000);assert.equal(a.u.x,x);assert.equal(a.events.filter(v=>v.name==='swordCut').length,C.COMBO_HITS[r-1]);}});
test('Counter stance reduces ranged damage but waits for a nearby enemy and counters once',()=>{const a=arena('S08',8),t=a.foe(1300,1700,{combatBaseAttack:1});a.fire(.6,0);a.e.hurt(a.u,100,t.id);assert.equal(a.u.hp,930);C.tickWarrior(a.e,.2);assert.equal(t.hp,10000);a.b.side=1;t.x=930;C.tickWarrior(a.e,.1);const hp=t.hp;assert(hp<10000);C.tickWarrior(a.e,.1);assert.equal(t.hp,hp);a.b.round++;C.tickWarrior(a.e,.1);assert(!a.u.martialGuard);});
test('Life slash consumes half current HP and increased mana before its stronger hit',()=>{for(const hit of [false,true]){const a=arena('S02',8),t=a.foe(hit?910:1400);const before=a.u.hp,cost=a.e.manaCost(C.SKILLS.S02,a.u,1);a.fire(1,20);assert.equal(a.u.hp,before/2);const expected=a.u.meleeAction.damage;a.run();assert.equal(10000-t.hp,hit?Math.round(expected):0);assert.equal(a.u.focus,1000-cost);details.lifeSlash={base:C.SKILLS.S02.damage,coefficient:.99,consumed:before/2,damage:expected,cost};}});
test('Leap follows a real parabola, deals single-target damage and stays at landing',()=>{const a=arena('S01'),p=a.fire(.65,45),pred=arena('S01');const guide=pred.e.predict(pred.u,C.SKILLS.S01,45,.65);a.run();assert(a.u.x>1000);assert(Math.abs(p.x-guide.x)<.01);assert(Math.abs(a.u.y-1700)<2);});
test('Path sweep damages each crossed enemy once',()=>{const a=arena('S06'),t=a.foe(1000,1700,{h:250});a.fire(.6,15);a.run();assert(t.hp<10000);assert.equal(a.b.hits,1);});
test('Manual dive requires a second input and changes landing and impact',()=>{const rows=[];for(const trigger of [false,true]){const a=arena('S04'),p=a.fire(.85,60);for(let i=0;i<35;i++)a.e.stepProjectile(p,C.STEP);assert(!p.dived);if(trigger){assert(a.e.manualDive());assert(!a.e.manualDive());assert(p.vy>=650);}a.run();rows.push({x:a.u.x,dive:!!p.dived});}assert(rows[0].x>rows[1].x+150);details.dive=rows;});
test('Drive pushes grounded enemies and leaves airborne enemies velocity unchanged',()=>{const a=arena('S15'),ground=a.foe(980,1700,{fixed:false,h:240}),air=a.foe(1000,1660,{fixed:false,h:240,airborne:true,vx:11,vy:12});a.fire(.6,12);a.run();assert(ground.hp<10000&&ground.vx>0);assert(air.hp<10000);assert.equal(air.vx,11);assert.equal(air.vy,12);});
test('Follow-up landing accepts only melee, forbids walking/jumping/switching and ends after one cast',()=>{const a=arena('S13',8);a.fire(.6,45);a.run();assert.equal(a.u.meleeFollow,'landing');a.e.finishAction();assert.equal(a.u.meleeFollow,'ready');assert(a.e.canAct());const x=a.u.x;a.e.move(1,1);assert.equal(a.u.x,x);assert(!a.e.jump());a.u.loadout=['S01','S09','S02','S00'];assert(!a.e.fire('S09',30,.5));assert(!a.e.fire('S01',30,.5));assert(a.e.fire('S02',30,.5));a.run();a.e.finishAction();assert(!a.u.meleeFollow&&a.u.acted);});
test('Moon slash remains ballistic, and piercing blade independently hits every crossed target once',()=>{const a=arena('S11'),one=a.foe(1000,1650,{h:260}),two=a.foe(1200,1650,{h:260}),p=a.fire(.7,10),vy=p.vy;a.e.stepProjectile(p,.01);assert(p.vy>vy);a.run();assert(one.hp<10000&&two.hp<10000);assert.equal(a.b.hits,2);});
test('Pull hits enemies then cuts in melee, protects allies and stops at walls or pits',()=>{for(const side of [0,1]){const a=arena('S10'),t=a.foe(1300,1700,{side,fixed:false});const hp=t.hp,p=a.fire(.7,10);Object.assign(p,{x:t.x-2,y:t.y-t.h*.5,vx:400,vy:0});a.e.stepProjectile(p,.02);assert(Math.abs(t.x-a.u.x)<180);assert(side===0?t.hp===hp:t.hp<hp-43);}const a=arena('S10'),t=a.foe(1300,1700,{fixed:false});a.b.terrain.push({id:'wall',x:1050,y:1400,w:50,h:300,hp:99999,maxHp:99999,mat:'rock'});C.pullToFront(a.e,a.u,t);assert(t.x>=1120);assert(!a.b.terrain.some(v=>C.terrainRectIntersects(v,t.x-t.r,t.y-t.h,t.r*2,t.h-2,.1)));});
test('Sword screen reduces front shots once, ignores rear/body, caps absorption and powers the next blade',()=>{const a=arena('S14',8);a.fire();const enemy=a.foe(1400);const p={id:99,skill:'LA01',owner:enemy.id,side:1,body:false,damage:100,radius:3,fieldHits:[]};a.b.projectiles.push(p);C.bladeScreenPass(a.e,p,{x:1100,y:1650},{x:900,y:1650});assert(Math.abs(p.damage-30)<.01);C.bladeScreenPass(a.e,p,{x:1100,y:1650},{x:900,y:1650});assert(Math.abs(p.damage-30)<.01);const rear={...p,id:100,damage:100,fieldHits:[]};C.bladeScreenPass(a.e,rear,{x:500,y:1650},{x:700,y:1650});assert.equal(rear.damage,100);for(let i=0;i<12;i++)C.bladeScreenPass(a.e,{...p,id:101+i,damage:200,fieldHits:[]},{x:1100,y:1650},{x:900,y:1650});assert.equal(a.u.bladeScreen.hits,7);assert(a.u.bladeStored<=.45);const stored=a.u.bladeStored;a.ready('S09');const base=a.e.effective(C.SKILLS.S09,a.u).damage,q=a.fire();assert(q.damage>=base*(1+stored)-.01);assert.equal(a.u.bladeStored,0);});
test('Orbit count, cast seed, deterministic paths, per-blade per-target two-hit cap and one preview path',()=>{for(let r=1;r<=8;r++){const a=arena('S12',r),t=a.foe(1250,1700,{r:260,h:500});a.e.random=()=>.318;const p=a.fire(.55,10);assert.equal(p.orbit.blades.length,C.ORBIT_BLADES[r-1]);const copy=plain(p),before=plain(p.orbit);assert.deepEqual(plain(C.orbitPoint(p,p.orbit.blades[0],.4)),plain(C.orbitPoint(copy,copy.orbit.blades[0],.4)));a.run();assert(t.hp<10000);for(const blade of p.orbit.blades)assert((blade.hits[t.id]||0)<=2);assert.equal(p.orbit.seed,before.seed);const pr=a.e.predict(a.u,C.SKILLS.S12,45,.5);assert(pr.points.length>10&&!pr.paths);}});
test('Three distinct branches grant harmony once, repetition preserves chain, next skill consumes bonus',()=>{const a=arena('S08',8);a.u.ranks.SP04=8;for(const id of ['S08','S08','S14','S01']){a.ready(id);a.fire();a.run();}assert(a.u.harmony);assert.equal(a.u.swordChain.length,0);a.ready('S00');const cost=a.e.manaCost(C.SKILLS.S00,a.u,1),d=a.e.effective(C.SKILLS.S00,a.u).damage;a.u.harmony=false;assert(cost<a.e.manaCost(C.SKILLS.S00,a.u,1));assert(d>a.e.effective(C.SKILLS.S00,a.u).damage);});
test('Training and lightness passives strengthen HP/armor/resistance and mobility; last stand fires once',()=>{const h=C.freshHero('knight'),before=C.heroStats(h,'knight');h.ranks.SP02=8;h.ranks.SP03=8;const after=C.heroStats(h,'knight');assert(after.hp>before.hp&&after.armor>before.armor&&after.move>before.move);const a=arena();a.b.mode='campaign';a.u.ranks.SP05=8;a.e.hurt(a.u,5000,'');assert(!a.u.dead&&a.u.hp>0&&a.u.lastStandUsed&&a.u.martialGuard);a.e.hurt(a.u,5000,'');assert(a.u.dead);});

function arrowHit(a,t,amount=100,extra={}){const p=a.b.projectiles[0]||{id:a.b.nextId++,skill:'A01',shot:a.b.shot,owner:a.u.id,side:0,damage:amount,rootDamage:amount,skillRank:1,vx:500,vy:0};Object.assign(p,extra);a.e.hurt(t,amount,a.u.id,true,p,{x:t.x,y:t.y-t.h*.5});return p;}
test('Salheun first hit stores direct damage, next own turn echoes the correct percentage without recursion',()=>{const a=arena('A01');a.u.ranks.AP05=1;const t=a.foe();a.fire();arrowHit(a,t);assert.equal(t.hp,9900);a.ready();a.fire();arrowHit(a,t);assert.equal(t.hp,9788);assert.equal(t.salheun[a.u.id].entries.at(-1).damage,100);assert.equal(a.b.hits,3);});
test('Salheun rank 3 decay, rank 8 four-turn memory, misses age records and histories are per enemy',()=>{for(const rank of [3,8]){const a=arena('A01');a.u.ranks.AP05=rank;const one=a.foe(),two=a.foe(1400);const losses=[];for(let turn=0;turn<6;turn++){if(turn)a.ready();a.fire();const hp=one.hp;arrowHit(a,one);losses.push(hp-one.hp);}const max=C.SALHEUN_TURNS[rank-1],ratio=C.SALHEUN_RATIO[rank-1];assert.equal(losses[5],100+Math.round(Array.from({length:max},(_,i)=>100*ratio*.55**i).reduce((x,y)=>x+y,0)));arrowHit(a,two);assert.equal(two.hp,9900);for(let i=0;i<=max;i++){a.ready();a.fire();}assert(!one.salheun?.[a.u.id]);details['salheun'+rank]=losses;}});
test('Salheun records actual critical direct damage, excludes blast/DoT/environment and echo source',()=>{const a=arena('A14');a.u.ranks.AP05=8;a.e.random=()=>0;const t=a.foe();a.fire();const hp=t.hp;arrowHit(a,t);assert.equal(t.salheun[a.u.id].entries[0].damage,hp-t.hp);const saved=JSON.stringify(t.salheun);a.e.hurt(t,55,a.u.id,false,a.b.projectiles[0]);a.e.hurt(t,55,'');a.e.hurt(t,55,a.u.id,false,undefined,undefined,'salheun');assert.equal(JSON.stringify(t.salheun),saved);});
test('Salheun repeats/followups/iron secondary are excluded and native multishot is weighted and capped',()=>{const a=arena('A04',8);a.u.ranks.AP05=8;const t=a.foe();a.fire();const hp=t.hp;arrowHit(a,t,100,{id:100});const first=hp-t.hp;for(let i=1;i<10;i++)arrowHit(a,t,100,{id:100+i});const h=t.salheun[a.u.id];assert(h.recorded<=h.cap&&h.recorded<=first*1.5);const saved=JSON.stringify(h);arrowHit(a,t,100,{id:201,followup:true});arrowHit(a,t,100,{id:202,followup:false,secondary:true,skill:'A08'});assert.equal(JSON.stringify(h),saved);});
test('Salheun piercing triggers independently per target, and deaths/stage end clean records',()=>{const a=arena('A02');a.u.ranks.AP05=8;const one=a.foe(),two=a.foe(1300);for(let i=0;i<2;i++){if(i)a.ready();a.fire();arrowHit(a,one);arrowHit(a,two);}assert(one.hp<9800&&two.hp<9800);one.hp=1;a.e.hurt(one,50,a.u.id);assert(!one.salheun);a.b.phase='won';a.e.tick();assert(!two.salheun);});
test('Enemy identity remains legacy; no player ultimate, Salheun or Jucheon enters enemy AI',()=>{const a=arena(),enemy=a.foe(1200,1700,{cls:'knight',side:1,loadout:['S02','S13','S99'],ranks:{SP05:8,AP05:8,MP05:8}});new C.Engine(a.b);assert(enemy.loadout.every(id=>id.startsWith('LS')));assert.equal(C.passiveRank(enemy,'AP05'),0);assert.equal(C.passiveRank(enemy,'MP05'),0);assert(!enemy.loadout.some(id=>C.SKILLS[id].martial));const spawned=C.makeUnit('knight',1,1500,1700);C.migrateEnemySkills(spawned);assert.equal(spawned.loadout[0],'LS01');});
test('Jucheon accumulates actual paid costs and completes after two to four mixed spells at every rank',()=>{for(let rank=1;rank<=8;rank++){const a=arena('M06',rank);a.u.ranks.MP05=rank;let n=0,sum=0;for(const id of ['M06','M03','M08','M13']){a.u.ranks[id]=rank;a.ready(id);const before=a.u.focus;a.fire();sum+=before-a.u.focus;n++;assert.equal(a.u.jucheon,Math.min(C.JUCHEON_THRESHOLD[rank-1],sum));if(a.u.jucheonReady)break;}assert(n>=2&&n<=4&&a.u.jucheonReady,'rank '+rank);details['jucheonCasts'+rank]=n;}});
test('Jucheon discount by rank, rank-eight free cast resets without self charging, non-ki actions do not charge',()=>{for(let rank=1;rank<=8;rank++){const a=arena('M06',rank);a.u.ranks.MP05=rank;const base=a.e.manaCost(C.SKILLS.M06,a.u);a.u.jucheonReady=true;a.u.jucheon=C.JUCHEON_THRESHOLD[rank-1];assert.equal(a.e.manaCost(C.SKILLS.M06,a.u),Math.round(base*(1-C.JUCHEON_DISCOUNT[rank-1])));const before=a.u.focus;a.fire();assert.equal(a.u.jucheon,0);assert(!a.u.jucheonReady);if(rank===8)assert.equal(a.u.focus,before);a.ready('M01');a.fire();assert.equal(a.u.jucheon,0);}});
test('Jucheon snapshots empowered gourd, wave and persistent stake effects instead of caster future state',()=>{for(const id of ['M06','M03','M10','M99']){const a=arena(id,8);a.u.ranks.MP05=8;const base=a.e.effective(C.SKILLS[id],a.u).damage;a.u.jucheonReady=true;a.u.jucheon=78;const p=a.fire(.3,40);assert.equal(p.effectBoost,.15);assert(p.damage>=base*1.15-.01);a.run();if(['M10','M99'].includes(id)){assert(a.b.stakes?.length);assert.equal(a.b.stakes[0].effectBoost,.15);}}});
test('Migration refunds only the old knight allocation, preserves XP and P5 ranks, and is idempotent',()=>{const p=C.defaults();p.heroes.knight.xp=C.xpAtLevel(15);p.heroes.knight.ranks={S01:5,S02:2,SP05:3};delete p.heroes.knight.martialRevision;p.heroes.archer.ranks.AP05=4;p.heroes.mage.ranks.MP05=6;const xp=p.heroes.knight.xp;C.migrateSkills(p);assert.deepEqual(plain(p.heroes.knight.ranks),{S00:1});assert.equal(p.heroes.knight.xp,xp);assert.equal(p.heroes.archer.ranks.AP05,4);assert.equal(p.heroes.mage.ranks.MP05,6);const after=JSON.stringify(p);C.migrateSkills(p);assert.equal(JSON.stringify(p),after);});


test('Validated mid-action saves preserve orbit seed, blade contacts, melee sequence, P5 histories and charges',()=>{
 for(const id of ['S12','S07','S08','S14','S02','S13','A01','M06']){const a=arena(id,8);a.b.heroes=C.freshRoster();const t=a.foe();if(id==='A01')a.u.ranks.AP05=8;if(id==='M06')a.u.ranks.MP05=8;a.fire();if(id==='A01')arrowHit(a,t);if(id==='S12')for(let i=0;i<20;i++)a.e.stepProjectile(a.b.projectiles[0],C.STEP);if(id==='S07')C.tickWarrior(a.e,.1);const p=C.defaults();p.saved=a.b;const b=C.validate(plain(p)).saved;assert.deepEqual(plain(b.projectiles),plain(a.b.projectiles),id);const u=b.units.find(v=>v.id===a.u.id);for(const key of ['meleeAction','arrowTurn','jucheon'])assert.equal(JSON.stringify(u[key]),JSON.stringify(a.u[key]));assert.equal(JSON.stringify(b.units.find(v=>v.id===t.id).salheun),JSON.stringify(t.salheun));const e=new C.Engine(b);for(let i=0;i<1800&&(b.projectiles.length||u.meleeAction);i++){C.tickWarrior(e,C.STEP);for(const q of [...b.projectiles])if(b.projectiles.includes(q))e.stepProjectile(q,C.STEP);}assert(!b.projectiles.length&&!u.meleeAction,id);}
 const a=arena('S12',8);a.b.heroes=C.freshRoster();a.fire();const p=C.defaults();p.saved=a.b;p.saved.projectiles[0].orbit.blades[0].radius=NaN;assert.throws(()=>C.validate(plain(p)));
});
test('Old in-flight knight moves retain legacy meaning while only player skill points are refunded',()=>{const a=arena('S01');a.fire();delete a.b.martialRevision;delete a.b.heroes.knight.martialRevision;a.b.heroes.knight.xp=C.xpAtLevel(15);a.b.heroes.knight.kills=17;a.b.heroes.knight.damage=6789;const enemy=a.foe(1400,1700,{cls:'knight',loadout:['S02']});const p=C.defaults();p.saved=a.b;C.migrateSkills(p);assert.equal(a.b.projectiles[0].skill,'LS01');assert.deepEqual(plain(a.u.ranks),{S00:1});assert.deepEqual(plain(enemy.loadout),['LS02']);assert.equal(a.b.heroes.knight.kills,17);assert.equal(a.b.heroes.knight.damage,6789);assert.equal(a.b.heroes.knight.xp,C.xpAtLevel(15));assert.equal(a.u.maxHp,C.heroStats(a.b.heroes.knight,'knight').hp);assert.equal(a.u.armor,C.heroStats(a.b.heroes.knight,'knight').armor);});
test('Salheun triggers only once for a native multi-arrow action and ages through a stunned own turn',()=>{const a=arena('A04',8);a.u.ranks.AP05=8;const t=a.foe();a.fire();arrowHit(a,t,100,{id:501});a.ready();a.fire();const hits=a.b.hits;for(let i=0;i<7;i++)arrowHit(a,t,100,{id:600+i});assert.equal(a.b.hits-hits,8);const turn=a.u.arrowTurn;a.u.stun=1;a.e.newRound();assert.equal(a.u.arrowTurn,turn+1);assert(a.u.acted);});
test('Salheun does not change the repeat volley count, cadence, damage or native spread',()=>{const runs=[];for(const rank of [0,8]){const a=arena('A04',8);a.u.ranks.AP01=8;a.u.ranks.AP05=rank;a.fire();const schedule=[];for(let i=0;i<400&&a.b.volley;i++){a.e.stepVolley(C.STEP);schedule.push(a.b.projectiles.map(p=>[p.skill,p.damage,p.vx,p.vy,p.followup]));}runs.push(schedule);}assert.deepEqual(runs[0],runs[1]);});
test('Life slash scales with HP cost and armor mitigation with a forced critical roll',()=>{const rows=[];for(const hp of [100,350,700]){const a=arena('S02',8),t=a.foe(900,1700,{armor:.4});a.u.hp=hp;a.e.random=()=>0;const before=t.hp;a.fire(.6,0);a.run();rows.push({hp,cost:Math.floor(hp*.5),damage:before-t.hp,remaining:a.u.hp});}assert(rows[2].damage>rows[1].damage&&rows[1].damage>rows[0].damage);assert(rows.every(r=>r.remaining===r.hp-r.cost));details.lifeHpBalance=rows;});


test('Jucheon increases actual healing and gourd fragments while wave geometry remains within its 5% cap',()=>{const rows=[];for(const boost of [0,.15]){const a=arena('M10',8);a.u.hp=200;a.u.focus=200;a.u.moveLeft=100;a.b.stakes=[{id:55,skill:'M10',owner:a.u.id,side:0,x:a.u.x,y:a.u.y,rank:8,damage:0,shot:1,effectBoost:boost}];C.tickRedesign(a.e,C.STEP);const heal=a.u.hp-200;const g=arena('M06',8);g.u.ranks.MP05=8;g.u.jucheonReady=!!boost;const p=g.fire(.5,30);g.e.impact(p,{x:p.x,y:p.y,n:{x:0,y:-1},terrain:g.b.terrain[0],t:0});const chip=g.b.projectiles.find(v=>v.secondary);assert(chip);const w=arena('M15',8);w.u.ranks.MP05=8;w.u.jucheonReady=!!boost;const pred=w.e.predict(w.u,C.SKILLS.M15,30,.5);rows.push({heal,fragment:chip.damage,geometry:pred.geometry});}assert(rows[1].heal>rows[0].heal);assert(rows[1].fragment>rows[0].fragment*1.15);assert(rows[1].geometry.radius<=rows[0].geometry.radius*1.051);details.jucheonEffects=rows;});


test('Melee and screen guides turn with aim before firing; the screen covers the full front half arc',()=>{const a=arena();a.u.facing=1;a.u.angle=160;const arcs=[],c={save(){},restore(){},translate(){},setLineDash(){},beginPath(){},moveTo(){},closePath(){},stroke(){},arc(...args){arcs.push(args);}};C.drawMeleeGuide(c,a.e,a.u,C.SKILLS.S00,1,.5);assert(Math.abs((arcs[0][3]+arcs[0][4])/2+160*Math.PI/180)<1e-8);arcs.length=0;C.drawMeleeGuide(c,a.e,a.u,C.SKILLS.S14,1,.5);assert(Math.abs(arcs[0][4]-arcs[0][3]-Math.PI)<1e-8);});
test('Martial flights share the same storm-field amplification as ordinary projectiles',()=>{const a=arena('S09'),p=a.fire(.5,30),damage=p.damage;a.b.fields=[{id:'storm',kind:'storm',x:p.x,y:p.y,radius:100,strength:100}];a.e.stepProjectile(p,C.STEP);assert.equal(p.amplification,1.3);assert.equal(p.damage,damage*1.3);a.e.stepProjectile(p,C.STEP);assert.equal(p.damage,damage*1.3);});

await mkdir('_local/reports/hwigyeom-p5',{recursive:true});await writeFile('_local/reports/hwigyeom-p5/unit.json',JSON.stringify({checks,details},null,2)+'\n');if(checks.some(c=>!c.pass))process.exitCode=1;
