import assert from 'node:assert/strict';
import {appHarness,plain,report} from './app-regression-helpers.mjs';
const h=await appHarness(),{g,C,click,finish,load,profileThrough,reload}=h,R=g.HonroRestJourney,D=g.HonroJourneyContent,checks=[];
let app;function check(name,fn){fn();checks.push(name);console.log('PASS',name);}
check('Prologue autoplays, blocks optional controls and resumes exact line',()=>{app=load(profileThrough(0));click('rest');assert.equal(app.dialogue.restKind,'map');g.HonroStory.next(app);g.HonroStory.next(app);const saved=plain(app.profile.honroJourney.story);click('camp');assert.equal(app.screen,'rest');app=reload();click('rest');assert.equal(app.dialogue.index,saved.index);assert.equal(app.dialogue.id,saved.id);finish(app);assert(app.profile.seen['rest-interlude-v1-1']);click('rest');assert.equal(app.dialogue,null);});
check('All chapters move narration into Seolo rest dialogue with no repeated interlude on entry',()=>{for(let id=1;id<=20;id++){app=load(profileThrough(id-1));click('rest');if(app.dialogue.restKind==='map')g.HonroStory.finish(app);assert.equal(app.dialogue.id,`rest-interlude-v1-${id}`);assert.deepEqual(plain(app.dialogue.lines),plain(D.interlude(id)));assert(app.dialogue.lines.every(l=>l[0]==='설오'));assert(!h.nodes.get('dialogue-root').innerHTML.includes('narration-overlay'));finish(app);click('journey-enter',{id:String(id)});assert.equal(app.stage.id,id);assert(!app.dialogue.lines.some(l=>D.interlude(id).some(n=>n[1]===l[1])));assert(app.dialogue.lines.some(l=>l[2]?.kind==='guide'));}});
check('Saved battle survives rest, book selection, cancel and continue',()=>{app=load(profileThrough(4));app.launch(5);finish(app);app.engine.active.hp-=17;app.engine.active.focus-=9;app.engine.b.round=7;app.engine.b.items.heal=0;click('rest');finish(app);const before=plain(app.profile.honroBattle);click('journey-book');click('journey-select',{id:'1'});assert.equal(R.currentId(app.profile),5);click('journey-replay',{id:'1'});assert(app.pendingJourneyLaunch);click('cancel-journey-launch');assert.deepEqual(plain(app.profile.honroBattle),before);click('continue');assert.deepEqual(plain(app.engine.b.units),before.units);assert.equal(app.engine.b.round,7);});
check('Confirmed replay and retry retain replay navigation without duplicate growth',()=>{click('rest');finish(app);const xp=app.profile.heroes.archer.xp;click('journey-book');click('journey-replay',{id:'1'});click('confirm-journey-launch');assert(app.engine.b.honroJourneyReplay);finish(app);click('retry');assert(app.engine.b.honroJourneyReplay);finish(app);app.engine.b.phase='won';app.outcome(true);assert.equal(app.profile.heroes.archer.xp,xp);click('result-continue');assert.equal(app.screen,'journey');assert.equal(D.next(app.profile).stageId,5);});
check('Stale confirmation cannot replace a newer saved session',()=>{app=load(profileThrough(4));app.launch(5);finish(app);click('rest');finish(app);click('journey-book');click('journey-replay',{id:'1'});app.profile.honroBattle.session+='-new';const before=plain(app.profile.honroBattle);click('confirm-journey-launch');assert.deepEqual(plain(app.profile.honroBattle),before);assert.equal(app.engine,null);assert.match(app.lastNotice,/바뀌었습니다/);});
check('Original-place dialogue never becomes next-place optional text after resumed victory',()=>{for(const id of [5,20])for(const kind of ['arrival','optional'])for(const legacy of [false,true]){app=load(profileThrough(id-1));app.launch(id);finish(app);if(kind==='arrival')delete app.profile.seen[`rest-interlude-v1-${id}`];click('rest');if(kind==='optional'){finish(app);click('rest-talk',{class:'archer'});}const original=app.dialogue.id;if(legacy){delete app.profile.honroJourney.story.stageId;app.persist();}app=reload();click('continue');finish(app);app.engine.b.phase='won';app.outcome(true);click('result-continue');assert.equal(app.dialogue.restKind,'arrival');assert.notEqual(app.dialogue.id,original);assert.equal(app.dialogue.id,`rest-interlude-v1-${id===20?'end':id+1}`);click('rest-talk',{class:'archer'});assert.equal(app.dialogue.restKind,'arrival');finish(app);}});
check('Sodan recruitment, optional-only actor clicks and all-companion fire are retained',()=>{app=load(profileThrough(10));app.profile.recruited=['archer','mage','knight'];click('rest');finish(app);assert(app.profile.recruited.includes('occultist'));assert.equal((app.root.innerHTML.match(/data-action="rest-talk"/g)||[]).length,4);click('rest-talk',{class:'occultist'});assert.equal(app.dialogue.restKind,'optional');finish(app);click('camp');assert.equal(app.screen,'camp');});
check('Only authored urgent links skip rest and survive reload at result',()=>{for(const id of [1,9,18]){app=load(profileThrough(id-1));app.launch(id);finish(app);app.engine.b.phase='won';app.outcome(true);assert.equal(app.profile.honroJourney.pendingDirect,id+1);app=reload();click('rest');assert.equal(app.stage.id,id+1);assert.equal(app.screen,'battle');assert.equal(app.profile.honroJourney.pendingDirect,undefined);}app=load(profileThrough(16));app.launch(17);finish(app);app.engine.b.phase='won';app.outcome(true);click('result-continue');assert.equal(app.screen,'rest');});
await report('rest-journey',checks);
