import {beforePlatformPassages} from './platform-passage-delta-helpers.mjs';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {runtime,battlefield} from '../game/tests/helpers.mjs';
const g=await runtime({legacyMaps:false}),D=g.HonroTerrainDomain,C=g.HONRO_CORE,plain=v=>JSON.parse(JSON.stringify(v)),hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),fixture=JSON.parse(await readFile('tests/fixtures/terrain-domain-baseline.json','utf8')),checks=[];
function check(name,fn){fn();checks.push(name);console.log('PASS',name);}
const between=(points,x)=>{const ys=[];for(let i=0;i<points.length;i++){const a=points[i],z=points[(i+1)%points.length];if((a.x<=x&&z.x>x)||(z.x<=x&&a.x>x))ys.push(a.y+(z.y-a.y)*(x-a.x)/(z.x-a.x));}return ys.sort((a,b)=>a-b);};
check('All 20 stages use a single canonical mesh containing stable playBounds',()=>{assert.equal(g.HONRO_PROJECT.version,6);for(const st of g.HONRO_PROJECT.stages){assert.deepEqual(plain(st.playBounds),{left:0,top:0,right:st.width,bottom:st.height});assert(st.terrains.some(t=>t.playProjection));assert.equal(D.validate(st).length,0);assert.deepEqual(plain(D.author({stages:[st]}).stages[0]),plain(st));}});
for(const before of fixture.stages)check(before.id+': exact original collision, combat setup and progression',()=>{const st=beforePlatformPassages(g.HONRO_PROJECT).stages.find(s=>s.id===before.id);for(const t of before.terrain)assert.equal(hash(g.HonroGeometry.terrain(st.terrains.find(v=>v.id===t.id),st.height)),t.hash,t.id);for(const key of ['units','events','initialState','objectives','encounters'])assert.equal(hash(st[key]),before[key],key);});
check('Cave corridors stay open and partial entrances have finite natural ridge tops',()=>{for(const st of g.HONRO_PROJECT.stages.slice(10)){const world=st.terrains.map(t=>g.HonroGeometry.terrain(t,st.height,true)),floor=world.find(t=>t.honroSurfaceRole==='floor'),roofs=world.filter(t=>t.honroCeiling);for(const side of [-1,1]){const edge=side<0?0:st.width;for(const roof of roofs){if(!between(C.poly(roof),edge-side*.1).length)continue;for(const d of [1,200,500,1000,2400,4000,5900]){const x=edge+side*d,f=between(C.poly(floor),x),r=between(C.poly(roof),x);assert(f.length>=2&&r.length>=2,st.id+' continuation');assert(f[0]-r.at(-1)>50,st.id+' open corridor at '+x);}}}if([12,13,20].includes(st.metadata.stageId))assert(roofs[0].y>=-2000);}});
check('Extended terrain never enlarges walking or knockback bounds',()=>{for(const id of [1,2,11,14,18,20]){const {b,e}=battlefield(g,id),u=e.active;assert(D.active(b));for(const side of [-1,1]){u.x=side<0?25:b.width-25;u.y=100;u.moveLeft=1e5;for(let i=0;i<30;i++)e.walk(u,side,1/60);assert(u.x>=25&&u.x<=b.width-25);u.vx=side*2000;u.vy=0;e.integrateBody(u,1/60);assert(u.dead||u.x>=-40&&u.x<=b.width+40);}assert(b.terrain.every(t=>t.x>=0&&t.x+t.w<=b.width));}});
check('Live rock-pin restoration updates the whole mesh and survives reload',()=>{const {b,e,app}=battlefield(g,12);g.HonroAct2.attach(app,e);const floor=b.terrain.find(t=>t.id==='act2-floor'),old=JSON.stringify(D.render(b).find(t=>t.id===floor.id).vertices);e.damageTerrain(b.terrain.find(t=>t.id==='rock-pin'),1000);const world=D.render(b).find(t=>t.id===floor.id);assert.notEqual(JSON.stringify(world.vertices),old);const source=b.honroWorldTerrain.find(t=>t.id===floor.id);assert.deepEqual(plain(D.projection({points:world.vertices,playProjection:source.honroDomainProjection}).points),plain(floor.vertices));assert.deepEqual(plain(D.render(plain(b)).find(t=>t.id===floor.id).vertices),plain(world.vertices));});
check('Save roundtrip preserves domain and old battles are never silently migrated',()=>{const {b}=battlefield(g,14),saved=JSON.stringify(b),restored=JSON.parse(saved);assert(D.active(restored));assert.equal(JSON.stringify(restored),saved);const legacy=plain(b);for(const key of ['honroWorldTerrain','honroPlayBounds','honroTerrainBounds','honroTerrainDomainVersion'])delete legacy[key];const before=JSON.stringify(legacy);D.render(legacy);assert.equal(JSON.stringify(legacy),before);assert(!D.active(legacy));});
check('Malformed, null and removed projection metadata are rejected safely',()=>{for(const bad of [null,[null],{},'points']){const st=plain(g.HONRO_PROJECT.stages[0]);st.terrains[0].points=bad;assert(D.validate(st).some(x=>x.level==='err'));}for(const bad of [null,true,{bounds:null},{bounds:{left:0,top:0,right:1,bottom:1},start:null}]){const st=plain(g.HONRO_PROJECT.stages[0]);st.terrains[0].playProjection=bad;assert(D.validate(st).some(x=>x.level==='err'));}const missing=plain(g.HONRO_PROJECT.stages[0]);delete missing.terrains[0].playProjection;assert(D.validate(missing).some(x=>x.level==='err'));for(const bad of [null,true,'bad',{bounds:null}]){const {b}=battlefield(g,1);b.honroWorldTerrain[0].honroDomainProjection=bad;assert(!D.active(b),'corrupted saved projection must not reach renderer');assert.strictEqual(D.render(b),b.terrain);}const {b}=battlefield(g,1);b.honroWorldTerrain[0].vertices=[{x:NaN,y:0}];assert(!D.active(b));assert.strictEqual(D.render(b),b.terrain);});
check('Workshop interior edits use stage limits rather than a stale solid AABB',()=>{const st=plain(g.HONRO_PROJECT.stages[1]),t=st.terrains.find(t=>t.id==='left-high-ground');for(const p of t.points)if(p.x>0)p.x+=80;const projected=g.HonroGeometry.terrain(t,st.height);assert.equal(projected.x+projected.w,1580);assert.equal(projected.x,0);});
await mkdir('_local/reports/terrain-domain',{recursive:true});await writeFile('_local/reports/terrain-domain/contracts.json',JSON.stringify({sourceCommit:fixture.sourceCommit,checks,collisionSolids:fixture.stages.reduce((n,s)=>n+s.terrain.length,0),limits:'Logic/geometry/save tests; native and browser pixels are separate.'},null,2)+'\n');
