(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const uid=(p='id')=>`${p}_${Math.random().toString(36).slice(2,8)}_${Date.now().toString(36).slice(-4)}`;
const deep=x=>structuredClone?structuredClone(x):JSON.parse(JSON.stringify(x));
const round=(v,n=1)=>Math.round(v*10**n)/10**n;
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const seeded=s=>{let x=(s|0)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return (x>>>0)/4294967296}};
const COLORS={soil:'#514c40',grass:'#385334',moss:'#475f44',rock:'#575d5a',scree:'#4b4d46',mud:'#443a32',water:'#426975',charred:'#332f2b',stone:'#66665e',wood:'#574b37'};

// Geometry helpers shared by human UI and Agent API.
function pointLineDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,n=dx*dx+dy*dy;if(!n)return dist(p,a);const t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/n,0,1),q={x:a.x+dx*t,y:a.y+dy*t};return dist(p,q)}
function rdpOpen(points,epsilon=0){return HonroGeometry.simplify(points,epsilon)}

function rdpClosed(points,epsilon=0){return HonroGeometry.simplifyClosed(points,epsilon)}

function pointInPoly(p,pts){let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const a=pts[i],b=pts[j];if(((a.y>p.y)!==(b.y>p.y))&&(p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y||1e-9)+a.x))inside=!inside}return inside}
function gridSnapPoint(p,size=project?.settings?.grid||40){const g=Math.max(2,+size||40);return{x:Math.round(p.x/g)*g,y:Math.round(p.y/g)*g}}
function terrainEditPoints(t){return t.type==='solid'?(t.points||[]):(t.control||[])}
function syncAssetCollision(a){if(a.vector)return;if(a.collisionMode!=='independent'&&a.collision.length)a.collision=deep(a.visual.filter(s=>s.type==='polygon').map(s=>s.points));if(a.reference&&a.visual.length)a.reference.bounds=HonroEnvironment.referenceForLegacyAsset(a).bounds}
function polylineNodeCount(st){return st.terrains.reduce((n,t)=>n+deriveTerrain(t).length,0)}
function assetNodeCount(a){if(a.vector)return 0;return a.visual.reduce((n,sh)=>n+(sh.points?.length||0),0)}
function sceneStats(st){let elementNodes=0;for(const e of st.elements){const a=project.library.find(x=>x.id===e.assetId);if(a)elementNodes+=assetNodeCount(a)}return{terrainControl:st.terrains.reduce((n,t)=>n+terrainEditPoints(t).length,0),terrainDerived:polylineNodeCount(st),elementNodes,elementCount:st.elements.length,materialCount:st.materials.length,total:polylineNodeCount(st)+elementNodes}}
function visibleRect(canvas,view,margin=100){const w=canvas.clientWidth/view.zoom,h=canvas.clientHeight/view.zoom;return{left:view.x-w/2-margin,right:view.x+w/2+margin,top:view.y-h/2-margin,bottom:view.y+h/2+margin}}
function elementVisible(a,inst,vr){const b=assetBounds(a),cx=inst.x+(b.x+b.w/2)*inst.scale,cy=inst.y+(b.y+b.h/2)*inst.scale,r=Math.hypot(b.w,b.h)*Math.abs(inst.scale||1)*.65+30;return !(cx+r<vr.left||cx-r>vr.right||cy+r<vr.top||cy-r>vr.bottom)}

function regularPoly(n,rx,ry,seed=1,skew=0){const r=seeded(seed),pts=[];for(let i=0;i<n;i++){const a=-Math.PI/2+i*Math.PI*2/n,f=.76+r()*.34;pts.push({x:Math.cos(a)*rx*f+(r()-.5)*skew,y:Math.sin(a)*ry*f});}return pts}

function shape(points,fill='#666',stroke='#222',alpha=1){return{type:'polygon',points,fill,stroke,alpha}}
function asset(id,name,category,visual,opt={}){const a={id,name,category,visual,collision:opt.collision?deep(visual.filter(s=>s.type==='polygon').map(s=>s.points)):[],anchor:{x:0,y:0},sockets:opt.sockets||[],breakable:!!opt.breakable,oneWay:!!opt.oneWay,tags:opt.tags||[],params:{}};a.reference=opt.reference||HonroEnvironment.referenceForLegacyAsset(a);return a}






function defaultStage(id=uid('stage'),name='새 스테이지',w=5000,h=3200){const st=HonroMaps.emptyStage(id,name,w,h);st.units.push(HonroUnits.record('archer',uid('unit'),220,500,'player'));return st}

function defaultLayers(){return HonroMaps.layers()}



function newProject(){return deep(HONRO_PROJECT)}

let project=loadAutosave()||newProject(), currentTab='stage', selectedAssetId=project.library[0]?.id, selected=null, selectedNode=-1, selectedShapeIndex=-1, tool='select', materialKind='grass', placementAssetId='rock_large', unitKind='hound', eventKind='trigger', previewProject=null;
let history=[],future=[],stageView={x:0,y:0,zoom:1},elementView={x:0,y:0,zoom:1},playState=null,drawStroke=[],paintStroke=[],solidDraft=[],elementPolygonDraft=[],scatterStamp=0,placementDepthLayer='L1',placementGroupId='',placementSupportId='';
const dom={};
let editorRuntime=null,editorRevision=0,overlayEnabled=true,boundsEnabled=false,playFrame=null,playReady=null,playSnapshot=null,previewCommandsKey=null;
function invalidateRuntime(){editorRuntime=null;editorRevision++}

function activeProject(){return previewProject||project}
function stage(){const p=activeProject();return p.stages.find(s=>s.id===p.activeStageId)||p.stages[0]}
function realStage(){return project.stages.find(s=>s.id===project.activeStageId)||project.stages[0]}
function activeAsset(){return project.library.find(a=>a.id===selectedAssetId)||project.library[0]}
function commit(label,fn,before=deep(project)){try{fn(project);project=HonroMaps.finalize(project)}catch(e){project=before;throw e}history.push({label,state:before});if(history.length>80)history.shift();future=[];previewProject=null;saveAutosave();renderAll();setStatus(label)}
function undo(){if(!history.length)return;future.push({label:'redo',state:deep(project)});project=history.pop().state;previewProject=null;saveAutosave();renderAll();toast('되돌렸습니다')}
function redo(){if(!future.length)return;history.push({label:'undo',state:deep(project)});project=future.pop().state;previewProject=null;saveAutosave();renderAll();toast('다시 적용했습니다')}
function saveAutosave(){if(project.settings.autosave)try{localStorage.setItem('honro-workshop-v3',JSON.stringify(project))}catch(e){}}
function loadAutosave(){try{const x=JSON.parse(localStorage.getItem('honro-workshop-v3')||localStorage.getItem('honro-workshop-v1'));return x?HonroMaps.normalize(x):null}catch{return null}}

function setStatus(s){if(dom.status)dom.status.textContent=s}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),1500)}

function deriveTerrain(t){return HonroGeometry.derive(t)}

function terrainSurfaceYs(t,x){return HonroGeometry.surfaces(t,x,stage().height)}

function sampleTerrainY(t,x,reference=Infinity){const ys=terrainSurfaceYs(t,x);if(!ys.length)return null;if(Number.isFinite(reference))return ys.reduce((a,b)=>Math.abs(a-reference)<=Math.abs(b-reference)?a:b);return Math.min(...ys)}
function nearestSurface(st,x,y=Infinity){return HonroGeometry.nearest(st,x,y)}

function materialPolygon(st,m){return HonroGeometry.material(st,m).points.map(p=>({x:p[0],y:p[1]}))}

function transformedShapes(a,e){if(a.vector){const b=assetBounds(a);return[{points:[{x:b.x,y:b.y},{x:b.x+b.w,y:b.y},{x:b.x+b.w,y:b.y+b.h},{x:b.x,y:b.y+b.h}].map(p=>HonroGeometry.transformPoint(p,a,e))}]}return HonroGeometry.shapes(a,e)}

function assetBounds(asset){if(asset.bounds)return asset.bounds;const pts=asset.visual.flatMap(s=>s.points);if(!pts.length)return{x:-20,y:-20,w:40,h:40};const xs=pts.map(p=>p.x),ys=pts.map(p=>p.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}
function snapElement(st,inst){if(!inst.snap)return inst;const sf=nearestSurface(st,inst.x,inst.y);if(sf)inst.y=sf.y;return inst}
function layerVisible(st,id){return st.layers.find(l=>l.id===id)?.visible!==false}
function layerLocked(st,id){return st.layers.find(l=>l.id===id)?.locked===true}

function init(){cacheDom();bindTop();bindCanvas(dom.stageCanvas,'stage');bindCanvas(dom.elementCanvas,'element');resizeAll();addEventListener('resize',resizeAll);renderAll();requestAnimationFrame(loop)}
function cacheDom(){Object.assign(dom,{stageCanvas:$('#stageCanvas'),stageOverlay:$('#stageOverlay'),elementCanvas:$('#elementCanvas'),playCanvas:$('#playCanvas'),status:$('#statusText'),left:$('#leftContent'),right:$('#rightContent')})}
function bindTop(){
 $$('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('#overlayToggle').onchange=e=>{overlayEnabled=e.target.checked;renderStage()};$('#boundsToggle').onchange=e=>{boundsEnabled=e.target.checked;renderStage()};$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;
 $('#exportBtn').onclick=downloadProject;$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=importFile;$('#newStageBtn').onclick=createStageDialog;
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(e.key==='Enter'){if(currentTab==='stage'&&tool==='solid')finalizeSolid();else if(currentTab==='element'&&elementTool==='polygon')finalizeElementPolygon();return}if(e.key==='Delete'||e.key==='Backspace'){if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(currentTab==='element'){const a=activeAsset();if(a.vector)return;if(selectedNode>=0){const n=nodeByGlobal(a,selectedNode);if(n&&n.shape.points.length>3)commit('Vertex 삭제',()=>{n.shape.points.splice(n.index,1);syncAssetCollision(a);selectedNode=-1})}else if(selectedShapeIndex>=0&&a.visual.length>1)commit('Polygon 삭제',()=>{a.visual.splice(selectedShapeIndex,1);syncAssetCollision(a);selectedShapeIndex=-1});return}deleteSelection()}if(e.key==='Escape'){selected=null;selectedNode=-1;selectedShapeIndex=-1;solidDraft=[];elementPolygonDraft=[];renderAll()}})
}
function switchTab(t){if(currentTab==='play'&&t!=='play')stopPlay(false);currentTab=t;document.body.classList.toggle('playing',t==='play');$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===t));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`${t}View`));renderAll();resizeAll()}
function resizeAll(){for(const c of [dom.stageCanvas,dom.stageOverlay,dom.elementCanvas]){if(!c)continue;const r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));c._dpr=d}fitInitialViews();renderAll()}
function fitInitialViews(){const st=stage();if(!stageView._fit&&dom.stageCanvas?.clientWidth){stageView.zoom=Math.min(dom.stageCanvas.clientWidth/st.width,dom.stageCanvas.clientHeight/st.height)*.9;stageView.x=st.width/2;stageView.y=st.height/2;stageView._fit=true}if(!elementView._fit){elementView.zoom=1;elementView.x=0;elementView.y=-100;elementView._fit=true}}

function renderAll(){invalidateRuntime();renderToolbars();renderPanels();if(currentTab==='stage')renderStage();else if(currentTab==='element')renderElement();else renderPlay();updateTop();requestAnimationFrame(()=>{renderAssetPreviews();renderUnitPreviews()})}
function updateTop(){$('#projectName').textContent=project.name;$('#undoBtn').disabled=!history.length;$('#redoBtn').disabled=!future.length}
function renderPanels(){if(currentTab==='stage')renderStagePanels();else if(currentTab==='element')renderElementPanels();else renderPlayPanels()}

function renderStagePanels(){const st=stage(),cats=['all','native','rock','tree','branch','vegetation','architecture','prop','environment'];const cat=renderStagePanels.cat||'all';
 dom.left.innerHTML=`<div class="panel-scroll">
 <div class="panel-section"><div class="panel-title"><span>STAGES</span><button class="btn sm" id="dupStage">복제</button></div><div class="stage-list">${activeProject().stages.map(s=>`<button class="stage-card ${s.id===st.id?'active':''}" data-stage="${s.id}">${esc(s.name)}<br><span class="muted">${s.width}×${s.height}</span></button>`).join('')}</div></div>
 <div class="panel-section"><div class="panel-title"><span>PLACE SETTINGS</span></div>${toolPlacementHtml()}<div class="row"><label>Depth</label><select id="placeDepthLayer" class="field">${['L1','L2','L3','L4'].filter(l=>l==='L1'||HonroEnvironment.preset(st).depths[l]!==undefined).map(l=>`<option value="${l}" ${placementDepthLayer===l?'selected':''}>${l}</option>`).join('')}</select></div>${placementEnvironmentHtml(st)}</div>
 <div class="panel-section"><div class="panel-title"><span>ASSET LIBRARY</span><button class="btn sm" id="gotoElements">편집</button></div><div class="library-filter">${cats.map(c=>`<button class="pill ${c===cat?'active':''}" data-cat="${c}">${c==='all'?'전체':c}</button>`).join('')}</div><div class="asset-grid">${project.library.filter(a=>cat==='all'||a.category===cat).map(assetCard).join('')}</div></div>
 <div class="panel-section"><div class="panel-title"><span>LAYERS</span></div><div class="layer-list">${st.layers.map(l=>`<div class="layer-item"><span class="eye ${l.visible?'':'off'}" data-eye="${l.id}">${l.visible?'◉':'○'}</span><span class="lock ${l.locked?'':'off'}" data-lock="${l.id}">◆</span><span class="name">${esc(l.name)}</span></div>`).join('')}</div></div>
 </div>`;
 $$('.stage-card').forEach(b=>b.onclick=()=>{project.activeStageId=b.dataset.stage;selected=null;stageView._fit=false;renderAll();resizeAll()});$('#dupStage').onclick=()=>duplicateStage(st.id);$('#gotoElements').onclick=()=>switchTab('element');$$('[data-cat]').forEach(b=>b.onclick=()=>{renderStagePanels.cat=b.dataset.cat;renderAll()});$$('.asset-card').forEach(b=>b.onclick=()=>{placementAssetId=b.dataset.asset;tool='place';renderAll()});const uk=$('#placeUnitKind');if(uk)uk.onchange=()=>unitKind=uk.value;const ek=$('#placeEventKind');if(ek)ek.onchange=()=>eventKind=ek.value;$$('[data-eye]').forEach(b=>b.onclick=()=>commit('레이어 표시 변경',p=>{const x=realStage().layers.find(l=>l.id===b.dataset.eye);x.visible=!x.visible}));$$('[data-lock]').forEach(b=>b.onclick=()=>commit('레이어 잠금 변경',p=>{const x=realStage().layers.find(l=>l.id===b.dataset.lock);x.locked=!x.locked}));
 dom.right.innerHTML=`<div class="panel-scroll">${stageInspectorHtml(st)}<div class="panel-section"><div class="panel-title"><span>AGENT COWORK</span><button class="btn sm" id="copyContext">Context 복사</button></div><textarea id="agentCommands" class="field agent-text" spellcheck="false">${esc(JSON.stringify([{op:'element.place',assetId:'rock_large',x:1600,layer:'interactive'}],null,2))}</textarea><div class="row"><button class="btn sm" id="previewCmd">Preview</button><button class="btn sm primary" id="applyCmd">Apply</button><button class="btn sm" id="discardCmd">Discard</button></div><div id="changes" class="changes">AI/Agent는 같은 Command API로 맵을 수정합니다.</div></div><div class="panel-section"><div class="panel-title"><span>VALIDATION</span><button class="btn sm" id="validateBtn">검사</button></div><div id="validation" class="validation">${validationHtml(validateStage(st))}</div></div></div>`;
 $$('[data-unit-kind]').forEach(b=>b.onclick=()=>{unitKind=b.dataset.unitKind;tool='unit';renderAll()});bindStageInspector(st);bindEnvironmentInspector(st);$('#copyContext').onclick=copyAgentContext;$('#previewCmd').onclick=()=>runAgent(false);$('#applyCmd').onclick=()=>runAgent(true);$('#discardCmd').onclick=()=>{clearPreview();$('#changes').textContent='Preview 취소'};$('#validateBtn').onclick=()=>$('#validation').innerHTML=validationHtml(validateStage(stage()));
}


function placementGroup(st){return st.environment.groups.find(g=>g.id===placementGroupId&&g.depthLayer===placementDepthLayer)||st.environment.groups.find(g=>g.depthLayer===placementDepthLayer&&g.zoneId===HonroEnvironment.zoneWeights(st,stageView.y).sort((a,b)=>b.weight-a.weight)[0]?.zone.id)||st.environment.groups.find(g=>g.depthLayer===placementDepthLayer)}
function options(items,value){return items.map(x=>`<option value="${esc(x.id)}" ${x.id===value?'selected':''}>${esc(x.name||x.id)}</option>`).join('')}
function placementEnvironmentHtml(st){if(placementDepthLayer==='L1')return '<p class="muted node-label">전장 지면에 배치 · WORLD</p>';const g=placementGroup(st);return `<div class="row"><label>Zone</label><select id="placeZone" class="field">${options(st.environment.zones,g?.zoneId)}</select></div><div class="row"><label>Group</label><select id="placeGroup" class="field">${options(st.environment.groups.filter(x=>x.depthLayer===placementDepthLayer&&x.zoneId===g?.zoneId),g?.id)}</select></div><div class="row"><label>Support</label><select id="placeSupport" class="field">${options(st.environment.surfaces.filter(x=>x.groupId===g?.id),placementSupportId)}</select></div><p class="muted node-label">${esc(g?.verticalMode||'')} · 지지면에 뿌리를 붙입니다.</p>`}
function environmentPanel(st){return `<div class="panel-section"><div class="panel-title">ENVIRONMENT</div><div class="row"><label>Atmosphere</label><select id="environmentPreset" class="field">${options(Object.keys(HonroEnvironment.ATMOSPHERES).map(id=>({id})),st.environment.atmosphere.preset)}</select></div><p class="muted node-label">구역 ${st.environment.zones.length} · 풍경 ${st.environment.groups.length} · 지지면 ${st.environment.surfaces.length}</p><details><summary>풍경 고급 편집</summary><p class="muted node-label">묶음·지지면·높이 구역을 함께 편집합니다. Apply 전에 구조를 검사합니다.</p><textarea id="environmentStructure" class="field agent-text">${esc(JSON.stringify({groups:st.environment.groups,surfaces:st.environment.surfaces,zones:st.environment.zones,atmosphere:st.environment.atmosphere},null,2))}</textarea><button id="applyEnvironment" class="btn sm">Apply</button></details>${(st.environment.migrationNotes||[]).map(n=>`<p class="muted node-label">${esc(n)}</p>`).join('')}</div>`}
function sceneryCompositionHtml(st,o){const g=HonroEnvironment.groupOf(st,o);return `<div class="row"><label>Group</label><select id="sceneryGroup" class="field">${options(st.environment.groups,g?.id)}</select></div><div class="row"><label>Support</label><select id="scenerySupport" class="field">${options(st.environment.surfaces.filter(s=>s.groupId===g?.id),o.supportId)}</select></div><p class="muted node-label">Zone: ${esc(g?.zoneId||'전체')} · X는 묶음 내부 좌표, Y는 부착점 오프셋입니다.</p><details><summary>묶음 설정</summary><p class="muted node-label">WORLD · 카메라 높이에 따른 배경 재배치는 없습니다.</p><div class="row"><label>Zone</label><select id="sceneryZone" class="field">${options(st.environment.zones,g?.zoneId)}</select></div><p class="muted node-label">같은 묶음의 지형과 모든 장식에 적용됩니다.</p></details>`}
function reattachScenery(st,o,changes){const a=project.library.find(a=>a.id===o.assetId),old=HonroEnvironment.groupOf(st,o),group=changes.groupId?st.environment.groups.find(g=>g.id===changes.groupId):st.environment.groups.find(g=>g.depthLayer===(changes.depthLayer||o.depthLayer)&&g.zoneId===old?.zoneId);const next=HonroEnvironment.place(st,a,{id:o.id,localX:o.x,scale:o.scale,rotation:o.rotation*180/Math.PI,depthLayer:group?.depthLayer||changes.depthLayer,groupId:group?.id,supportId:changes.supportId});Object.assign(o,next)}
function bindEnvironmentInspector(st){
 const depth=$('#placeDepthLayer');if(depth)depth.onchange=()=>{placementDepthLayer=depth.value;placementGroupId='';placementSupportId='';renderAll()};
 const group=$('#placeGroup');if(group)group.onchange=()=>{placementGroupId=group.value;placementSupportId='';renderAll()};
 const zone=$('#placeZone');if(zone)zone.onchange=()=>{placementGroupId=st.environment.groups.find(g=>g.depthLayer===placementDepthLayer&&g.zoneId===zone.value)?.id||'';placementSupportId='';renderAll()};
 const support=$('#placeSupport');if(support)support.onchange=()=>placementSupportId=support.value;
 const bind=(id,fn)=>{const el=$('#'+id);if(el)el.onchange=()=>{try{commit('환경 변경',()=>fn(realStage(),el.value))}catch(e){toast(e.message);renderAll()}}};
 bind('environmentPreset',(s,value)=>s.environment.atmosphere={preset:value});
 bind('sceneryGroup',(s,value)=>reattachScenery(s,getSelected(s),{groupId:value}));
 bind('scenerySupport',(s,value)=>reattachScenery(s,getSelected(s),{groupId:getSelected(s).groupId,supportId:value}));
 bind('sceneryZone',(s,value)=>HonroEnvironment.groupOf(s,getSelected(s)).zoneId=value);
 const apply=$('#applyEnvironment');if(apply)apply.onclick=()=>{try{const value=JSON.parse($('#environmentStructure').value);commit('풍경 구조 변경',()=>{for(const key of ['groups','surfaces','zones','atmosphere'])if(value[key]!==undefined)realStage().environment[key]=value[key]})}catch(e){toast(e.message);renderAll()}};
}
function drawEnvironmentGuides(ctx,c,st,view){if(!overlayEnabled||selected?.type!=='scenery')return;const e=getSelected(st),sf=e&&HonroEnvironment.supportOf(st,e),g=e&&HonroEnvironment.groupOf(st,e);if(!sf||!g)return;const t=HonroEnvironment.groupTransform(view,c.clientWidth,c.clientHeight,st,g);ctx.save();ctx.setTransform(c._dpr||1,0,0,c._dpr||1,0,0);ctx.strokeStyle='#e7c883';ctx.lineWidth=1.5;ctx.setLineDash([6,5]);ctx.beginPath();sf.points.forEach((p,i)=>i?ctx.lineTo(t.x+p.x*t.scale,t.y+p.y*t.scale):ctx.moveTo(t.x+p.x*t.scale,t.y+p.y*t.scale));ctx.stroke();ctx.restore()}

function toolPlacementHtml(){const a=project.library.find(x=>x.id===placementAssetId);if(tool==='unit')return `<div class="row"><label>Unit</label><select id="placeUnitKind" class="field">${HonroUnits.catalog().map(u=>`<option value="${u.kind}" ${unitKind===u.kind?'selected':''}>${esc(u.name)}</option>`).join('')}</select></div><div class="unit-palette">${HonroUnits.catalog().map(u=>`<button class="asset-card" data-unit-kind="${u.kind}"><canvas data-unit-preview="${u.kind}"></canvas><span>${esc(u.name)}</span></button>`).join('')}</div>`;if(tool==='event')return `<div class="row"><label>Event</label><select id="placeEventKind" class="field">${['trigger','objective','interaction','spawn','dialogue'].map(x=>`<option ${eventKind===x?'selected':''}>${x}</option>`).join('')}</select></div>`;if(tool==='scatter')return `<div class="muted node-label">Scatter asset: <strong>${esc(a?.name||'선택 없음')}</strong><br>Asset Library에서 먼저 요소를 선택한 뒤 Scatter tool로 전환하세요.</div>`;if(tool==='place')return `<div class="muted node-label">배치 요소: <strong>${esc(a?.name||'선택 없음')}</strong><br>surface snap이 기본 적용됩니다.</div>`;return `<div class="muted node-label">${toolHelp()}</div>`}
function assetCard(a){return`<button class="asset-card ${placementAssetId===a.id&&tool==='place'?'active':''}" data-asset="${a.id}"><div class="asset-preview"><canvas data-asset-preview="${a.id}"></canvas></div><div class="asset-name">${esc(a.name)}</div><div class="asset-cat">${a.category}</div>${a.collision.length?'<span class="asset-badge">COL</span>':''}</button>`}
function stageInspectorHtml(st){const stats=sceneStats(st);let body=`<div class="panel-section"><div class="panel-title"><span>STAGE</span></div><div class="row"><label>이름</label><input id="stageName" class="field" value="${esc(st.name)}"></div><div class="split"><div><label class="node-label">Width</label><input id="stageW" class="field num" type="number" value="${st.width}"></div><div><label class="node-label">Height</label><input id="stageH" class="field num" type="number" value="${st.height}"></div></div><div class="row"><label>Backdrop</label><select id="stageBackdrop" class="field">${['forest','temple','gate','river','valley','bridge','tree','shrine'].map(x=>`<option ${st.backdrop===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="split"><div><label class="node-label">Grid</label><input id="gridSize" class="field num" type="number" min="4" max="256" value="${project.settings.grid||40}"></div><div><label class="node-label">Adaptive LOD</label><div style="padding:6px 0"><input id="adaptiveLOD" type="checkbox" checked disabled> runtime raster LOD</div></div></div></div>`;
 body+=environmentPanel(st);
 body+=`<div class="panel-section"><div class="panel-title"><span>PERFORMANCE</span></div><div class="perf-grid"><span>Terrain</span><strong>${stats.terrainDerived}</strong><span>Element vector</span><strong>${stats.elementNodes}</strong><span>Total nodes</span><strong class="${stats.total>6000?'warn':'good'}">${stats.total}</strong></div><div class="row"><label>LOD ε</label><input id="stageOptimizeEps" class="field" type="number" min="0" max="80" step="1" value="4"><button id="optimizeStage" class="btn sm">전체 적용</button></div><div class="muted node-label">ε가 클수록 export/render node가 줄어듭니다. 원본 control은 유지됩니다.</div></div>`;
 if(!selected)return body+`<div class="panel-section"><div class="panel-title"><span>TOOL</span></div>${toolHelp()}</div><div class="panel-section"><div class="panel-title"><span>MATERIAL</span></div>${materialGrid()}</div>`;
 const o=getSelected(st);if(!o)return body;
 body+=`<div class="panel-section"><div class="panel-title"><span>SELECTED · ${selected.type.toUpperCase()}</span><button id="deleteSelected" class="btn sm danger">삭제</button></div><div class="row"><label>ID</label><input id="stableId" class="field" value="${esc(o.id)}"></div>`;
 if(selected.type==='terrain'){
  const raw=(o.type==='solid'?(o.points||[]):(()=>{const old=o.detail?.optimizeEpsilon;o.detail.optimizeEpsilon=0;const p=deriveTerrain(o).length;o.detail.optimizeEpsilon=old;delete o.__derivedCache;return Array(p).fill(0)})()).length,optimized=deriveTerrain(o).length;
  body+=`<div class="row"><label>이름</label><input id="objName" class="field" value="${esc(o.name||o.id)}"></div><div class="row"><label>Type</label><strong>${o.type}</strong></div><div class="row"><label>Material</label><select id="terrainBase" class="field">${Object.keys(COLORS).map(x=>`<option ${o.baseMaterial===x?'selected':''}>${x}</option>`).join('')}</select></div>`;
  if(o.type!=='solid')body+=`<div class="split"><div><label class="node-label">Generated spacing</label><input id="terrainSpacing" type="number" class="field" value="${o.detail?.spacing||20}"></div><div><label class="node-label">Roughness</label><input id="terrainRough" type="number" class="field" value="${o.detail?.roughness||0}"></div></div><div class="row"><label>Optimize ε</label><input id="terrainOptimize" type="number" class="field" min="0" max="80" step="1" value="${o.detail?.optimizeEpsilon||0}"></div><div class="row"><button id="roughenBtn" class="btn sm">Detail randomize</button><button id="smoothBtn" class="btn sm">Smooth controls</button></div><div class="muted node-label">Control ${o.control.length} · Raw ${raw} → Optimized ${optimized}</div>`;
  else body+=`<div class="muted node-label">Closed solid polygon · ${o.points?.length||0} vertices · overhang/cave 지원</div>`;
 }
 if(selected.type==='element'){const a=project.library.find(x=>x.id===o.assetId);body+=`<div class="row"><label>Asset</label><div>${esc(a?.name||o.assetId)}</div></div><div class="split"><div><label class="node-label">Scale</label><input id="elScale" class="field" type="number" step=".05" value="${o.scale}"></div><div><label class="node-label">Rotation°</label><input id="elRot" class="field" type="number" value="${round(o.rotation*180/Math.PI)}"></div></div><div class="row"><label>Layer</label><select id="elLayer" class="field">${st.layers.map(l=>`<option value="${l.id}" ${o.layer===l.id?'selected':''}>${esc(l.name)}</option>`).join('')}</select></div><div class="row"><label>Surface snap</label><input id="elSnap" type="checkbox" ${o.snap?'checked':''}></div>`}
 if(selected.type==='scenery'){body+=sceneryCompositionHtml(st,o);const a=project.library.find(x=>x.id===o.assetId);body+=`<div class="row"><label>Asset</label><strong>${esc(a?.name||o.assetId)}</strong></div><div class="row"><label>Depth</label><select id="sceneryDepth" class="field">${['L2','L3','L4'].filter(l=>HonroEnvironment.preset(st).depths[l]!==undefined).map(l=>`<option value="${l}" ${o.depthLayer===l?'selected':''}>${l}</option>`).join('')}</select></div><div class="row"><label>Physical scale</label><input id="sceneryScale" class="field" type="number" step=".05" min="${a?.reference?.backgroundRange?.[0]??.7}" max="${a?.reference?.backgroundRange?.[1]??1.3}" value="${o.scale}"></div>`}
 if(selected.type==='unit'){body+=unitInspector(o)}
 if(selected.type==='event'){body+=eventInspector(o)}
  if(['element','scenery','unit','event'].includes(selected.type))body+=`<div class="split"><label>X<input id="objectX" class="field" type="number" step="any" value="${o.x??0}"></label><label>Y<input id="objectY" class="field" type="number" step="any" value="${o.y??0}"></label></div>`;

 return body+`</div><div class="panel-section"><div class="panel-title"><span>MATERIAL</span></div>${materialGrid()}</div>`}
function materialGrid(){return`<div class="materials">${['soil','grass','moss','rock','scree','mud','water','charred','stone'].map(k=>`<button class="material ${materialKind===k?'active':''}" data-mat="${k}" data-kind="${k}">${k}</button>`).join('')}</div><div class="row"><label>Brush</label><input id="brushRange" class="field" type="range" min="40" max="700" value="220"><span id="brushVal" class="node-label">220</span></div>`}
function toolHelp(){const h={select:'클릭 선택 · 드래그 이동 · Terrain/solid node 직접 편집 · Ctrl+드래그: Grid snap',terrain:'마우스로 지표면을 그리면 고밀도 ground로 변환',solid:'클릭으로 닫힌 polygon 점 추가 · 더블클릭/Enter로 완료 · 동굴/overhang 제작',material:'지면 위를 드래그하여 material 구간 paint',place:'Library 요소 배치 후 자동으로 선택모드 · surface snap',scatter:'브러시 영역에 요소를 자연스럽게 scatter',unit:'아군/적/NPC 배치',event:'Trigger/Objective/Event marker 배치',pan:'드래그로 카메라 이동'};return`<div class="muted" style="font-size:10px;line-height:1.7">${h[tool]||''}</div>`}
function bindStageInspector(st){
 bindExtendedInspector(st);
 const change=(id,fn)=>{const e=$('#'+id);if(e)e.onchange=()=>commit('속성 변경',()=>fn(realStage(),e))};change('stageName',(s,e)=>s.name=e.value);change('stageW',(s,e)=>{s.width=Math.max(800,+e.value||s.width);HonroEnvironment.resize(s)});change('stageH',(s,e)=>{s.height=Math.max(600,+e.value||s.height);HonroEnvironment.resize(s)});change('stageBackdrop',(s,e)=>{s.backdrop=e.value;s.environment=HonroEnvironment.makeEnvironment(s)});change('objName',(s,e)=>{const o=getSelected(s);o.name=e.value});change('terrainBase',(s,e)=>getSelected(s).baseMaterial=e.value);change('terrainSpacing',(s,e)=>getSelected(s).detail.spacing=clamp(+e.value||20,6,180));change('terrainRough',(s,e)=>getSelected(s).detail.roughness=clamp(+e.value||0,0,80));change('terrainOptimize',(s,e)=>getSelected(s).detail.optimizeEpsilon=clamp(+e.value||0,0,100));change('elScale',(s,e)=>getSelected(s).scale=clamp(+e.value||1,.1,8));change('elRot',(s,e)=>getSelected(s).rotation=(+e.value||0)*Math.PI/180);change('elLayer',(s,e)=>getSelected(s).layer=e.value);change('gridSize',(s,e)=>project.settings.grid=clamp(+e.value||40,4,256));
 const lod=$('#adaptiveLOD');if(lod)lod.onchange=()=>commit('Adaptive LOD 변경',p=>p.settings.adaptiveLOD=lod.checked);const all=$('#optimizeStage');if(all)all.onclick=()=>{const eps=clamp(+$('#stageOptimizeEps').value||0,0,100);commit(`Stage terrain LOD ε=${eps}`,()=>{for(const t of realStage().terrains){if(t.type==='solid')t.points=HonroGeometry.simplifyClosed(t.points,eps);else{t.detail??={};t.detail.optimizeEpsilon=eps;delete t.__derivedCache}}})};
 change('sceneryDepth',(s,e)=>reattachScenery(s,getSelected(s),{depthLayer:e.value}));change('sceneryScale',(s,e)=>{const o=getSelected(s),a=project.library.find(a=>a.id===o.assetId),r=a.reference.backgroundRange;o.scale=clamp(+e.value||1,r[0],r[1])});const snap=$('#elSnap');if(snap)snap.onchange=()=>commit('Snap 변경',()=>getSelected(realStage()).snap=snap.checked);change('unitType',(s,e)=>{const u=getSelected(s),next=HonroUnits.record(e.value,u.id,u.x,u.y,u.team);Object.keys(u).forEach(k=>delete u[k]);Object.assign(u,next)});change('unitTeam',(s,e)=>getSelected(s).team=e.value);change('eventType',(s,e)=>getSelected(s).type=e.value);change('eventLabel',(s,e)=>getSelected(s).label=e.value);
 const d=$('#deleteSelected');if(d)d.onclick=deleteSelection;const r=$('#roughenBtn');if(r)r.onclick=()=>commit('Terrain detail randomize',()=>{const o=getSelected(realStage());o.detail.seed=(o.detail.seed||1)+17;delete o.__derivedCache});const sm=$('#smoothBtn');if(sm)sm.onclick=()=>commit('Terrain controls smooth',()=>{const o=getSelected(realStage());o.control=o.control.map((p,i,a)=>i&&i<a.length-1?{x:p.x,y:(a[i-1].y+p.y*2+a[i+1].y)/4}:p);delete o.__derivedCache});$$('[data-mat]').forEach(b=>b.onclick=()=>{materialKind=b.dataset.mat;tool='material';renderAll()});const br=$('#brushRange');if(br){br.oninput=()=>$('#brushVal').textContent=br.value}
}
function getSelected(st){if(!selected)return null;if(selected.type==='scenery')return st.environment.placements.find(x=>x.id===selected.id);const map={terrain:'terrains',element:'elements',unit:'units',event:'events',material:'materials'};return st[map[selected.type]]?.find(x=>x.id===selected.id)}
function deleteSelection(){const st=realStage(),o=getSelected(st);if(!o)return;commit('삭제',()=>{if(selected.type==='scenery')st.environment.placements=st.environment.placements.filter(x=>x.id!==selected.id);else{const map={terrain:'terrains',element:'elements',unit:'units',event:'events',material:'materials'};st[map[selected.type]]=st[map[selected.type]].filter(x=>x.id!==selected.id)};if(selected.type==='terrain')st.materials=st.materials.filter(m=>m.terrainId!==selected.id);selected=null;selectedNode=-1})}

function renderElementPanels(){const a=activeAsset(),nodeCount=assetNodeCount(a);dom.left.innerHTML=`<div class="panel-scroll"><div class="panel-section"><div class="panel-title"><span>ELEMENT LIBRARY</span><button id="newAsset" class="btn sm">새 요소</button></div><div class="asset-grid">${project.library.map(x=>`<button class="asset-card ${x.id===a.id?'active':''}" data-edit-asset="${x.id}"><div class="asset-preview"><canvas data-asset-preview="${x.id}"></canvas></div><div class="asset-name">${esc(x.name)}</div><div class="asset-cat">${x.category}</div></button>`).join('')}</div></div></div>`;$$('[data-edit-asset]').forEach(b=>b.onclick=()=>{selectedAssetId=b.dataset.editAsset;selectedNode=-1;selectedShapeIndex=-1;elementPolygonDraft=[];if(activeAsset().vector&&elementTool==='polygon')elementTool='point';renderAll()});$('#newAsset').onclick=()=>commit('요소 생성',p=>{const a=asset(uid('custom'),'새 요소','custom',[shape(regularPoly(6,60,40,Math.floor(Math.random()*999)),'#5b625e','#222d30')],{collision:true,tags:['custom']});p.library.push(a);selectedAssetId=a.id;selectedShapeIndex=0});
 dom.right.innerHTML=`<div class="panel-scroll"><div class="panel-section"><div class="panel-title"><span>ELEMENT</span><div><button id="dupAsset" class="btn sm">복제</button> <button id="delAsset" class="btn sm danger">삭제</button></div></div><div class="row"><label>이름</label><input id="assetName" class="field" value="${esc(a.name)}"></div><div class="row"><label>Category</label><input id="assetCat" class="field" value="${esc(a.category)}"></div><div class="row"><label>Collision</label><input id="assetCollision" type="checkbox" ${a.collision.length?'checked':''}></div><div class="row"><label>Breakable</label><input id="assetBreak" type="checkbox" ${a.breakable?'checked':''}></div><div class="row"><label>One-way</label><input id="assetOneWay" type="checkbox" ${a.oneWay?'checked':''}></div><div class="row"><button id="randomizeAsset" class="btn">모양 Randomize</button><button id="addPolygon" class="btn">+ Polygon</button></div></div>
 <div class="panel-section"><div class="panel-title"><span>OPTIMIZE</span></div><div class="row"><label>Nodes</label><strong>${nodeCount}</strong></div><div class="row"><label>Threshold ε</label><input id="assetOptimizeEps" type="number" class="field" min="0" max="60" step=".5" value="2"><button id="optimizeAsset" class="btn sm">간소화</button></div><div class="muted node-label">RDP 기반. Undo 가능. 복잡한 바위/나무는 1~3부터 권장.</div></div>
 <div class="panel-section"><div class="panel-title"><span>GRID</span></div><div class="row"><label>Grid size</label><input id="elementGridSize" class="field" type="number" min="4" max="256" value="${project.settings.grid||40}"></div><div class="muted node-label">Ctrl+vertex/shape drag = grid snap</div></div>
 <div class="panel-section"><div class="panel-title"><span>ANCHOR</span></div><div class="muted node-label">(${round(a.anchor.x)}, ${round(a.anchor.y)}) · Anchor tool로 클릭</div></div><div class="panel-section"><div class="panel-title"><span>SOCKETS</span><button id="addSocket" class="btn sm">추가</button></div><div class="socket-list">${a.sockets.length?a.sockets.map(s=>`<div class="socket-item"><span>◇</span><span style="flex:1">${esc(s.id)}</span><span>${round(s.x)}, ${round(s.y)}</span></div>`).join(''):'<div class="empty">socket 없음</div>'}</div></div><div class="panel-section"><div class="panel-title"><span>VECTOR</span></div><div class="muted" style="font-size:10px;line-height:1.6">Point: vertex drag · Polygon: 새 polygon 작성<br>빈 polygon 내부 클릭: shape 선택/이동<br>더블클릭: edge vertex 추가 · Ctrl+드래그: grid snap</div></div></div>`;
  dom.right.querySelector('.panel-scroll').insertAdjacentHTML('beforeend',assetDetails(a));bindAssetDetails();
 $('#assetName').onchange=e=>commit('요소 이름 변경',()=>activeAsset().name=e.target.value);$('#assetCat').onchange=e=>commit('카테고리 변경',()=>activeAsset().category=e.target.value);$('#assetCollision').onchange=e=>commit('Collision 변경',()=>{const a=activeAsset();a.collision=e.target.checked?deep(a.visual.map(s=>s.points)):[]});$('#assetBreak').onchange=e=>commit('Breakable 변경',()=>activeAsset().breakable=e.target.checked);$('#assetOneWay').onchange=e=>commit('One-way 변경',()=>activeAsset().oneWay=e.target.checked);$('#dupAsset').onclick=()=>commit('요소 복제',p=>{const a=deep(activeAsset());a.id=uid('asset');a.name+=' Copy';p.library.push(a);selectedAssetId=a.id});$('#delAsset').onclick=()=>{if(project.library.length<=1)return;commit('요소 삭제',p=>{p.library=p.library.filter(x=>x.id!==selectedAssetId);selectedAssetId=p.library[0].id})};$('#randomizeAsset').onclick=()=>randomizeAsset();$('#addSocket').onclick=()=>{elementTool='socket';toast('캔버스에서 socket 위치를 클릭하세요')};$('#addPolygon').onclick=()=>{elementTool='polygon';elementPolygonDraft=[];selectedShapeIndex=-1;toast('새 polygon 점을 클릭하세요 · 더블클릭/Enter 완료')};$('#elementGridSize').onchange=e=>commit('Grid 변경',p=>p.settings.grid=clamp(+e.target.value||40,4,256));$('#optimizeAsset').onclick=()=>{if(activeAsset().vector)return;const eps=clamp(+$('#assetOptimizeEps').value||0,0,100);commit(`Element simplify ε=${eps}`,()=>{const a=activeAsset();a.visual=a.visual.map(sh=>({...sh,points:rdpClosed(sh.points,eps)}));syncAssetCollision(a);selectedNode=-1;selectedShapeIndex=-1})};
 if(a.vector){for(const id of ['randomizeAsset','addPolygon','optimizeAsset','assetCollision','assetCollisionMode']){const control=$('#'+id);if(control){control.disabled=true;control.title='SVG 원본을 편집하거나 별도 collision JSON을 사용하세요';}}}
}
function renderPlayPanels(){
 dom.left.innerHTML='';dom.right.innerHTML='';
 $('#playFromStart').onclick=()=>resetPlay('start');$('#playFromSelected').onclick=()=>resetPlay('selected');$('#playFromCamera').onclick=()=>resetPlay('camera');$('#stopPlay').onclick=()=>stopPlay();
 if(!playFrame)resetPlay();
}

function drawGridWorld(ctx,st,view){const g=project.settings.grid||40;if(view.zoom<.18)return;ctx.strokeStyle='#bfd8c20a';ctx.lineWidth=1/view.zoom;ctx.beginPath();for(let x=0;x<=st.width;x+=g){ctx.moveTo(x,0);ctx.lineTo(x,st.height)}for(let y=0;y<=st.height;y+=g){ctx.moveTo(0,y);ctx.lineTo(st.width,y)}ctx.stroke();ctx.strokeStyle='#d8c18355';ctx.lineWidth=2/view.zoom;ctx.strokeRect(0,0,st.width,st.height)}

function drawEvents(ctx,st){for(const e of st.events){if(!Number.isFinite(e.x)||!Number.isFinite(e.y))continue;ctx.strokeStyle='#d3b26e';ctx.lineWidth=2;ctx.setLineDash([5,4]);ctx.beginPath();ctx.arc(e.x,e.y,22,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#d3b26e';ctx.font='9px sans-serif';ctx.textAlign='center';ctx.fillText(e.type,e.x,e.y-28)}}
function drawSelection(ctx,st,mode){if(currentTab!=='stage'||!selected)return;const o=getSelected(st);if(!o)return;ctx.save();ctx.strokeStyle='#f1cf83';ctx.fillStyle='#f1cf83';ctx.lineWidth=2/stageView.zoom;if(selected.type==='terrain'){const pts=deriveTerrain(o);ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));if(o.type==='solid')ctx.closePath();ctx.stroke();if(tool==='select'){const edit=terrainEditPoints(o);for(let i=0;i<edit.length;i++){const p=edit[i];ctx.beginPath();ctx.arc(p.x,p.y,6/stageView.zoom,0,Math.PI*2);ctx.fillStyle=i===selectedNode?'#fff0b3':'#c9ac6b';ctx.fill()}}}else if(selected.type==='element'){const a=project.library.find(x=>x.id===o.assetId),inst=snapElement(st,{...o});if(a){for(const sh of transformedShapes(a,inst)){ctx.beginPath();sh.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke()}}}else if(['unit','event'].includes(selected.type)){const x=o.x,y=o.y;ctx.strokeRect(x-20/stageView.zoom,y-50/stageView.zoom,40/stageView.zoom,60/stageView.zoom)}ctx.restore()}
function drawStageUI(ctx,c,st,view){drawEnvironmentGuides(ctx,c,st,view);const d=c._dpr||1,w=c.clientWidth,h=c.clientHeight;ctx.setTransform(d,0,0,d,0,0);if(selected?.type==='scenery'&&overlayEnabled){const e=st.environment.placements.find(e=>e.id===selected.id),a=project.library.find(a=>a.id===e?.assetId);if(e&&a){const b=HonroEnvironment.screenBounds(a,e,view,w,h,st);ctx.save();ctx.strokeStyle='#f1cf83';ctx.lineWidth=2;ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.restore()}}$('#stageZoom').textContent=`${Math.round(view.zoom*100)}%`;$('#stageCoord').textContent=`${Math.round(view.x)}, ${Math.round(view.y)}`;}
function ensureRuntime(){
 if(editorRuntime)return editorRuntime;
 const st=stage(),p=activeProject(),profile=HonroMaps.profileFor(st),b=HonroMaps.createBattle(st,p,profile);
 if(st.terrains.length&&b.units.length)HonroStageRules.sanitizeStageBattle(b);
 // Layer switches affect only this disposable preview; the authored map stays intact.
 const hidden=new Set([...(st.environment?.hiddenLayers||[]),...st.layers.filter(l=>!l.visible).map(l=>l.id)]);
 b.terrain=b.terrain.filter(t=>!hidden.has(st.terrains.find(x=>x.id===t.id)?.layer||'terrain'));
 b.honroLandmarks=b.honroLandmarks.filter(l=>!hidden.has(st.elements.find(e=>e.id===l.id)?.layer||l.layer||'back'));
 b.honroEnvironment.placements=b.honroEnvironment.placements.filter(e=>!hidden.has(e.depthLayer));
 b.honroEnvironment.hiddenLayers=[...hidden];
 b.honroEnvironment.skyVisible=b.honroEnvironment.skyVisible!==false&&!hidden.has('L5');
 if(hidden.has('units'))b.units=[];
 if(hidden.has('events'))b.honroMarkers=[];
 b.sceneVersion+=editorRevision;
 const engine=new HONRO_CORE.Engine(b,()=>{},true),scene=new HonroScene(dom.stageCanvas);scene.manual=true;scene.editorView=true;
 scene.missionTargets=HonroObjectives.state(b,HONRO_CONTENT.stages[(st.metadata.stageId||1)-1]).targets;
 editorRuntime={engine,scene,profile};return editorRuntime;
}
function renderStage(){
 if(!dom.stageCanvas||!dom.stageCanvas.clientWidth)return;
 const {engine,scene}=ensureRuntime();Object.assign(scene,{x:stageView.x,y:stageView.y,scale:stageView.zoom,manual:true});
 scene.render(engine,0,'',.6,false,0);
 Object.assign(stageView,{x:scene.x,y:scene.y,zoom:scene.scale});
 const c=dom.stageOverlay,ctx=c.getContext('2d'),d=dom.stageCanvas.width/dom.stageCanvas.clientWidth;
 if(c.width!==dom.stageCanvas.width)c.width=dom.stageCanvas.width;if(c.height!==dom.stageCanvas.height)c.height=dom.stageCanvas.height;
 c._dpr=d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,c.clientWidth,c.clientHeight);
 if(overlayEnabled){ctx.save();ctx.translate(c.clientWidth/2,c.clientHeight/2);ctx.scale(stageView.zoom,stageView.zoom);ctx.translate(-stageView.x,-stageView.y);
  drawGridWorld(ctx,stage(),stageView);if(layerVisible(stage(),'events'))drawEvents(ctx,stage());drawSelection(ctx,stage(),'stage');if(tool==='solid'&&solidDraft.length)drawWorldDraft(ctx,solidDraft,true);if(drawStroke.length)drawWorldDraft(ctx,drawStroke);ctx.restore();if(paintStroke.length)drawTransientBand(paintStroke);}
 drawStageUI(ctx,c,stage(),stageView);
 if(boundsEnabled)drawBounds(ctx,c,stage(),stageView);
}

function drawBounds(ctx,c,st,view){const B=HonroBounds,w=c.clientWidth,h=c.clientHeight,rows=[
 ['Play','#e8cc82',B.play(st)],['Camera focus','#84c8e3',B.focus(st)],['Visual · tactical min','#b5a2db',B.visual(st,w,h)],['Terrain domain','#90ad91',B.terrain(st)]];
 ctx.save();ctx.setTransform(c._dpr||1,0,0,c._dpr||1,0,0);ctx.lineWidth=1.5;ctx.font='12px sans-serif';
 rows.forEach(([label,color,b],i)=>{const a=HonroCamera.screen(view,w,h,{x:b.left,y:b.top}),z=view.zoom;
  ctx.strokeStyle=color;ctx.setLineDash(i?[7,5]:[]);ctx.strokeRect(a.x,a.y,(b.right-b.left)*z,(b.bottom-b.top)*z);
  ctx.fillStyle='#102027e8';ctx.fillRect(12,44+i*22,206,20);ctx.fillStyle=color;ctx.fillText(label,20,58+i*22);});
 ctx.setLineDash([]);ctx.fillStyle='#d8ddd4';ctx.fillText('가로 시야 '+Math.round(w/view.zoom)+' · 최소 줌 '+Math.round(B.zoomLimits(w).min*100)+'%',20,150);ctx.restore();
}

function renderAssetPreviews(){for(const c of $$('[data-asset-preview]')){
 const a=project.library.find(x=>x.id===c.dataset.assetPreview);if(!a)continue;
 const r=c.getBoundingClientRect();c.width=Math.max(80,Math.round(r.width));c.height=Math.max(40,Math.round(r.height));const ctx=c.getContext('2d'),b=assetBounds(a),z=Math.min(c.width/(b.w+20),c.height/(b.h+20));
 const scene=Object.assign(Object.create(HonroScene.prototype),{_staticCacheBuild:true,time:0,scale:z});ctx.save();ctx.translate(c.width/2,c.height/2);ctx.scale(z,z);ctx.translate(-(b.x+b.w/2),-(b.y+b.h/2));HonroElements.draw(ctx,a,{x:0,y:0,scale:1,rotation:0},scene);ctx.restore();
}}

let elementTool='point';
function renderElement(){if(!dom.elementCanvas)return;const c=dom.elementCanvas,ctx=c.getContext('2d'),d=c._dpr||1,w=c.clientWidth,h=c.clientHeight,a=activeAsset(),grid=Math.max(4,project.settings.grid||40);ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#0c171b';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.scale(elementView.zoom,elementView.zoom);ctx.translate(-elementView.x,-elementView.y);ctx.strokeStyle='#263a3d';ctx.lineWidth=1/elementView.zoom;for(let x=-1500;x<1500;x+=grid){ctx.beginPath();ctx.moveTo(x,-1500);ctx.lineTo(x,1500);ctx.stroke()}for(let y=-1500;y<1500;y+=grid){ctx.beginPath();ctx.moveTo(-1500,y);ctx.lineTo(1500,y);ctx.stroke()}HonroElements.draw(ctx,a,{x:a.anchor.x,y:a.anchor.y,scale:1,rotation:0},Object.assign(Object.create(HonroScene.prototype),{_staticCacheBuild:true,time:0,scale:elementView.zoom}));if(!a.vector&&selectedShapeIndex>=0&&a.visual[selectedShapeIndex]){const sh=a.visual[selectedShapeIndex];ctx.beginPath();sh.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.strokeStyle='#f0ce80';ctx.lineWidth=2/elementView.zoom;ctx.stroke();}ctx.fillStyle='#f0ce80';for(const sh of a.vector?[]:a.visual)for(let i=0;i<sh.points.length;i++){const p=sh.points[i];ctx.beginPath();ctx.arc(p.x,p.y,5/elementView.zoom,0,Math.PI*2);ctx.fillStyle=selectedNode===nodeGlobalIndex(a,sh,i)?'#fff0b0':'#c39f5e';ctx.fill()}if(elementPolygonDraft.length){ctx.strokeStyle='#e3c67f';ctx.fillStyle='#e3c67f';ctx.setLineDash([5/elementView.zoom,4/elementView.zoom]);ctx.beginPath();elementPolygonDraft.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.setLineDash([]);for(const p of elementPolygonDraft){ctx.beginPath();ctx.arc(p.x,p.y,4/elementView.zoom,0,Math.PI*2);ctx.fill()}}ctx.strokeStyle='#8dc0a8';ctx.lineWidth=2/elementView.zoom;ctx.beginPath();ctx.moveTo(a.anchor.x-8,a.anchor.y);ctx.lineTo(a.anchor.x+8,a.anchor.y);ctx.moveTo(a.anchor.x,a.anchor.y-8);ctx.lineTo(a.anchor.x,a.anchor.y+8);ctx.stroke();for(const s of a.sockets){ctx.strokeStyle='#a7a8d7';ctx.beginPath();ctx.arc(s.x,s.y,7/elementView.zoom,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function nodeGlobalIndex(a,shapeObj,i){let k=0;for(const sh of a.visual){if(sh===shapeObj)return k+i;k+=sh.points.length}return -1}
function nodeByGlobal(a,idx){let k=0;for(let si=0;si<a.visual.length;si++){const sh=a.visual[si];if(idx<k+sh.points.length)return{shape:sh,shapeIndex:si,index:idx-k,point:sh.points[idx-k]};k+=sh.points.length}return null}
function randomizeAsset(){if(activeAsset().vector)return;commit('요소 모양 Randomize',()=>{const a=activeAsset(),r=seeded(Date.now()&0xffff);for(const sh of a.visual)for(const p of sh.points){p.x+=(r()-.5)*9;p.y+=(r()-.5)*7}syncAssetCollision(a)})}

function bindCanvas(c,kind){let pointer=null;c.addEventListener('contextmenu',e=>e.preventDefault());c.addEventListener('wheel',e=>{e.preventDefault();const view=kind==='stage'?stageView:elementView;const before=screenToWorld(c,e.offsetX,e.offsetY,view),factor=Math.exp(-e.deltaY*.0015);view.zoom=clamp(view.zoom*factor,.05,5);const after=screenToWorld(c,e.offsetX,e.offsetY,view);view.x+=before.x-after.x;view.y+=before.y-after.y;if(kind==='stage')renderStage();else renderElement()},{passive:false});c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);pointer={sx:e.offsetX,sy:e.offsetY,lastX:e.offsetX,lastY:e.offsetY,button:e.button,before:deep(project)};if(kind==='stage')stagePointerDown(e,pointer);else elementPointerDown(e,pointer)});c.addEventListener('pointermove',e=>{if(!pointer)return;if(kind==='stage')stagePointerMove(e,pointer);else elementPointerMove(e,pointer);pointer.lastX=e.offsetX;pointer.lastY=e.offsetY});c.addEventListener('pointerup',e=>{if(!pointer)return;if(kind==='stage')stagePointerUp(e,pointer);else elementPointerUp(e,pointer);pointer=null});c.addEventListener('dblclick',e=>{if(kind==='element')elementDoubleClick(e);else if(tool==='solid')finalizeSolid()})}
function screenToWorld(c,x,y,v){return HonroCamera.world(v,c.clientWidth,c.clientHeight,x,y)}
function screenToSceneryWorld(c,x,y,layer,groupId){const st=stage(),g=st.environment.groups.find(g=>g.id===(groupId||placementGroup(st)?.id)&&g.depthLayer===layer);return g?HonroEnvironment.groupWorld(stageView,c.clientWidth,c.clientHeight,st,g.id,{x,y}):HonroEnvironment.world(stageView,c.clientWidth,c.clientHeight,st,layer,{x,y})}

function worldToScreen(c,p,v){return HonroCamera.screen(v,c.clientWidth,c.clientHeight,p)}

function stagePointerDown(e,p){const st=realStage(),raw=screenToWorld(dom.stageCanvas,e.offsetX,e.offsetY,stageView),w=e.ctrlKey?gridSnapPoint(raw):raw;if(e.button===1||tool==='pan'||e.button===2){p.pan=true;return}if(tool==='terrain'){drawStroke=[w];return}if(tool==='solid'){if(e.detail<2){solidDraft.push({x:clamp(w.x,0,st.width),y:clamp(w.y,0,st.height)});renderStage()}return}if(tool==='material'){paintStroke=[w];return}if(tool==='place'){const a=project.library.find(x=>x.id===placementAssetId);if(!a)return;
 if(placementDepthLayer!=='L1'&&(a.collision.length||a.interactionType)){toast('충돌·상호작용 요소는 L1에만 배치할 수 있습니다.');return}
 commit('요소 배치',()=>{if(placementDepthLayer==='L1'){const inst={id:uid('el'),assetId:a.id,x:w.x,y:w.y,rotation:0,scale:1,layer:a.layer||(a.collision.length?'interactive':'back'),depthLayer:'L1',snap:true};snapElement(st,inst);st.elements.push(inst);selected={type:'element',id:inst.id}}
 else{const q=screenToSceneryWorld(dom.stageCanvas,e.offsetX,e.offsetY,placementDepthLayer),inst=HonroEnvironment.place(st,a,{id:uid('scenery'),localX:q.x,depthLayer:placementDepthLayer,groupId:placementGroup(st)?.id,supportId:placementSupportId||undefined});st.environment.placements.push(inst);selected={type:'scenery',id:inst.id}}});tool='select';renderAll();return}
if(tool==='scatter'){scatterAt(st,placementDepthLayer==='L1'?w:screenToSceneryWorld(dom.stageCanvas,e.offsetX,e.offsetY,placementDepthLayer));return}if(tool==='unit'){commit('유닛 배치',()=>{const sf=nearestSurface(st,w.x,w.y),u=HonroUnits.record(unitKind,uid('unit'),w.x,sf?.y??w.y);st.units.push(u);selected={type:'unit',id:u.id}});tool='select';renderAll();return}if(tool==='event'){commit('이벤트 배치',()=>{const ev={id:uid('event'),type:eventKind,x:w.x,y:w.y,label:eventKind};st.events.push(ev);selected={type:'event',id:ev.id}});tool='select';renderAll();return}
 // Visible terrain handles must win over decorative elements. Ctrl additionally lets the user grab
 // any nearby terrain control and immediately starts a grid-snapped node drag.
 const nodeRadius=12/stageView.zoom;
 if(selected?.type==='terrain'){
   const t=getSelected(st),n=t&&!layerLocked(st,t.layer||'terrain')&&layerVisible(st,t.layer||'terrain')?nearestControl(t,raw,nodeRadius):-1;
   if(n>=0){selectedNode=n;p.dragNode=true;renderAll();return}
 }
 if(e.ctrlKey){let best=null,bestD=Infinity;for(let i=st.terrains.length-1;i>=0;i--){const t=st.terrains[i];if(layerLocked(st,t.layer||'terrain')||!layerVisible(st,t.layer||'terrain'))continue;const pts=terrainEditPoints(t);for(let j=0;j<pts.length;j++){const d=dist(pts[j],raw);if(d<nodeRadius&&d<bestD){bestD=d;best={t,n:j}}}}if(best){selected={type:'terrain',id:best.t.id};selectedNode=best.n;p.dragNode=true;renderAll();return}}
 const hit=hitStage(st,raw);selected=hit;selectedNode=-1;if(hit?.type==='terrain'){const t=getSelected(st),n=nearestControl(t,raw,nodeRadius);if(n>=0){selectedNode=n;p.dragNode=true}else{p.dragTerrain=true;p.startWorld=raw;p.originTerrain=deep(t)}}else if(hit){p.dragObj=true;p.origin=deep(getSelected(st));p.startWorld=hit.type==='scenery'?screenToSceneryWorld(dom.stageCanvas,e.offsetX,e.offsetY,p.origin.depthLayer,p.origin.groupId):raw}renderAll()}
function stagePointerMove(e,p){if(!p.pan)invalidateRuntime();const st=realStage(),raw=screenToWorld(dom.stageCanvas,e.offsetX,e.offsetY,stageView),w=e.ctrlKey?gridSnapPoint(raw):raw;if(p.pan){stageView.x-=(e.offsetX-p.lastX)/stageView.zoom;stageView.y-=(e.offsetY-p.lastY)/stageView.zoom;renderStage();return}if(tool==='terrain'&&drawStroke.length){if(dist(drawStroke.at(-1),w)>12/stageView.zoom)drawStroke.push(w);renderStage();drawTransientLine(drawStroke,'#dbbf7c');return}if(tool==='solid'&&solidDraft.length){renderStage();drawTransientPolygon(solidDraft);return}if(tool==='material'&&paintStroke.length){paintStroke.push(w);renderStage();drawTransientBand(paintStroke);return}if(tool==='scatter'&&e.buttons){if(performance.now()-scatterStamp>70){scatterAt(st,placementDepthLayer==='L1'?w:screenToSceneryWorld(dom.stageCanvas,e.offsetX,e.offsetY,placementDepthLayer));scatterStamp=performance.now()}return}if(p.dragNode&&selected?.type==='terrain'){const t=getSelected(st);if(!t)return;const pts=terrainEditPoints(t);pts[selectedNode]={x:clamp(w.x,0,st.width),y:clamp(w.y,0,st.height)};if(t.type!=='solid')pts.sort((a,b)=>a.x-b.x);delete t.__derivedCache;renderStage();return}if(p.dragTerrain&&selected?.type==='terrain'){const t=getSelected(st),g=project.settings.grid||40,dx=e.ctrlKey?Math.round((raw.x-p.startWorld.x)/g)*g:raw.x-p.startWorld.x,dy=e.ctrlKey?Math.round((raw.y-p.startWorld.y)/g)*g:raw.y-p.startWorld.y;if(t.type==='solid')t.points=p.originTerrain.points.map(q=>({x:q.x+dx,y:q.y+dy}));else{t.control=p.originTerrain.control.map(q=>({x:q.x+dx,y:q.y+dy}));if(t.type==='ground')t.floor=(p.originTerrain.floor||st.height+180)+dy}delete t.__derivedCache;renderStage();return}if(p.dragObj&&selected){const o=getSelected(st);if(!o)return;const point=selected.type==='scenery'?screenToSceneryWorld(dom.stageCanvas,e.offsetX,e.offsetY,o.depthLayer,o.groupId):raw,g=project.settings.grid||40,dx=e.ctrlKey?Math.round((point.x-p.startWorld.x)/g)*g:point.x-p.startWorld.x,dy=e.ctrlKey?Math.round((point.y-p.startWorld.y)/g)*g:point.y-p.startWorld.y;o.x=selected.type==='scenery'?p.origin.x+dx:clamp(p.origin.x+dx,0,st.width);o.y=selected.type==='scenery'?(o.supportId?0:p.origin.y+dy):clamp(p.origin.y+dy,0,st.height);if(selected.type==='element'&&o.snap)snapElement(st,o);renderStage()}}
function stagePointerUp(e,p){const st=realStage();if(tool==='terrain'&&drawStroke.length>1){const points=prepareControl(drawStroke,st);drawStroke=[];commit('Terrain draw',()=>{const t={id:uid('terrain'),name:`Ground ${st.terrains.length+1}`,type:'ground',control:points,floor:st.height+180,baseMaterial:'soil',detail:{spacing:18,roughness:7,seed:Math.floor(Math.random()*100000),optimizeEpsilon:0},layer:'terrain'};st.terrains.push(t);selected={type:'terrain',id:t.id}});tool='select';renderAll()}else if(tool==='material'&&paintStroke.length>1){const xs=paintStroke.map(p=>p.x),mid=paintStroke[Math.floor(paintStroke.length/2)],sf=nearestSurface(st,mid.x,mid.y);paintStroke=[];if(sf)commit('Material paint',()=>{st.materials.push({id:uid('mat'),terrainId:sf.terrain.id,x1:clamp(Math.min(...xs),0,st.width),x2:clamp(Math.max(...xs),0,st.width),kind:materialKind,depth:materialKind==='water'?38:26,alpha:.9})})}else if(p.dragNode||p.dragObj||p.dragTerrain){commit('Edit geometry',()=>{},p.before)}}
function prepareControl(stroke,st){let pts=[...stroke].filter(p=>p.x>=0&&p.x<=st.width&&p.y>=0&&p.y<=st.height).sort((a,b)=>a.x-b.x);const merged=[];for(const p of pts){if(!merged.length||p.x-merged.at(-1).x>24)merged.push({x:round(p.x),y:round(p.y)});else merged.at(-1).y=(merged.at(-1).y+p.y)/2}if(merged.length>32){const step=Math.ceil(merged.length/28);pts=merged.filter((_,i)=>i%step===0||i===merged.length-1)}else pts=merged;return pts.length>=2?pts:[{x:100,y:st.height*.6},{x:st.width-100,y:st.height*.5}]}
function nearestControl(t,w,rad){let best=-1,d=Infinity;terrainEditPoints(t).forEach((p,i)=>{const x=dist(p,w);if(x<d&&x<rad){d=x;best=i}});return best}
function hitStage(st,w){for(const type of ['event','unit']){const arr=type==='event'?st.events:st.units;for(let i=arr.length-1;i>=0;i--){const o=arr[i];if(!layerVisible(st,type==='event'?'events':'units')||layerLocked(st,type==='event'?'events':'units'))continue;if(dist(o,w)<35/stageView.zoom)return{type,id:o.id}}}for(let i=st.elements.length-1;i>=0;i--){const o=st.elements[i];if(layerLocked(st,o.layer)||!layerVisible(st,o.layer))continue;const a=project.library.find(x=>x.id===o.assetId);if(!a)continue;const inst=snapElement(st,{...o});const shapes=transformedShapes(a,inst);if(shapes.some(sh=>pointInPoly(w,sh.points))||dist(inst,w)<30/stageView.zoom)return{type:'element',id:o.id}}for(let i=st.terrains.length-1;i>=0;i--){const t=st.terrains[i];if(layerLocked(st,t.layer||'terrain')||!layerVisible(st,t.layer||'terrain'))continue;const poly=terrainPolygon(t,st),ys=terrainSurfaceYs(t,w.x);if((poly.length>=3&&pointInPoly(w,poly))||ys.some(y=>Math.abs(y-w.y)<18/stageView.zoom))return{type:'terrain',id:t.id}}const screen=HonroCamera.screen(stageView,dom.stageCanvas.clientWidth,dom.stageCanvas.clientHeight,w);for(let i=st.environment.placements.length-1;i>=0;i--){const e=st.environment.placements[i],a=project.library.find(a=>a.id===e.assetId);if(!a||layerLocked(st,e.depthLayer)||!layerVisible(st,e.depthLayer))continue;const b=HonroEnvironment.screenBounds(a,e,stageView,dom.stageCanvas.clientWidth,dom.stageCanvas.clientHeight,st);if(screen.x>=b.x&&screen.x<=b.x+b.w&&screen.y>=b.y&&screen.y<=b.y+b.h)return{type:'scenery',id:e.id}}return null}
function terrainPolygon(t,st){const pts=deriveTerrain(t);if(t.type==='solid')return pts;if(t.type==='ground')return[...pts,{x:pts.at(-1)?.x??0,y:t.floor||st.height+100},{x:pts[0]?.x??0,y:t.floor||st.height+100}];if(t.type==='platform'){const th=t.thickness||80;return[...pts,...[...pts].reverse().map(p=>({x:p.x,y:p.y+th}))]}return pts}
function drawWorldDraft(ctx,pts,closed=false){if(!pts.length)return;ctx.save();ctx.strokeStyle='#f0c978';ctx.fillStyle='#f0c978';ctx.lineWidth=3/stageView.zoom;ctx.setLineDash([8/stageView.zoom,5/stageView.zoom]);ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));if(closed&&pts.length>2)ctx.closePath();ctx.stroke();ctx.setLineDash([]);for(const p of pts){ctx.beginPath();ctx.arc(p.x,p.y,5/stageView.zoom,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawTransientPolygon(arr){if(!overlayEnabled)return;const c=dom.stageOverlay,ctx=c.getContext('2d'),d=c._dpr||1;ctx.setTransform(d,0,0,d,0,0);ctx.save();ctx.translate(c.clientWidth/2,c.clientHeight/2);ctx.scale(stageView.zoom,stageView.zoom);ctx.translate(-stageView.x,-stageView.y);drawWorldDraft(ctx,arr,true);ctx.restore()}
function finalizeSolid(){if(tool!=='solid'||solidDraft.length<3)return;const pts=solidDraft.map(p=>({...p}));solidDraft=[];commit('Solid polygon 생성',()=>{const st=realStage(),t={id:uid('solid'),name:`Solid ${st.terrains.filter(x=>x.type==='solid').length+1}`,type:'solid',points:pts,baseMaterial:'rock',layer:'terrain',breakable:false};st.terrains.push(t);selected={type:'terrain',id:t.id}});tool='select';renderAll()}
function drawTransientLine(arr,color){if(!overlayEnabled)return;const c=dom.stageOverlay,ctx=c.getContext('2d'),d=c._dpr||1;ctx.setTransform(d,0,0,d,0,0);ctx.save();ctx.translate(c.clientWidth/2,c.clientHeight/2);ctx.scale(stageView.zoom,stageView.zoom);ctx.translate(-stageView.x,-stageView.y);ctx.strokeStyle=color;ctx.lineWidth=3/stageView.zoom;ctx.beginPath();arr.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.restore()}
function drawTransientBand(arr){if(!overlayEnabled)return;const xs=arr.map(p=>p.x);const c=dom.stageOverlay,ctx=c.getContext('2d');const p1=worldToScreen(c,{x:Math.min(...xs),y:arr.at(-1).y},stageView),p2=worldToScreen(c,{x:Math.max(...xs),y:arr.at(-1).y},stageView);ctx.save();ctx.strokeStyle='#d8bd78';ctx.lineWidth=5;ctx.globalAlpha=.7;ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke();ctx.restore()}
function scatterAt(st,w){const a=project.library.find(x=>x.id===placementAssetId)||project.library.find(x=>x.category==='vegetation');if(!a)return;if(placementDepthLayer!=='L1'&&(a.collision.length||a.interactionType))return;const radius=+($('#brushRange')?.value||220),r=seeded(Math.floor(w.x*31+w.y*17+st.elements.length+st.environment.placements.length));commit('Scatter 요소',()=>{for(let i=0;i<5;i++){const ang=r()*Math.PI*2,rr=Math.sqrt(r())*radius,x=w.x+Math.cos(ang)*rr;if(placementDepthLayer!=='L1'){const e=HonroEnvironment.place(st,a,{id:uid('scenery'),localX:x,scale:.85+r()*.3,depthLayer:placementDepthLayer,groupId:placementGroup(st)?.id,supportId:placementSupportId||undefined});st.environment.placements.push(e);continue}const xx=clamp(x,0,st.width),sf=nearestSurface(st,xx,w.y);if(!sf)continue;const e={id:uid('el'),assetId:a.id,x:xx,y:sf.y,rotation:(r()-.5)*.28,scale:.75+r()*.65,layer:a.layer||(a.collision.length?'interactive':'back'),depthLayer:'L1',snap:true,scatter:true};if(st.elements.some(o=>dist(o,e)<35))continue;st.elements.push(e)}})}

function elementPointerDown(e,p){const raw=screenToWorld(dom.elementCanvas,e.offsetX,e.offsetY,elementView),w=e.ctrlKey?gridSnapPoint(raw):raw,a=activeAsset();if(e.button===1||e.button===2){p.pan=true;return}if(elementTool==='polygon'){if(e.detail<2){elementPolygonDraft.push({...w});renderElement()}return}if(elementTool==='anchor'){commit('Anchor 설정',()=>{a.anchor={x:w.x,y:w.y}});elementTool='point';return}if(elementTool==='socket'){commit('Socket 추가',()=>{a.sockets.push({id:`socket_${a.sockets.length+1}`,x:w.x,y:w.y})});elementTool='point';return}if(a.vector){selectedNode=-1;selectedShapeIndex=-1;renderElement();return}selectedNode=nearestAssetNode(a,raw,10/elementView.zoom);if(selectedNode>=0){p.dragNode=true;selectedShapeIndex=nodeByGlobal(a,selectedNode)?.shapeIndex??selectedShapeIndex;return}for(let i=a.visual.length-1;i>=0;i--)if(pointInPoly(raw,a.visual[i].points)){selectedShapeIndex=i;p.dragShape=true;p.startWorld=raw;p.originShape=deep(a.visual[i].points);renderElement();return}selectedShapeIndex=-1;renderElement()}
function elementPointerMove(e,p){if(p.pan){elementView.x-=(e.offsetX-p.lastX)/elementView.zoom;elementView.y-=(e.offsetY-p.lastY)/elementView.zoom;renderElement();return}const raw=screenToWorld(dom.elementCanvas,e.offsetX,e.offsetY,elementView),w=e.ctrlKey?gridSnapPoint(raw):raw;if(p.dragNode&&selectedNode>=0){const n=nodeByGlobal(activeAsset(),selectedNode);if(n){n.point.x=w.x;n.point.y=w.y;selectedShapeIndex=n.shapeIndex;syncAssetCollision(activeAsset());renderElement()}}else if(p.dragShape&&selectedShapeIndex>=0){const sh=activeAsset().visual[selectedShapeIndex],g=project.settings.grid||40,dx=e.ctrlKey?Math.round((raw.x-p.startWorld.x)/g)*g:raw.x-p.startWorld.x,dy=e.ctrlKey?Math.round((raw.y-p.startWorld.y)/g)*g:raw.y-p.startWorld.y;sh.points=p.originShape.map(q=>({x:q.x+dx,y:q.y+dy}));syncAssetCollision(activeAsset());renderElement()}}
function elementPointerUp(e,p){if(p.dragNode||p.dragShape){commit('Edit geometry',()=>{},p.before)}}
function elementDoubleClick(e){if(activeAsset().vector)return;if(elementTool==='polygon'){finalizeElementPolygon();return}const a=activeAsset(),raw=screenToWorld(dom.elementCanvas,e.offsetX,e.offsetY,elementView),w=e.ctrlKey?gridSnapPoint(raw):raw;let best=null,d=Infinity;for(const sh of a.visual)for(let i=0;i<sh.points.length;i++){const p=sh.points[i],q=sh.points[(i+1)%sh.points.length],hit=pointSegmentDistance(w,p,q);if(hit.d<d){d=hit.d;best={sh,i,point:hit.point}}}if(best&&d<12/elementView.zoom)commit('Vertex 추가',()=>{best.sh.points.splice(best.i+1,0,e.ctrlKey?gridSnapPoint(best.point):best.point);syncAssetCollision(a)})}
function finalizeElementPolygon(){if(activeAsset().vector)return;if(elementTool!=='polygon'||elementPolygonDraft.length<3)return;const pts=elementPolygonDraft.map(p=>({...p}));elementPolygonDraft=[];commit('Element polygon 추가',()=>{const a=activeAsset(),base=a.visual[selectedShapeIndex]||a.visual[0];a.visual.push(shape(pts,base?.fill||'#5b625e',base?.stroke||'#222d30',base?.alpha??1));selectedShapeIndex=a.visual.length-1;syncAssetCollision(a)});elementTool='point';renderAll()}
function nearestAssetNode(a,w,rad){let k=0,best=-1,d=Infinity;for(const sh of a.visual)for(const p of sh.points){const dd=dist(p,w);if(dd<d&&dd<rad){d=dd;best=k}k++}return best}
function pointSegmentDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,n=dx*dx+dy*dy,t=n?clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/n,0,1):0,q={x:a.x+dx*t,y:a.y+dy*t};return{d:dist(p,q),point:q}}

function resetPlay(from='start'){
 if(playFrame)stopPlay(false);
 const snapshot=deep(project),st=snapshot.stages.find(s=>s.id===snapshot.activeStageId);
 playSnapshot={stageView:deep(stageView),elementView:deep(elementView),selected:deep(selected),selectedNode,selectedShapeIndex,tool};
 const frame=document.createElement('iframe');frame.id='runtimeFrame';frame.title='HONRO 실제 게임 플레이테스트';frame.allow='autoplay; fullscreen';
 const base=document.baseURI.replace(/[&"<>]/g,c=>({'&':'&amp;','"':'&quot;','<':'&lt;','>':'&gt;'}[c]));
 const head='<base href="'+base+'"><script>globalThis.HONRO_EMBEDDED=true;<'+ '/script>';
 frame.srcdoc=HONRO_PLAYTEST_HTML.replace('<head>','<head>'+head);
 playFrame=frame;playState={from,stageId:st.id};
 playReady=new Promise((resolve,reject)=>{frame.onload=()=>{try{
  const app=frame.contentWindow.HonroApp;app.launchMap(snapshot,st.id,{from,unitId:selected?.type==='unit'?selected.id:null,camera:deep(stageView)});
  frame.contentWindow.focus();resolve(app);
 }catch(e){toast('Playtest: '+e.message);reject(e);}};});
 $('#runtimeHost').replaceChildren(frame);playReady.catch(()=>{});return playReady;
}
function stopPlay(returnToStage=true){
 if(playFrame){try{playFrame.contentWindow.HonroApp?.audio?.dispose?.()}catch{}playFrame.remove();}
 playFrame=null;playState=null;playReady=null;
 if(playSnapshot){({stageView,elementView,selected,selectedNode,selectedShapeIndex,tool}=playSnapshot);playSnapshot=null;}
 if(returnToStage)switchTab('stage');
}
function renderPlay(){}
function loop(ts){if(currentTab==='stage')renderStage();requestAnimationFrame(loop)}

function renderToolbars(){const host=$('#stageToolbar');if(host)host.innerHTML=[['select','선택'],['terrain','지형'],['solid','Solid'],['material','재질'],['place','배치'],['scatter','Scatter'],['unit','유닛'],['event','이벤트'],['pan','Pan']].map(([id,n])=>`<button class="tool ${tool===id?'active':''}" data-tool="${id}">${n}</button>`).join('<span class="toolbar-sep"></span>');$$('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;if(tool!=='solid')solidDraft=[];renderAll()});const eh=$('#elementToolbar');if(eh)eh.innerHTML=[['point','Point'],['polygon','Polygon'],['anchor','Anchor'],['socket','Socket']].map(([id,n])=>`<button class="tool ${elementTool===id?'active':''}" data-etool="${id}" ${activeAsset().vector&&['point','polygon'].includes(id)?'disabled title="SVG 원본에서 경로를 편집하세요"':''}>${n}</button>`).join('');$$('[data-etool]').forEach(b=>b.onclick=()=>{elementTool=b.dataset.etool;if(elementTool!=='polygon')elementPolygonDraft=[];renderAll()})}
function validateStage(st){return HonroMaps.validate({...activeProject(),stages:[st]})}

function validationHtml(arr){return arr.map(x=>`<div class="validation-item ${x.level}">${esc(x.text)}</div>`).join('')}

function exportHonroSpec(st=realStage()){return {...deep(project),stages:[deep(st)],activeStageId:st.id}}

function materialRuntimeKind(k){return({water:'shallow-water',rock:'exposed-rock',grass:'grass-mass',moss:'moss',mud:'mud-track',charred:'charred-soil',stone:'stone-road'}[k]||k)}
function downloadProject(){download(`${safe(project.name)}.honro-map.json`,JSON.stringify(project,null,2),'application/json')}
function downloadHonroDraft(){download(`${safe(realStage().name)}.honro-map.json`,HonroMaps.serialize(exportHonroSpec()),'application/json')}

function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importProject(x){
 const next=HonroMaps.normalize(x),errors=HonroMaps.validate(next).filter(x=>x.level==='err');if(errors.length)throw Error(errors.map(x=>x.text).join('\n'));
 commit('Project import',p=>{Object.keys(p).forEach(k=>delete p[k]);Object.assign(p,next);selected=null;stageView._fit=false;});resizeAll();return deep(project);
}
function importFile(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{const x=JSON.parse(r.result);if(x.stages&&x.library)importProject(x);else if(x.kind==='honro-workshop-stage-pack'){const merged=deep(project),stages=deep(x.stages);for(const st of stages)if(merged.stages.some(s=>s.id===st.id))st.id=uid('stage');merged.stages.push(...stages);merged.activeStageId=stages[0].id;merged.version=1;importProject(merged)}else if(x.dimensions)importHonroSpec(x);else throw Error('지원하지 않는 JSON');toast('Project를 불러왔습니다')}catch(err){toast('Import 실패: '+err.message)}};r.readAsText(f);e.target.value=''}

function importHonroSpec(spec){commit('Legacy HONRO import',p=>{const st=HonroMaps.importSpec(spec,uid('stage'),p);p.stages.push(st);p.activeStageId=st.id;stageView._fit=false});resizeAll()}

function duplicateStage(id){commit('Stage 복제',p=>{const st=deep(p.stages.find(s=>s.id===id));st.id=uid('stage');st.name+=' Copy';p.stages.push(st);p.activeStageId=st.id;stageView._fit=false})}

function createStageDialog(){const m=$('#newStageModal');m.classList.add('open');$('#createStageConfirm').onclick=()=>{const name=$('#newStageName').value||'새 스테이지',w=+$('#newStageW').value||5000,h=+$('#newStageH').value||3200;commit('Stage 생성',p=>{const st=defaultStage(uid('stage'),name,w,h);p.stages.push(st);p.activeStageId=st.id;stageView._fit=false});m.classList.remove('open')};$('#createStageCancel').onclick=()=>m.classList.remove('open')}

function agentContext(){const st=realStage();return{workshop:'HONRO Workshop 3',stage:{id:st.id,name:st.name,width:st.width,height:st.height,backdrop:st.backdrop},counts:{terrains:st.terrains.length,materials:st.materials.length,elements:st.elements.length,units:st.units.length,events:st.events.length,...sceneStats(st)},selection:selected,availableAssets:project.library.map(a=>({id:a.id,name:a.name,category:a.category,tags:a.tags,collision:!!a.collision.length,nodes:assetNodeCount(a)})),commandAPI:['world.set','stage.update','object.update','asset.add','terrain.add','terrain.addSolid','terrain.roughen','terrain.moveNode','terrain.optimize','material.paint','element.place','element.move','element.delete','element.scatter','asset.optimize','asset.update','unit.place','unit.update','unit.move','event.place','encounter.add','objective.add','move','rotate','scale','rename','delete',...Object.keys(HonroCommands.aliases)],availableUnits:HonroUnits.catalog(),validation:validateStage(st)}}
async function copyAgentContext(){await navigator.clipboard.writeText(JSON.stringify(agentContext(),null,2));toast('Agent context 복사 완료')}
function previewCommands(cmds){previewProject=applyCommands(project,cmds);previewCommandsKey=JSON.stringify(cmds);invalidateRuntime();renderStage();return diffSummary(project,previewProject)}
function applyPreview(){if(!previewProject)throw Error('No change set preview');const next=previewProject;commit('Agent changes',p=>Object.assign(p,next));previewCommandsKey=null;return deep(project)}
function clearPreview(){previewProject=null;previewCommandsKey=null;invalidateRuntime();renderStage()}
function runAgent(apply){try{let cmds=JSON.parse($('#agentCommands').value);if(!Array.isArray(cmds))cmds=[cmds];if(!previewProject||previewCommandsKey!==JSON.stringify(cmds))previewCommands(cmds);const summary=diffSummary(project,previewProject);if(apply)applyPreview();$('#changes').innerHTML=summary.map(x=>esc(x)).join('<br>')}catch(e){$('#changes').textContent=e.message}}

function applyCommands(p,cmds){return HonroCommands.apply(p,cmds)}

function diffSummary(a,b){const sa=a.stages.find(s=>s.id===a.activeStageId),sb=b.stages.find(s=>s.id===b.activeStageId),out=[];if(sa.width!==sb.width||sa.height!==sb.height)out.push(`World ${sa.width}×${sa.height} → ${sb.width}×${sb.height}`);for(const k of ['terrains','materials','elements','units','events']){const d=sb[k].length-sa[k].length;if(d)out.push(`${k}: ${d>0?'+':''}${d}`)}return out.length?out:['구조 수 변화 없음 · 속성/위치 변경']}

window.HonroWorkshopAPI={
 getProject:()=>deep(project),getContext:()=>deep(agentContext()),queryScene:()=>({stage:deep(realStage()),camera:deep(stageView),selection:deep(selected),validation:HonroMaps.validate(project)}),
 getEditorState:()=>({stageView:deep(stageView),elementView:deep(elementView),tool,elementTool,selected:deep(selected),selectedNode,selectedShapeIndex,overlayEnabled,history:history.length,future:future.length}),
 getPlayState:()=>playFrame?deep(playFrame.contentWindow.HonroApp?.engine?.b||playState):null,
 validate:()=>deep(validateStage(realStage())),validateMap:()=>HonroMaps.validate(project),previewCommands,applyPreview,discardPreview:clearPreview,clearPreview,
 applyCommands:cmds=>{if(previewProject&&previewCommandsKey===JSON.stringify(cmds))return applyPreview();const next=applyCommands(project,cmds);commit('API commands',p=>Object.assign(p,next));return deep(project)},
 exportHonroSpec:()=>deep(exportHonroSpec()),exportProject:()=>HonroMaps.serialize(project),importProject,
 undo,redo,select:(type,id)=>{selected={type,id};renderAll()},
 selectStage:id=>{if(!project.stages.some(s=>s.id===id))throw Error('Missing stage');project.activeStageId=id;selected=null;stageView._fit=false;resizeAll()},
 setCamera:view=>{Object.assign(stageView,view);renderStage()},
 setOverlay:enabled=>{overlayEnabled=!!enabled;$('#overlayToggle').checked=overlayEnabled;renderStage()},
 setBoundsOverlay:enabled=>{boundsEnabled=!!enabled;$('#boundsToggle').checked=boundsEnabled;renderStage()},
 getRuntime:()=>ensureRuntime(),render:renderStage,
 startPlaytest:from=>{switchTab('play');if(from&&from!=='start')return resetPlay(from);return playReady},stopPlaytest:stopPlay,
 getPlayApp:()=>playFrame?.contentWindow.HonroApp,
 switchTab
};

function unitTypes(){return HonroUnits.catalog().map(u=>u.kind)}


function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function safe(s){return String(s).replace(/[^\w가-힣-]+/g,'_')}


function unitInspector(o){return `<div class="row"><label>종류</label><select id="unitType" class="field">${HonroUnits.catalog().map(u=>`<option value="${u.kind}" ${o.kind===u.kind?'selected':''}>${esc(u.name)}</option>`).join('')}</select></div>
 <div class="row"><label>Team</label><select id="unitTeam" class="field">${['player','ally','enemy','npc'].map(v=>`<option ${v===o.team?'selected':''}>${v}</option>`).join('')}</select></div>
 <div class="row"><label>Facing</label><select id="unitFacing" class="field"><option value="1" ${o.facing!==-1?'selected':''}>오른쪽</option><option value="-1" ${o.facing===-1?'selected':''}>왼쪽</option></select></div>
 <div class="split"><label>Level<input id="unitLevel" class="field" type="number" min="1" max="25" value="${o.levelOverride??o.level??1}"></label><label>Rank<input id="unitRank" class="field" type="number" min="1" max="8" value="${o.rank??1}"></label></div>
 <div class="row"><label>Encounter</label><input id="unitEncounter" class="field" value="${esc(o.encounterGroup??o.honroCluster??'')}"></div>
 <div class="row"><label>Behavior</label><select id="unitBehavior" class="field">${['default','aggressive','stationary'].map(v=>`<option ${v===(o.behavior||'default')?'selected':''}>${v}</option>`).join('')}</select></div>
 <div class="row"><label>Boss</label><input id="unitBoss" type="checkbox" ${o.boss||o.honroFinalBoss?'checked':''}><label>Miniboss</label><input id="unitMiniboss" type="checkbox" ${o.miniboss||o.honroMidboss?'checked':''}></div>
 <label class="node-label">Stage overrides (JSON)<textarea id="unitOverrides" class="field">${esc(JSON.stringify(o.stageOverrides||{},null,2))}</textarea></label>`}
function eventInspector(o){return `<div class="row"><label>Type</label><select id="eventType" class="field">${['trigger','objective','interaction','spawn','dialogue'].map(v=>`<option ${o.type===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="row"><label>Label</label><input id="eventLabel" class="field" value="${esc(o.label||o.text||'')}"></div>
 <div class="row"><label>Radius</label><input id="eventRadius" class="field" type="number" value="${o.radius??160}"></div>
 ${['when','action','lines'].map(k=>`<label class="node-label">${k} (JSON)<textarea id="event-${k}" class="field">${esc(JSON.stringify(o[k]??(k==='lines'?[]:null),null,2))}</textarea></label>`).join('')}`}
function bindExtendedInspector(st){
 const change=(id,key,parse=v=>v)=>{const el=$('#'+id);if(el)el.onchange=()=>{try{const value=parse(el.type==='checkbox'?el.checked:el.value);commit('속성 변경',()=>getSelected(realStage())[key]=value)}catch(e){toast(e.message);renderAll()}}};
 for(const [id,key] of [['objectX','x'],['objectY','y'],['unitFacing','facing'],['unitLevel','levelOverride'],['unitRank','rank'],['eventRadius','radius']])change(id,key,Number);
 change('unitEncounter','encounterGroup');change('unitBehavior','behavior');change('unitBoss','boss');change('unitMiniboss','miniboss');change('unitOverrides','stageOverrides',JSON.parse);
 for(const k of ['when','action','lines'])change('event-'+k,k,JSON.parse);
 const id=$('#stableId');if(id)id.onchange=()=>{try{const before=selected.id,next=HonroCommands.apply(project,[{op:'rename',id:before,newId:id.value}]);commit('ID 변경',p=>Object.assign(p,next));selected.id=id.value;renderAll()}catch(e){toast(e.message);renderAll()}};
}
function renderUnitPreviews(){
 if(!$$('[data-unit-preview]').length)return;
 const st=stage(),p=HonroMaps.profileFor(st),b=HonroMaps.createBattle(st,activeProject(),p),content=HONRO_CONTENT.stages[(st.metadata.stageId||1)-1];
 for(const canvas of $$('[data-unit-preview]')){canvas.width=100;canvas.height=104;const scene=new HonroScene(canvas),c=canvas.getContext('2d'),record=HonroUnits.record(canvas.dataset.unitPreview,'palette-unit',0,0),u=HonroUnits.create(record,b,p,content);const z=Math.min(.75,80/u.h);
  c.save();c.translate(50,94);c.scale(z,z);scene.time=0;scene.unit(c,u,false,0);c.restore();}
}
function assetDetails(a){return `<div class="panel-section"><div class="panel-title">GAME ASSET</div>
 <div class="row"><label>Material</label><input id="assetMaterial" class="field" value="${esc(a.material||'wood')}"></div>
 <div class="row"><label>Climbable</label><input id="assetClimbable" type="checkbox" ${a.climbable?'checked':''}></div>
 <div class="row"><label>Interaction</label><input id="assetInteraction" class="field" value="${esc(a.interactionType||'')}"></div>
 <div class="row"><label>Layer</label><input id="assetLayer" class="field" value="${esc(a.layer||'interactive')}"></div>
 <div class="row"><label>Collision mode</label><select id="assetCollisionMode" class="field"><option value="visual" ${a.collisionMode!=='independent'?'selected':''}>Visual에 맞춤</option><option value="independent" ${a.collisionMode==='independent'?'selected':''}>별도 polygon</option></select></div>
 ${a.vector?'<div class="muted node-label">순수 SVG 원본 · v1. 전체 배치·회전·크기·기준점과 별도 충돌 polygon은 편집할 수 있습니다. SVG의 경로 편집은 원본 파일에서 합니다.</div><button id="exportVectorSource" class="btn">SVG 원본 내보내기</button>':''}
 ${['collision','sockets','tags','params'].map(k=>`<label class="node-label">${k} (JSON)<textarea id="asset-${k}" class="field">${esc(JSON.stringify(a[k],null,2))}</textarea></label>`)}
 </div>`}
function bindAssetDetails(){
 if($('#exportVectorSource'))$('#exportVectorSource').onclick=()=>download(safe(activeAsset().name)+'.svg',activeAsset().vector.source,'image/svg+xml');
 const change=(id,key,parse=v=>v)=>{const el=$('#'+id);if(el)el.onchange=()=>{try{const value=parse(el.type==='checkbox'?el.checked:el.value);commit('Asset 속성',()=>activeAsset()[key]=value)}catch(e){toast(e.message);renderAll()}}};
 for(const [id,key] of [['assetMaterial','material'],['assetClimbable','climbable'],['assetInteraction','interactionType'],['assetLayer','layer'],['assetCollisionMode','collisionMode']])change(id,key);
 for(const k of ['collision','sockets','tags','params'])change('asset-'+k,k,JSON.parse);
}

addEventListener('DOMContentLoaded',init);
})();
