(function(G){'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>JSON.parse(JSON.stringify(x));
function host(app){let node=$('dialogue-root');if(!node){node=document.createElement('div');node.id='dialogue-root';app.root.appendChild(node);}return node;}
function allowed(app,who){return who==='서술'||app.screen!=='battle'||app.canSpeak(who);}
function queue(app,lines){const b=app.engine?.b;if(!b)return;const hs=b.honroState;hs.storyQueue??=[];hs.storyQueue.push(...lines.filter(l=>allowed(app,l[0])));app.dirty=true;}
function start(app,lines,options={}){lines=lines.filter(l=>allowed(app,l[0]));if(!lines.length){if(options.after==='outcome')app.outcome(true);return false;}app.cancelInput();app.acc=0;app.turnNotice=null;const banner=$('turn-banner');if(banner)banner.hidden=true;if(!app.dialogue&&app.scene)app.storyCamera={x:app.scene.x,y:app.scene.y,scale:app.scene.scale,manual:app.scene.manual};app.dialogue={lines:clone(lines),index:0,...options};save(app);draw(app);return true;}
function save(app){if(app.engine&&!app.training){app.engine.b.honroStory=app.dialogue?clone(app.dialogue):null;app.profile.honroBattle=clone(app.engine.b);app.persist();app.dirty=true;}else if(app.screen==='map'){app.profile.honroMapStory=app.dialogue?.id?{id:app.dialogue.id,index:app.dialogue.index}:null;app.persist();}}
function drawBust(cv,actor,cls){const source=document.createElement('canvas');source.width=640;source.height=900;const c=source.getContext('2d'),scene=new G.HonroScene(source),u={...(actor||{}),portraitOnly:true,cls,x:0,y:0,h:100,r:22,side:actor?.side??0,dead:false,maxHp:0,angle:25,facing:1,moving:0,hurt:0,anim:0,jumping:false};c.translate(320,820);c.scale(6,6);scene.unit(c,u,false,0);const pixels=c.getImageData(0,0,source.width,source.height).data;let top=source.height,bottom=0;for(let y=0;y<source.height;y++)for(let x=0;x<source.width;x++)if(pixels[(y*source.width+x)*4+3]>24){top=Math.min(top,y);bottom=y;break;}if(top>=bottom)return;const pad=(bottom-top)*.035,sy=Math.max(0,top-pad),height=(bottom-top)*.46+pad,width=height*cv.width/cv.height;cv.getContext('2d').drawImage(source,source.width/2-width/2,sy,width,height,0,0,cv.width,cv.height);}
function narrationSVG(kind='road'){
 const base=`<svg viewBox="0 0 1200 700" preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="sky" x2="0" y2="1"><stop stop-color="#102027"/><stop offset="1" stop-color="#293a36"/></linearGradient><linearGradient id="fog"><stop stop-color="#d8d0b0" stop-opacity=".12"/><stop offset="1" stop-color="#d8d0b0" stop-opacity="0"/></linearGradient></defs><rect width="1200" height="700" fill="url(#sky)"/><path d="M0 440Q210 250 430 390T830 340T1200 410V700H0Z" fill="#304139"/><path d="M0 520Q260 370 540 490T960 430T1200 470V700H0Z" fill="#1a3030"/>`;
 let art='';
 if(kind==='tavern')art='<path d="M150 540V250H970V540M110 260Q555 90 1010 260" fill="#17272a" stroke="#8c8066" stroke-width="18"/><rect x="280" y="400" width="440" height="32" fill="#725f47"/><path d="M420 376l150-25 75 30-165 26z" fill="#cabd9c" opacity=".8"/>';
 else if(kind==='cliff')art='<path d="M120 620L360 110L500 620M730 620L930 170L1080 620" fill="#263b38" stroke="#7c8978" stroke-width="5"/><path d="M450 610Q620 560 780 610" stroke="#c1b18b" stroke-width="16" fill="none"/><path d="M560 580h150" stroke="#d1c2a2" stroke-width="6"/>';
 else if(kind==='ferry')art='<path d="M0 545Q400 500 1200 560V700H0Z" fill="#17383c"/><path d="M370 535Q520 600 665 535L700 500H330Z" fill="#3f4c44" stroke="#a89a79" stroke-width="5"/><path d="M210 560H850M260 560V470M780 560V470" stroke="#8b7a5d" stroke-width="10"/>';
 else if(kind==='gate')art='<path d="M300 570V250H900V570M220 270Q600 120 980 270" fill="#1a2a2d" stroke="#8f8168" stroke-width="18"/><rect x="510" y="350" width="180" height="220" fill="#09191d"/>';
 else if(kind==='waterfall')art='<path d="M140 620L400 90L560 620M770 620L1030 150L1160 620" fill="#263b38"/><path d="M700 80Q660 220 650 620" stroke="#9bbfc1" stroke-width="45" opacity=".65"/><path d="M690 70Q650 220 648 620" stroke="#d4e2d5" stroke-width="7" opacity=".7"/>';
 else if(kind==='bridge')art='<path d="M100 520H430M760 520H1100" stroke="#aa9771" stroke-width="28"/><path d="M430 520l130 40m70-10 130-30" stroke="#8b7557" stroke-width="12"/><path d="M150 380v160M1050 380v160" stroke="#4d5647" stroke-width="18"/>';
 else if(kind==='terrace')art='<path d="M0 580H420V500H720V420H1200V700H0Z" fill="#33443b"/><path d="M0 580H420M420 500H720M720 420H1200" stroke="#a08f6b" stroke-width="8"/>';
 else if(kind==='bier')art='<path d="M360 530H840M420 530V420H780V530" stroke="#8f805e" stroke-width="16"/><path d="M390 420Q600 330 810 420" fill="#c1b89c" opacity=".38"/><path d="M455 390v-120m290 120v-120" stroke="#d2c7a9" stroke-width="4"/>';
 else if(kind==='yard'||kind==='upper-yard')art='<path d="M180 560V300H1020V560M140 315Q600 145 1060 315" fill="#19292b" stroke="#80755e" stroke-width="15"/><path d="M250 540Q600 470 950 540" stroke="#a96661" stroke-width="4" opacity=".65"/>';
 else art='<path d="M260 650Q420 420 600 350T940 140" stroke="#9d8e6d" stroke-width="55" fill="none" opacity=".5"/>';
 return base+art+'<rect width="1200" height="700" fill="url(#fog)" opacity=".45"/></svg>';
}
function narration(node,d,meta,line,app){const next=d.lines[d.index+1],nextNarration=next&&(next[0]==='서술'||next[2]?.kind==='narration'),count=meta.paragraphs?`문단 ${meta.paragraph||1} / ${meta.paragraphs}`:'서술',stageId=app?.stage?.id,stageArt=d.after==='entry'&&stageId?G.HONRO_STAGE_INTRO_ART?.[stageId]:null;node.innerHTML=`<div class="narration-overlay"><div class="narration-art ${stageArt?'stage-intro-art':''}">${stageArt?`<img src="${stageArt}" alt="${esc(app.stage?.name||'스테이지')} 컨셉 아트">`:narrationSVG(meta.art||'road')}</div><section class="narration-card" role="dialog" aria-modal="true"><div class="narration-kicker">${esc(d.title||'첫째 막')}</div><p id="story-line">${esc(line)}</p><div class="narration-actions"><span>${count}</span><button class="ghost" data-action="dialogue-skip">건너뛰기</button><button class="primary" data-action="dialogue-next">${nextNarration?'다음 문단':next?'대화로':'계속'} <b>›</b></button></div></section></div>`;}
function draw(app){const node=host(app),d=app.dialogue;document.body.classList.toggle('story-lock',!!d);if(app.scene)app.scene.storyFrozen=!!d;if(!d){node.innerHTML='';if(app.scene){app.scene.goalFocus=null;app.scene.cinematic=null;app.scene.focusUntil=app.scene.speakerUntil=0;app.scene.storyRelease?.(app.storyCamera,450);}app.storyCamera=null;return;}while(d.index<d.lines.length&&!allowed(app,d.lines[d.index][0]))d.index++;if(d.index>=d.lines.length){finish(app);return;}const [who,line,meta={}] = d.lines[d.index];if(meta.kind==='narration'||who==='서술'){if(app.scene){app.scene.goalFocus=null;app.scene.cinematic=null;app.scene.storyTween=null;}narration(node,d,meta,line,app);node.querySelector('[data-action="dialogue-next"]').focus({preventScroll:true});save(app);return;}const actor=app.speakerUnits(who).find(u=>!u.dead&&u.hp>0);if(app.scene&&actor){app.scene.cinematic=actor.id;app.scene.storyFocus?.(actor.id,500);}else if(app.scene)app.scene.cinematic=null;if(app.scene){app.scene.goalFocus=meta.focus?G.HonroObjectives.focus(app,meta.focus):null;if(app.scene.goalFocus)app.scene.cinematic=null;}const portrait=G.HONRO_STORY_PORTRAITS[who],cls=actor?.cls||portrait?.class,imageZoom=Math.max(1,Math.min(3,Number(portrait?.imageZoom)||1.65));const color=G.HONRO_CONTENT.hero[cls]?.color||'#c9b37f';node.innerHTML=`<div class="story-overlay"><section class="story-scene dialogue-scene" style="--speaker:${color}" role="dialog" aria-modal="true" aria-labelledby="story-speaker" aria-describedby="story-line"><div class="story-portrait" aria-label="${esc(who)}">${portrait?.src?`<img src="${esc(portrait.src)}" alt="${esc(who)}" style="--portrait-zoom:${imageZoom}">`:cls?'<canvas id="story-portrait-canvas" width="400" height="440"></canvas>':'<div class="story-seal" aria-hidden="true">혼<br>로</div>'}</div><div class="story-copy"><div class="story-location">${esc(d.title||app.stage?.name||'길 위')}<span>${d.index+1} / ${d.lines.length}</span></div><h2 id="story-speaker"><i></i>${esc(who)}</h2><p id="story-line">${esc(line)}</p><div class="story-actions"><span>Space / Enter</span><button class="ghost" data-action="dialogue-skip">대화 넘기기</button><button class="primary" data-action="dialogue-next">${d.index+1===d.lines.length?'계속 걷기':'다음'} <b>›</b></button></div></div></section></div>`;if(cls&&!portrait?.src)drawBust($('story-portrait-canvas'),actor,cls);node.querySelector('[data-action="dialogue-next"]').focus({preventScroll:true});save(app);}
function finish(app){const d=app.dialogue;if(!d)return;app.dialogue=null;save(app);draw(app);app.acc=0;if(d.id){app.profile.seen[d.id]=true;app.profile.honroMapStory=null;app.persist();}if(d.after==='outcome')app.outcome(true);else if(d.after==='entry')turn(app,true);}
function next(app){if(!app.dialogue)return;app.dialogue.index++;draw(app);}function key(app,e){if(['Space','Enter','Escape','Tab'].includes(e.code))e.preventDefault();if(e.code==='Tab'){const buttons=[...host(app).querySelectorAll('button')],index=buttons.indexOf(document.activeElement);buttons[(index+(e.shiftKey?-1:1)+buttons.length)%buttons.length]?.focus();}else if(['Space','Enter'].includes(e.code)&&!e.repeat){if(document.activeElement?.dataset.action==='dialogue-skip')finish(app);else next(app);}}
function drain(app){const queue=app.engine?.b.honroState.storyQueue||[];if(!queue.length)return false;const lines=queue.splice(0);return start(app,lines,{title:app.stage.name+' · 길 위의 사건'});}
function map(app){const completed=Math.max(0,...Object.keys(app.profile.cleared).map(Number)),id=`map-story-v${G.HonroStoryContent.version}-${completed}`;if(app.profile.seen[id])return;const lines=G.HonroStoryContent.mapScenes[completed];if(!lines)return;const index=app.profile.honroMapStory?.id===id?app.profile.honroMapStory.index:0;start(app,lines,{id,index:Math.min(index,lines.length-1),title:completed?'다음 길로':'연목으로 가는 길'});}
function turnSide(b){return ['ally','summon'].includes(b.phase)?'ally':b.side===0?'player':'enemy';}function turnLabel(b){const side=turnSide(b);return side!=='player'&&!hasPhaseUnit(b,side)?'':{player:'아군 턴',enemy:'적군 턴',ally:'동맹군 턴'}[side];}function hasPhaseUnit(b,side){if(side==='enemy')return b.units.some(u=>u.side===1&&!u.dead&&u.hp>0);if(side==='ally'){const ids=b.honroState?.allyQueue?.ids||[];return ids.some(id=>{const u=b.units.find(v=>v.id===id);return u&&!u.dead&&u.hp>0;});}return true;}function turnPaused(app,now=performance.now()){return !!app.turnNotice&&now<app.turnNotice.pauseUntil;}
function turn(app,force=false){const b=app.engine?.b;if(!b||app.training||app.dialogue||app.done)return;const side=turnSide(b),key=`${b.round}:${side}`;if(!force&&app.lastTurnNotice===key)return;app.lastTurnNotice=key;if(!hasPhaseUnit(b,side)){app.turnNotice=null;const old=$('turn-banner');if(old)old.hidden=true;return;}const now=performance.now();app.turnNotice={until:now+1050,pauseUntil:now+(side==='player'?250:700),side};app.acc=0;app.cancelInput();app.audio?.play('turn');const actor=b.phase==='ally'?b.honroState?.allyQueue?.ids[b.honroState.allyQueue.index]:b.phase==='summon'?b.summonTurn?.queue[b.summonTurn.index]:b.active;if(actor&&side!=='player')app.scene?.focusUnit(actor,1200);let node=$('turn-banner');if(!node){node=document.createElement('div');node.id='turn-banner';node.setAttribute('role','status');app.root.appendChild(node);}node.hidden=false;node.dataset.side=side;node.innerHTML=`<small>${b.round}번째 턴</small><strong>${turnLabel(b)}</strong><i></i>`;}
function tick(app,now){if(app.dialogue){const d=app.dialogue;if(!allowed(app,d.lines[d.index]?.[0]))draw(app);if(app.screen==='map'&&d.id)app.profile.honroMapStory={id:d.id,index:d.index};}if(app.turnNotice&&now>=app.turnNotice.until){app.turnNotice=null;const node=$('turn-banner');if(node)node.hidden=true;}}
G.HonroStory={start,queue,draw,next,finish,drain,map,turn,tick,key,turnSide,turnLabel,turnPaused};
})(globalThis);
