import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {actors} from './recipes.mjs';
import {countPath} from '../party-forge/build.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),sha=s=>createHash('sha256').update(s).digest('hex');
async function writeChanged(file,data){try{if(await readFile(file,'utf8')===data)return;}catch(error){if(error.code!=='ENOENT')throw error;}await writeFile(file,data);}
export async function buildActors(){
 const out=path.join(root,'_local/reports/actor-forge'),dest=path.join(root,'shared/assets/actors');await mkdir(out,{recursive:true});await mkdir(dest,{recursive:true});
 const base=JSON.parse(await readFile(path.join(root,'tests/fixtures/actor-baseline.json'),'utf8'));
 for(const [name,hash]of Object.entries(base.sources))if(sha(await readFile(path.join(root,name)))!==hash)throw Error('Changed actor reference: '+name);
 const sourceFiles=['tools/actor-forge/catalog.mjs','tools/actor-forge/shapes.mjs','tools/actor-forge/humans.mjs','tools/actor-forge/spirits.mjs','tools/actor-forge/objects.mjs','tools/actor-forge/anatomy.mjs','tools/actor-forge/recipes.mjs','shared/assets/rebuild-game-adapter.mjs','shared/runtime/actor-vector.js','shared/runtime/monster-vector.js'];
 const texts=await Promise.all(sourceFiles.map(n=>readFile(path.join(root,n),'utf8'))),sourceSha256=sha(sourceFiles.map((n,i)=>n+'\n'+texts[i].replace(/\r\n/g,'\n')).join('\n')),rows=[];
 for(const a of actors){
  const ids=new Set();for(const p of a.parts){if(ids.has(p.id)||p.parent&&!ids.has(p.parent))throw Error(a.id+': invalid part '+p.id);ids.add(p.id);}
  for(const clip of Object.values(a.clips))for(const t of clip.tracks){if(!ids.has(t.part)||t.keys[0][0]!==0||t.keys.at(-1)[0]!==1)throw Error(a.id+': invalid track');}
  const paths=a.parts.flatMap(p=>p.paths),counts=paths.map(p=>countPath(p.d)),anchors=counts.reduce((s,p)=>s+p.anchors,0),old=base.assets[a.id]?.anchors;
  if(anchors>(old?old*3.15:240))throw Error(`${a.id}: ${anchors} exceeds ${old?`${old} x 3.15`:'new summon budget 240'}`);
  for(const p of paths)if(/NaN|Infinity|[^MLCQZ\d.,\s+-]/.test(p.d)||p.fill&&!a.palette[p.fill]||p.stroke&&!a.palette[p.stroke])throw Error(a.id+': invalid absolute path');
  const raw=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${a.viewBox.join(' ')}"><title>${a.name}</title>\n${a.parts.map(p=>`<g id="${p.id}" stroke-linecap="round" stroke-linejoin="round">${p.paths.map(v=>`<path d="${v.d}" fill="${v.fill?a.palette[v.fill]:'none'}" stroke="${v.stroke?a.palette[v.stroke]:'none'}" stroke-width="${v.width}"/>`).join('')}</g>`).join('\n')}\n</svg>\n`,svg=raw.replace(/\n\s*/g,''),rig=JSON.stringify({version:1,baseHeight:a.baseHeight,viewBox:a.viewBox,parts:a.parts.map(({paths,...p})=>p)},null,2)+'\n',anim=JSON.stringify(a.clips,null,2)+'\n';
  await writeChanged(path.join(dest,a.id+'.svg'),svg);await writeChanged(path.join(dest,a.id+'.rig.json'),rig);await writeChanged(path.join(dest,a.id+'.animation.json'),anim);
  rows.push({id:a.id,name:a.name,anchors,previousAnchors:old??0,ratio:old?anchors/old:1,controls:counts.reduce((s,p)=>s+p.controls,0),parts:a.parts.length,paths:paths.length,colors:new Set(paths.flatMap(p=>[p.fill,p.stroke]).filter(Boolean)).size,lodPaths:[0,1,2].map(n=>paths.filter(p=>p.lod<=n).length),rawSvgBytes:Buffer.byteLength(raw),optimizedSvgBytes:Buffer.byteLength(svg),rigBytes:Buffer.byteLength(rig),animationBytes:Buffer.byteLength(anim),sha256:sha(svg)});
 }
 const bundle='// Generated by tools/actor-forge/build.mjs.\nglobalThis.HONRO_ACTORS='+JSON.stringify({version:1,sourceSha256,assets:Object.fromEntries(actors.map(a=>[a.id,a]))})+';\n';await writeChanged(path.join(dest,'actors.runtime.js'),bundle);
 const styleReferences={};for(const name of ['shared/assets/party/party.runtime.js','shared/assets/monsters/monsters.runtime.js'])styleReferences[name]=sha(await readFile(path.join(root,name)));
 const report={sourceFiles,sourceSha256,styleReferences,baseline:'tests/fixtures/actor-baseline.json',anchorBudget:{maxRatio:3.15,noMinimum:true},runtimeBytes:Buffer.byteLength(bundle),adapterBytes:Buffer.byteLength(texts.at(-2)),assets:rows};await writeFile(path.join(out,'metrics.json'),JSON.stringify(report,null,2)+'\n');return report;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(JSON.stringify(await buildActors(),null,2));
