import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import vm from 'node:vm';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createParty} from './recipes.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const read=async name=>(await readFile(path.join(root,name),'utf8')).replace(/\r\n/g,'\n'),sha=text=>createHash('sha256').update(text).digest('hex'),bytes=text=>Buffer.byteLength(text);
export function countPath(d){let anchors=0,controls=0;for(const [,cmd,args]of d.matchAll(/([MLQCZ])([^MLQCZ]*)/gi)){const n=(args.match(/[-+]?(?:\d*\.)?\d+/g)||[]).length,k=cmd.toUpperCase(),arity={M:2,L:2,Q:4,C:6,Z:1}[k];if(n%arity)throw Error('Invalid path arity');anchors+=n/arity;controls+=k==='Q'?n/4:k==='C'?n/3:0;}return{anchors,controls};}
export async function buildParty(){
 const baseline=JSON.parse(await read('tests/fixtures/party-baseline.json')),reference=JSON.parse(await read('tools/party-forge/references.json')),source=await read(baseline.source),legacy={};
 if(sha(source)!==baseline.sha256)throw Error('The immutable v006 baseline has changed');
 const comparisonSource=await read(reference.baseline.source),previous={};if(sha(comparisonSource)!==reference.baseline.sha256)throw Error('The v008 comparison baseline has changed');vm.runInNewContext(comparisonSource,previous);
 for(const [id,a]of Object.entries(previous.HONRO_PARTY))if(a.paths.reduce((n,p)=>n+countPath(p.d).anchors,0)!==reference.assets[id].anchors)throw Error('Invalid v008 anchor budget: '+id);
 for(const r of Object.values(reference.assets)){const data=await readFile(path.join(root,'tools/party-forge/references',r.file));if(sha(data)!==r.sha256)throw Error('Reference sheet hash mismatch: '+r.file);}
 vm.runInNewContext(source,legacy);const rigSource=await read('shared/runtime/party-rig.js'),ctx={};vm.runInNewContext(rigSource,ctx);const assets=createParty(legacy.HONRO_PARTY,ctx.HonroVectorRig);
 const sourceFiles=['tools/party-forge/motion.mjs','tools/party-forge/recipes.mjs','tools/party-forge/proportions.mjs','tools/party-forge/head-scale.mjs','tools/party-forge/balance.mjs','tools/party-forge/shape-bounds.mjs','tools/party-forge/sheet-faces.mjs','tools/party-forge/portrait-shapes.mjs','tools/party-forge/references.json','shared/runtime/party-rig.js','shared/assets/rebuild-game-adapter.mjs'],texts=await Promise.all(sourceFiles.map(read)),sourceSha256=sha(sourceFiles.map((name,i)=>name+'\n'+texts[i]).join('\n'));
 const output=path.join(root,'shared/assets/party'),reports=path.join(root,'_local/reports/party-forge');await mkdir(output,{recursive:true});await mkdir(reports,{recursive:true});const rows=[];
 for(const [id,a]of Object.entries(assets)){
  const ref=reference.assets[id];a.design={reference:'tools/party-forge/references/'+ref.file,referenceSha256:ref.sha256,faceCrop:ref.faceCrop,brief:ref.brief,anchorBudget:[reference.baseline.minRatio,reference.baseline.maxRatio],comparisonVersion:8};
  const ids=new Set(a.rig.parts.map(p=>p.id)),paths=new Set();for(const p of a.paths){if(paths.has(p.id)||!ids.has(p.part)||p.fill&&!a.palette[p.fill]||p.stroke&&!a.palette[p.stroke]||/NaN|Infinity|[^MLQCZmlcqz\d.,\s+-]/.test(p.d))throw Error(id+': invalid path '+p.id);paths.add(p.id);}
  for(const p of a.rig.parts)if(p.parent&&!ids.has(p.parent))throw Error(id+': invalid parent');
  const counts=a.paths.map(p=>countPath(p.d)),anchors=counts.reduce((s,p)=>s+p.anchors,0),controls=counts.reduce((s,p)=>s+p.controls,0),ratio=anchors/baseline.assets[id].anchors;
  const previousRatio=anchors/ref.anchors;if(previousRatio<reference.baseline.minRatio||previousRatio>reference.baseline.maxRatio)throw Error(`${id}: ${anchors}/${ref.anchors} = ${previousRatio.toFixed(3)}; expected the same v008 anchor count`);
  const raw=ctx.HonroVectorRig.poseSVG(a,'idle',0),svg=raw.replaceAll(/\n\s*/g,''),rig=JSON.stringify({canvas:a.canvas,rig:a.rig,constraints:a.constraints,face:a.face},null,2)+'\n',animation=JSON.stringify(a.animation,null,2)+'\n';
  await writeFile(path.join(output,id+'.svg'),svg);await writeFile(path.join(output,id+'.rig.json'),rig);await writeFile(path.join(output,id+'.animation.json'),animation);
  rows.push({id,name:a.name_ko,anchors,controls,originalAnchors:baseline.assets[id].anchors,anchorRatio:ratio,previousAnchors:ref.anchors,previousRatio,faceAnchors:a.paths.filter(p=>p.part==='head').reduce((s,p)=>s+countPath(p.d).anchors,0),paths:a.paths.length,parts:a.rig.parts.length,colors:new Set(a.paths.flatMap(p=>[p.fill,p.stroke]).filter(Boolean)).size,lodPaths:[0,1,2].map(n=>a.paths.filter(p=>(p.detail||0)<=n).length),rawSvgBytes:bytes(raw),optimizedSvgBytes:bytes(svg),rigBytes:bytes(rig),animationBytes:bytes(animation),sha256:sha(svg)});
 }
 const bundle='// Generated by tools/party-forge/build.mjs.\nglobalThis.HONRO_PARTY='+JSON.stringify(assets)+';globalThis.HONRO_ARCHER=globalThis.HONRO_PARTY.seol_o;globalThis.HONRO_PARTY_ART='+JSON.stringify({version:10,sourceSha256})+';\n';
 await writeFile(path.join(output,'party.runtime.js'),bundle);
 const report={sourceFiles,sourceSha256,baseline:reference.baseline.source,anchorBudget:{minRatio:reference.baseline.minRatio,maxRatio:reference.baseline.maxRatio},runtimeBytes:bytes(bundle),rigRuntimeBytes:bytes(rigSource),assets:rows};await writeFile(path.join(reports,'metrics.json'),JSON.stringify(report,null,2)+'\n');return report;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(JSON.stringify(await buildParty(),null,2));
