/** Pure view builders for the armory. State changes stay in App/progression. */
import type { Profile, ClassId, Skill, Unit, ExistenceVector } from './types';
import { SKILLS, CLASSES } from './data';
import { icon } from './icons';
import { escapeHTML as esc } from './math';
import { MANA_COST_MULTIPLIER } from './balance';
import {skillPlayNotes} from './skillNotes';
import {skillGrowthRows} from './progression';
import {attackForSkill,normalizedAttack,effectiveDefenseForUnit} from './existence';
export {skillPlayNotes} from './skillNotes';
import { BRANCHES, TALENTS, TALENT_MAP, CLASS_IDS, STAT_KEYS, STAT_LABELS, statGainLabel, statTrainingRank, baseSkill, heroStats, levelOf, xpFraction, xpAtLevel, xpToNext, pointsLeft, trainReason, untrainReason, requiredRankLevel, ultimateProgress, ultimateUnlocked, ultimateSkill, MAX_LEVEL } from './progression';
const clsName=(c:ClassId)=>({mage:'마법사',archer:'궁수',knight:'검사',occultist:'심령술사'})[c];
const tier=(id:string)=> SKILLS[id]?.basic?'기본':SKILLS[id]?.capstone?'비기':SKILLS[id]?.ultimate?'ULT':String((TALENT_MAP[id]?.row??0)+1);
const color=(id:string)=>{const s=SKILLS[id],n=TALENT_MAP[id];return s?.ultimate?s.color:n?BRANCHES[n.cls][n.branch].color:'#80949e';};
const pip=(r:number)=>`<span class="rank-track" aria-hidden="true">${Array.from({length:8},(_,i)=>`<i class="${i<r?'on':''}"></i>`).join('')}</span>`;
function existenceBars(title:string,values:ExistenceVector,max:number,note:string){
 const rows=([['form','형'],['qi','기'],['soul','혼']] as const).map(([key,label])=>{const percent=Math.round(values[key]*100);return `<span class="existence-part" style="--existence-width:${Math.min(100,values[key]/max*100)}%" title="${label} ${percent}%"><b>${label}</b><i aria-hidden="true"><em></em></i><strong>${percent}%</strong></span>`;}).join('');
 return `<div class="existence-info" role="group" aria-label="${title}"><div class="existence-caption">${title}<small>${note}</small></div><div class="existence-parts">${rows}</div></div>`;
}
export function existenceAttackView(skill:Skill){return existenceBars('공격 속성',normalizedAttack(skill.existenceAttack||attackForSkill(skill)),1,'형 · 기 · 혼');}
export function existenceDefenseView(unit:Unit){return existenceBars('피해 반응',effectiveDefenseForUnit(unit),1.5,'100% = 보통 피해');}
export function skillStamp(id:string,size=28){const s=SKILLS[id];return `<span class="skill-stamp ${s?.ultimate?'ultimate-stamp':''}" style="--branch:${color(id)}">${s?icon('skill:'+id,'',size):icon('plus','',size)}${s?`<b>${tier(id)}</b>`:''}</span>`;}
function slotMeta(p:Profile,cls:ClassId,id:string|undefined){const s=id?SKILLS[id]:undefined;if(!s)return {branch:'배운 액티브 선택',tier:'',rank:'',color:'#80949e'};if(s.basic)return {branch:'기본 공격 · SP 불필요',tier:'',rank:'항상 사용 가능',color:s.color};if(s.ultimate)return {branch:'궁극기',tier:'3계열 완성',rank:'ULT',color:s.color};const n=TALENT_MAP[id!],r=p.heroes[cls].ranks[id!]||0,br=n?BRANCHES[cls][n.branch]:undefined;return {branch:br?.name||'액티브',tier:n?`${n.row+1}단계`:'',rank:`Lv.${r}/8`,color:color(id!)};}
export function slotCard(p:Profile,cls:ClassId,i:number,action='choose-slot',incoming=''){
 const id=p.loadouts[cls][i],s=SKILLS[id],meta=slotMeta(p,cls,id);
 return `<button class="loadout-slot slot-card ${s?'occupied':'vacant'} ${s?.ultimate?'ultimate-slot':''}" style="--branch:${meta.color}" data-action="${action}" data-slot="${i}" ${incoming?`data-skill="${incoming}"`:''} aria-label="슬롯 ${i+1}, ${s?`${s.name}, ${meta.branch} ${meta.tier}, ${meta.rank}`:'빈 슬롯'}"><span class="slot-tag">${i===0?'01 · 기본기':`0${i+1} · ${incoming?'교체':'액티브'}`}</span><span class="slot-main">${s?skillStamp(id):'<span class="empty-stamp">+</span>'}<span class="slot-info"><strong>${s?.name||'기술 장착'}</strong><small>${s?`${meta.branch}${meta.tier?' · '+meta.tier:''}`:'배운 액티브 선택'}</small></span></span><span class="slot-foot">${s?`<span>${meta.rank}</span>${s.basic?'':s.ultimate?'<span class="ultimate-pips">◆ ◆ ◆</span>':pip(p.heroes[cls].ranks[id]||0)}`:'<span>빈 슬롯</span>'}${i!==0?icon('chevron','',12):''}</span></button>`;
}
export function campView(p:Profile,cls:ClassId,portraits:Record<string,string>,header:string,branch=0){
 const h=p.heroes[cls],lv=levelOf(h),stats=heroStats(h,cls),pts=pointsLeft(h,cls),ult=ultimateSkill(cls),up=ultimateProgress(h,cls),unlocked=ultimateUnlocked(h,cls),equipped=p.loadouts[cls].includes(ult);
 const passives=TALENTS.filter(n=>n.cls===cls&&n.passive&&(h.ranks[n.id]||0)>0);
 return `<main class="screen camp-screen camp-v5">${header}<div class="camp-scroll" id="camp-scroll"><div class="armory-shell">
 <nav class="hero-tabs" aria-label="용병 선택">${CLASS_IDS.map(c=>`<button class="hero-tab ${c===cls?'active':''}" data-action="hero" data-class="${c}" aria-pressed="${c===cls}"><img src="${portraits[c]}" alt=""><span><strong>${CLASSES[c].person}</strong><small>${clsName(c)} · Lv.${levelOf(p.heroes[c])}</small></span>${pointsLeft(p.heroes[c],c)>0?`<span class="point-dot">${pointsLeft(p.heroes[c],c)} SP</span>`:''}</button>`).join('')}</nav>
  <section class="hero-summary"><div class="summary-identity"><img src="${portraits[cls]}" alt=""><div><div class="micro-label">${clsName(cls)} / 원정 용병</div><h2>${CLASSES[cls].person}<span>Lv.${lv}</span></h2><div class="xp-meter"><i style="width:${xpFraction(h)*100}%"></i></div><div class="xp-text">${lv===MAX_LEVEL?'최대 레벨':`${(h.xp-xpAtLevel(lv)).toLocaleString()} / ${xpToNext(lv).toLocaleString()} XP`}</div></div></div><div class="stat-row">${[['HP',stats.hp],['MP',stats.mp],['공격',`${stats.attack.toFixed(2)}×`],['방어',`${Math.round(stats.armor*100)}%`],['치명 확률',`${(stats.critChance*100).toFixed(1)}%`],['치명 배율',`${stats.critMultiplier.toFixed(2)}×`],['이동',stats.move],['MP 회복',stats.regen]].map(([a,b])=>`<div class="stat"><small>${a}</small><strong>${b}</strong></div>`).join('')}</div><button class="btn ghost small summary-tune" data-action="tuning">조율</button></section>
  <section class="stat-invest-panel"><div class="stat-invest-head"><h3>기초 단련 <span>${statTrainingRank(h)}회</span></h3><small>기예 대신 1 SP로 모든 기본 능력 강화</small></div><p class="stat-invest-character">${{mage:'담허는 기력과 술법에 무게를 둔다.',archer:'설오는 공격과 치명에 무게를 둔다.',knight:'휘겸은 체력, 방어와 이동에 무게를 둔다.',occultist:'소단은 기력과 혼술에 무게를 둔다.'}[cls]}</p><div class="stat-invest-gains">${STAT_KEYS.map(key=>`<span>${STAT_LABELS[key]} <b>${statGainLabel(cls,key)}</b></span>`).join('')}</div><div class="stat-invest-actions"><span>남은 ${pts} SP</span><button type="button" class="btn ghost small" data-action="refund-stat" ${statTrainingRank(h)?'':'disabled'}>1회 되돌리기</button><button type="button" class="btn primary small" data-action="invest-stat" ${pts>0&&statTrainingRank(h)<60?'':'disabled'}>기초 단련 · 1 SP</button></div></section>
 <section class="equipped-panel"><div class="section-caption"><h3>출전 기술 <span>4 SLOT</span></h3><small>기본기 + 선택 액티브 3개</small></div><div class="loadout-cards">${[0,1,2,3].map(i=>slotCard(p,cls,i)).join('')}</div></section>
 ${SKILLS[ult].ultimate?`<section class="ultimate-panel ${unlocked?'unlocked':'locked'}" style="--branch:${SKILLS[ult].color}"><div class="ultimate-core">${skillStamp(ult,35)}<div><div class="micro-label">ULTIMATE · ${up.learned} / ${up.total}</div><h3>${SKILLS[ult].name}</h3><p>${unlocked?'세 액티브 계열 완성 · 전투에서 장착 가능':'세 액티브 계열의 모든 기술을 Lv.1 이상 습득하면 해금'}</p></div></div><div class="ultimate-progress"><i style="width:${up.learned/up.total*100}%"></i></div><div class="ultimate-actions"><button class="btn ${unlocked?'primary':'ghost'} small" data-action="ultimate-detail" data-skill="${ult}">${unlocked?'궁극기 보기':'해금 조건 보기'}</button>${unlocked&&!equipped?`<button class="btn small" data-action="equip-prompt" data-skill="${ult}">장착</button>`:equipped?'<span class="ultimate-equipped">장착 중</span>':''}</div></section>`:''}
 <section class="passive-summary"><div class="passive-caption">${icon('rune','',16)}<strong>패시브</strong><span>습득 즉시 자동 적용</span></div><div class="passive-pills">${passives.map(n=>`<button class="passive-chip" style="--branch:${color(n.id)}" data-action="talent" data-talent="${n.id}">${icon(n.icon,'',17)}<span>${n.name}</span><b>Lv.${h.ranks[n.id]}</b></button>`).join('')||'<span class="no-passives">아직 배운 패시브가 없습니다.</span>'}</div></section>
 <div class="tree-tools"><h3>스킬트리 <span class="sp-counter">${pts}<small> SP</small></span></h3><span class="spacer"></span><button class="btn ghost small" data-action="auto-train">추천 분배</button><button class="btn ghost small" data-action="reset-talents">초기화</button></div>
 <nav class="branch-tabs" aria-label="스킬 계열">${BRANCHES[cls].map((br,b)=>`<button data-action="camp-branch" data-branch="${b}" aria-pressed="${b===branch}" class="${b===branch?'active':''}" style="--branch:${br.color}">${br.name}</button>`).join('')}</nav>
 <div class="tree-grid">${BRANCHES[cls].map((br,b)=>`<section class="branch ${b===branch?'mobile-current':''}" data-branch-panel="${b}" style="--branch:${br.color}"><div class="branch-head"><h3><i></i>${br.name}</h3><span>${b===3?'습득 즉시 적용':'액티브'}</span></div><div class="branch-nodes">${TALENTS.filter(n=>n.cls===cls&&n.branch===b).map(n=>{
 const rank=h.ranks[n.id]||0,reason=trainReason(h,n.id),refundReason=untrainReason(h,n.id),equipped=!n.passive&&p.loadouts[cls].includes(n.id),locked=!rank&&!!reason;
 return `<div class="tree-node-wrap ${n.passive?'passive-node-wrap':''}"><button class="tree-node ${n.passive?'passive-node':''} ${rank?'learned':locked?'locked':'available'} ${equipped?'equipped':''}" data-action="talent" data-talent="${n.id}" aria-label="${n.name}, ${n.row+1}단계, 기술 레벨 ${rank} / 8${equipped?', 장착 중':''}"><span class="node-tier">${n.row+1}<small>단계</small></span>${skillStamp(n.id,23)}<span class="node-body"><span class="node-name">${n.name}</span><span class="node-sub">${rank?`<b>Lv.${rank}</b><span>/8</span>`:`용병 Lv.${n.required}`}${equipped?'<em>장착</em>':n.passive&&rank?'<em>적용 중</em>':''}</span>${pip(rank)}</span></button><div class="node-stepper" aria-label="${n.name} 빠른 강화"><button type="button" class="rank-step minus" data-action="talent-minus" data-talent="${n.id}" ${refundReason?'disabled':''} title="${refundReason||'1 SP 회수'}" aria-label="${n.name} 1포인트 회수">−</button><span>${rank}<small>/8</small></span><button type="button" class="rank-step plus" data-action="talent-plus" data-talent="${n.id}" ${reason?'disabled':''} title="${reason||'1 SP 투자'}" aria-label="${n.name} 1포인트 투자">+</button></div></div>`;
 }).join('')}</div></section>`).join('')}</div>
 </div></div></main>`;
}
export function talentView(p:Profile,id:string,closeButton:string){
 if(SKILLS[id]?.basic){const s=SKILLS[id];return `${closeButton}<h2>${s.name}</h2><p class="skill-desc">${s.desc}</p><p class="skill-mechanics">${esc(skillPlayNotes(id))}</p>${existenceAttackView(s)}<p>기본 공격 · SP 투자 없음 · 항상 사용 가능</p><canvas aria-label="${esc(s.name)} 시연" id="skill-preview" width="720" height="360"></canvas>`;}
 const n=TALENT_MAP[id],s=SKILLS[id],h=p.heroes[n.cls],rank=h.ranks[id]||0,reason=trainReason(h,id),br=BRANCHES[n.cls][n.branch],equipped=p.loadouts[n.cls].includes(id),next=Math.min(8,rank+1);
 const before=skillGrowthRows(id,rank),after=skillGrowthRows(id,next);
 const preview=!s.passive?`<section class="skill-preview-shell"><canvas aria-label="${esc(s.name)} 시연" id="skill-preview" data-skill="${id}" width="720" height="360"></canvas></section>`:'';
 const summary=`<section class="skill-modal-summary"><div class="talent-heading">${skillStamp(id,35)}<div><div class="micro-label">${br.name} · ${tier(id)}단계</div><h2>${n.name}</h2><span class="ability-type">${s.passive?'패시브 · 습득 시 자동 적용':equipped?'액티브 · 장착 중':'액티브'}</span></div></div><div class="rank-banner"><strong>Lv.${rank}<small> / 8</small></strong>${pip(rank)}<span>${pointsLeft(h,n.cls)} SP</span></div><p class="skill-desc">${esc(n.desc)}</p><p class="skill-mechanics">${esc(skillPlayNotes(id))}</p>${!s.passive?existenceAttackView(s):''}</section>`;
 const stats=`<section class="skill-modal-stats"><div class="effect-compare ${rank>=8?'at-max':''}"><div class="effect-heading"><span>효과</span><span>${rank?'현재':'미습득'}</span><span>${rank<8?`Lv.${next}`:'최대'}</span></div>${after.map((row,i)=>`<div class="effect-row"><span>${row.label}</span><span>${rank?before[i]?.value||'—':'—'}</span><strong>${row.value}</strong></div>`).join('')}</div>${rank<8?`<div class="upgrade-requirement">${reason||`강화 가능 · 용병 Lv.${requiredRankLevel(n,next)}`}<span>${rank?'강화':'습득'} 1 SP</span></div>`:'<div class="upgrade-requirement">최고 레벨에 도달했습니다.</div>'}<div class="dialog-actions">${!s.passive&&rank>0&&id!==baseSkill(n.cls)?`<button class="btn" data-action="equip-prompt" data-skill="${id}">${equipped?'슬롯 변경':'장착'}</button>`:''}<button class="btn primary" data-action="train" data-talent="${id}" ${reason?'disabled':''}>${rank>=8?'최대 레벨':rank?'강화 · 1 SP':'습득 · 1 SP'}</button></div></section>`;
 return `${closeButton}<div class="talent-detail talent-v5 ${s.passive?'passive-detail':''}" style="--branch:${br.color}"><div class="skill-modal-grid">${summary}${!s.passive?`<section class="skill-modal-preview">${preview}</section>`:''}${stats}</div></div>`;
}
export function ultimateView(p:Profile,cls:ClassId,close:string){
 const h=p.heroes[cls],id=ultimateSkill(cls),s=SKILLS[id],prog=ultimateProgress(h,cls),unlocked=ultimateUnlocked(h,cls),equipped=p.loadouts[cls].includes(id),cost=Math.round(s.cost*MANA_COST_MULTIPLIER);
 const summary=`<section class="skill-modal-summary"><div class="talent-heading">${skillStamp(id,42)}<div><div class="micro-label">CLASS ULTIMATE · ${prog.learned}/${prog.total}</div><h2>${s.name}</h2><span class="ability-type">${unlocked?'해금됨 · 기력이 있으면 사용 가능':'세 액티브 계열 완성 필요'}</span></div></div><p class="skill-desc">${esc(s.desc)}</p><p class="skill-mechanics">${esc(skillPlayNotes(id))}</p>${existenceAttackView(s)}<div class="ultimate-progress big"><i style="width:${prog.learned/prog.total*100}%"></i></div></section>`;
 const preview=`<section class="skill-preview-shell ultimate-preview"><canvas aria-label="${esc(s.name)} 시연" id="skill-preview" data-skill="${id}" width="720" height="360"></canvas></section>`;
 const stats=`<section class="skill-modal-stats"><div class="ultimate-stat-grid"><div><small>기본 피해</small><strong>${s.damage}</strong></div><div><small>효과 반경</small><strong>${s.radius||'직격'}</strong></div><div><small>MP</small><strong>${cost}</strong></div><div><small>재사용</small><strong>제한 없음</strong></div></div><div class="upgrade-requirement">${unlocked?'모든 액티브 기술을 최소 Lv.1 습득했습니다.':`액티브 기술 ${prog.total-prog.learned}개를 더 습득하세요.`}<span>${prog.learned} / ${prog.total}</span></div>${unlocked?`<div class="dialog-actions"><button class="btn primary" data-action="equip-prompt" data-skill="${id}">${equipped?'슬롯 변경':'궁극기 장착'}</button></div>`:''}</section>`;
 return `${close}<div class="talent-detail ultimate-detail" style="--branch:${s.color}"><div class="skill-modal-grid">${summary}<section class="skill-modal-preview">${preview}</section>${stats}</div></div>`;
}
export function slotLibrary(p:Profile,cls:ClassId,slot:number,close:string){
 const h=p.heroes[cls],current=p.loadouts[cls][slot],ult=ultimateSkill(cls),ultUnlocked=ultimateUnlocked(h,cls);
 const sections=BRANCHES[cls].slice(0,3).map((br,b)=>{const skills=TALENTS.filter(n=>n.cls===cls&&n.branch===b&&n.id!==baseSkill(cls)&&h.ranks[n.id]>0);if(!skills.length)return '';return `<section style="--branch:${br.color}"><h3>${br.name}</h3>${skills.map(n=>`<button data-action="equip-slot" data-skill="${n.id}" class="equip-option ${current===n.id?'current':''}">${skillStamp(n.id,25)}<span><strong>${n.name}</strong><small>${tier(n.id)}단계 · Lv.${h.ranks[n.id]}/8</small></span><em>${current===n.id?'현재':p.loadouts[cls].includes(n.id)?'교환':'장착'}</em></button>`).join('')}</section>`;}).join('');
 const ultimate=ultUnlocked?`<section class="equip-ultimate" style="--branch:${SKILLS[ult].color}"><h3>궁극기</h3><button data-action="equip-slot" data-skill="${ult}" class="equip-option ultimate-option ${current===ult?'current':''}">${skillStamp(ult,28)}<span><strong>${SKILLS[ult].name}</strong><small>세 액티브 계열 완성 · 기력 소모</small></span><em>${current===ult?'현재':p.loadouts[cls].includes(ult)?'교환':'장착'}</em></button></section>`:'';
 return `${close}<div class="equip-v5"><div class="micro-label">ACTIVE LOADOUT</div><h2>슬롯 ${slot+1} 변경</h2><div class="equip-library">${sections}${ultimate||''}${!sections&&!ultimate?'<p>스킬트리에서 액티브를 먼저 배우세요.</p>':''}</div></div>`;
}
