(function(G){'use strict';
const C=G.HONRO_CORE,H=G.HONRO_CONTENT,clone=x=>JSON.parse(JSON.stringify(x)),clamp=C.clamp;
// Monster attacks are authored as monster skills.  Human seal troops may reuse martial techniques,
// but beasts/spirits do not masquerade as player classes just to borrow their buttons.
const MONSTER_SKILLS={
 HBT01:{id:'HBT01',cls:'mage',name:'울림비명',tag:'박쥐 · 초음파',desc:'앞쪽 공기를 떨게 하는 짧고 빠른 초음파. 직접 피해는 낮고 폭발 반경이 넓다.',cost:0,damage:18,radius:92,mode:'honroSonic',icon:'resonance',color:'#a9beb0',speed:.994,wind:.10,terrain:.15,gravity:.08},
 HBT02:{id:'HBT02',cls:'mage',name:'메아리침',tag:'박쥐 · 반향',desc:'가느다란 반향 덩어리를 직선에 가깝게 쏜다.',cost:0,damage:23,radius:26,mode:'honroEchoNeedle',icon:'resonance',color:'#869f9d',speed:.896,wind:.12,terrain:.10,gravity:.12},
 HGS01:{id:'HGS01',cls:'occultist',name:'망자의 한숨',tag:'행렬귀 · 저중력',desc:'느리게 떠가는 한숨이 닿은 곳의 기운을 흐린다.',cost:0,damage:25,radius:56,mode:'honroDeadBreath',icon:'rune',color:'#a99ab4',speed:.82,wind:.15,terrain:.20,gravity:.22},
 HGS02:{id:'HGS02',cls:'occultist',name:'상여그늘',tag:'행렬귀 · 음영',desc:'낮게 깔리는 혼기 덩어리.',cost:0,damage:21,radius:76,mode:'honroFuneralShade',icon:'vortex',color:'#8e8298',speed:.76,wind:.22,terrain:.18,gravity:.30},
 HBR01:{id:'HBR01',cls:'knight',name:'뿌리쐐기',tag:'뿌리짐승 · 파편',desc:'굳은 뿌리 파편을 무겁게 던진다.',cost:0,damage:35,radius:48,mode:'honroRootShard',icon:'break',color:'#8b8b6d',speed:.76,wind:.55,terrain:1.30,gravity:1.18},
 HBR02:{id:'HBR02',cls:'knight',name:'흙울음',tag:'뿌리짐승 · 충격',desc:'흙과 돌을 뭉쳐 낮게 날린다.',cost:0,damage:29,radius:82,mode:'honroEarthRoar',icon:'quake',color:'#727b5f',speed:.72,wind:.62,terrain:1.65,gravity:1.25},
 HLN01:{id:'HLN01',cls:'occultist',name:'혼불방울',tag:'등불귀 · 혼불',desc:'느린 혼불이 목표 부근에서 크게 번진다.',cost:0,damage:24,radius:84,mode:'honroSoulFlame',icon:'flame',color:'#c4c697',speed:.68,wind:.18,terrain:.10,gravity:.16},
 HLN02:{id:'HLN02',cls:'occultist',name:'혼무씨',tag:'등불귀 · 혼무',desc:'짙은 혼무 덩어리를 떨어뜨린다.',cost:0,damage:20,radius:112,mode:'honroMistSeed',icon:'rune',color:'#9fae92',speed:.62,wind:.26,terrain:.10,gravity:.35},
 HSH01:{id:'HSH01',cls:'occultist',name:'수의가시',tag:'수의귀 · 투과',desc:'얇은 수의 조각이 지형을 스치듯 지나간다.',cost:0,damage:32,radius:24,mode:'honroShroudNeedle',icon:'pierce',color:'#aea0ad',speed:.756,wind:.18,terrain:.12,gravity:.20,phase:'terrain'},
 HSH02:{id:'HSH02',cls:'occultist',name:'매듭실',tag:'수의귀 · 결박',desc:'긴 천조각처럼 날아가 넓게 터진다.',cost:0,damage:22,radius:74,mode:'honroShroudKnot',icon:'bind',color:'#8d7b89',speed:.86,wind:.30,terrain:.10,gravity:.40},
 HCW01:{id:'HCW01',cls:'archer',name:'썩은깃',tag:'산송장 까마귀 · 깃',desc:'썩은 깃을 뭉쳐 날리는 독자 공격.',cost:0,damage:23,radius:38,mode:'honroRotFeather',icon:'arrow',color:'#879184',speed:.826,wind:.38,terrain:.18,gravity:.60},
 HCW02:{id:'HCW02',cls:'archer',name:'검은깃비',tag:'산송장 까마귀 · 산개',desc:'검은 깃 덩어리를 크게 흩뿌린다.',cost:0,damage:18,radius:82,mode:'honroFeatherBurst',icon:'rain',color:'#66766f',speed:.92,wind:.55,terrain:.15,gravity:.75},
 HWD01:{id:'HWD01',cls:'knight',name:'장승못',tag:'장승 · 목편',desc:'묵직한 나무못을 날린다.',cost:0,damage:34,radius:34,mode:'honroWoodSpike',icon:'break',color:'#a08e67',speed:.82,wind:.42,terrain:.85,gravity:1.05},
 HWD02:{id:'HWD02',cls:'knight',name:'터줏바람',tag:'장승 · 밀침',desc:'나무틈에서 터지는 압력파.',cost:0,damage:24,radius:100,mode:'honroWardGust',icon:'push',color:'#8f997d',speed:.76,wind:.28,terrain:.25,gravity:.30},
 HMO01:{id:'HMO01',cls:'knight',name:'곡소리',tag:'상두꾼 · 충격파',desc:'목 없는 몸에서 검은 울림이 퍼진다.',cost:0,damage:30,radius:92,mode:'honroMournerWail',icon:'resonance',color:'#9f7978',speed:.80,wind:.20,terrain:.25,gravity:.24},
 HMO02:{id:'HMO02',cls:'knight',name:'상여추',tag:'상두꾼 · 중량',desc:'상여 장식의 무거운 파편을 던진다.',cost:0,damage:42,radius:52,mode:'honroBierWeight',icon:'slam',color:'#8e7762',speed:.70,wind:.48,terrain:1.15,gravity:1.30}
};
Object.assign(C.SKILLS,MONSTER_SKILLS);
const ARCHETYPES={
 ghost:{name:'떠도는 혼',role:'fire',look:'ghost',cls:'occultist',skills:['HGS01','HGS02'],hp:102,attack:.50,h:105,r:21,intent:'망자의 한숨'},
 shade:{name:'매듭진 수의귀',role:'ice',look:'shade',cls:'occultist',skills:['HSH01','HSH02'],hp:126,attack:.51,h:115,r:22,intent:'수의가시와 매듭실'},
 hound:{name:'들린 산개',role:'leaper',look:'beast',variant:'hound',cls:'knight',skills:['HBR01','HBR02'],hp:108,attack:.54,h:88,r:32,intent:'빠른 돌진과 흙파편'},
 boar:{name:'들린 멧돼지',role:'leaper',look:'beast',variant:'boar',cls:'knight',skills:['HBR01','HBR02'],hp:154,attack:.64,h:108,r:41,intent:'무거운 돌진과 흙울음'},
 stag:{name:'들린 숫사슴',role:'leaper',look:'beast',variant:'stag',cls:'knight',skills:['HBR01','HBR02'],hp:132,attack:.58,h:116,r:38,intent:'뿔 돌진과 뿌리쐐기'},
 bat:{name:'들린 산박쥐',role:'storm',look:'bat',cls:'mage',skills:['HBT01','HBT02'],hp:70,attack:.38,h:66,r:28,flying:true,intent:'초음파와 반향'},
 crow:{name:'들린 까마귀',role:'bow',look:'crow',cls:'archer',skills:['HCW01','HCW02'],hp:88,attack:.47,h:80,r:33,flying:true,intent:'썩은깃과 검은깃비'},
 human:{name:'들린 사람',role:'bow',look:'human',cls:'archer',skills:['A01','A02'],hp:116,attack:.50,h:91,r:21,intent:'불규칙한 사격'},
 lantern:{name:'혼을 삼킨 등불',role:'fire',look:'lantern',cls:'occultist',skills:['HLN01','HLN02'],hp:94,attack:.53,h:92,r:25,flying:true,intent:'혼불과 혼무'},
 warden:{name:'들린 장승',role:'guard',look:'warden',cls:'knight',skills:['HWD01','HWD02'],hp:194,attack:.65,h:146,r:32,intent:'장승못과 터줏바람'},
 mourner:{name:'들린 상두꾼',role:'leaper',look:'mourner',cls:'knight',skills:['HMO01','HMO02'],hp:164,attack:.60,h:120,r:26,intent:'곡소리와 상여추'}
};
const THEMED=[
 ['hound','bat','crow','stag'],
 ['bat','crow','hound','stag'],
 ['hound','boar','crow','bat'],
 ['hound','human','boar','crow'],
 ['crow','stag','bat','lantern'],
 ['boar','crow','hound','bat'],
 ['human','hound','crow','stag'],
 ['hound','crow','mourner','warden'],
 ['hound','boar','crow','lantern'],
 ['stag','crow','hound','shade']
];
function selectInitialSpawns(spawns,cap){
 const groups=[];for(const sp of spawns){let g=groups.find(x=>x.id===sp.cluster);if(!g){g={id:sp.cluster,items:[]};groups.push(g);}g.items.push(sp);}const out=[];let depth=0;
 while(out.length<cap){let added=false;for(const g of groups){if(out.length>=cap)break;if(g.items[depth]){out.push(g.items[depth]);added=true;}}if(!added)break;depth++;}
 return out;
}
function top(b,x,reference,support){return G.HonroMapEngine.surfaceY(b.terrain,x,reference,support)?.y??b.height-150;}
function createEnemy(b,st,x,kind,index,y,absolute=false){const def=ARCHETYPES[kind]||ARCHETYPES.ghost,u=C.makeEnemy({role:def.role,x,y:y??top(b,x)},b.terrain,C.STAGES[st.id-1],index);const mult=C.DIFFICULTIES[b.difficulty]||C.DIFFICULTIES.normal;
 Object.assign(u,{id:'foe-'+index,name:def.name,honroType:def.look,h:def.h,r:def.r,x,y:y??top(b,x),awake:false,aggroUntil:0,group:Math.floor(x/(st.w/4)),fixed:!!def.flying,elite:st.id===1?false:index%11===10,cls:def.cls||u.cls,loadout:[...(def.skills||u.loadout)],intent:def.intent||u.intent,honroVariant:def.variant||kind});u.ranks={...u.ranks};for(const sid of u.loadout)u.ranks[sid]=Math.max(1,Math.min(4,1+Math.floor((st.level-1)/3)));
 if(def.flying&&!absolute)u.y-=170+(index%3)*85;
 u.armor=u.elite?.12:.04;u.spawnX=u.x;u.spawnY=u.y;u.honroDifficulty=b.difficulty;u.level=Math.floor(G.HonroProgression.plan(st.id).entryLevel);G.HonroProgression.tuneEnemy(st,u,kind);G.HonroProgression.enemyXP(b,u);return u;
}
function ally(b,st,id,role,x,y){
 const cls=role==='ritualist'||role==='healer'||role==='daoist'?'mage':role==='medium'?'occultist':'knight';
 const names={porter:'만석',guard:'노위',archer:'철언',healer:'단비',ritualist:'보각',daoist:'담허',medium:'소단',scout:'나루지기'};
 const loadout=cls==='knight'?['S01','S09']:cls==='occultist'?['O01','O06']:role==='daoist'?['M01','M06']:['M01'];
 const level=st.recruit===cls?G.HonroProgression.joinLevel(st):Math.max(1,Math.floor(G.HonroProgression.plan(st.id)?.entryLevel||st.level||1));
 const u=C.makeUnit(cls,2,x,y??top(b,x),{id,name:names[role]||'동맹',level,loadout:[...loadout]});
 const ref=G.HonroProgression.referenceStats(st),profile={guard:[1.34,.70,.18],porter:[.98,.48,.08],healer:[.82,.30,.06],ritualist:[.90,.44,.08],daoist:[1.06,.62,.09],medium:[1.00,.60,.08],scout:[.90,.48,.08]}[role]||[.90,.48,.08];
 let hp=Math.round(ref.hp*profile[0]),attack=ref.attack*profile[1],armor=profile[2];
 if(id==='npc-damheo'){hp=Math.round(hp*1.18);attack*=1.15;armor=.12;}
 if(id==='npc-hwigyeom'){hp=Math.round(hp*1.32);attack*=1.20;armor=.24;}
 Object.assign(u,{honroAlly:true,allyRole:role,honroType:'ally',role:'ally-'+role,fixed:false,hp,maxHp:hp,focus:160,maxFocus:160,attack,armor,r:20,h:90,acted:true,allyState:'follow',awake:true,group:-1,damageBy:{},spawnX:x,spawnY:y??top(b,x)});
 for(const sid of loadout)u.ranks[sid]=Math.max(1,Math.min(4,1+Math.floor((level-1)/2)));
 return u;
}
function midboss(b,st,id,name,kind,x,y){const u=createEnemy(b,st,x,kind,900+st.id,y,true);Object.assign(u,{id,name,awake:true,aggroUntil:999,group:-3,honroMidboss:true,elite:true});u.armor=Math.max(u.armor||0,.14);G.HonroProgression.tuneMidboss(b,st,u);u.spawnX=u.x;u.spawnY=u.y;return u;}

function build(st,profile,training,cls,skill,legacy){if(training){const b=legacy({...st,w:2400,h:1380},profile,true,cls,skill);b.honroRevision=20;return b;}
 const template=st.template||st.id,b=C.createBattle(1,clone(profile),'practice',{party:['archer'],distance:900});Object.assign(b,{stage:st.id,honroStage:st.id,honroRevision:20,mode:'campaign',width:st.w,height:st.h,vertical:template===7,terrain:[],units:[],projectiles:[],fields:[],drafts:[],waters:[],zones:[],decor:[],events:[],queue:[],round:1,side:0,phase:'aim',turnAge:0,resolveAge:0,reviewLeft:0,reviewDamage:{},heroDamage:0,damageDone:0,shots:0,kills:0,winnerReason:'',lastShots:{},heroes:clone(profile.heroes),honroMarkers:[],honroLandmarks:[],honroEvents:[],enemyLimit:st.active,sceneVersion:80,session:'honro-act1-'+Date.now(),startXP:Object.fromEntries(Object.entries(profile.heroes).map(([k,v])=>[k,v.xp]))});delete b.volley;delete b.summonTurn;
 b.honroState={flags:{},collected:[],hold:0,lastRound:1,rescued:false,rescuedCount:0,receivers:0,ledger:false,sodanCoop:false,coopHold:0,allyQueue:null,combatLog:[],respawns:0};b.wind=[7,-9,-11,9,18,13,6,-10,5,-7][st.id-1];
 const add=(id,x,y,w,h,mat='rock',extra={})=>{const hp=extra.hp??(mat==='wood'?400:99999),t=G.HonroMapEngine.solid(id,[[x,y],[x+w,y],[x+w,y+h],[x,y+h]],{mat,hp,maxHp:extra.maxHp??hp,route:true,...extra});b.terrain.push(t);return t;};
 const mark=(type,x,y,label,extra={})=>{const m={id:extra.id||'marker-'+b.honroMarkers.length,type,x,y,label,...extra};b.honroMarkers.push(m);return m;};const landmark=(kind,x,y,size=1)=>b.honroLandmarks.push({kind,x,y,size});const route=[];
 const map=G.HonroMapEngine.compile(st,G.HONRO_STAGE_MAPS[st.id]);b.terrain=map.terrain;b.honroLandmarks=map.landmarks;b.honroMapAnchors=map.anchors;b.honroMap=map.design;b.honroMapRevision=map.revision;b.honroRoute=map.routes;b.honroSurfaceZones=map.surfaceZones||[];b.honroDetailStats=map.detailStats||{};b.honroLayoutRevision=G.HonroLayouts.revision;b.vertical=b.height>b.width*1.08;
 const A=name=>map.anchors[name],AX=(name,fallback=0)=>A(name)?.x??fallback,AY=(name,fallback)=>A(name)?.y??fallback;
 if(st.id===2)b.honroEscortGoalX=AX('exit',3660);
 for(let i=0;i<map.sectors.length;i++){const sec=map.sectors[i];mark('sector',sec.x,sec.y,sec.label||st.sectors?.[i]||['들머리','길목','마당','너머'][i],{sector:i});if(i>0)mark('rest',sec.x-120,top(b,sec.x-120,sec.y),'불씨',{radius:170,sector:i});}
 const party=profile.recruited||['archer'];party.forEach((c,i)=>{let x=AX('start',330)+i*110,y=top(b,x,AY('start'));if(st.id===2){if(c==='archer'){x=AX('archerPerch',520);y=AY('archerPerch',top(b,x));}else{x=AX('procession',1920)-210+i*95;y=top(b,x,AY('procession'));}}const u=C.makeUnit(c,0,x,y,{id:'p-'+c,name:H.hero[c].name,loadout:[...profile.loadouts[c]],tune:profile.tuning[c]??.5,h:92,r:22});C.applyHero(u,b.heroes[c],true);u.h=92;u.spawnX=x;u.spawnY=y;u.acted=false;u.cooldowns={};b.units.push(u);});
 const initialSpawns=selectInitialSpawns(map.enemySpawns,G.HonroProgression.plan(st.id).initialEnemies);for(let i=0;i<initialSpawns.length;i++){const sp=initialSpawns[i],u=createEnemy(b,st,sp.x,sp.kind,i,sp.y,true);u.group=sp.group;u.honroCluster=sp.cluster;u.honroSpawnReason=sp.reason;u.honroTacticalReason=sp.tactical;u.honroEncounterRole=sp.role;b.units.push(u);}
 const objective=(name,x,y,hp,kind='bier')=>{const u=C.makeUnit('knight',2,x,y??top(b,x),{id:'objective',name,role:kind==='bier'?'caravan':'ward',hp,maxHp:hp,r:kind==='bier'?58:34,h:110,fixed:true,loadout:[]});u.honroType=kind;u.honroCivilian=true;b.units.push(u);return u;};const seal=(id,x,y,hp=430)=>add(id,x-42,(y??top(b,x))-148,84,148,'stone',{honroSeal:true,device:'ward',hp,maxHp:hp,route:false,oneWay:true});const evt=(id,when,action,text,lines=[])=>b.honroEvents.push({id,when,action,text,lines,once:true});const wave=(n,x,kind)=>({type:'spawn',n,x,kind});const neutral=(role,x)=>({type:'ally',role,x});
 if(st.id===1){mark('exit',AX('exit',st.w-180),AY('exit',top(b,st.w-180)),'고개 끝');evt('cart',{progress:1250},wave(2,AX('cart',2100)+420,'hound'),'버려진 수레 뒤에서 들린 산개가 튀어나온다.',[['설오','사람이 없는데도 짐승 눈이 저 모양이군. 들린 건가.']]);evt('more',{progress:3200},null,'수풀 위 검은 새들이 설오 쪽으로 한꺼번에 고개를 돌린다.',[['설오','하루에 둘도 아니고… 소문보다 심하군.']]);const wc=ally(b,st,'npc-woodcutter','scout',AX('woodcutter',3550),AY('woodcutter'));wc.name='나무꾼';wc.honroCivilian=true;wc.fixed=true;b.units.push(wc);evt('witness',{progress:AX('woodcutter',3550)-100},null,'길가 바위 뒤에 숨어 있던 나무꾼이 모습을 드러낸다.',[['나무꾼','죽였소? 저것들 말이오. 어젯밤부터 계속 움직였소.'],['설오','처음부터 저랬습니까?'],['나무꾼','처음엔 말 한 마리였소. 말이 쓰러지니까 옆에 있던 짐승이 또 달려들었고.'],['설오','어디서부터 그랬는지 보셨습니까?'],['나무꾼','모르오. 시작되기 전에 저 위에서 종소리를 한 번 들었소.'],['설오','절이 있습니까?'],['나무꾼','없소. 이 산엔 절 같은 건 없소.']]);evt('ridge',{progress:AX('ridge',4440)-260},null,'능선 끝에서 들린 숫사슴들이 길을 가로막는다.',[['설오','저 아래… 상여가 멈췄군. 뒤에 붙은 것도 같은 것들인가.']]);
 }else if(st.id===2){const x=AX('procession',1920),y=AY('procession',top(b,x));objective('홍만의 상여',x,y,1700);const porter=ally(b,st,'ally-bokman','porter',x-120,y),guard=ally(b,st,'ally-baeksan','guard',x+120,y),dao=ally(b,st,'npc-damheo','daoist',x+235,y),yeon=ally(b,st,'npc-yeonsil','healer',x+330,y);porter.name='복만';guard.name='백산';dao.name='담허';yeon.name='연실';yeon.honroCivilian=true;b.units.push(porter,guard,dao,yeon);evt('procession-seen',{progress:AX('procession',1920)},null,'상여가 협곡의 가장 낮은 길을 지난다.',[['담허','활 든 양반. 우리 편이면 왼쪽부터 좀 치워주시게.'],['설오','왜 왼쪽입니까?'],['담허','오른쪽 놈은 아직 몸을 못 찾았거든.']]);evt('road-pressure',{progress:AX('leftBasin',2280)-80},wave(1,AX('leftBasin',2280),'hound'),'들린 산개들이 상여 앞으로 내려온다.');evt('sniper-seen',{progress:AX('leftBasin',2280)+120},{type:'sniperAmbush',n:1},'까마귀 떼가 능선의 설오를 향한다.',[['설오','놈들이 내 자리를 알아챘다.'],['담허','아래는 내가 붙들지. 자네는 하늘부터 비우게.']]);evt('right-cliff',{progress:AX('rightBasin',3150)-250},{type:'wind',value:18},'맞은편 절벽에 들린 짐승들이 모습을 드러낸다.');evt('last-flight',{progress:AX('exit',3660)-180},null,'출구 앞에서 마지막 무리가 상여를 덮친다.');
 }else if(st.id===3){mark('ledger',AX('ledger',6540),AY('ledger',top(b,AX('ledger',6540))),'홍만의 장부',{id:'ledger',action:'ledger'});const hw3=ally(b,st,'npc-hwigyeom','guard',AX('ferry',2550)-260,AY('ferry'));hw3.name='휘겸';b.units.push(hw3);const mb3=midboss(b,st,'midboss-stage3','침수된 나루장승','warden',AX('mudflat',3700)+260,AY('mudflat'));b.units.push(mb3);evt('midboss-stage3-seen',{progress:AX('ferry',2550)+180},null,'물에 잠긴 장승이 나루 바닥에서 몸을 일으킨다.',[['휘겸','저 장승은 원래 배를 지키던 것이오. 안에 든 것만 떼어내시오.']]);evt('dock-beasts',{progress:AX('ferry',2680)},wave(1,AX('mudflat',3700),'boar'),'나루 아래에서 들린 짐승들이 올라온다.');evt('transfer',{progress:AX('cargo',5480)},null,'부서진 그릇에서 빠져나온 기척을 따라 까마귀 떼가 들끓는다.',[['설오','하나를 쓰러뜨리면 옆의 놈이 바로 달려듭니다.'],['담허','몸만 바꿔 붙는 듯하군. 장부부터 찾고 나가세.']]);
 }else if(st.id===4){objective('피란문',AX('gate',1050),AY('gate'),3600,'gate');const hw=ally(b,st,'npc-hwigyeom','guard',AX('gate',1050)+230,AY('gate')),ch=ally(b,st,'npc-chunrye','healer',AX('gate',1050)-260,AY('gate'));hw.name='휘겸';ch.name='춘례';ch.honroCivilian=true;b.units.push(hw,ch);for(const [i,r,k,n]of[[0,3,'hound',2],[1,7,'crow',2]])evt('siege-'+i,{round:r},wave(n,[AX('leftLane',1800),AX('rightLane',3780)][i],k),['산개들이 피난문으로 몰린다.','마지막 피란 행렬을 노린 까마귀 떼가 동쪽에서 내려온다.'][i]);
 }else if(st.id===5){seal('cliff-cleat',AX('cleat',3190),AY('cleat'),520);const hw=ally(b,st,'npc-hwigyeom','guard',AX('basin',2150),AY('basin'));hw.name='휘겸';b.units.push(hw);mark('receiver',AX('receiver',1510),AY('receiver'),'담허의 받이진',{id:'receiver-5',action:'ritual',requiredClass:'mage'});evt('lower-beasts',{progress:AX('basin',2150)-150},wave(3,AX('waterfallFoot',3000),'stag'),'계곡 아래에서 들린 사슴들이 올라온다.');evt('bell',{broken:1},null,'절벽의 고리쇠가 깨지며 먼 곳에서 작은 방울 소리가 한 번 난다.',[['설오','들으셨습니까?'],['담허','들었네. 절 종은 아니야. 방울이군.']]);
 }else if(st.id===6){const x=AX('rescue',4050);objective('부상자 운반대',x,AY('rescue',top(b,x)),1850,'civilian');mark('exit',AX('exit',6300),AY('exit',top(b,AX('exit',6300))),'북문 쉼터');b.units.push(ally(b,st,'ally-ropeguard','guard',AX('start',330)+330,AY('start')));const mb6=midboss(b,st,'midboss-stage6','부러진 교각귀','warden',AX('pillarNest',3100)+80,AY('pillarNest'));b.units.push(mb6);evt('midboss-stage6-seen',{progress:AX('westHead',1450)+350},null,'부러진 교각에 박힌 장승이 뿌리째 돌아선다.',[['휘겸','저걸 쓰러뜨려야 운반대가 교각 아래를 지나갈 수 있소.']]);evt('bridge-crows',{progress:AX('westHead',1450)},wave(2,AX('pillarNest',3100)-280,'crow'),'까마귀 떼가 나무다리 위로 내려온다.');evt('bridge-boars',{progress:AX('pillarNest',3100)},wave(2,AX('rescue',4050)+650,'boar'),'들린 멧돼지들이 다리 기둥을 들이받는다.');evt('pursuit',{rescued:true},wave(2,AX('eastHead',5200),'hound'),'부상자를 옮기자 뒤쪽 산개들이 따라붙는다.');
 }else if(st.id===7){for(let i=0;i<3;i++){const key=['resident1','resident2','resident3'][i],x=AX(key),y=AY(key),u=ally(b,st,'resident-'+(i+1),'healer',x,y);u.name=['덕수','월이','칠복'][i];u.honroCivilian=true;u.fixed=true;u.hp=u.maxHp=600;b.units.push(u);mark('resident',x,y-80,u.name,{id:'resident-marker-'+(i+1),action:'rescue',target:u.id});}evt('yard-hounds',{progress:AX('resident1',1180)},wave(2,AX('knot1',1750),'hound'),'마당 아래에서 들린 산개들이 올라온다.');evt('upper-crows',{progress:AX('resident2',3000)-150},wave(2,AX('hollow',1200),'crow'),'지붕 위 까마귀 떼가 구조 중인 사람을 노린다.');
 }else if(st.id===8){[AX('knotWest',3100),AX('knotEast',5400)].forEach((x,i)=>seal('bier-knot-'+i,x,AY(i?'knotEast':'knotWest'),480));const bx=AX('bier',6900);const boss=C.makeUnit('knight',1,bx,AY('bier',top(b,bx)),{id:'boss',name:'빈 상여',role:'golem',honroType:'bier',hp:2500,maxHp:2500,attack:1.0,armor:.08,r:70,h:150,loadout:['HMO01','HMO02'],fixed:false,awake:true,aggroUntil:999,group:0});boss.combatBaseHp=2500/(C.DIFFICULTIES[b.difficulty]?.hp||1);boss.combatBaseAttack=1/(C.DIFFICULTIES[b.difficulty]?.damage||1);G.HonroProgression.tuneBoss(b,st,boss);boss.honroMidboss=true;b.units.push(boss);evt('bier-side',{progress:AX('store',1750)},wave(1,AX('courtyard',4250),'hound'),'빈 상여를 따라 들린 산개들이 창고 밖으로 튀어나온다.');evt('bier-crows',{broken:1},wave(1,AX('bier',6900)-450,'crow'),'첫 결박이 끊기자 까마귀 떼가 상여 위로 내려앉는다.');
 }else if(st.id===9){mark('receiver',AX('receiverWest',850),AY('receiverWest'),'서쪽 받이진',{id:'receiver-west',action:'receiver'});mark('receiver',AX('receiverEast',2670),AY('receiverEast'),'동쪽 받이진',{id:'receiver-east',action:'receiver'});const sx=AX('sodan',3180),sod=ally(b,st,'npc-sodan','medium',sx,AY('sodan',top(b,sx)));sod.name='소단';sod.honroCivilian=true;sod.honroAlly=false;sod.fixed=true;b.units.push(sod);evt('evac-beasts',{progress:AX('receiverWest',850)},wave(3,AX('well',1700),'hound'),'대피로 뒤쪽에 들린 짐승들이 나타난다.');evt('evac-crows',{progress:AX('well',1700)},wave(3,AX('receiverEast',2670),'crow'),'윗마당에서 까마귀 떼가 내려온다.');
 }else if(st.id===10){mark('receiver',AX('receiverWest',1050),AY('receiverWest'),'서쪽 받이진',{id:'receiver-west',action:'receiver'});mark('receiver',AX('receiverEast',4200),AY('receiverEast'),'동쪽 받이진',{id:'receiver-east',action:'receiver'});const rx=AX('ritual',2600);const boss=C.makeUnit('occultist',1,rx,AY('ritual',top(b,rx)),{id:'boss',name:'소단',role:'medium',honroType:'human',honroCivilian:true,hp:3600,maxHp:3600,attack:2.2,armor:.14,r:22,h:96,loadout:['O01','O09','O10'],fixed:false,awake:true,aggroUntil:999,group:0});boss.ranks={O01:5,O09:5,O10:5};boss.honroFinalBoss=true;G.HonroProgression.tuneBoss(b,st,boss);b.units.push(boss);evt('sodan-hounds',{progress:AX('receiverWest',1050)},wave(2,AX('westHall',1650),'hound'),'윗마당 밖에서 들린 짐승들이 몰려든다.');}
 b.active=b.units.find(u=>u.side===0&&!u.summoned).id;b.honroActiveLimit=st.active;b.honroState.carriagePauseUntilRound=0;G.HonroEncounters.configure(b);b.honroCounters={initialEnemies:b.units.filter(u=>u.side===1).length,allyActions:0,spawned:0};G.HonroProgression.initialize(b,profile);return b;
}
G.HonroWorld={build,top,createEnemy,ally,archetypes:ARCHETYPES};
})(globalThis);
