from pathlib import Path
p=Path('/mnt/data/HONRO_MAP_WORKSHOP_V2/src/app.js')
s=p.read_text()

def replace_func(name,new_body):
    global s
    marker=f'function {name}('
    a=s.index(marker)
    b=s.find('\nfunction ', a+len(marker))
    if b<0:
        b=s.find('\naddEventListener(', a+len(marker))
    if b<0:
        raise RuntimeError('next function not found '+name)
    s=s[:a]+new_body.rstrip()+s[b:]

# helpers after COLORS
needle="const COLORS={soil:'#514c40',grass:'#385334',moss:'#475f44',rock:'#575d5a',scree:'#4b4d46',mud:'#443a32',water:'#426975',charred:'#332f2b',stone:'#66665e',wood:'#574b37'};\n"
helpers=r'''const COLORS={soil:'#514c40',grass:'#385334',moss:'#475f44',rock:'#575d5a',scree:'#4b4d46',mud:'#443a32',water:'#426975',charred:'#332f2b',stone:'#66665e',wood:'#574b37'};

// Geometry helpers shared by human UI and Agent API.
function pointLineDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,n=dx*dx+dy*dy;if(!n)return dist(p,a);const t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/n,0,1),q={x:a.x+dx*t,y:a.y+dy*t};return dist(p,q)}
function rdpOpen(points,epsilon=0){if(!epsilon||points.length<=2)return points.map(p=>({...p}));let max=0,index=-1;for(let i=1;i<points.length-1;i++){const d=pointLineDistance(points[i],points[0],points.at(-1));if(d>max){max=d;index=i}}if(max<=epsilon||index<0)return[{...points[0]},{...points.at(-1)}];const l=rdpOpen(points.slice(0,index+1),epsilon),r=rdpOpen(points.slice(index),epsilon);return[...l.slice(0,-1),...r]}
function rdpClosed(points,epsilon=0){if(!epsilon||points.length<=3)return points.map(p=>({...p}));let pivot=1,max=0;for(let i=1;i<points.length;i++){const d=dist(points[0],points[i]);if(d>max){max=d;pivot=i}}const a=rdpOpen(points.slice(0,pivot+1),epsilon),b=rdpOpen([...points.slice(pivot),points[0]],epsilon);const out=[...a.slice(0,-1),...b.slice(0,-1)];return out.length>=3?out:points.slice(0,3).map(p=>({...p}))}
function pointInPoly(p,pts){let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const a=pts[i],b=pts[j];if(((a.y>p.y)!==(b.y>p.y))&&(p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y||1e-9)+a.x))inside=!inside}return inside}
function gridSnapPoint(p,size=project?.settings?.grid||40){const g=Math.max(2,+size||40);return{x:Math.round(p.x/g)*g,y:Math.round(p.y/g)*g}}
function terrainEditPoints(t){return t.type==='solid'?(t.points||[]):(t.control||[])}
function syncAssetCollision(a){if(a.collision.length)a.collision=deep(a.visual.filter(s=>s.type==='polygon').map(s=>s.points))}
function polylineNodeCount(st){return st.terrains.reduce((n,t)=>n+deriveTerrain(t).length,0)}
function assetNodeCount(a){return a.visual.reduce((n,sh)=>n+(sh.points?.length||0),0)}
function sceneStats(st){let elementNodes=0;for(const e of st.elements){const a=project.library.find(x=>x.id===e.assetId);if(a)elementNodes+=assetNodeCount(a)}return{terrainControl:st.terrains.reduce((n,t)=>n+terrainEditPoints(t).length,0),terrainDerived:polylineNodeCount(st),elementNodes,elementCount:st.elements.length,materialCount:st.materials.length,total:polylineNodeCount(st)+elementNodes}}
function visibleRect(canvas,view,margin=100){const w=canvas.clientWidth/view.zoom,h=canvas.clientHeight/view.zoom;return{left:view.x-w/2-margin,right:view.x+w/2+margin,top:view.y-h/2-margin,bottom:view.y+h/2+margin}}
function elementVisible(a,inst,vr){const b=assetBounds(a),cx=inst.x+(b.x+b.w/2)*inst.scale,cy=inst.y+(b.y+b.h/2)*inst.scale,r=Math.hypot(b.w,b.h)*Math.abs(inst.scale||1)*.65+30;return !(cx+r<vr.left||cx-r>vr.right||cy+r<vr.top||cy-r>vr.bottom)}
'''
assert needle in s
s=s.replace(needle,helpers,1)

# default project and runtime state
s=s.replace("settings:{grid:40,snap:true,autosave:true}","settings:{grid:40,snap:true,autosave:true,adaptiveLOD:true}")
s=s.replace("let project=loadAutosave()||newProject(), currentTab='stage', selectedAssetId=project.library[0]?.id, selected=null, selectedNode=-1, tool='select', materialKind='grass', placementAssetId='rock_large', unitKind='hound', eventKind='trigger', previewProject=null;\nlet history=[],future=[],stageView={x:0,y:0,zoom:1},elementView={x:0,y:0,zoom:1},playState=null,drawStroke=[],paintStroke=[],scatterStamp=0;",
"let project=loadAutosave()||newProject(), currentTab='stage', selectedAssetId=project.library[0]?.id, selected=null, selectedNode=-1, selectedShapeIndex=-1, tool='select', materialKind='grass', placementAssetId='rock_large', unitKind='hound', eventKind='trigger', previewProject=null;\nlet history=[],future=[],stageView={x:0,y:0,zoom:1},elementView={x:0,y:0,zoom:1},playState=null,drawStroke=[],paintStroke=[],solidDraft=[],elementPolygonDraft=[],scatterStamp=0;")

replace_func('loadAutosave',r'''function loadAutosave(){try{const x=JSON.parse(localStorage.getItem('honro-workshop-v1'));if(!x?.version)return null;x.settings={grid:40,snap:true,autosave:true,adaptiveLOD:true,...x.settings};for(const st of x.stages||[])for(const t of st.terrains||[]){t.detail={spacing:18,roughness:0,seed:1,optimizeEpsilon:0,...t.detail}}return x}catch(e){return null}}''')

# terrain derivation + surface functions
replace_func('deriveTerrain',r'''function deriveTerrain(t){
 if(t.type==='solid')return (t.points||[]).map(p=>({...p}));
 if(t.type!=='ground'&&t.type!=='platform')return (t.points||[]).map(p=>({...p}));
 const c=[...(t.control||[])].sort((a,b)=>a.x-b.x);if(c.length<2)return c;
 const spacing=Math.max(6,t.detail?.spacing||24),rough=t.detail?.roughness||0,eps=Math.max(0,+t.detail?.optimizeEpsilon||0);
 const sig=`${spacing}|${rough}|${t.detail?.seed||1}|${eps}|`+c.map(p=>`${round(p.x,2)},${round(p.y,2)}`).join(';');
 if(t.__derivedCache?.sig===sig)return t.__derivedCache.points;
 const r=seeded(t.detail?.seed||1),raw=[];for(let i=0;i<c.length-1;i++){const a=c[i],b=c[i+1],n=Math.max(1,Math.ceil(Math.abs(b.x-a.x)/spacing));for(let k=0;k<n;k++){const u=k/n,sm=u*u*(3-2*u),edge=Math.sin(Math.PI*u),micro=(r()*2-1)*rough*edge+Math.sin((a.x+k*37)*.017)*rough*.26;raw.push({x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*sm+micro})}}raw.push({...c.at(-1)});
 const points=eps?rdpOpen(raw,eps):raw;try{Object.defineProperty(t,'__derivedCache',{value:{sig,points},writable:true,configurable:true,enumerable:false})}catch{}return points
}''')

# insert terrain surface helpers before sampleTerrainY replacement
replace_func('sampleTerrainY',r'''function terrainSurfaceYs(t,x){
 if(t.type!=='solid'){const pts=deriveTerrain(t),ys=[];for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1];if(x>=Math.min(a.x,b.x)-1e-6&&x<=Math.max(a.x,b.x)+1e-6&&Math.abs(b.x-a.x)>1e-6){const u=(x-a.x)/(b.x-a.x);ys.push(a.y+(b.y-a.y)*u)}}return ys}
 const pts=t.points||[],ys=[];for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length];if((x>=Math.min(a.x,b.x)-1e-6&&x<=Math.max(a.x,b.x)+1e-6)&&Math.abs(b.x-a.x)>1e-6){const u=(x-a.x)/(b.x-a.x);if(u>=-1e-6&&u<=1+1e-6)ys.push(a.y+(b.y-a.y)*u)}}return [...new Set(ys.map(v=>round(v,4)))].sort((a,b)=>a-b)
}
function sampleTerrainY(t,x,reference=Infinity){const ys=terrainSurfaceYs(t,x);if(!ys.length)return null;if(Number.isFinite(reference))return ys.reduce((a,b)=>Math.abs(a-reference)<=Math.abs(b-reference)?a:b);return Math.min(...ys)}''')

replace_func('nearestSurface',r'''function nearestSurface(st,x,y=Infinity){let best=null;for(const t of st.terrains){for(const sy of terrainSurfaceYs(t,x)){const d=Number.isFinite(y)?Math.abs(sy-y):sy;if(!best||d<best.d)best={terrain:t,y:sy,d}}}return best}''')

replace_func('materialPolygon',r'''function materialPolygon(st,m){const t=st.terrains.find(x=>x.id===m.terrainId);if(!t||t.type==='solid')return[];const pts=deriveTerrain(t).filter(p=>p.x>=Math.min(m.x1,m.x2)&&p.x<=Math.max(m.x1,m.x2));if(pts.length<2)return[];const depth=m.depth||24;if(m.kind==='water'){const level=Math.min(pts[0].y,pts.at(-1).y)+Math.min(34,depth);return[{x:pts[0].x,y:level},{x:pts.at(-1).x,y:level},...pts.slice().reverse()]}return[...pts,...pts.slice().reverse().map(p=>({x:p.x,y:p.y+depth}))]}''')

replace_func('snapElement',r'''function snapElement(st,inst){if(!inst.snap)return inst;const sf=nearestSurface(st,inst.x,inst.y);if(sf)inst.y=sf.y;return inst}''')

# renderAll conditional + preview only on panel rebuild
replace_func('renderAll',r'''function renderAll(){renderToolbars();renderPanels();if(currentTab==='stage')renderStage();else if(currentTab==='element')renderElement();else renderPlay();updateTop();requestAnimationFrame(renderAssetPreviews)}''')

# Stage inspector UI
replace_func('stageInspectorHtml',r'''function stageInspectorHtml(st){const stats=sceneStats(st);let body=`<div class="panel-section"><div class="panel-title"><span>STAGE</span></div><div class="row"><label>이름</label><input id="stageName" class="field" value="${esc(st.name)}"></div><div class="split"><div><label class="node-label">Width</label><input id="stageW" class="field num" type="number" value="${st.width}"></div><div><label class="node-label">Height</label><input id="stageH" class="field num" type="number" value="${st.height}"></div></div><div class="row"><label>Backdrop</label><select id="stageBackdrop" class="field">${['forest','ravine','river','village','shrine','bridge'].map(x=>`<option ${st.backdrop===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="split"><div><label class="node-label">Grid</label><input id="gridSize" class="field num" type="number" min="4" max="256" value="${project.settings.grid||40}"></div><div><label class="node-label">Adaptive LOD</label><div style="padding:6px 0"><input id="adaptiveLOD" type="checkbox" ${project.settings.adaptiveLOD!==false?'checked':''}> zoom-out 간소화</div></div></div></div>`;
 body+=`<div class="panel-section"><div class="panel-title"><span>PERFORMANCE</span></div><div class="perf-grid"><span>Terrain</span><strong>${stats.terrainDerived}</strong><span>Element vector</span><strong>${stats.elementNodes}</strong><span>Total nodes</span><strong class="${stats.total>6000?'warn':'good'}">${stats.total}</strong></div><div class="row"><label>LOD ε</label><input id="stageOptimizeEps" class="field" type="number" min="0" max="80" step="1" value="4"><button id="optimizeStage" class="btn sm">전체 적용</button></div><div class="muted node-label">ε가 클수록 export/render node가 줄어듭니다. 원본 control은 유지됩니다.</div></div>`;
 if(!selected)return body+`<div class="panel-section"><div class="panel-title"><span>TOOL</span></div>${toolHelp()}</div><div class="panel-section"><div class="panel-title"><span>MATERIAL</span></div>${materialGrid()}</div>`;
 const o=getSelected(st);if(!o)return body;
 body+=`<div class="panel-section"><div class="panel-title"><span>SELECTED · ${selected.type.toUpperCase()}</span><button id="deleteSelected" class="btn sm danger">삭제</button></div><div class="row"><label>ID</label><input class="field" value="${esc(o.id)}" disabled></div>`;
 if(selected.type==='terrain'){
  const raw=(o.type==='solid'?(o.points||[]):(()=>{const old=o.detail?.optimizeEpsilon;o.detail.optimizeEpsilon=0;const p=deriveTerrain(o).length;o.detail.optimizeEpsilon=old;delete o.__derivedCache;return Array(p).fill(0)})()).length,optimized=deriveTerrain(o).length;
  body+=`<div class="row"><label>이름</label><input id="objName" class="field" value="${esc(o.name||o.id)}"></div><div class="row"><label>Type</label><strong>${o.type}</strong></div><div class="row"><label>Material</label><select id="terrainBase" class="field">${Object.keys(COLORS).map(x=>`<option ${o.baseMaterial===x?'selected':''}>${x}</option>`).join('')}</select></div>`;
  if(o.type!=='solid')body+=`<div class="split"><div><label class="node-label">Generated spacing</label><input id="terrainSpacing" type="number" class="field" value="${o.detail?.spacing||20}"></div><div><label class="node-label">Roughness</label><input id="terrainRough" type="number" class="field" value="${o.detail?.roughness||0}"></div></div><div class="row"><label>Optimize ε</label><input id="terrainOptimize" type="number" class="field" min="0" max="80" step="1" value="${o.detail?.optimizeEpsilon||0}"></div><div class="row"><button id="roughenBtn" class="btn sm">Detail randomize</button><button id="smoothBtn" class="btn sm">Smooth controls</button></div><div class="muted node-label">Control ${o.control.length} · Raw ${raw} → Optimized ${optimized}</div>`;
  else body+=`<div class="muted node-label">Closed solid polygon · ${o.points?.length||0} vertices · overhang/cave 지원</div>`;
 }
 if(selected.type==='element'){const a=project.library.find(x=>x.id===o.assetId);body+=`<div class="row"><label>Asset</label><div>${esc(a?.name||o.assetId)}</div></div><div class="split"><div><label class="node-label">Scale</label><input id="elScale" class="field" type="number" step=".05" value="${o.scale}"></div><div><label class="node-label">Rotation°</label><input id="elRot" class="field" type="number" value="${round(o.rotation*180/Math.PI)}"></div></div><div class="row"><label>Layer</label><select id="elLayer" class="field">${st.layers.map(l=>`<option value="${l.id}" ${o.layer===l.id?'selected':''}>${esc(l.name)}</option>`).join('')}</select></div><div class="row"><label>Surface snap</label><input id="elSnap" type="checkbox" ${o.snap?'checked':''}></div>`}
 if(selected.type==='unit'){body+=`<div class="row"><label>종류</label><select id="unitType" class="field">${unitTypes().map(x=>`<option ${o.kind===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="row"><label>Team</label><select id="unitTeam" class="field">${['player','ally','enemy','npc'].map(x=>`<option ${o.team===x?'selected':''}>${x}</option>`).join('')}</select></div>`}
 if(selected.type==='event'){body+=`<div class="row"><label>Type</label><select id="eventType" class="field">${['trigger','objective','interaction','spawn','dialogue'].map(x=>`<option ${o.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="row"><label>Label</label><input id="eventLabel" class="field" value="${esc(o.label||'')}"></div>`}
 return body+`</div><div class="panel-section"><div class="panel-title"><span>MATERIAL</span></div>${materialGrid()}</div>`}''')

replace_func('toolHelp',r'''function toolHelp(){const h={select:'클릭 선택 · 드래그 이동 · Terrain/solid node 직접 편집 · Ctrl+드래그: Grid snap',terrain:'마우스로 지표면을 그리면 고밀도 ground로 변환',solid:'클릭으로 닫힌 polygon 점 추가 · 더블클릭/Enter로 완료 · 동굴/overhang 제작',material:'지면 위를 드래그하여 material 구간 paint',place:'Library 요소 배치 후 자동으로 선택모드 · surface snap',scatter:'브러시 영역에 요소를 자연스럽게 scatter',unit:'아군/적/NPC 배치',event:'Trigger/Objective/Event marker 배치',pan:'드래그로 카메라 이동'};return`<div class="muted" style="font-size:10px;line-height:1.7">${h[tool]||''}</div>`}''')

replace_func('bindStageInspector',r'''function bindStageInspector(st){
 const change=(id,fn)=>{const e=$('#'+id);if(e)e.onchange=()=>commit('속성 변경',()=>fn(realStage(),e))};change('stageName',(s,e)=>s.name=e.value);change('stageW',(s,e)=>s.width=Math.max(800,+e.value||s.width));change('stageH',(s,e)=>s.height=Math.max(600,+e.value||s.height));change('stageBackdrop',(s,e)=>s.backdrop=e.value);change('objName',(s,e)=>{const o=getSelected(s);o.name=e.value});change('terrainBase',(s,e)=>getSelected(s).baseMaterial=e.value);change('terrainSpacing',(s,e)=>getSelected(s).detail.spacing=clamp(+e.value||20,6,180));change('terrainRough',(s,e)=>getSelected(s).detail.roughness=clamp(+e.value||0,0,80));change('terrainOptimize',(s,e)=>getSelected(s).detail.optimizeEpsilon=clamp(+e.value||0,0,100));change('elScale',(s,e)=>getSelected(s).scale=clamp(+e.value||1,.1,8));change('elRot',(s,e)=>getSelected(s).rotation=(+e.value||0)*Math.PI/180);change('elLayer',(s,e)=>getSelected(s).layer=e.value);change('gridSize',(s,e)=>project.settings.grid=clamp(+e.value||40,4,256));
 const lod=$('#adaptiveLOD');if(lod)lod.onchange=()=>commit('Adaptive LOD 변경',p=>p.settings.adaptiveLOD=lod.checked);const all=$('#optimizeStage');if(all)all.onclick=()=>{const eps=clamp(+$('#stageOptimizeEps').value||0,0,100);commit(`Stage terrain LOD ε=${eps}`,()=>{for(const t of realStage().terrains)if(t.type!=='solid'){t.detail??={};t.detail.optimizeEpsilon=eps;delete t.__derivedCache}})};
 const snap=$('#elSnap');if(snap)snap.onchange=()=>commit('Snap 변경',()=>getSelected(realStage()).snap=snap.checked);change('unitType',(s,e)=>getSelected(s).kind=e.value);change('unitTeam',(s,e)=>getSelected(s).team=e.value);change('eventType',(s,e)=>getSelected(s).type=e.value);change('eventLabel',(s,e)=>getSelected(s).label=e.value);
 const d=$('#deleteSelected');if(d)d.onclick=deleteSelection;const r=$('#roughenBtn');if(r)r.onclick=()=>commit('Terrain detail randomize',()=>{const o=getSelected(realStage());o.detail.seed=(o.detail.seed||1)+17;delete o.__derivedCache});const sm=$('#smoothBtn');if(sm)sm.onclick=()=>commit('Terrain controls smooth',()=>{const o=getSelected(realStage());o.control=o.control.map((p,i,a)=>i&&i<a.length-1?{x:p.x,y:(a[i-1].y+p.y*2+a[i+1].y)/4}:p);delete o.__derivedCache});$$('[data-mat]').forEach(b=>b.onclick=()=>{materialKind=b.dataset.mat;tool='material';renderAll()});const br=$('#brushRange');if(br){br.oninput=()=>$('#brushVal').textContent=br.value}
}''')

# element panels
replace_func('renderElementPanels',r'''function renderElementPanels(){const a=activeAsset(),nodeCount=assetNodeCount(a);dom.left.innerHTML=`<div class="panel-scroll"><div class="panel-section"><div class="panel-title"><span>ELEMENT LIBRARY</span><button id="newAsset" class="btn sm">새 요소</button></div><div class="asset-grid">${project.library.map(x=>`<button class="asset-card ${x.id===a.id?'active':''}" data-edit-asset="${x.id}"><div class="asset-preview"><canvas data-asset-preview="${x.id}"></canvas></div><div class="asset-name">${esc(x.name)}</div><div class="asset-cat">${x.category}</div></button>`).join('')}</div></div></div>`;$$('[data-edit-asset]').forEach(b=>b.onclick=()=>{selectedAssetId=b.dataset.editAsset;selectedNode=-1;selectedShapeIndex=-1;renderAll()});$('#newAsset').onclick=()=>commit('요소 생성',p=>{const a=asset(uid('custom'),'새 요소','custom',[shape(regularPoly(6,60,40,Math.floor(Math.random()*999)),'#5b625e','#222d30')],{collision:true,tags:['custom']});p.library.push(a);selectedAssetId=a.id;selectedShapeIndex=0});
 dom.right.innerHTML=`<div class="panel-scroll"><div class="panel-section"><div class="panel-title"><span>ELEMENT</span><div><button id="dupAsset" class="btn sm">복제</button> <button id="delAsset" class="btn sm danger">삭제</button></div></div><div class="row"><label>이름</label><input id="assetName" class="field" value="${esc(a.name)}"></div><div class="row"><label>Category</label><input id="assetCat" class="field" value="${esc(a.category)}"></div><div class="row"><label>Collision</label><input id="assetCollision" type="checkbox" ${a.collision.length?'checked':''}></div><div class="row"><label>Breakable</label><input id="assetBreak" type="checkbox" ${a.breakable?'checked':''}></div><div class="row"><label>One-way</label><input id="assetOneWay" type="checkbox" ${a.oneWay?'checked':''}></div><div class="row"><button id="randomizeAsset" class="btn">모양 Randomize</button><button id="addPolygon" class="btn">+ Polygon</button></div></div>
 <div class="panel-section"><div class="panel-title"><span>OPTIMIZE</span></div><div class="row"><label>Nodes</label><strong>${nodeCount}</strong></div><div class="row"><label>Threshold ε</label><input id="assetOptimizeEps" type="number" class="field" min="0" max="60" step=".5" value="2"><button id="optimizeAsset" class="btn sm">간소화</button></div><div class="muted node-label">RDP 기반. Undo 가능. 복잡한 바위/나무는 1~3부터 권장.</div></div>
 <div class="panel-section"><div class="panel-title"><span>GRID</span></div><div class="row"><label>Grid size</label><input id="elementGridSize" class="field" type="number" min="4" max="256" value="${project.settings.grid||40}"></div><div class="muted node-label">Ctrl+vertex/shape drag = grid snap</div></div>
 <div class="panel-section"><div class="panel-title"><span>ANCHOR</span></div><div class="muted node-label">(${round(a.anchor.x)}, ${round(a.anchor.y)}) · Anchor tool로 클릭</div></div><div class="panel-section"><div class="panel-title"><span>SOCKETS</span><button id="addSocket" class="btn sm">추가</button></div><div class="socket-list">${a.sockets.length?a.sockets.map(s=>`<div class="socket-item"><span>◇</span><span style="flex:1">${esc(s.id)}</span><span>${round(s.x)}, ${round(s.y)}</span></div>`).join(''):'<div class="empty">socket 없음</div>'}</div></div><div class="panel-section"><div class="panel-title"><span>VECTOR</span></div><div class="muted" style="font-size:10px;line-height:1.6">Point: vertex drag · Polygon: 새 polygon 작성<br>빈 polygon 내부 클릭: shape 선택/이동<br>더블클릭: edge vertex 추가 · Ctrl+드래그: grid snap</div></div></div>`;
 $('#assetName').onchange=e=>commit('요소 이름 변경',()=>activeAsset().name=e.target.value);$('#assetCat').onchange=e=>commit('카테고리 변경',()=>activeAsset().category=e.target.value);$('#assetCollision').onchange=e=>commit('Collision 변경',()=>{const a=activeAsset();a.collision=e.target.checked?deep(a.visual.map(s=>s.points)):[]});$('#assetBreak').onchange=e=>commit('Breakable 변경',()=>activeAsset().breakable=e.target.checked);$('#assetOneWay').onchange=e=>commit('One-way 변경',()=>activeAsset().oneWay=e.target.checked);$('#dupAsset').onclick=()=>commit('요소 복제',p=>{const a=deep(activeAsset());a.id=uid('asset');a.name+=' Copy';p.library.push(a);selectedAssetId=a.id});$('#delAsset').onclick=()=>{if(project.library.length<=1)return;commit('요소 삭제',p=>{p.library=p.library.filter(x=>x.id!==selectedAssetId);selectedAssetId=p.library[0].id})};$('#randomizeAsset').onclick=()=>randomizeAsset();$('#addSocket').onclick=()=>{elementTool='socket';toast('캔버스에서 socket 위치를 클릭하세요')};$('#addPolygon').onclick=()=>{elementTool='polygon';elementPolygonDraft=[];selectedShapeIndex=-1;toast('새 polygon 점을 클릭하세요 · 더블클릭/Enter 완료')};$('#elementGridSize').onchange=e=>commit('Grid 변경',p=>p.settings.grid=clamp(+e.target.value||40,4,256));$('#optimizeAsset').onclick=()=>{const eps=clamp(+$('#assetOptimizeEps').value||0,0,100);commit(`Element simplify ε=${eps}`,()=>{const a=activeAsset();a.visual=a.visual.map(sh=>({...sh,points:rdpClosed(sh.points,eps)}));syncAssetCollision(a);selectedNode=-1;selectedShapeIndex=-1})};
}''')

# drawing scene and terrain/elements
replace_func('drawScene',r'''function drawScene(ctx,c,view,mode='stage'){const st=stage(),d=c._dpr||1,w=c.clientWidth,h=c.clientHeight,vr=visibleRect(c,view,180);ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.scale(view.zoom,view.zoom);ctx.translate(-view.x,-view.y);drawBackdrop(ctx,st,w/view.zoom,h/view.zoom,view);drawGridWorld(ctx,st,view);
 const layers=['far','mid','back'];for(const lid of layers)if(layerVisible(st,lid))drawElements(ctx,st,lid,vr,view.zoom);
 if(layerVisible(st,'terrain')){for(const t of st.terrains)drawTerrain(ctx,t,st,view.zoom);for(const m of st.materials)drawMaterial(ctx,m,st)}
 if(layerVisible(st,'interactive'))drawElements(ctx,st,'interactive',vr,view.zoom);if(layerVisible(st,'units'))drawUnits(ctx,st);if(layerVisible(st,'front'))drawElements(ctx,st,'front',vr,view.zoom);if(layerVisible(st,'events'))drawEvents(ctx,st);drawSelection(ctx,st,mode);if(tool==='solid'&&solidDraft.length)drawWorldDraft(ctx,solidDraft,true);ctx.restore();drawStageUI(ctx,c,st,view)}''')

replace_func('drawTerrain',r'''function drawTerrain(ctx,t,st,zoom=1){let pts=deriveTerrain(t);if(pts.length<2)return;const lod=project.settings.adaptiveLOD!==false&&zoom<.45?Math.max(0,(1/zoom-2)*1.3):0;if(lod){pts=t.type==='solid'?rdpClosed(pts,lod):rdpOpen(pts,lod)}ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(const p of pts.slice(1))ctx.lineTo(p.x,p.y);if(t.type==='ground'){ctx.lineTo(pts.at(-1).x,t.floor||st.height+100);ctx.lineTo(pts[0].x,t.floor||st.height+100)}else if(t.type==='platform'){const th=t.thickness||80;for(const p of [...pts].reverse())ctx.lineTo(p.x,p.y+th)}ctx.closePath();ctx.fillStyle=COLORS[t.baseMaterial]||'#46514a';ctx.fill();ctx.strokeStyle='#a7b397';ctx.lineWidth=2/Math.max(.1,zoom);ctx.stroke();if(t.type==='ground'){ctx.strokeStyle='#1d2d2c';ctx.lineWidth=1/Math.max(.1,zoom);for(let i=8;i<pts.length;i+=12){const p=pts[i];ctx.beginPath();ctx.moveTo(p.x,p.y+10);ctx.lineTo(p.x+18,p.y+22);ctx.stroke()}}}''')

replace_func('drawElements',r'''function drawElements(ctx,st,layer,vr=null,zoom=1){for(const e of st.elements){if(e.layer!==layer)continue;const a=project.library.find(x=>x.id===e.assetId);if(!a)continue;const inst=snapElement(st,{...e});if(vr&&!elementVisible(a,inst,vr))continue;let shapes=transformedShapes(a,inst);ctx.save();ctx.globalAlpha=layer==='back'?0.65:layer==='far'?0.42:layer==='mid'?0.55:1;for(const sh of shapes){let pts=sh.points;if(project.settings.adaptiveLOD!==false&&zoom<.4&&pts.length>6)pts=rdpClosed(pts,Math.max(1,(1/zoom-2)*.8));ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();if(sh.fill){ctx.fillStyle=sh.fill;const base=ctx.globalAlpha;ctx.globalAlpha=base*(sh.alpha??1);ctx.fill();ctx.globalAlpha=base}if(sh.stroke){ctx.strokeStyle=sh.stroke;ctx.lineWidth=1.5/Math.max(.1,zoom);ctx.stroke()}}if(a.breakable){ctx.strokeStyle='#caa96a';ctx.setLineDash([7,6]);ctx.lineWidth=1.2/Math.max(.1,zoom);const b=assetBounds(a);ctx.strokeRect(inst.x+(b.x*inst.scale),inst.y+(b.y*inst.scale),b.w*inst.scale,b.h*inst.scale);ctx.setLineDash([])}ctx.restore()}}''')

replace_func('drawSelection',r'''function drawSelection(ctx,st,mode){if(currentTab!=='stage'||!selected)return;const o=getSelected(st);if(!o)return;ctx.save();ctx.strokeStyle='#f1cf83';ctx.fillStyle='#f1cf83';ctx.lineWidth=2/stageView.zoom;if(selected.type==='terrain'){const pts=deriveTerrain(o);ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));if(o.type==='solid')ctx.closePath();ctx.stroke();if(tool==='select'){const edit=terrainEditPoints(o);for(let i=0;i<edit.length;i++){const p=edit[i];ctx.beginPath();ctx.arc(p.x,p.y,6/stageView.zoom,0,Math.PI*2);ctx.fillStyle=i===selectedNode?'#fff0b3':'#c9ac6b';ctx.fill()}}}else if(selected.type==='element'){const a=project.library.find(x=>x.id===o.assetId),inst=snapElement(st,{...o});if(a){for(const sh of transformedShapes(a,inst)){ctx.beginPath();sh.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke()}}}else if(['unit','event'].includes(selected.type)){const x=o.x,y=o.y;ctx.strokeRect(x-20/stageView.zoom,y-50/stageView.zoom,40/stageView.zoom,60/stageView.zoom)}ctx.restore()}''')

replace_func('drawStageUI',r'''function drawStageUI(ctx,c,st,view){const d=c._dpr||1,w=c.clientWidth,h=c.clientHeight;ctx.setTransform(d,0,0,d,0,0);$('#stageZoom').textContent=`${Math.round(view.zoom*100)}%`;$('#stageCoord').textContent=`${Math.round(view.x)}, ${Math.round(view.y)}`;}''')

# element render with selected shape and grid
replace_func('renderElement',r'''function renderElement(){if(!dom.elementCanvas)return;const c=dom.elementCanvas,ctx=c.getContext('2d'),d=c._dpr||1,w=c.clientWidth,h=c.clientHeight,a=activeAsset(),grid=Math.max(4,project.settings.grid||40);ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#0c171b';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.scale(elementView.zoom,elementView.zoom);ctx.translate(-elementView.x,-elementView.y);ctx.strokeStyle='#263a3d';ctx.lineWidth=1/elementView.zoom;for(let x=-1500;x<1500;x+=grid){ctx.beginPath();ctx.moveTo(x,-1500);ctx.lineTo(x,1500);ctx.stroke()}for(let y=-1500;y<1500;y+=grid){ctx.beginPath();ctx.moveTo(-1500,y);ctx.lineTo(1500,y);ctx.stroke()}for(let si=0;si<a.visual.length;si++){const sh=a.visual[si];ctx.beginPath();sh.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();if(sh.fill){ctx.fillStyle=sh.fill;ctx.globalAlpha=sh.alpha??1;ctx.fill();ctx.globalAlpha=1}ctx.strokeStyle=si===selectedShapeIndex?'#f0ce80':(sh.stroke||'#58686a');ctx.lineWidth=(si===selectedShapeIndex?2.8:1.5)/elementView.zoom;ctx.stroke()}ctx.fillStyle='#f0ce80';for(const sh of a.visual)for(let i=0;i<sh.points.length;i++){const p=sh.points[i];ctx.beginPath();ctx.arc(p.x,p.y,5/elementView.zoom,0,Math.PI*2);ctx.fillStyle=selectedNode===nodeGlobalIndex(a,sh,i)?'#fff0b0':'#c39f5e';ctx.fill()}if(elementPolygonDraft.length){ctx.strokeStyle='#e3c67f';ctx.fillStyle='#e3c67f';ctx.setLineDash([5/elementView.zoom,4/elementView.zoom]);ctx.beginPath();elementPolygonDraft.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.setLineDash([]);for(const p of elementPolygonDraft){ctx.beginPath();ctx.arc(p.x,p.y,4/elementView.zoom,0,Math.PI*2);ctx.fill()}}ctx.strokeStyle='#8dc0a8';ctx.lineWidth=2/elementView.zoom;ctx.beginPath();ctx.moveTo(a.anchor.x-8,a.anchor.y);ctx.lineTo(a.anchor.x+8,a.anchor.y);ctx.moveTo(a.anchor.x,a.anchor.y-8);ctx.lineTo(a.anchor.x,a.anchor.y+8);ctx.stroke();for(const s of a.sockets){ctx.strokeStyle='#a7a8d7';ctx.beginPath();ctx.arc(s.x,s.y,7/elementView.zoom,0,Math.PI*2);ctx.stroke()}ctx.restore()}''')

# bindCanvas dblclick stage solid
replace_func('bindCanvas',r'''function bindCanvas(c,kind){let pointer=null;c.addEventListener('contextmenu',e=>e.preventDefault());c.addEventListener('wheel',e=>{e.preventDefault();const view=kind==='stage'?stageView:elementView;const before=screenToWorld(c,e.offsetX,e.offsetY,view),factor=Math.exp(-e.deltaY*.0015);view.zoom=clamp(view.zoom*factor,.05,5);const after=screenToWorld(c,e.offsetX,e.offsetY,view);view.x+=before.x-after.x;view.y+=before.y-after.y;if(kind==='stage')renderStage();else renderElement()},{passive:false});c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);pointer={sx:e.offsetX,sy:e.offsetY,lastX:e.offsetX,lastY:e.offsetY,button:e.button,before:deep(project)};if(kind==='stage')stagePointerDown(e,pointer);else elementPointerDown(e,pointer)});c.addEventListener('pointermove',e=>{if(!pointer)return;if(kind==='stage')stagePointerMove(e,pointer);else elementPointerMove(e,pointer);pointer.lastX=e.offsetX;pointer.lastY=e.offsetY});c.addEventListener('pointerup',e=>{if(!pointer)return;if(kind==='stage')stagePointerUp(e,pointer);else elementPointerUp(e,pointer);pointer=null});c.addEventListener('dblclick',e=>{if(kind==='element')elementDoubleClick(e);else if(tool==='solid')finalizeSolid()})}''')

# stage interactions
replace_func('stagePointerDown',r'''function stagePointerDown(e,p){const st=realStage(),raw=screenToWorld(dom.stageCanvas,e.offsetX,e.offsetY,stageView),w=e.ctrlKey?gridSnapPoint(raw):raw;if(e.button===1||tool==='pan'||e.button===2){p.pan=true;return}if(tool==='terrain'){drawStroke=[w];return}if(tool==='solid'){if(e.detail<2){solidDraft.push({x:clamp(w.x,0,st.width),y:clamp(w.y,0,st.height)});renderStage()}return}if(tool==='material'){paintStroke=[w];return}if(tool==='place'){const a=project.library.find(x=>x.id===placementAssetId);if(!a)return;commit('요소 배치',()=>{const inst={id:uid('el'),assetId:a.id,x:w.x,y:w.y,rotation:0,scale:1,layer:a.collision.length?'interactive':'back',snap:true};snapElement(st,inst);st.elements.push(inst);selected={type:'element',id:inst.id}});tool='select';renderAll();return}if(tool==='scatter'){scatterAt(st,w);return}if(tool==='unit'){commit('유닛 배치',()=>{const sf=nearestSurface(st,w.x,w.y),u={id:uid('unit'),kind:unitKind,team:unitKind==='archer'?'player':'enemy',x:w.x,y:sf?.y??w.y,label:unitKind};st.units.push(u);selected={type:'unit',id:u.id}});tool='select';renderAll();return}if(tool==='event'){commit('이벤트 배치',()=>{const ev={id:uid('event'),type:eventKind,x:w.x,y:w.y,label:eventKind};st.events.push(ev);selected={type:'event',id:ev.id}});tool='select';renderAll();return}
 const hit=hitStage(st,w);selected=hit;selectedNode=-1;if(hit?.type==='terrain'){const t=getSelected(st),n=nearestControl(t,w,12/stageView.zoom);if(n>=0){selectedNode=n;p.dragNode=true}else{p.dragTerrain=true;p.startWorld=w;p.originTerrain=deep(t)}}else if(hit){p.dragObj=true;p.startWorld=w;p.origin=deep(getSelected(st))}renderAll()}''')

replace_func('stagePointerMove',r'''function stagePointerMove(e,p){const st=realStage(),raw=screenToWorld(dom.stageCanvas,e.offsetX,e.offsetY,stageView),w=e.ctrlKey?gridSnapPoint(raw):raw;if(p.pan){stageView.x-=(e.offsetX-p.lastX)/stageView.zoom;stageView.y-=(e.offsetY-p.lastY)/stageView.zoom;renderStage();return}if(tool==='terrain'&&drawStroke.length){if(dist(drawStroke.at(-1),w)>12/stageView.zoom)drawStroke.push(w);renderStage();drawTransientLine(drawStroke,'#dbbf7c');return}if(tool==='solid'&&solidDraft.length){renderStage();drawTransientPolygon(solidDraft);return}if(tool==='material'&&paintStroke.length){paintStroke.push(w);renderStage();drawTransientBand(paintStroke);return}if(tool==='scatter'&&e.buttons){if(performance.now()-scatterStamp>70){scatterAt(st,w);scatterStamp=performance.now()}return}if(p.dragNode&&selected?.type==='terrain'){const t=getSelected(st);if(!t)return;const pts=terrainEditPoints(t);pts[selectedNode]={x:clamp(w.x,0,st.width),y:clamp(w.y,0,st.height)};if(t.type!=='solid')pts.sort((a,b)=>a.x-b.x);delete t.__derivedCache;renderStage();return}if(p.dragTerrain&&selected?.type==='terrain'){const t=getSelected(st),dx=w.x-p.startWorld.x,dy=w.y-p.startWorld.y;if(t.type==='solid')t.points=p.originTerrain.points.map(q=>({x:q.x+dx,y:q.y+dy}));else{t.control=p.originTerrain.control.map(q=>({x:q.x+dx,y:q.y+dy}));if(t.type==='ground')t.floor=(p.originTerrain.floor||st.height+180)+dy}delete t.__derivedCache;renderStage();return}if(p.dragObj&&selected){const o=getSelected(st);if(!o)return;const dx=w.x-p.startWorld.x,dy=w.y-p.startWorld.y;o.x=clamp(p.origin.x+dx,0,st.width);o.y=clamp(p.origin.y+dy,0,st.height);if(selected.type==='element'&&o.snap)snapElement(st,o);renderStage()}}''')

replace_func('stagePointerUp',r'''function stagePointerUp(e,p){const st=realStage();if(tool==='terrain'&&drawStroke.length>1){const points=prepareControl(drawStroke,st);drawStroke=[];commit('Terrain draw',()=>{const t={id:uid('terrain'),name:`Ground ${st.terrains.length+1}`,type:'ground',control:points,floor:st.height+180,baseMaterial:'soil',detail:{spacing:18,roughness:7,seed:Math.floor(Math.random()*100000),optimizeEpsilon:0},layer:'terrain'};st.terrains.push(t);selected={type:'terrain',id:t.id}});tool='select';renderAll()}else if(tool==='material'&&paintStroke.length>1){const xs=paintStroke.map(p=>p.x),mid=paintStroke[Math.floor(paintStroke.length/2)],sf=nearestSurface(st,mid.x,mid.y);paintStroke=[];if(sf&&sf.terrain.type!=='solid')commit('Material paint',()=>{st.materials.push({id:uid('mat'),terrainId:sf.terrain.id,x1:clamp(Math.min(...xs),0,st.width),x2:clamp(Math.max(...xs),0,st.width),kind:materialKind,depth:materialKind==='water'?38:26,alpha:.9})})}else if(p.dragNode||p.dragObj||p.dragTerrain){history.push({label:'드래그 이전',state:p.before});future=[];previewProject=null;saveAutosave();renderAll()}}''')

replace_func('nearestControl',r'''function nearestControl(t,w,rad){let best=-1,d=Infinity;terrainEditPoints(t).forEach((p,i)=>{const x=dist(p,w);if(x<d&&x<rad){d=x;best=i}});return best}''')

replace_func('hitStage',r'''function hitStage(st,w){for(const type of ['event','unit']){const arr=type==='event'?st.events:st.units;for(let i=arr.length-1;i>=0;i--){const o=arr[i];if(dist(o,w)<35/stageView.zoom)return{type,id:o.id}}}for(let i=st.elements.length-1;i>=0;i--){const o=st.elements[i];if(layerLocked(st,o.layer))continue;const a=project.library.find(x=>x.id===o.assetId);if(!a)continue;const inst=snapElement(st,{...o});const shapes=transformedShapes(a,inst);if(shapes.some(sh=>pointInPoly(w,sh.points))||dist(inst,w)<30/stageView.zoom)return{type:'element',id:o.id}}for(let i=st.terrains.length-1;i>=0;i--){const t=st.terrains[i],poly=terrainPolygon(t,st),ys=terrainSurfaceYs(t,w.x);if((poly.length>=3&&pointInPoly(w,poly))||ys.some(y=>Math.abs(y-w.y)<18/stageView.zoom))return{type:'terrain',id:t.id}}return null}''')

# new world draft and solid functions: insert before drawTransientLine by replacing it with prefixed functions
marker='function drawTransientLine(arr,color)'
pos=s.index(marker)
insert=r'''function terrainPolygon(t,st){const pts=deriveTerrain(t);if(t.type==='solid')return pts;if(t.type==='ground')return[...pts,{x:pts.at(-1)?.x??0,y:t.floor||st.height+100},{x:pts[0]?.x??0,y:t.floor||st.height+100}];if(t.type==='platform'){const th=t.thickness||80;return[...pts,...[...pts].reverse().map(p=>({x:p.x,y:p.y+th}))]}return pts}
function drawWorldDraft(ctx,pts,closed=false){if(!pts.length)return;ctx.save();ctx.strokeStyle='#f0c978';ctx.fillStyle='#f0c978';ctx.lineWidth=3/stageView.zoom;ctx.setLineDash([8/stageView.zoom,5/stageView.zoom]);ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));if(closed&&pts.length>2)ctx.closePath();ctx.stroke();ctx.setLineDash([]);for(const p of pts){ctx.beginPath();ctx.arc(p.x,p.y,5/stageView.zoom,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawTransientPolygon(arr){const c=dom.stageCanvas,ctx=c.getContext('2d'),d=c._dpr||1;ctx.setTransform(d,0,0,d,0,0);ctx.save();ctx.translate(c.clientWidth/2,c.clientHeight/2);ctx.scale(stageView.zoom,stageView.zoom);ctx.translate(-stageView.x,-stageView.y);drawWorldDraft(ctx,arr,true);ctx.restore()}
function finalizeSolid(){if(tool!=='solid'||solidDraft.length<3)return;const pts=solidDraft.map(p=>({...p}));solidDraft=[];commit('Solid polygon 생성',()=>{const st=realStage(),t={id:uid('solid'),name:`Solid ${st.terrains.filter(x=>x.type==='solid').length+1}`,type:'solid',points:pts,baseMaterial:'rock',layer:'terrain',breakable:false};st.terrains.push(t);selected={type:'terrain',id:t.id}});tool='select';renderAll()}
'''
s=s[:pos]+insert+s[pos:]

# element handlers
replace_func('elementPointerDown',r'''function elementPointerDown(e,p){const raw=screenToWorld(dom.elementCanvas,e.offsetX,e.offsetY,elementView),w=e.ctrlKey?gridSnapPoint(raw):raw,a=activeAsset();if(e.button===1||e.button===2){p.pan=true;return}if(elementTool==='polygon'){if(e.detail<2){elementPolygonDraft.push({...w});renderElement()}return}if(elementTool==='anchor'){commit('Anchor 설정',()=>{a.anchor={x:w.x,y:w.y}});elementTool='point';return}if(elementTool==='socket'){commit('Socket 추가',()=>{a.sockets.push({id:`socket_${a.sockets.length+1}`,x:w.x,y:w.y})});elementTool='point';return}selectedNode=nearestAssetNode(a,w,10/elementView.zoom);if(selectedNode>=0){p.dragNode=true;selectedShapeIndex=nodeByGlobal(a,selectedNode)?.shapeIndex??selectedShapeIndex;return}for(let i=a.visual.length-1;i>=0;i--)if(pointInPoly(w,a.visual[i].points)){selectedShapeIndex=i;p.dragShape=true;p.startWorld=w;p.originShape=deep(a.visual[i].points);renderElement();return}selectedShapeIndex=-1;renderElement()}''')

# nodeByGlobal needs shapeIndex
replace_func('nodeByGlobal',r'''function nodeByGlobal(a,idx){let k=0;for(let si=0;si<a.visual.length;si++){const sh=a.visual[si];if(idx<k+sh.points.length)return{shape:sh,shapeIndex:si,index:idx-k,point:sh.points[idx-k]};k+=sh.points.length}return null}''')

replace_func('elementPointerMove',r'''function elementPointerMove(e,p){if(p.pan){elementView.x-=(e.offsetX-p.lastX)/elementView.zoom;elementView.y-=(e.offsetY-p.lastY)/elementView.zoom;renderElement();return}const raw=screenToWorld(dom.elementCanvas,e.offsetX,e.offsetY,elementView),w=e.ctrlKey?gridSnapPoint(raw):raw;if(p.dragNode&&selectedNode>=0){const n=nodeByGlobal(activeAsset(),selectedNode);if(n){n.point.x=w.x;n.point.y=w.y;selectedShapeIndex=n.shapeIndex;syncAssetCollision(activeAsset());renderElement()}}else if(p.dragShape&&selectedShapeIndex>=0){const sh=activeAsset().visual[selectedShapeIndex],dx=w.x-p.startWorld.x,dy=w.y-p.startWorld.y;sh.points=p.originShape.map(q=>({x:q.x+dx,y:q.y+dy}));syncAssetCollision(activeAsset());renderElement()}}''')

replace_func('elementPointerUp',r'''function elementPointerUp(e,p){if(p.dragNode||p.dragShape){history.push({label:'Vector edit 이전',state:p.before});future=[];saveAutosave();renderAll()}}''')

replace_func('elementDoubleClick',r'''function elementDoubleClick(e){if(elementTool==='polygon'){finalizeElementPolygon();return}const a=activeAsset(),raw=screenToWorld(dom.elementCanvas,e.offsetX,e.offsetY,elementView),w=e.ctrlKey?gridSnapPoint(raw):raw;let best=null,d=Infinity;for(const sh of a.visual)for(let i=0;i<sh.points.length;i++){const p=sh.points[i],q=sh.points[(i+1)%sh.points.length],hit=pointSegmentDistance(w,p,q);if(hit.d<d){d=hit.d;best={sh,i,point:hit.point}}}if(best&&d<12/elementView.zoom)commit('Vertex 추가',()=>{best.sh.points.splice(best.i+1,0,e.ctrlKey?gridSnapPoint(best.point):best.point);syncAssetCollision(a)})}''')

# insert finalizeElementPolygon before nearestAssetNode
marker='function nearestAssetNode(a,w,rad)'
pos=s.index(marker)
insert=r'''function finalizeElementPolygon(){if(elementTool!=='polygon'||elementPolygonDraft.length<3)return;const pts=elementPolygonDraft.map(p=>({...p}));elementPolygonDraft=[];commit('Element polygon 추가',()=>{const a=activeAsset(),base=a.visual[selectedShapeIndex]||a.visual[0];a.visual.push(shape(pts,base?.fill||'#5b625e',base?.stroke||'#222d30',base?.alpha??1));selectedShapeIndex=a.visual.length-1;syncAssetCollision(a)});elementTool='point';renderAll()}
'''
s=s[:pos]+insert+s[pos:]

# play update with solid ceiling + wall basic
replace_func('updatePlay',r'''function updatePlay(dt){if(currentTab!=='play'||!playState)return;const st=stage(),p=playState,k=p.keys,left=k.has('ArrowLeft')||k.has('KeyA'),right=k.has('ArrowRight')||k.has('KeyD'),bodyH=48;p.vx+=(right-left)*900*dt;p.vx*=Math.pow(.06,dt);p.vx=clamp(p.vx,-270,270);if(k.has('Space')&&p.onGround){p.vy=-510;p.onGround=false;k.delete('Space')}p.vy+=1100*dt;const oldX=p.x,oldY=p.y,oldHead=oldY-bodyH;p.x=clamp(p.x+p.vx*dt,0,st.width);p.y+=p.vy*dt;
 // Side-wall rejection for arbitrary solid polygons.
 for(const t of st.terrains.filter(t=>t.type==='solid'))if(pointInPoly({x:p.x,y:p.y-bodyH*.5},t.points||[])){p.x=oldX;p.vx=0;break}
 const surfaces=[];for(const t of st.terrains)for(const y of terrainSurfaceYs(t,p.x))surfaces.push({y,t});for(const el of st.elements){const a=project.library.find(x=>x.id===el.assetId);if(!a?.collision.length)continue;const inst=snapElement(st,{...el}),shapes=transformedShapes(a,inst);for(const sh of shapes){for(const y of polyIntersectionsY(sh.points,p.x))surfaces.push({y,t:null})}}
 if(p.vy>=0){const candidates=surfaces.filter(s=>oldY<=s.y+8&&p.y>=s.y-2).sort((a,b)=>a.y-b.y);if(candidates.length){p.y=candidates[0].y;p.vy=0;p.onGround=true}else p.onGround=false}else{const newHead=p.y-bodyH,candidates=surfaces.filter(s=>newHead<=s.y&&oldHead>=s.y).sort((a,b)=>b.y-a.y);if(candidates.length){p.y=candidates[0].y+bodyH;p.vy=0}}
 p.cam.x+=(p.x-p.cam.x)*clamp(dt*4,0,1);p.cam.y+=(p.y-p.cam.y)*clamp(dt*4,0,1)}''')

replace_func('polyTopAtX',r'''function polyIntersectionsY(pts,x){const ys=[];for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length];if((x>=a.x&&x<=b.x)||(x>=b.x&&x<=a.x)){const dx=b.x-a.x;if(Math.abs(dx)<1e-5)continue;const t=(x-a.x)/dx;if(t>=0&&t<=1)ys.push(a.y+(b.y-a.y)*t)}}return ys.sort((a,b)=>a-b)}
function polyTopAtX(pts,x){const ys=polyIntersectionsY(pts,x);return ys.length?ys[0]:null}''')

# export/import solids
replace_func('exportHonroSpec',r'''function exportHonroSpec(st=realStage()){return{dimensions:[st.width,st.height],design:{title:st.name,question:'Workshop authored',gameplay:['workshop']},backdrop:{kind:st.backdrop},grounds:st.terrains.filter(t=>t.type==='ground').map(t=>({id:t.id,top:deriveTerrain(t).map(p=>[round(p.x),round(p.y)]),floor:t.floor||st.height+180,surfaceKind:t.baseMaterial==='rock'?'rock':'soil',mat:t.baseMaterial==='wood'?'wood':'earth'})),ribbons:st.terrains.filter(t=>t.type==='platform').map(t=>({id:t.id,top:deriveTerrain(t).map(p=>[round(p.x),round(p.y)]),thickness:t.thickness||80,oneWay:!!t.oneWay,indestructible:!t.breakable,route:false,surfaceKind:t.baseMaterial,mat:t.baseMaterial==='wood'?'wood':'rock'})),solids:st.terrains.filter(t=>t.type==='solid').map(t=>({id:t.id,points:(t.points||[]).map(p=>[round(p.x),round(p.y)]),indestructible:!t.breakable,route:false,surfaceKind:t.baseMaterial,mat:t.baseMaterial==='wood'?'wood':'rock'})),surfaceZones:st.materials.map(m=>({kind:materialRuntimeKind(m.kind),points:materialPolygon(st,m).map(p=>[round(p.x),round(p.y)]),alpha:m.alpha??.9})),landmarks:st.elements.filter(e=>{const a=project.library.find(x=>x.id===e.assetId);return !a?.collision.length}).map(e=>({id:e.id,kind:e.assetId,x:round(e.x),y:round(e.y),size:e.scale,layer:e.layer,rotation:e.rotation})),editorData:{version:2,elements:deep(st.elements),units:deep(st.units),events:deep(st.events),layers:deep(st.layers)}}}''')

replace_func('importHonroSpec',r'''function importHonroSpec(spec){commit('HONRO spec import',p=>{const st=defaultStage(uid('stage'),spec.design?.title||'Imported Stage',spec.dimensions[0],spec.dimensions[1]);st.backdrop=spec.backdrop?.kind||'forest';for(const g of spec.grounds||[]){st.terrains.push({id:g.id||uid('terrain'),name:g.id||'Ground',type:'ground',control:downsample(g.top.map(([x,y])=>({x,y})),24),floor:g.floor||st.height+100,baseMaterial:g.mat==='wood'?'wood':g.surfaceKind==='rock'?'rock':'soil',detail:{spacing:18,roughness:0,seed:1,optimizeEpsilon:0},layer:'terrain'})}for(const r of spec.ribbons||[]){st.terrains.push({id:r.id||uid('platform'),name:r.id||'Platform',type:'platform',control:downsample(r.top.map(([x,y])=>({x,y})),20),thickness:r.thickness||80,oneWay:!!r.oneWay,breakable:r.indestructible===false,baseMaterial:r.mat==='wood'?'wood':'rock',detail:{spacing:18,roughness:0,seed:1,optimizeEpsilon:0},layer:'terrain'})}for(const q of spec.solids||[]){st.terrains.push({id:q.id||uid('solid'),name:q.id||'Solid',type:'solid',points:q.points.map(([x,y])=>({x,y})),breakable:q.indestructible===false,baseMaterial:q.mat==='wood'?'wood':'rock',layer:'terrain'})}p.stages.push(st);p.activeStageId=st.id;stageView._fit=false})}''')

# agent context
replace_func('agentContext',r'''function agentContext(){const st=realStage();return{workshop:'HONRO Workshop v2',stage:{id:st.id,name:st.name,width:st.width,height:st.height,backdrop:st.backdrop},counts:{terrains:st.terrains.length,materials:st.materials.length,elements:st.elements.length,units:st.units.length,events:st.events.length,...sceneStats(st)},selection:selected,availableAssets:project.library.map(a=>({id:a.id,name:a.name,category:a.category,tags:a.tags,collision:!!a.collision.length,nodes:assetNodeCount(a)})),commandAPI:['world.set','terrain.add','terrain.addSolid','terrain.roughen','terrain.moveNode','terrain.optimize','material.paint','element.place','element.move','element.delete','element.scatter','asset.optimize','unit.place','event.place','delete'],validation:validateStage(st)}}''')

# extend applyCommands by simple string replacement for terrain.add and asset.optimize cases
old="case'terrain.add':{const t={id:c.id||uid('terrain'),name:c.name||'Agent Ground',type:c.type||'ground',control:(c.control||[]).map(([x,y])=>({x,y})),floor:c.floor||st.height+100,baseMaterial:c.material||'soil',detail:{spacing:c.spacing||18,roughness:c.roughness||6,seed:c.seed||42},layer:'terrain'};st.terrains.push(t);break}case'terrain.roughen':"
new="case'terrain.add':{const t={id:c.id||uid('terrain'),name:c.name||'Agent Ground',type:c.type||'ground',control:(c.control||[]).map(([x,y])=>({x,y})),floor:c.floor||st.height+100,baseMaterial:c.material||'soil',detail:{spacing:c.spacing||18,roughness:c.roughness||6,seed:c.seed||42,optimizeEpsilon:c.optimizeEpsilon||0},layer:'terrain'};st.terrains.push(t);break}case'terrain.addSolid':{st.terrains.push({id:c.id||uid('solid'),name:c.name||'Agent Solid',type:'solid',points:(c.points||[]).map(([x,y])=>({x,y})),baseMaterial:c.material||'rock',breakable:!!c.breakable,layer:'terrain'});break}case'terrain.optimize':{const t=st.terrains.find(x=>x.id===c.id);if(t&&t.type!=='solid'){t.detail??={};t.detail.optimizeEpsilon=clamp(c.epsilon??0,0,100);delete t.__derivedCache}break}case'terrain.roughen':"
assert old in s
s=s.replace(old,new,1)
# insert asset.optimize before unit.place
old="case'unit.place':{const sf=nearestSurface(st,c.x,c.y??st.height/2);"
new="case'asset.optimize':{const a=p.library.find(x=>x.id===c.id);if(a){a.visual=a.visual.map(sh=>({...sh,points:rdpClosed(sh.points,c.epsilon||2)}));syncAssetCollision(a)}break}case'unit.place':{const sf=nearestSurface(st,c.x,c.y??st.height/2);"
assert old in s
s=s.replace(old,new,1)

# toolbar
replace_func('renderToolbars',r'''function renderToolbars(){const host=$('#stageToolbar');if(host)host.innerHTML=[['select','선택'],['terrain','지형'],['solid','Solid'],['material','재질'],['place','배치'],['scatter','Scatter'],['unit','유닛'],['event','이벤트'],['pan','Pan']].map(([id,n])=>`<button class="tool ${tool===id?'active':''}" data-tool="${id}">${n}</button>`).join('<span class="toolbar-sep"></span>');$$('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;if(tool!=='solid')solidDraft=[];renderAll()});const eh=$('#elementToolbar');if(eh)eh.innerHTML=[['point','Point'],['polygon','Polygon'],['anchor','Anchor'],['socket','Socket']].map(([id,n])=>`<button class="tool ${elementTool===id?'active':''}" data-etool="${id}">${n}</button>`).join('');$$('[data-etool]').forEach(b=>b.onclick=()=>{elementTool=b.dataset.etool;if(elementTool!=='polygon')elementPolygonDraft=[];renderAll()})}''')

# keyboard support: patch bindTop manually
old="document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(e.key==='Delete'||e.key==='Backspace'){if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;deleteSelection()}if(e.key==='Escape'){selected=null;selectedNode=-1;renderAll()}})"
new="document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(e.key==='Enter'){if(currentTab==='stage'&&tool==='solid')finalizeSolid();else if(currentTab==='element'&&elementTool==='polygon')finalizeElementPolygon();return}if(e.key==='Delete'||e.key==='Backspace'){if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(currentTab==='element'){const a=activeAsset();if(selectedNode>=0){const n=nodeByGlobal(a,selectedNode);if(n&&n.shape.points.length>3)commit('Vertex 삭제',()=>{n.shape.points.splice(n.index,1);syncAssetCollision(a);selectedNode=-1})}else if(selectedShapeIndex>=0&&a.visual.length>1)commit('Polygon 삭제',()=>{a.visual.splice(selectedShapeIndex,1);syncAssetCollision(a);selectedShapeIndex=-1});return}deleteSelection()}if(e.key==='Escape'){selected=null;selectedNode=-1;selectedShapeIndex=-1;solidDraft=[];elementPolygonDraft=[];renderAll()}})"
assert old in s
s=s.replace(old,new,1)

p.write_text(s)
print('patched app.js')
