/** Whole-act canonical adapter. No Stage 18 candidate recipe or monotone-X assumption. */
import {readFile,writeFile,mkdir,readdir}from'node:fs/promises';import path from'node:path';import vm from'node:vm';
import{pathToFileURL}from'node:url';
import{ROOT,loadRuntime,makeCanvas,writeJSON}from'./runtime.mjs';import{sourceSnapshot,assertUnchangedSource}from'./source.mjs';import{hash}from'./state.mjs';
const clone=x=>structuredClone(x);const check=(ok,message)=>{if(!ok)throw Error(message);};const finite=n=>Number.isFinite(n);
const point=p=>Array.isArray(p)?{x:p[0],y:p[1]}:p;
export async function actSourceSnapshot(root=ROOT){const source=await sourceSnapshot(root),rows=[];async function scan(dir){for(const ent of await readdir(dir,{withFileTypes:true})){const f=path.join(dir,ent.name);if(ent.isDirectory())await scan(f);else if(ent.isFile())rows.push([path.relative(root,f),hash(await readFile(f))]);else throw Error('Unexpected build input link '+f);}}for(const dir of ['workshop/recipes','tools/map-forge','tools/environment','tools/intent-pipeline'])await scan(path.join(root,dir));return{...source,codeHash:hash({core:source.codeHash,actInputs:rows.sort((a,b)=>a[0].localeCompare(b[0]))}),adapter:'whole-act-canonical-v1'};}
export function actStages(project,ids){const stages=ids.map(id=>project.stages.find(s=>s.metadata?.stageId===id));check(stages.every(Boolean),'Whole-act project is missing a requested stage');check(new Set(ids).size===ids.length,'Duplicate stage request');return stages;}
export function validateActPlanDocument(document,ids){check(document.documentType==='honro-act2-spatial-design-proposal','Unsupported approved spatial plan document');check(JSON.stringify(document.scope)===JSON.stringify(ids),'Approved document scope differs from requested act');check(Array.isArray(document.stages)&&document.stages.length===ids.length,'Approved document must cover the complete act');for(const id of ids)check(document.stages.some(s=>s.stageId===id),'Approved plan missing stage '+id);return document;}
export function assertSpaceContract(stage){const s=stage.design?.space;check(s&&s.version===1&&s.geometryRevision>=3,'Stage '+stage.metadata.stageId+' has no implemented full-act spatial contract');check(typeof s.topologyId==='string'&&s.topologyId,'Stage topologyId missing');check(Array.isArray(s.rooms)&&s.rooms.length>0,'Stage rooms missing');check(Array.isArray(s.connections),'Stage connections missing');check(Array.isArray(s.surfaces)&&s.surfaces.length>0,'Stage surfaces missing');check(Array.isArray(stage.routes)&&stage.routes.length>1,'Canonical traversal route missing');for(const p of stage.routes){const q=point(p);check(finite(q.x)&&finite(q.y),'Non-finite route point');}return s;}
export function compileActProject(g,input,{stageIds,approvedPlan,baseline}={}){
 check(Array.isArray(stageIds)&&stageIds.length>1,'Whole-act adapter requires an explicit multi-stage scope');validateActPlanDocument(approvedPlan,stageIds);const project=g.HonroMaps.finalize(clone(input));const stages=actStages(project,stageIds),battles=[];
 for(const st of stages){assertSpaceContract(st);if(g.HonroAct2SpacePlan?.validate){const errors=g.HonroAct2SpacePlan.validate(st);check(!errors.length,'Spatial references invalid: '+errors.join('; '));}const authored=approvedPlan.stages.find(s=>s.stageId===st.metadata.stageId);check(st.design.space.topologyId===authored.topologyId,'Topology deviates from approved plan at stage '+st.metadata.stageId);const b=g.HonroMaps.createBattle(st,project);check(b.honroStage===st.metadata.stageId,'Compiler selected the wrong chapter');check(b.width===st.width&&b.height===st.height,'Compiled dimensions differ from stage');battles.push({stageId:st.metadata.stageId,battle:b});}
 if(baseline){const isOther=s=>!stageIds.includes(s.metadata?.stageId);check(hash(project.stages.filter(isOther))===hash(baseline.stages.filter(isOther)),'Unapproved stage data changed outside the act');}
 return{project,stages,battles};
}
export async function authorActProject(g,base,recipe=path.join(ROOT,'workshop/recipes/act2-caves.js')){vm.runInContext(await readFile(recipe,'utf8'),g,{filename:recipe});check(g.HonroAct2Design?.build,'Whole-act recipe does not export its canonical builder');let project=g.HonroAct2Design.build(clone(base));const {applyAct2VectorArt}=await import(pathToFileURL(path.join(ROOT,'tools/environment/build-act2-art.mjs')).href);project=await applyAct2VectorArt(project);const {applyAct2SceneComposition}=await import(pathToFileURL(path.join(ROOT,'tools/environment/act2-scene-composition.mjs')).href);project=await applyAct2SceneComposition(project);return g.HonroMaps.finalize(project);}
function objectiveContract(st){return{steps:st.initialState?.honroAct2Steps,activeLimit:st.initialState?.honroActiveLimit,units:st.units.map(({x,y,...u})=>u),markers:st.markers.filter(m=>m.action==='act2'||m.id.startsWith('spirit-lamp')).map(({x,y,...m})=>m)};}
function structuralTerrain(st){return st.terrains.filter(t=>t.properties?.honroCeiling||t.properties?.honroSpaceSurfaceId&&!t.properties?.honroAct2Target).map(t=>({id:t.id,points:t.points,oneWay:t.oneWay,breakable:t.breakable}));}
export function validateActImplementation(g,compiled,{stageIds,approvedPlan,baseline}){
 const checks=[],stages=[],add=(name,fn)=>{try{const evidence=fn();checks.push({name,status:'passed',evidence});}catch(e){checks.push({name,status:'failed',reason:e.message});}};
 add('canonical-schema',()=>{const errors=g.HonroMaps.validate(compiled.project).filter(x=>x.level==='err');check(!errors.length,errors.map(x=>x.text).join('; '));return{stageIds,scope:'Full canonical project/environment/bounds schema'};});
 add('objective-contract',()=>{check(baseline,'Immutable baseline project required');for(const st of compiled.stages){const old=baseline.stages.find(s=>s.metadata?.stageId===st.metadata.stageId);check(old,'Baseline stage missing');check(hash(objectiveContract(st))===hash(objectiveContract(old)),'Gameplay/objective/roster contract changed at '+st.metadata.stageId);}return'Objective sequences, classes, active caps, unit definitions and interaction semantics preserved; coordinate changes excluded.';});
 add('approved-spatial-contract',()=>{for(const st of compiled.stages){const plan=assertSpaceContract(st),expected=approvedPlan.stages.find(s=>s.stageId===st.metadata.stageId);check(plan.topologyId===expected.topologyId,'Unapproved topology');}return'All requested chapters implement their own approved topology IDs and spatial metadata.';});
 add('outside-act-preserved',()=>{check(baseline,'Immutable baseline required');const others=p=>p.stages.filter(s=>!stageIds.includes(s.metadata?.stageId));check(hash(others(compiled.project))===hash(others(baseline)),'Data outside act changed');const used=new Set(others(baseline).flatMap(s=>[...s.elements,...(s.environment?.placements||[])].map(e=>e.assetId)));for(const id of used)check(hash(baseline.library.find(a=>a.id===id))===hash(compiled.project.library.find(a=>a.id===id)),'Shared asset outside approved act changed: '+id);return'Other act stage records and their referenced library assets are unchanged';});
 add('shared-spatial-continuity',()=>{const groups=new Map();for(const st of compiled.stages){const id=st.design.space.sharedSpaceId;if(id){const prior=groups.get(id);if(prior){check(hash(structuralTerrain(prior))===hash(structuralTerrain(st)),'Shared space terrain differs: '+id);const bells=s=>s.elements.filter(e=>e.assetId?.endsWith(':bell')).map(e=>({assetId:e.assetId,x:e.x,y:e.y,scale:e.scale}));check(hash(bells(prior))===hash(bells(st)),'Shared bell position differs: '+id);}else groups.set(id,st);}}return{sharedSpaces:[...groups.keys()]};});
 add('vector-asset-validity',()=>{const vectors=compiled.project.library.filter(a=>a.vector);if(vectors.length){check(g.HonroVectorArt?.validate,'Vector display-list validator is not loaded');for(const a of vectors){const errors=g.HonroVectorArt.validate(a.vector);check(!errors.length,a.id+': '+errors.join('; '));}}return{vectorAssets:vectors.length,note:'Schema/security check only, not artistic approval'};});
 add('save-compatibility',()=>{for(const row of compiled.battles){const restored=JSON.parse(JSON.stringify(row.battle));check(hash(g.HonroAct2.state(row.battle))===hash(g.HonroAct2.state(restored)),'Objective state roundtrip differs at '+row.stageId);}return'New battle JSON/objective roundtrip only; legacy ongoing-save regression must be supplied separately.';});
 for(const row of compiled.battles){const st=compiled.stages.find(s=>s.metadata.stageId===row.stageId),e=new g.HONRO_CORE.Engine(clone(row.battle),()=>{},true),players=e.b.units.filter(u=>u.side===0),support=players.map(u=>({id:u.id,ok:!!e.surface(u.x,u.y-45,u.y+45)}));stages.push({stageId:row.stageId,topologyId:st.design.space.topologyId,sharedSpaceId:st.design.space.sharedSpaceId||null,rooms:st.design.space.rooms.length,terrainCount:st.terrains.length,routePoints:st.routes.length,playerSupport:support,compiledTerrainHash:hash(row.battle.terrain),battleHash:hash(row.battle)});}
 add('spawn-support',()=>{const failures=stages.flatMap(s=>s.playerSupport.filter(p=>!p.ok).map(p=>({stage:s.stageId,...p})));check(!failures.length,'Player support missing: '+JSON.stringify(failures));return'All player start positions use exposed canonical collision support.';});
 for(const[name,reason]of[['creative-implementation','Compiled geometry/render evidence does not by itself validate finished assets against the approved art; implementation review required.'],['movement-physics','Import the complete act traversal report; compiling maps is not traversal evidence.'],['normal-playthrough','Requires normal unmodified combat clear evidence for the complete act.'],['browser-game-workshop','Native Canvas is not browser Game/Workshop/HUD/input verification.'],['performance','Requires actual browser performance measurement.'],['legacy-save-compatibility','New battle roundtrip is not an old-save regression.']])checks.push({name,status:'blocked',reason});
 return{schemaVersion:1,adapter:'whole-act-canonical-v1',stageIds,projectHash:hash(compiled.project),checks,stages,artisticApproval:false,publicationAuthorized:false};
}
export function viewsForStage(st){const authored=st.design.space.views;const list=Array.isArray(authored)?authored:Object.entries(authored||{}).map(([id,v])=>({id,...v}));const views=[];
 for(const [i,v]of list.entries()){const c=v.camera||v,focus=c.center||c.focus||c;const x=c.x??focus.x,y=c.y??focus.y,scale=c.scale??c.zoom;if(finite(x)&&finite(y)&&finite(scale))views.push({name:String(v.id||v.name||`authored-${i}`).replace(/[^\w-]/g,'-'),x,y,scale,width:v.width||1440,height:v.height||960,overview:!!v.overview||v.id==='overview'});}
 const spawn=st.anchors?.spawn||st.units.find(u=>u.team==='player'),mid=st.routes[Math.floor(st.routes.length/2)],focus=point(mid);
 if(!views.some(v=>v.overview))views.unshift({name:'overview',x:st.width/2,y:st.height/2,scale:Math.min(1400/st.width,860/st.height),width:1440,height:960,overview:true});
 if(!views.some(v=>!v.overview))views.push({name:'entry',x:spawn.x+450,y:spawn.y-280,scale:.6,width:1440,height:960,overview:false},{name:'place',x:focus.x,y:focus.y-350,scale:.48,width:1440,height:960,overview:false});
 if(!views.some(v=>v.height>v.width))views.push({name:'portrait',x:spawn.x+230,y:spawn.y-250,scale:.48,width:720,height:1080,overview:false});
 return views;
}
export async function renderActProject(runtime,compiled,out){const{g,canvasModule}=runtime;check(canvasModule,'Renderer runtime required');await mkdir(out,{recursive:true});const renders=[];
 for(const st of compiled.stages)for(const view of viewsForStage(st)){const b=g.HonroMaps.createBattle(st,compiled.project),e=new g.HONRO_CORE.Engine(b,()=>{},true),canvas=makeCanvas(canvasModule,view.width,view.height),scene=new g.HonroScene(canvas);Object.assign(scene,{x:view.x,y:view.y,scale:view.scale,manual:true,time:2,editorView:view.overview,skillPreview:view.overview});scene.render(e,0,'',.6,false,0);await new Promise(r=>setTimeout(r,20));scene.render(e,0,'',.6,false,0);const file=path.join(out,`stage-${st.metadata.stageId}-${view.name}.png`),bytes=canvas.toBuffer('image/png');await writeFile(file,bytes);renders.push({kind:'render',path:path.relative(ROOT,file),sha256:hash(bytes),stageId:st.metadata.stageId,view,method:'Actual common HonroMaps, Engine and HonroScene via native Canvas',limitations:['Not browser/HUD/input/performance proof','Not a normal combat clear','Overview uses inspection zoom']});}
 return renders;
}
export async function prepareActRuntime(){const before=await actSourceSnapshot(),runtime=await loadRuntime({render:true});vm.runInContext(await readFile(path.join(ROOT,'workshop/recipes/act2-caves.js'),'utf8'),runtime.g);const after=await actSourceSnapshot();assertUnchangedSource(before,after);return{runtime,source:{...after,runtimeHash:runtime.bundleHash}};}

export async function importActRenderManifest(file,compiled,runtimeHash){
 const manifest=JSON.parse(await readFile(file,'utf8')),folder=path.dirname(file);check(manifest.bundleSha256===runtimeHash,'Render manifest belongs to a different runtime bundle');
 const recordedProject=JSON.parse(await readFile(path.join(folder,'campaign.json'),'utf8'));check(hash(recordedProject)===hash(compiled.project),'Render manifest belongs to a different canonical project');
 const ids=compiled.stages.map(s=>s.metadata.stageId),rows=manifest.results.filter(r=>ids.includes(r.stageId));
 for(const id of ids){const matches=rows.filter(r=>r.stageId===id);check(matches.some(r=>r.view.overview)&&matches.some(r=>!r.view.overview&&r.view.width>r.view.height)&&matches.some(r=>r.view.height>r.view.width),'Render coverage incomplete for stage '+id);}
 const refs=[];for(const r of rows){const name=path.resolve(folder,r.file);check(name.startsWith(path.resolve(folder)+path.sep),'Unsafe render manifest file');check(hash(await readFile(name))===r.sha256,'Render evidence bytes changed: '+r.file);refs.push({kind:'render',path:path.relative(ROOT,name),sha256:r.sha256,stageId:r.stageId,view:r.view,method:r.source,limitations:r.limits||[]});}return refs;
}
