#!/usr/bin/env node
import{readFile,writeFile,mkdir}from'node:fs/promises';import path from'node:path';
import{ROOT,writeJSON}from'./runtime.mjs';import{readRun,saveRun,hash,basisOf,recordImplementationSource,recordTechnical,nextQuestion,deliveryStatus}from'./state.mjs';
import{actSourceSnapshot,prepareActRuntime,authorActProject,compileActProject,validateActImplementation,renderActProject,importActRenderManifest,validateActPlanDocument,assertSpaceContract}from'./act-adapter.mjs';import{assertUnchangedSource}from'./source.mjs';
const[command='inspect',...argv]=process.argv.slice(2),args={};for(let i=0;i<argv.length;i++){if(!argv[i].startsWith('--'))throw Error('Expected --argument');const key=argv[i].slice(2);args[key]=!argv[i+1]||argv[i+1].startsWith('--')?true:argv[++i];}
const runId=args.run||'act2-concepts';if(!/^[a-z0-9][a-z0-9_-]*$/i.test(runId))throw Error('Unsafe run ID');const dir=path.join(ROOT,'_local/reports/intent-pipeline/runs',runId),local=f=>{const p=path.resolve(ROOT,f);if(!p.startsWith(ROOT+path.sep))throw Error('Artifact is outside this checkout');return p;};
const json=f=>readFile(f,'utf8').then(JSON.parse),ref=async(file,kind)=>({kind,path:path.relative(ROOT,file),sha256:hash(await readFile(file))});
async function authorizedInput(run){const auth=run.implementationAuthorization;if(auth?.status!=='approved'||run.intent.executionMode!=='implementation')throw Error('The delivered whole-act plan is not approved for implementation');for(const a of auth.planArtifacts){if(hash(await readFile(local(a.path)))!==a.sha256)throw Error('Approved delivered plan was changed: '+a.path);}const planRef=auth.planArtifacts.find(a=>a.kind==='layout-plan'),plan=await json(local(planRef.path));validateActPlanDocument(plan,auth.scope.stageIds);return{plan,stageIds:auth.scope.stageIds};}
async function main(){const run=await readRun(dir),input=await authorizedInput(run),projectPath=args.project?local(args.project):path.join(ROOT,'shared/data/campaign.json'),project=await json(projectPath);if(command==='inspect'){const stages=project.stages.filter(s=>input.stageIds.includes(s.metadata?.stageId));const readiness=stages.map(s=>{try{assertSpaceContract(s);return{stageId:s.metadata.stageId,implemented:true,topologyId:s.design.space.topologyId};}catch(e){return{stageId:s.metadata.stageId,implemented:false,blocker:e.message};}});console.log(JSON.stringify({scope:input.stageIds,status:deliveryStatus(run),readiness,publicationAuthorized:false},null,2));process.exitCode=readiness.every(r=>r.implemented)?0:3;return;}
 if(command!=='build')throw Error('Use inspect or build [--author] [--project REPO_LOCAL_JSON] [--skip-render]');
 const prepared=await prepareActRuntime();let authored=project;if(args.author)authored=await authorActProject(prepared.runtime.g,project);
 const baselinePath=path.join(dir,'approved-plan/baseline-project.json'),baseline=await json(baselinePath);if(hash(await readFile(baselinePath))!==run.source.projectHash)throw Error('The immutable baseline project does not match the approved source hash');
 const compiled=compileActProject(prepared.runtime.g,authored,{...input,approvedPlan:input.plan,baseline}),report=validateActImplementation(prepared.runtime.g,compiled,{...input,approvedPlan:input.plan,baseline});
 const buildId=hash({source:prepared.source,project:compiled.project}).slice(0,16),out=path.join(dir,'implementation-builds',buildId);await mkdir(out,{recursive:true});
 const projectFile=path.join(out,'campaign.json'),reportFile=path.join(out,'technical.json');await writeJSON(projectFile,compiled.project);await writeJSON(reportFile,report);
 const projectRef=await ref(projectFile,'compiled-map');projectRef.sourceProjectHash=projectRef.sha256;const artifacts=[projectRef,await ref(reportFile,'technical-report')];
 for(const row of compiled.battles){const file=path.join(out,`stage-${row.stageId}-battle.json`);await writeJSON(file,row.battle);artifacts.push({...await ref(file,'compiled-battle'),stageId:row.stageId});}
 if(args['render-manifest'])artifacts.push(...await importActRenderManifest(local(args['render-manifest']),compiled,prepared.runtime.bundleHash));else if(!args['skip-render'])artifacts.push(...await renderActProject(prepared.runtime,compiled,path.join(out,'renders')));
 assertUnchangedSource(prepared.source,await actSourceSnapshot());
 const withSource=recordImplementationSource(run,prepared.source),next=recordTechnical(withSource,{basis:basisOf(withSource),checks:report.checks,artifacts});await saveRun(dir,next,{expectedRevision:run.revision});await writeJSON(path.join(dir,'question.json'),nextQuestion(next));await writeJSON(path.join(dir,'status.json'),deliveryStatus(next));
 console.log(JSON.stringify({buildId,adapter:'whole-act-canonical-v1',stageIds:input.stageIds,artifacts:artifacts.map(a=>({kind:a.kind,path:a.path,stageId:a.stageId})),checks:report.checks,status:deliveryStatus(next),limits:'Compilation and native Canvas evidence only. Final art, browser, normal combat and performance remain separate.'},null,2));process.exitCode=report.checks.some(c=>c.status==='failed')?3:0;
}
main().catch(e=>{console.error(JSON.stringify({error:e.message,command,runId,productionReady:false}));process.exitCode=4;});
