/** Reconstructed bounded current-source reviewer. Not a recovery of the old
 * approval orchestration. No browser, publication, shell strings or auto-approval. */
import {readFile,writeFile,mkdir,readdir,lstat,open,unlink} from 'node:fs/promises';
import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';import path from 'node:path';
export const JOB_SCHEMA='honro-recovered-review/v1',BROWSER_SCHEMA='honro-browser-evidence/v1';
const check=(ok,msg)=>{if(!ok)throw Error(msg);},hash=x=>createHash('sha256').update(typeof x==='string'||Buffer.isBuffer(x)?x:JSON.stringify(x)).digest('hex'),stamp=()=>new Date().toISOString();
const validId=id=>typeof id==='string'&&/^[a-zA-Z0-9_-]+$/.test(id);
export async function localFile(root,relative){check(typeof relative==='string'&&!path.isAbsolute(relative),'Checkout-relative path required');const full=path.resolve(root,relative);check(full.startsWith(path.resolve(root)+path.sep),'Path outside checkout');let cursor=root;for(const p of path.relative(root,full).split(path.sep)){cursor=path.join(cursor,p);check(!(await lstat(cursor)).isSymbolicLink(),'Evidence symlink rejected');}return full;}
export async function fileRef(root,relative,kind='artifact'){const bytes=await readFile(await localFile(root,relative));return{path:relative,kind,sha256:hash(bytes),bytes:bytes.length};}
async function verifyRef(root,ref){check(ref&&/^[a-f0-9]{64}$/.test(ref.sha256),'SHA256 reference required');check((await fileRef(root,ref.path)).sha256===ref.sha256,'Evidence bytes changed: '+ref.path);}
export async function fingerprints(root){const source=[],target=[];async function walk(relative=''){for(const e of await readdir(path.join(root,relative),{withFileTypes:true})){if(['.git','node_modules','_local','__pycache__'].includes(e.name))continue;const name=path.join(relative,e.name).split(path.sep).join('/');check(!e.isSymbolicLink(),'Source symlink needs explicit provenance: '+name);if(e.isDirectory())await walk(name);else if(e.isFile()){const ref=await fileRef(root,name);if(['HONRO.html','HONRO_WORKSHOP.html'].includes(name)||/^assets\/bgm\/.*\.mp3$/i.test(name))target.push(ref);else source.push(ref);}}}await walk();const digest=rows=>hash(rows.sort((a,b)=>a.path.localeCompare(b.path)).map(x=>[x.path,x.sha256]));check(target.some(x=>x.path==='HONRO.html')&&target.some(x=>x.path==='HONRO_WORKSHOP.html'),'Both built HTML artifacts required');return{sourceDigest:digest(source),targetDigest:digest(target),source,target};}
const dir=(root,id)=>{check(validId(id),'Unsafe job ID');return path.join(root,'_local/reports/review-jobs',id);};
async function save(root,job){job.updatedAt=stamp();await writeFile(path.join(dir(root,job.id),'job.json'),JSON.stringify(job,null,2)+'\n');}
export async function loadJob(root,id){const j=JSON.parse(await readFile(path.join(dir(root,id),'job.json'),'utf8'));check(j.schema===JOB_SCHEMA,'Historical job schema is not silently adopted; preserve it and create a new recovered review');return j;}
export async function createJob(root,{id,stageIds,goal,mode='current-source',runId}){check(mode==='current-source'&&!runId,'Recovered reviewer supports explicit current-source review only; intent/canonical orchestration remains separate');check(typeof goal==='string'&&goal.trim(),'Explicit review goal required');check(stageIds?.length&&new Set(stageIds).size===stageIds.length&&stageIds.every(n=>Number.isInteger(n)&&n>=1&&n<=20),'Unique stage IDs 1–20 required');await mkdir(path.dirname(dir(root,id)),{recursive:true});await mkdir(dir(root,id));const job={schema:JOB_SCHEMA,id,goal,stageIds,createdAt:stamp(),commands:{},imports:[],knownFailures:[],artistic:null,publicationAuthorized:false};await save(root,job);return job;}
export function commandPlan(job){const cmds=[['build','node',['workshop/build.mjs']],['typecheck','npm',['--prefix','game','run','typecheck']],['game-regressions','npm',['--prefix','game','test']],['rest-journey','npm',['run','test:rest-journey']],['sodan-charge','npm',['run','test:sodan-charge']],['camp-persistence','npm',['run','test:camp-persistence']],['campaign-continuity','npm',['run','test:campaign-continuity']],['camera-follow','npm',['run','test:camera-follow']],['battle-help','npm',['run','test:battle-help']]];if(job.stageIds.some(n=>n<=10))cmds.push(['act1-offline','npm',['run','test:act1:offline']]);if(job.stageIds.some(n=>n>=11))cmds.push(['act2-offline','npm',['run','test:act2:offline']]);return cmds.map(([id,executable,args])=>({id,executable,args}));}
export function browserRequirements(stageIds){return[...stageIds.map(stageId=>({surface:'game',check:'normal-playthrough',stageId})),...(stageIds.length>1?[{surface:'game',check:'campaign-continuity'}]:[]),...['controls','save-resume','mobile-portrait','mobile-landscape','performance'].map(check=>({surface:'game',check})),...['stage-view','playtest','save-load','performance'].map(check=>({surface:'workshop',check}))];}
const rowKeys=row=>(row.stageIds||[row.stageId??null]).map(stageId=>`${row.surface}/${row.check}/${stageId??''}`);
function validateCoverage(row){check(['passed','failed','partial','blocked','not-run'].includes(row.status),'Explicit coverage status required');check(row.surface==='game'||row.surface==='workshop','Unknown browser surface');check(typeof row.check==='string'&&row.check,'Check name required');check(typeof row.detail==='string'&&row.detail.trim(),'Observed detail required');if(row.status==='passed'&&row.check==='normal-playthrough')check(row.method==='normal-input'&&row.completed===true&&row.debug===false&&Array.isArray(row.modifications)&&row.modifications.length===0,'Normal play requires completed ordinary-input, non-debug and unmodified evidence');if(row.status==='passed'&&row.check==='campaign-continuity')check(row.method==='normal-input'&&row.sameProfile===true&&row.resetCount===0,'Continuity needs an unreset same-profile record');if(row.status==='passed'&&row.check==='performance')check(row.metrics&&Object.values(row.metrics).length&&Object.values(row.metrics).every(v=>typeof v==='number'&&Number.isFinite(v)&&v>=0),'Performance requires measured numeric metrics');}
export async function importBrowser(root,id,relative){const job=await loadJob(root,id),current=await fingerprints(root),packetRef=await fileRef(root,relative,'browser-packet'),p=JSON.parse(await readFile(await localFile(root,relative),'utf8'));check(p.schema===BROWSER_SCHEMA&&p.kind==='browser-live-play','Actual browser-live-play packet required');check(p.sourceDigest===current.sourceDigest&&p.targetDigest===current.targetDigest,'Stale source or built target');check(typeof p.observer==='string'&&p.observer.trim()&&Number.isFinite(Date.parse(p.observedAt))&&Date.parse(p.observedAt)<=Date.now()+300000,'Observer and real observation time required');check(Array.isArray(p.coverage)&&p.coverage.length&&Array.isArray(p.evidence),'Coverage and evidence required');for(const ref of p.evidence)await verifyRef(root,ref);
const seen=new Set();for(const row of p.coverage){validateCoverage(row);for(const n of row.stageIds||[row.stageId].filter(Boolean))check(job.stageIds.includes(n),'Coverage exceeds stage scope');for(const key of rowKeys(row)){check(!seen.has(key),'Duplicate coverage');seen.add(key);}const refs=(row.evidencePaths||[]).map(x=>p.evidence.find(e=>e.path===x));check(refs.length>=2&&refs.every(Boolean)&&refs.some(x=>x.kind==='screenshot')&&refs.some(x=>x.kind==='browser-report'),'Each observation needs linked screenshot and browser report');for(const key of rowKeys(row)){if(row.status==='failed'){const old=job.knownFailures.find(x=>x.key===key);if(!old||Date.parse(old.observedAt)<=Date.parse(p.observedAt)){const f={key,observedAt:p.observedAt,packet:packetRef,resolvedBy:null};if(old)Object.assign(old,f);else job.knownFailures.push(f);}}else if(row.status==='passed'){const f=job.knownFailures.find(x=>x.key===key);if(f&&Date.parse(p.observedAt)>Date.parse(f.observedAt))f.resolvedBy={sourceDigest:p.sourceDigest,targetDigest:p.targetDigest,packet:packetRef};}}}
job.imports.push({packet:packetRef,evidence:p.evidence,coverage:p.coverage,observedAt:p.observedAt,sourceDigest:p.sourceDigest,targetDigest:p.targetDigest});job.artistic=null;await save(root,job);return status(root,id);}
export async function status(root,id){const job=await loadJob(root,id),current=await fingerprints(root),integrity=[];for(const receipt of job.imports){for(const ref of [receipt.packet,...receipt.evidence])try{await verifyRef(root,ref);}catch(e){integrity.push(e.message);}}for(const f of job.knownFailures)try{await verifyRef(root,f.packet);}catch(e){integrity.push(e.message);}
const requirements=browserRequirements(job.stageIds).map(r=>{const key=rowKeys(r)[0],matches=job.imports.filter(p=>p.sourceDigest===current.sourceDigest&&p.targetDigest===current.targetDigest).flatMap(p=>p.coverage.filter(row=>rowKeys(row).includes(key)).map(row=>({...row,observedAt:p.observedAt}))).sort((a,b)=>Date.parse(b.observedAt)-Date.parse(a.observedAt)||(a.status==='failed'?-1:1));return{...r,status:matches[0]?.status||'missing'};});
const unresolved=job.knownFailures.filter(f=>f.resolvedBy?.sourceDigest!==current.sourceDigest||f.resolvedBy?.targetDigest!==current.targetDigest),technical=[];for(const cmd of commandPlan(job)){const c=job.commands[cmd.id];let passed=c?.status==='passed'&&c.sourceDigest===current.sourceDigest&&c.targetDigest===current.targetDigest;if(passed)try{await verifyRef(root,c.log);}catch(e){passed=false;integrity.push(e.message);}technical.push({id:cmd.id,status:passed?'passed':c?.status==='failed'?'failed':'not-run'});}
let artistic=job.artistic?.sourceDigest===current.sourceDigest&&job.artistic?.targetDigest===current.targetDigest;if(artistic)for(const ref of [job.artistic.packet,...job.artistic.renderEvidence])try{await verifyRef(root,ref);}catch(e){artistic=false;integrity.push(e.message);}
const ready=technical.every(x=>x.status==='passed')&&requirements.every(x=>x.status==='passed')&&!unresolved.length&&!integrity.length&&artistic;const report={schema:JOB_SCHEMA,id,status:ready?'ready-for-local-delivery':'blocked',sourceDigest:current.sourceDigest,targetDigest:current.targetDigest,technical,browser:requirements,unresolvedFailures:unresolved,integrityProblems:integrity,artistic:!!artistic,publicationAuthorized:false,limits:['Reconstructed bounded reviewer; old orchestration/historical evidence adapters are not silently restored.','Source/artifact hashes prove bytes, not observer identity or truth.','No command result proves browser play or artwork approval.']};await writeFile(path.join(dir(root,id),'reviewer.json'),JSON.stringify(report,null,2)+'\n');return report;}
export async function resume(root,id,{through}={}){const lock=path.join(dir(root,id),'.lock'),handle=await open(lock,'wx');try{let job=await loadJob(root,id);for(const cmd of commandPlan(job)){if(through==='build'&&cmd.id!=='build')break;const before=await fingerprints(root);job.commands[cmd.id]={status:'running',startedAt:stamp()};await save(root,job);const result=spawnSync(cmd.executable,cmd.args,{cwd:root,encoding:'utf8',timeout:600000,maxBuffer:32*1024*1024,shell:false});const logPath=`_local/reports/review-jobs/${id}/${cmd.id}-${Date.now()}.log`;await writeFile(path.join(root,logPath),(result.stdout||'')+(result.stderr||'')+(result.error?.message||''));const after=await fingerprints(root);job.commands[cmd.id]={status:result.status===0&&before.sourceDigest===after.sourceDigest?'passed':result.error?.code==='ENOENT'?'missing':'failed',exitCode:result.status,sourceDigest:after.sourceDigest,targetDigest:after.targetDigest,log:await fileRef(root,logPath,'command-log')};job.artistic=null;await save(root,job);if(job.commands[cmd.id].status!=='passed')break;}return await status(root,id);}finally{await handle.close();await unlink(lock);}}
export async function approveArt(root,id,relative){const r=await status(root,id);check(r.technical.every(x=>x.status==='passed')&&r.browser.every(x=>x.status==='passed')&&!r.unresolvedFailures.length&&!r.integrityProblems.length,'Technical/browser evidence must pass first');const j=await loadJob(root,id),p=JSON.parse(await readFile(await localFile(root,relative),'utf8'));check(p.actor==='user'&&typeof p.reference==='string'&&p.reference.trim()&&Number.isFinite(Date.parse(p.approvedAt)),'Explicit user approval reference/time required');check(p.sourceDigest===r.sourceDigest&&p.targetDigest===r.targetDigest,'Stale art approval');check(p.renderEvidence?.length,'Current render evidence required');for(const ref of p.renderEvidence){check(ref.targetDigest===r.targetDigest,'Render must target current artifacts');await verifyRef(root,ref);}j.artistic={...p,packet:await fileRef(root,relative,'user-art-approval')};await save(root,j);return status(root,id);}
export async function deliver(root,id){const r=await status(root,id);check(r.status==='ready-for-local-delivery','Delivery blocked: current technical/browser/art evidence missing');const result={...r,deliveredAt:stamp(),kind:'local-manifest-only'};await writeFile(path.join(dir(root,id),'delivery.json'),JSON.stringify(result,null,2)+'\n');return result;}
