(function(G){'use strict';
const VERSION=1,cache=new WeakMap(),validPaint=s=>s===undefined||s==='none'||/^#[\da-f]{6}([\da-f]{2})?$/i.test(s)||/^url\(#[\w-]+\)$/.test(s);
function validate(vector){const errors=[];if(!vector||vector.version!==VERSION)return['Unsupported vector asset version'];if(vector.gradients!==undefined&&(!vector.gradients||typeof vector.gradients!=='object'||Array.isArray(vector.gradients)))return['Invalid vector gradient table'];const v=vector.viewBox;if(!Array.isArray(v)||v.length!==4||v.some(n=>!Number.isFinite(n))||v[2]<=0||v[3]<=0)errors.push('Invalid vector bounds');let n=0;
 const walk=(node,depth=0)=>{if(!node||!['g','path'].includes(node.tag)||depth>24||++n>512){errors.push('Invalid or excessive vector tree');return;}if(!validPaint(node.fill)||!validPaint(node.stroke))errors.push('Unsafe vector paint');if(node.tag==='g'&&node.opacity!==undefined&&node.opacity!==1)errors.push('Group opacity requires isolated compositing and is not supported');for(const color of [node.fill,node.stroke])if(color?.startsWith('url(')&&!Object.hasOwn(vector.gradients||{},color.slice(5,-1)))errors.push('Missing vector gradient');if(node.fillRule!==undefined&&!['nonzero','evenodd'].includes(node.fillRule))errors.push('Invalid fill rule');if(node.lineJoin!==undefined&&!['round','bevel','miter'].includes(node.lineJoin))errors.push('Invalid line join');if(node.lineCap!==undefined&&!['round','butt','square'].includes(node.lineCap))errors.push('Invalid line cap');if(node.opacity!==undefined&&(!Number.isFinite(node.opacity)||node.opacity<0||node.opacity>1))errors.push('Invalid vector opacity');if(node.lineWidth!==undefined&&(!Number.isFinite(node.lineWidth)||node.lineWidth<0||node.lineWidth>100))errors.push('Invalid vector stroke');if(node.transform&&(!Array.isArray(node.transform)||node.transform.length!==6||node.transform.some(n=>!Number.isFinite(n))))errors.push('Invalid vector transform');if(node.tag==='path'){if(typeof node.d!=='string'||node.d.length>60000||/[^mMzZlLhHvVcCsSqQtTaA0-9.eE+\-,\s]/.test(node.d))errors.push('Invalid vector path');}else if(!Array.isArray(node.children))errors.push('Invalid vector children');else node.children.forEach(c=>walk(c,depth+1));};walk(vector.root);
 for(const g of Object.values(vector.gradients||{})){if(!['linear','radial'].includes(g.type)||!Array.isArray(g.stops)||g.stops.length<2||g.stops.length>16){errors.push('Invalid vector gradient');continue;}const keys=g.type==='linear'?['x1','y1','x2','y2']:['cx','cy','r',...['fx','fy'].filter(k=>g[k]!==undefined)];if(keys.some(k=>!Number.isFinite(g[k]))||g.type==='radial'&&g.r<=0)errors.push('Invalid gradient coordinates');let previous=-1;for(const s of g.stops){if(!Number.isFinite(s.offset)||s.offset<previous||s.offset<0||s.offset>1||!/^#[\da-f]{6}$/i.test(s.color)||!Number.isFinite(s.opacity)||s.opacity<0||s.opacity>1)errors.push('Invalid vector stop');previous=s.offset;}}
 if(vector.source!==undefined&&(typeof vector.source!=='string'||vector.source.length>300000||/<\?|<!|\bon\w+\s*=|href\s*=|style\s*=|<\s*(?:script|image|foreignObject|use)\b/i.test(vector.source)))errors.push('Unsafe vector source');return errors;
}
function prepare(vector){let data=cache.get(vector);if(data)return data;const errors=validate(vector);if(errors.length)throw Error(errors.join('; '));let count=0;const walk=node=>{if(node.tag==='path'){count++;return{...node,path:new Path2D(node.d)};}return{...node,children:node.children.map(walk)};};data={root:walk(vector.root),pathCount:count};cache.set(vector,data);return data;}
function draw(c,asset,inst){if(!asset.vector)return false;const data=prepare(asset.vector),gradients=Object.create(null);
 c.save();c.translate(inst.x||0,inst.y||0);c.rotate(inst.rotation||0);c.scale(inst.scale??1,inst.scale??1);c.translate(-(asset.anchor?.x||0),-(asset.anchor?.y||0));
 const paint=color=>{if(!color?.startsWith('url('))return color;const id=color.slice(5,-1),m=c.getTransform(),key=id+':'+[m.a,m.b,m.c,m.d,m.e,m.f].join(',');if(gradients[key])return gradients[key];const g=asset.vector.gradients[id],v=g.type==='linear'?c.createLinearGradient(g.x1,g.y1,g.x2,g.y2):c.createRadialGradient(g.fx??g.cx,g.fy??g.cy,0,g.cx,g.cy,g.r);for(const s of g.stops)v.addColorStop(s.offset,s.color+Math.round(s.opacity*255).toString(16).padStart(2,'0'));return gradients[key]=v;};
 const walk=(node,inherited={fill:'#000000',stroke:'none',lineWidth:1})=>{c.save();if(node.transform)c.transform(...node.transform);c.globalAlpha*=node.opacity??1;const style={...inherited,...node};if(node.tag==='path'){if(style.fill!=='none'){c.fillStyle=paint(style.fill);c.fill(node.path,style.fillRule||'nonzero');}if(style.stroke!=='none'){c.strokeStyle=paint(style.stroke);c.lineWidth=style.lineWidth;c.lineJoin=style.lineJoin||'miter';c.lineCap=style.lineCap||'butt';c.miterLimit=4;c.setLineDash([]);c.stroke(node.path);}}else for(const child of node.children)walk(child,style);c.restore();};walk(data.root);c.restore();return true;
}
G.HonroVectorArt={VERSION,validate,prepare,draw};
})(globalThis);
